items:
- uid: com.microsoft.azure.management.network._application_gateway_sku_name
  id: _application_gateway_sku_name
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._application_gateway_sku_name_1a5f8361dda3f9e8b8a851af608a9246b6
  - com.microsoft.azure.management.network._application_gateway_sku_name_1a6b546027688a476248391021e8e931b4
  - com.microsoft.azure.management.network._application_gateway_sku_name_1ab4f5f88c1ace85d67b1b8ac5bb1251c0
  href: com.microsoft.azure.management.network._application_gateway_sku_name.yml
  langs:
  - java
  name: ApplicationGatewaySkuName
  fullName: com.microsoft.azure.management.network.ApplicationGatewaySkuName
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySkuName.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySkuName.java
    startLine: 13
  package: com.microsoft.azure.management.network
  summary: <p>Defines values for <xref href="com.microsoft.azure.management.network._application_gateway_sku_name" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: &o1
    content: public class ApplicationGatewaySkuName
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.network._application_gateway_sku_name_1a5f8361dda3f9e8b8a851af608a9246b6
  id: _application_gateway_sku_name_1a5f8361dda3f9e8b8a851af608a9246b6
  parent: com.microsoft.azure.management.network._application_gateway_sku_name
  href: com.microsoft.azure.management.network._application_gateway_sku_name.yml
  langs:
  - java
  name: STANDARD_LARGE
  fullName: final String com.microsoft.azure.management.network.ApplicationGatewaySkuName.STANDARD_LARGE
  type: Field
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySkuName.java
    startLine: 21
  package: com.microsoft.azure.management.network
  summary: <p>Static value Standard_Large for <xref href="com.microsoft.azure.management.network._application_gateway_sku_name" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public static final String STANDARD_LARGE= "Standard_Large"
    return:
      type: 3d93591e
- uid: com.microsoft.azure.management.network._application_gateway_sku_name_1a6b546027688a476248391021e8e931b4
  id: _application_gateway_sku_name_1a6b546027688a476248391021e8e931b4
  parent: com.microsoft.azure.management.network._application_gateway_sku_name
  href: com.microsoft.azure.management.network._application_gateway_sku_name.yml
  langs:
  - java
  name: STANDARD_MEDIUM
  fullName: final String com.microsoft.azure.management.network.ApplicationGatewaySkuName.STANDARD_MEDIUM
  type: Field
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySkuName.java
    startLine: 18
  package: com.microsoft.azure.management.network
  summary: <p>Static value Standard_Medium for <xref href="com.microsoft.azure.management.network._application_gateway_sku_name" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public static final String STANDARD_MEDIUM= "Standard_Medium"
    return:
      type: 3d93591e
- uid: com.microsoft.azure.management.network._application_gateway_sku_name_1ab4f5f88c1ace85d67b1b8ac5bb1251c0
  id: _application_gateway_sku_name_1ab4f5f88c1ace85d67b1b8ac5bb1251c0
  parent: com.microsoft.azure.management.network._application_gateway_sku_name
  href: com.microsoft.azure.management.network._application_gateway_sku_name.yml
  langs:
  - java
  name: STANDARD_SMALL
  fullName: final String com.microsoft.azure.management.network.ApplicationGatewaySkuName.STANDARD_SMALL
  type: Field
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySkuName.java
    startLine: 15
  package: com.microsoft.azure.management.network
  summary: <p>Static value Standard_Small for <xref href="com.microsoft.azure.management.network._application_gateway_sku_name" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public static final String STANDARD_SMALL= "Standard_Small"
    return:
      type: 3d93591e
references:
- uid: 3d93591e
  spec.java:
  - name: final String
    fullName: final String
- uid: com.microsoft.azure.management.network._application_gateway_sku_name
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_sku_name.yml
  name: ApplicationGatewaySkuName
  fullName: com.microsoft.azure.management.network.ApplicationGatewaySkuName
  type: Class
  summary: <p>Defines values for <xref href="com.microsoft.azure.management.network._application_gateway_sku_name" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: *o1
