items:
- uid: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options
  id: _compute_node_get_remote_login_settings_options
  parent: com.microsoft.azure.batch.protocol.models
  children:
  - com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options_1a905ddb308767be9b3de9e7640217ba0b
  - com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options_1aedd96a583cd9f12ab4b8e691056f7405
  - com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options_1a25f38119b4d04033efc2eb0fbc14318c
  - com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options_1ab66f96fbfe1019000b26b3fdc51e8c18
  - com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options_1a176a382b23cd67a8c4cdabbc479ac9b4
  - com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options_1a490b40eeae07bd93c10e8f59f001a7dd
  - com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options_1a6108079c99bb7b380d9113ec2c4079cf
  - com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options_1ae3608e372d27e1d22e671a16b0496a08
  href: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options.yml
  langs:
  - java
  name: ComputeNodeGetRemoteLoginSettingsOptions
  fullName: com.microsoft.azure.batch.protocol.models.ComputeNodeGetRemoteLoginSettingsOptions
  type: Class
  source:
    remote: &o0
      path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ComputeNodeGetRemoteLoginSettingsOptions.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ComputeNodeGetRemoteLoginSettingsOptions.java
    startLine: 15
  assemblies:
  - com.microsoft.azure.batch.protocol.models
  package: com.microsoft.azure.batch.protocol.models
  summary: <p>Additional parameters for the ComputeNode_GetRemoteLoginSettings operation. </p>
  syntax: &o1
    content: public class ComputeNodeGetRemoteLoginSettingsOptions
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options_1a905ddb308767be9b3de9e7640217ba0b
  id: _compute_node_get_remote_login_settings_options_1a905ddb308767be9b3de9e7640217ba0b
  parent: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options
  href: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options.yml
  langs:
  - java
  name: clientRequestId()
  fullName: String com.microsoft.azure.batch.protocol.models.ComputeNodeGetRemoteLoginSettingsOptions.clientRequestId()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ComputeNodeGetRemoteLoginSettingsOptions.java
    startLine: 70
  assemblies:
  - com.microsoft.azure.batch.protocol.models
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the clientRequestId value.</p>

    <p></p>
  syntax:
    content: public String clientRequestId()
    return:
      type: "26831127"
      description: <p>the clientRequestId value </p>
- uid: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options_1aedd96a583cd9f12ab4b8e691056f7405
  id: _compute_node_get_remote_login_settings_options_1aedd96a583cd9f12ab4b8e691056f7405
  parent: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options
  href: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options.yml
  langs:
  - java
  name: ocpDate()
  fullName: DateTime com.microsoft.azure.batch.protocol.models.ComputeNodeGetRemoteLoginSettingsOptions.ocpDate()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ComputeNodeGetRemoteLoginSettingsOptions.java
    startLine: 110
  assemblies:
  - com.microsoft.azure.batch.protocol.models
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the ocpDate value.</p>

    <p></p>
  syntax:
    content: public DateTime ocpDate()
    return:
      type: 230df18c
      description: <p>the ocpDate value </p>
- uid: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options_1a25f38119b4d04033efc2eb0fbc14318c
  id: _compute_node_get_remote_login_settings_options_1a25f38119b4d04033efc2eb0fbc14318c
  parent: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options
  href: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options.yml
  langs:
  - java
  name: returnClientRequestId()
  fullName: Boolean com.microsoft.azure.batch.protocol.models.ComputeNodeGetRemoteLoginSettingsOptions.returnClientRequestId()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ComputeNodeGetRemoteLoginSettingsOptions.java
    startLine: 90
  assemblies:
  - com.microsoft.azure.batch.protocol.models
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the returnClientRequestId value.</p>

    <p></p>
  syntax:
    content: public Boolean returnClientRequestId()
    return:
      type: 866c2227
      description: <p>the returnClientRequestId value </p>
- uid: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options_1ab66f96fbfe1019000b26b3fdc51e8c18
  id: _compute_node_get_remote_login_settings_options_1ab66f96fbfe1019000b26b3fdc51e8c18
  parent: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options
  href: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options.yml
  langs:
  - java
  name: timeout()
  fullName: Integer com.microsoft.azure.batch.protocol.models.ComputeNodeGetRemoteLoginSettingsOptions.timeout()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ComputeNodeGetRemoteLoginSettingsOptions.java
    startLine: 50
  assemblies:
  - com.microsoft.azure.batch.protocol.models
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the timeout value.</p>

    <p></p>
  syntax:
    content: public Integer timeout()
    return:
      type: 08effaa0
      description: <p>the timeout value </p>
- uid: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options_1a176a382b23cd67a8c4cdabbc479ac9b4
  id: _compute_node_get_remote_login_settings_options_1a176a382b23cd67a8c4cdabbc479ac9b4
  parent: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options
  href: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options.yml
  langs:
  - java
  name: withClientRequestId(String clientRequestId)
  fullName: ComputeNodeGetRemoteLoginSettingsOptions com.microsoft.azure.batch.protocol.models.ComputeNodeGetRemoteLoginSettingsOptions.withClientRequestId(String clientRequestId)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ComputeNodeGetRemoteLoginSettingsOptions.java
    startLine: 80
  assemblies:
  - com.microsoft.azure.batch.protocol.models
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the clientRequestId value.</p>

    <p></p>
  syntax:
    content: public ComputeNodeGetRemoteLoginSettingsOptions withClientRequestId(String clientRequestId)
    parameters:
    - id: clientRequestId
      type: "26831127"
      description: <p>the clientRequestId value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options_1a490b40eeae07bd93c10e8f59f001a7dd
  id: _compute_node_get_remote_login_settings_options_1a490b40eeae07bd93c10e8f59f001a7dd
  parent: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options
  href: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options.yml
  langs:
  - java
  name: withOcpDate(DateTime ocpDate)
  fullName: ComputeNodeGetRemoteLoginSettingsOptions com.microsoft.azure.batch.protocol.models.ComputeNodeGetRemoteLoginSettingsOptions.withOcpDate(DateTime ocpDate)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ComputeNodeGetRemoteLoginSettingsOptions.java
    startLine: 123
  assemblies:
  - com.microsoft.azure.batch.protocol.models
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the ocpDate value.</p>

    <p></p>
  syntax:
    content: public ComputeNodeGetRemoteLoginSettingsOptions withOcpDate(DateTime ocpDate)
    parameters:
    - id: ocpDate
      type: 230df18c
      description: <p>the ocpDate value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options_1a6108079c99bb7b380d9113ec2c4079cf
  id: _compute_node_get_remote_login_settings_options_1a6108079c99bb7b380d9113ec2c4079cf
  parent: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options
  href: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options.yml
  langs:
  - java
  name: withReturnClientRequestId(Boolean returnClientRequestId)
  fullName: ComputeNodeGetRemoteLoginSettingsOptions com.microsoft.azure.batch.protocol.models.ComputeNodeGetRemoteLoginSettingsOptions.withReturnClientRequestId(Boolean returnClientRequestId)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ComputeNodeGetRemoteLoginSettingsOptions.java
    startLine: 100
  assemblies:
  - com.microsoft.azure.batch.protocol.models
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the returnClientRequestId value.</p>

    <p></p>
  syntax:
    content: public ComputeNodeGetRemoteLoginSettingsOptions withReturnClientRequestId(Boolean returnClientRequestId)
    parameters:
    - id: returnClientRequestId
      type: 866c2227
      description: <p>the returnClientRequestId value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options_1ae3608e372d27e1d22e671a16b0496a08
  id: _compute_node_get_remote_login_settings_options_1ae3608e372d27e1d22e671a16b0496a08
  parent: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options
  href: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options.yml
  langs:
  - java
  name: withTimeout(Integer timeout)
  fullName: ComputeNodeGetRemoteLoginSettingsOptions com.microsoft.azure.batch.protocol.models.ComputeNodeGetRemoteLoginSettingsOptions.withTimeout(Integer timeout)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ComputeNodeGetRemoteLoginSettingsOptions.java
    startLine: 60
  assemblies:
  - com.microsoft.azure.batch.protocol.models
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the timeout value.</p>

    <p></p>
  syntax:
    content: public ComputeNodeGetRemoteLoginSettingsOptions withTimeout(Integer timeout)
    parameters:
    - id: timeout
      type: 08effaa0
      description: <p>the timeout value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: 08effaa0
  spec.java:
  - name: Integer
    fullName: Integer
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 866c2227
  spec.java:
  - name: Boolean
    fullName: Boolean
- uid: 230df18c
  spec.java:
  - name: DateTime
    fullName: DateTime
- uid: com.microsoft.rest._date_time_rfc1123
  parent: com.microsoft.rest
  href: com.microsoft.rest._date_time_rfc1123.yml
  name: DateTimeRfc1123
  fullName: com.microsoft.rest.DateTimeRfc1123
  type: Class
  summary: <p>Simple wrapper over joda.time.DateTime used for specifying RFC1123 format during serialization/deserialization. </p>
  syntax:
    content: public class DateTimeRfc1123
- uid: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options
  parent: com.microsoft.azure.batch.protocol.models
  href: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_options.yml
  name: ComputeNodeGetRemoteLoginSettingsOptions
  fullName: com.microsoft.azure.batch.protocol.models.ComputeNodeGetRemoteLoginSettingsOptions
  type: Class
  summary: <p>Additional parameters for the ComputeNode_GetRemoteLoginSettings operation. </p>
  syntax: *o1
