items:
- uid: com.microsoft.azure.management.network.implementation.api._vpn_client_configuration
  id: _vpn_client_configuration
  parent: com.microsoft.azure.management.network.implementation.api
  children:
  - com.microsoft.azure.management.network.implementation.api._vpn_client_configuration_1ad8b4e01df02819cfab59cdee8eb7bce6
  - com.microsoft.azure.management.network.implementation.api._vpn_client_configuration_1a129fd73ecb3e7006c05c0e82af90aa13
  - com.microsoft.azure.management.network.implementation.api._vpn_client_configuration_1ac002a530c4fecb43f94b1c2ac19e02b4
  - com.microsoft.azure.management.network.implementation.api._vpn_client_configuration_1a0cea6379f978cc0c62ad4feed9af35bf
  - com.microsoft.azure.management.network.implementation.api._vpn_client_configuration_1a16b3cb5cde2898040a9440a33ecb81db
  - com.microsoft.azure.management.network.implementation.api._vpn_client_configuration_1a02ae305843255945b7a2d83f97d17fbb
  href: com.microsoft.azure.management.network.implementation.api._vpn_client_configuration.yml
  langs:
  - java
  name: VpnClientConfiguration
  fullName: com.microsoft.azure.management.network.implementation.api.VpnClientConfiguration
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/api/VpnClientConfiguration.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/api/VpnClientConfiguration.java
    startLine: 13
  assemblies:
  - com.microsoft.azure.management.network.implementation.api
  package: com.microsoft.azure.management.network.implementation.api
  summary: >-
    <p>

      <xref href="com.microsoft.azure.management.network.implementation.api._vpn_client_configuration" data-throw-if-not-resolved="false"></xref> for P2S client. </p>
  syntax: &o1
    content: public class VpnClientConfiguration
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.network.implementation.api._vpn_client_configuration_1ad8b4e01df02819cfab59cdee8eb7bce6
  id: _vpn_client_configuration_1ad8b4e01df02819cfab59cdee8eb7bce6
  parent: com.microsoft.azure.management.network.implementation.api._vpn_client_configuration
  href: com.microsoft.azure.management.network.implementation.api._vpn_client_configuration.yml
  langs:
  - java
  name: vpnClientAddressPool()
  fullName: AddressSpace com.microsoft.azure.management.network.implementation.api.VpnClientConfiguration.vpnClientAddressPool()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/api/VpnClientConfiguration.java
    startLine: 35
  assemblies:
  - com.microsoft.azure.management.network.implementation.api
  package: com.microsoft.azure.management.network.implementation.api
  summary: >-
    <p>Get the vpnClientAddressPool value.</p>

    <p></p>
  syntax:
    content: public AddressSpace vpnClientAddressPool()
    return:
      type: com.microsoft.azure.management.network.implementation.api._address_space
      description: <p>the vpnClientAddressPool value </p>
- uid: com.microsoft.azure.management.network.implementation.api._vpn_client_configuration_1a129fd73ecb3e7006c05c0e82af90aa13
  id: _vpn_client_configuration_1a129fd73ecb3e7006c05c0e82af90aa13
  parent: com.microsoft.azure.management.network.implementation.api._vpn_client_configuration
  href: com.microsoft.azure.management.network.implementation.api._vpn_client_configuration.yml
  langs:
  - java
  name: vpnClientRevokedCertificates()
  fullName: List<VpnClientRevokedCertificate> com.microsoft.azure.management.network.implementation.api.VpnClientConfiguration.vpnClientRevokedCertificates()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/api/VpnClientConfiguration.java
    startLine: 75
  assemblies:
  - com.microsoft.azure.management.network.implementation.api
  package: com.microsoft.azure.management.network.implementation.api
  summary: >-
    <p>Get the vpnClientRevokedCertificates value.</p>

    <p></p>
  syntax:
    content: public List< VpnClientRevokedCertificate > vpnClientRevokedCertificates()
    return:
      type: f6a6204dcom.microsoft.azure.management.network.implementation.api._vpn_client_revoked_certificate9ec3e006
      description: <p>the vpnClientRevokedCertificates value </p>
- uid: com.microsoft.azure.management.network.implementation.api._vpn_client_configuration_1ac002a530c4fecb43f94b1c2ac19e02b4
  id: _vpn_client_configuration_1ac002a530c4fecb43f94b1c2ac19e02b4
  parent: com.microsoft.azure.management.network.implementation.api._vpn_client_configuration
  href: com.microsoft.azure.management.network.implementation.api._vpn_client_configuration.yml
  langs:
  - java
  name: vpnClientRootCertificates()
  fullName: List<VpnClientRootCertificate> com.microsoft.azure.management.network.implementation.api.VpnClientConfiguration.vpnClientRootCertificates()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/api/VpnClientConfiguration.java
    startLine: 55
  assemblies:
  - com.microsoft.azure.management.network.implementation.api
  package: com.microsoft.azure.management.network.implementation.api
  summary: >-
    <p>Get the vpnClientRootCertificates value.</p>

    <p></p>
  syntax:
    content: public List< VpnClientRootCertificate > vpnClientRootCertificates()
    return:
      type: f6a6204dcom.microsoft.azure.management.network.implementation.api._vpn_client_root_certificate9ec3e006
      description: <p>the vpnClientRootCertificates value </p>
- uid: com.microsoft.azure.management.network.implementation.api._vpn_client_configuration_1a0cea6379f978cc0c62ad4feed9af35bf
  id: _vpn_client_configuration_1a0cea6379f978cc0c62ad4feed9af35bf
  parent: com.microsoft.azure.management.network.implementation.api._vpn_client_configuration
  href: com.microsoft.azure.management.network.implementation.api._vpn_client_configuration.yml
  langs:
  - java
  name: withVpnClientAddressPool(AddressSpace vpnClientAddressPool)
  fullName: VpnClientConfiguration com.microsoft.azure.management.network.implementation.api.VpnClientConfiguration.withVpnClientAddressPool(AddressSpace vpnClientAddressPool)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/api/VpnClientConfiguration.java
    startLine: 45
  assemblies:
  - com.microsoft.azure.management.network.implementation.api
  package: com.microsoft.azure.management.network.implementation.api
  summary: >-
    <p>Set the vpnClientAddressPool value.</p>

    <p></p>
  syntax:
    content: public VpnClientConfiguration withVpnClientAddressPool(AddressSpace vpnClientAddressPool)
    parameters:
    - id: vpnClientAddressPool
      type: com.microsoft.azure.management.network.implementation.api._address_space
      description: <p>the vpnClientAddressPool value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation.api._vpn_client_configuration
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation.api._vpn_client_configuration" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network.implementation.api._vpn_client_configuration_1a16b3cb5cde2898040a9440a33ecb81db
  id: _vpn_client_configuration_1a16b3cb5cde2898040a9440a33ecb81db
  parent: com.microsoft.azure.management.network.implementation.api._vpn_client_configuration
  href: com.microsoft.azure.management.network.implementation.api._vpn_client_configuration.yml
  langs:
  - java
  name: withVpnClientRevokedCertificates(List< VpnClientRevokedCertificate > vpnClientRevokedCertificates)
  fullName: VpnClientConfiguration com.microsoft.azure.management.network.implementation.api.VpnClientConfiguration.withVpnClientRevokedCertificates(List< VpnClientRevokedCertificate > vpnClientRevokedCertificates)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/api/VpnClientConfiguration.java
    startLine: 85
  assemblies:
  - com.microsoft.azure.management.network.implementation.api
  package: com.microsoft.azure.management.network.implementation.api
  summary: >-
    <p>Set the vpnClientRevokedCertificates value.</p>

    <p></p>
  syntax:
    content: public VpnClientConfiguration withVpnClientRevokedCertificates(List< VpnClientRevokedCertificate > vpnClientRevokedCertificates)
    parameters:
    - id: vpnClientRevokedCertificates
      type: f6a6204dcom.microsoft.azure.management.network.implementation.api._vpn_client_revoked_certificate9ec3e006
      description: <p>the vpnClientRevokedCertificates value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation.api._vpn_client_configuration
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation.api._vpn_client_configuration" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network.implementation.api._vpn_client_configuration_1a02ae305843255945b7a2d83f97d17fbb
  id: _vpn_client_configuration_1a02ae305843255945b7a2d83f97d17fbb
  parent: com.microsoft.azure.management.network.implementation.api._vpn_client_configuration
  href: com.microsoft.azure.management.network.implementation.api._vpn_client_configuration.yml
  langs:
  - java
  name: withVpnClientRootCertificates(List< VpnClientRootCertificate > vpnClientRootCertificates)
  fullName: VpnClientConfiguration com.microsoft.azure.management.network.implementation.api.VpnClientConfiguration.withVpnClientRootCertificates(List< VpnClientRootCertificate > vpnClientRootCertificates)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/api/VpnClientConfiguration.java
    startLine: 65
  assemblies:
  - com.microsoft.azure.management.network.implementation.api
  package: com.microsoft.azure.management.network.implementation.api
  summary: >-
    <p>Set the vpnClientRootCertificates value.</p>

    <p></p>
  syntax:
    content: public VpnClientConfiguration withVpnClientRootCertificates(List< VpnClientRootCertificate > vpnClientRootCertificates)
    parameters:
    - id: vpnClientRootCertificates
      type: f6a6204dcom.microsoft.azure.management.network.implementation.api._vpn_client_root_certificate9ec3e006
      description: <p>the vpnClientRootCertificates value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation.api._vpn_client_configuration
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation.api._vpn_client_configuration" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: f6a6204dcom.microsoft.azure.management.network.implementation.api._vpn_client_root_certificate9ec3e006
  spec.java:
  - name: 'List< '
    fullName: 'List< '
  - uid: com.microsoft.azure.management.network.implementation.api._vpn_client_root_certificate
    name: VpnClientRootCertificate
    fullName: com.microsoft.azure.management.network.implementation.api.VpnClientRootCertificate
    href: com.microsoft.azure.management.network.implementation.api._vpn_client_root_certificate.yml
  - name: ' >'
    fullName: ' >'
- uid: f6a6204dcom.microsoft.azure.management.network.implementation.api._vpn_client_revoked_certificate9ec3e006
  spec.java:
  - name: 'List< '
    fullName: 'List< '
  - uid: com.microsoft.azure.management.network.implementation.api._vpn_client_revoked_certificate
    name: VpnClientRevokedCertificate
    fullName: com.microsoft.azure.management.network.implementation.api.VpnClientRevokedCertificate
    href: com.microsoft.azure.management.network.implementation.api._vpn_client_revoked_certificate.yml
  - name: ' >'
    fullName: ' >'
- uid: com.microsoft.azure.management.network.implementation.api._address_space
  parent: com.microsoft.azure.management.network.implementation.api
  href: com.microsoft.azure.management.network.implementation.api._address_space.yml
  name: AddressSpace
  fullName: com.microsoft.azure.management.network.implementation.api.AddressSpace
  type: Class
  summary: >-
    <p>

      <xref href="com.microsoft.azure.management.network.implementation.api._address_space" data-throw-if-not-resolved="false"></xref> contains an array of IP address ranges that can be used by subnets. </p>
  syntax:
    content: public class AddressSpace
- uid: com.microsoft.azure.management.network.implementation.api._vpn_client_root_certificate
  parent: com.microsoft.azure.management.network.implementation.api
  href: com.microsoft.azure.management.network.implementation.api._vpn_client_root_certificate.yml
  name: VpnClientRootCertificate
  fullName: com.microsoft.azure.management.network.implementation.api.VpnClientRootCertificate
  type: Class
  summary: <p>VPN client root certificate of virtual network gateway. </p>
  syntax:
    content: public class VpnClientRootCertificate
- uid: com.microsoft.azure.management.network.implementation.api._vpn_client_revoked_certificate
  parent: com.microsoft.azure.management.network.implementation.api
  href: com.microsoft.azure.management.network.implementation.api._vpn_client_revoked_certificate.yml
  name: VpnClientRevokedCertificate
  fullName: com.microsoft.azure.management.network.implementation.api.VpnClientRevokedCertificate
  type: Class
  summary: <p>VPN client revoked certificate of virtual network gateway. </p>
  syntax:
    content: public class VpnClientRevokedCertificate
- uid: com.microsoft.azure.management.network.implementation.api._vpn_client_configuration
  parent: com.microsoft.azure.management.network.implementation.api
  href: com.microsoft.azure.management.network.implementation.api._vpn_client_configuration.yml
  name: VpnClientConfiguration
  fullName: com.microsoft.azure.management.network.implementation.api.VpnClientConfiguration
  type: Class
  summary: >-
    <p>

      <xref href="com.microsoft.azure.management.network.implementation.api._vpn_client_configuration" data-throw-if-not-resolved="false"></xref> for P2S client. </p>
  syntax: *o1
