items:
- uid: com.microsoft.azure.management.resources.implementation._resource_manager._configurable_impl
  id: _configurable_impl
  parent: com.microsoft.azure.management.resources.implementation
  children:
  - com.microsoft.azure.management.resources.implementation._resource_manager._configurable_impl_1af4c9ba25285dcef28300afcf5370a8d1
  href: com.microsoft.azure.management.resources.implementation._resource_manager._configurable_impl.yml
  langs:
  - java
  name: ResourceManager.ConfigurableImpl
  fullName: com.microsoft.azure.management.resources.implementation.ResourceManager.ConfigurableImpl
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/implementation/ResourceManager.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/implementation/ResourceManager.java
    startLine: 85
  package: com.microsoft.azure.management.resources.implementation
  summary: <p>The implementation for <xref href="com.microsoft.azure.management.resources.implementation._resource_manager._configurable" data-throw-if-not-resolved="false"></xref> interface. </p>
  syntax:
    content: private class ConfigurableImpl
  inheritedMembers:
  - com.microsoft.azure.management.resources.fluentcore.arm.implementation._azure_configurable_impl_1ae9ea36bcd724a700079ad4bc744aec6a
  - com.microsoft.azure.management.resources.fluentcore.arm.implementation._azure_configurable_impl_1a2b00ae56e701d90468d350789e298497
  - com.microsoft.azure.management.resources.fluentcore.arm.implementation._azure_configurable_impl_1aafe59e689115ee8186dfe906aba1e9b6
  - com.microsoft.azure.management.resources.fluentcore.arm.implementation._azure_configurable_impl_1a917f35b91b0f5585ff0d9c591277c4f4
  - com.microsoft.azure.management.resources.fluentcore.arm.implementation._azure_configurable_impl_1a5adb6e7076868aadd349d24caa8eb5d8
  - com.microsoft.azure.management.resources.fluentcore.arm.implementation._azure_configurable_impl_1a305af8d42d42e60f662ad691c3b01d5c
  - com.microsoft.azure.management.resources.fluentcore.arm.implementation._azure_configurable_impl_1a8629e9cdd8a6aefcdd5723193cdabe7f
  - com.microsoft.azure.management.resources.fluentcore.arm.implementation._azure_configurable_impl_1a342d6ba8e6f08073fd8a51eab9e69e01
  - com.microsoft.azure.management.resources.fluentcore.arm.implementation._azure_configurable_impl_1a5256b96383a591f65cd6d6b711215183
  - com.microsoft.azure.management.resources.fluentcore.arm.implementation._azure_configurable_impl_1a4daa725f678c35c4b8554f961039a265
- uid: com.microsoft.azure.management.resources.implementation._resource_manager._configurable_impl_1af4c9ba25285dcef28300afcf5370a8d1
  id: _configurable_impl_1af4c9ba25285dcef28300afcf5370a8d1
  parent: com.microsoft.azure.management.resources.implementation._resource_manager._configurable_impl
  href: com.microsoft.azure.management.resources.implementation._resource_manager._configurable_impl.yml
  langs:
  - java
  name: authenticate(ServiceClientCredentials credentials)
  fullName: ResourceManager.Authenticated com.microsoft.azure.management.resources.implementation.ResourceManager.ConfigurableImpl.authenticate(ServiceClientCredentials credentials)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/implementation/ResourceManager.java
    startLine: 86
  package: com.microsoft.azure.management.resources.implementation
  syntax:
    content: public ResourceManager.Authenticated authenticate(ServiceClientCredentials credentials)
    parameters:
    - id: credentials
      type: com.microsoft.rest.credentials._service_client_credentials
    return:
      type: 7e525b48
references:
- uid: 7e525b48
  spec.java:
  - name: ResourceManager.Authenticated
    fullName: ResourceManager.Authenticated
- uid: com.microsoft.azure.management.resources.fluentcore.arm.implementation._azure_configurable_impl_1ae9ea36bcd724a700079ad4bc744aec6a
  parent: com.microsoft.azure.management.resources.fluentcore.arm.implementation._azure_configurable_impl
  href: com.microsoft.azure.management.resources.fluentcore.arm.implementation._azure_configurable_impl.yml
  name: AzureConfigurableImpl()
  fullName: com.microsoft.azure.management.resources.fluentcore.arm.implementation.AzureConfigurableImpl< T extends AzureConfigurable< T >.AzureConfigurableImpl()
  type: Method
  syntax:
    content: protected AzureConfigurableImpl()
- uid: com.microsoft.azure.management.resources.fluentcore.arm.implementation._azure_configurable_impl_1a2b00ae56e701d90468d350789e298497
  parent: com.microsoft.azure.management.resources.fluentcore.arm.implementation._azure_configurable_impl
  href: com.microsoft.azure.management.resources.fluentcore.arm.implementation._azure_configurable_impl.yml
  name: buildRestClient(ServiceClientCredentials credentials)
  fullName: RestClient com.microsoft.azure.management.resources.fluentcore.arm.implementation.AzureConfigurableImpl< T extends AzureConfigurable< T >.buildRestClient(ServiceClientCredentials credentials)
  type: Method
  syntax:
    content: protected RestClient buildRestClient(ServiceClientCredentials credentials)
    parameters:
    - id: credentials
      type: com.microsoft.rest.credentials._service_client_credentials
    return:
      type: com.microsoft.azure._rest_client
- uid: com.microsoft.azure.management.resources.fluentcore.arm.implementation._azure_configurable_impl_1aafe59e689115ee8186dfe906aba1e9b6
  parent: com.microsoft.azure.management.resources.fluentcore.arm.implementation._azure_configurable_impl
  href: com.microsoft.azure.management.resources.fluentcore.arm.implementation._azure_configurable_impl.yml
  name: withCallbackExecutor(Executor executor)
  fullName: T com.microsoft.azure.management.resources.fluentcore.arm.implementation.AzureConfigurableImpl< T extends AzureConfigurable< T >.withCallbackExecutor(Executor executor)
  type: Method
  summary: >-
    <p>Sets the executor for async callbacks to run on.</p>

    <p></p>
  syntax:
    content: public T withCallbackExecutor(Executor executor)
    parameters:
    - id: executor
      type: 6f968643
      description: <p>the executor to execute the callbacks. </p>
    return:
      type: 8ce1ecb9
      description: <p>the configurable object itself for chaining </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm.implementation._azure_configurable_impl_1a917f35b91b0f5585ff0d9c591277c4f4
  parent: com.microsoft.azure.management.resources.fluentcore.arm.implementation._azure_configurable_impl
  href: com.microsoft.azure.management.resources.fluentcore.arm.implementation._azure_configurable_impl.yml
  name: withConnectionTimeout(long timeout, TimeUnit unit)
  fullName: T com.microsoft.azure.management.resources.fluentcore.arm.implementation.AzureConfigurableImpl< T extends AzureConfigurable< T >.withConnectionTimeout(long timeout, TimeUnit unit)
  type: Method
  summary: >-
    <p>Set the connection timeout on the HTTP client. Default is 10 seconds.</p>

    <p></p>
  syntax:
    content: public T withConnectionTimeout(long timeout, TimeUnit unit)
    parameters:
    - id: timeout
      type: 0364520f
      description: <p>the timeout numeric value </p>
    - id: unit
      type: 02b8628b
      description: <p>the time unit for the numeric value </p>
    return:
      type: 8ce1ecb9
      description: <p>the configurable object itself for chaining </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm.implementation._azure_configurable_impl_1a5adb6e7076868aadd349d24caa8eb5d8
  parent: com.microsoft.azure.management.resources.fluentcore.arm.implementation._azure_configurable_impl
  href: com.microsoft.azure.management.resources.fluentcore.arm.implementation._azure_configurable_impl.yml
  name: withInterceptor(Interceptor interceptor)
  fullName: T com.microsoft.azure.management.resources.fluentcore.arm.implementation.AzureConfigurableImpl< T extends AzureConfigurable< T >.withInterceptor(Interceptor interceptor)
  type: Method
  summary: >-
    <p>Plug in an interceptor into the HTTP pipeline.</p>

    <p></p>
  syntax:
    content: public T withInterceptor(Interceptor interceptor)
    parameters:
    - id: interceptor
      type: 910a0506
      description: <p>the interceptor to plug in </p>
    return:
      type: 8ce1ecb9
      description: <p>the configurable object itself </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm.implementation._azure_configurable_impl_1a305af8d42d42e60f662ad691c3b01d5c
  parent: com.microsoft.azure.management.resources.fluentcore.arm.implementation._azure_configurable_impl
  href: com.microsoft.azure.management.resources.fluentcore.arm.implementation._azure_configurable_impl.yml
  name: withLogLevel(HttpLoggingInterceptor.Level level)
  fullName: T com.microsoft.azure.management.resources.fluentcore.arm.implementation.AzureConfigurableImpl< T extends AzureConfigurable< T >.withLogLevel(HttpLoggingInterceptor.Level level)
  type: Method
  summary: >-
    <p>Set the logging level on the HTTP client.</p>

    <p></p>
  syntax:
    content: public T withLogLevel(HttpLoggingInterceptor.Level level)
    parameters:
    - id: level
      type: b12c7a8c
      description: <p>the OkHttp logging level </p>
    return:
      type: 8ce1ecb9
      description: <p>the configurable object itself </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm.implementation._azure_configurable_impl_1a8629e9cdd8a6aefcdd5723193cdabe7f
  parent: com.microsoft.azure.management.resources.fluentcore.arm.implementation._azure_configurable_impl
  href: com.microsoft.azure.management.resources.fluentcore.arm.implementation._azure_configurable_impl.yml
  name: withMaxIdleConnections(int maxIdleConnections)
  fullName: T com.microsoft.azure.management.resources.fluentcore.arm.implementation.AzureConfigurableImpl< T extends AzureConfigurable< T >.withMaxIdleConnections(int maxIdleConnections)
  type: Method
  summary: >-
    <p>Set the maximum idle connections for the HTTP client. Default is 5.</p>

    <p></p>
  syntax:
    content: public T withMaxIdleConnections(int maxIdleConnections)
    parameters:
    - id: maxIdleConnections
      type: f75371fa
      description: <p>the maximum idle connections </p>
    return:
      type: 8ce1ecb9
      description: <p>the configurable object itself for chaining </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm.implementation._azure_configurable_impl_1a342d6ba8e6f08073fd8a51eab9e69e01
  parent: com.microsoft.azure.management.resources.fluentcore.arm.implementation._azure_configurable_impl
  href: com.microsoft.azure.management.resources.fluentcore.arm.implementation._azure_configurable_impl.yml
  name: withProxy(Proxy proxy)
  fullName: T com.microsoft.azure.management.resources.fluentcore.arm.implementation.AzureConfigurableImpl< T extends AzureConfigurable< T >.withProxy(Proxy proxy)
  type: Method
  summary: >-
    <p>Sets the proxy for the HTTP client.</p>

    <p></p>
  syntax:
    content: public T withProxy(Proxy proxy)
    parameters:
    - id: proxy
      type: abc26ef5
      description: <p>the proxy to use </p>
    return:
      type: 8ce1ecb9
      description: <p>the configurable object itself for chaining </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm.implementation._azure_configurable_impl_1a5256b96383a591f65cd6d6b711215183
  parent: com.microsoft.azure.management.resources.fluentcore.arm.implementation._azure_configurable_impl
  href: com.microsoft.azure.management.resources.fluentcore.arm.implementation._azure_configurable_impl.yml
  name: withReadTimeout(long timeout, TimeUnit unit)
  fullName: T com.microsoft.azure.management.resources.fluentcore.arm.implementation.AzureConfigurableImpl< T extends AzureConfigurable< T >.withReadTimeout(long timeout, TimeUnit unit)
  type: Method
  summary: >-
    <p>Set the read timeout on the HTTP client. Default is 10 seconds.</p>

    <p></p>
  syntax:
    content: public T withReadTimeout(long timeout, TimeUnit unit)
    parameters:
    - id: timeout
      type: 0364520f
      description: <p>the timeout numeric value </p>
    - id: unit
      type: 02b8628b
      description: <p>the time unit for the numeric value </p>
    return:
      type: 8ce1ecb9
      description: <p>the configurable object itself for chaining </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm.implementation._azure_configurable_impl_1a4daa725f678c35c4b8554f961039a265
  parent: com.microsoft.azure.management.resources.fluentcore.arm.implementation._azure_configurable_impl
  href: com.microsoft.azure.management.resources.fluentcore.arm.implementation._azure_configurable_impl.yml
  name: withUserAgent(String userAgent)
  fullName: T com.microsoft.azure.management.resources.fluentcore.arm.implementation.AzureConfigurableImpl< T extends AzureConfigurable< T >.withUserAgent(String userAgent)
  type: Method
  summary: >-
    <p>Specify the user agent header.</p>

    <p></p>
  syntax:
    content: public T withUserAgent(String userAgent)
    parameters:
    - id: userAgent
      type: "26831127"
      description: <p>the user agent to use </p>
    return:
      type: 8ce1ecb9
      description: <p>the configurable object itself </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm.implementation._azure_configurable_impl
  parent: com.microsoft.azure.management.resources.fluentcore.arm.implementation
  href: com.microsoft.azure.management.resources.fluentcore.arm.implementation._azure_configurable_impl.yml
  name: AzureConfigurableImpl
  fullName: com.microsoft.azure.management.resources.fluentcore.arm.implementation.AzureConfigurableImpl
  type: Class
  summary: >-
    <p>The implementation for <xref href="com.microsoft.azure.management.resources.fluentcore.arm._azure_configurable" data-throw-if-not-resolved="false"></xref> and the base class for configurable implementations.</p>

    <p></p>
  syntax:
    content: public class AzureConfigurableImpl<T extends AzureConfigurable< T>
    typeParameters:
    - type: 8ce1ecb9
- uid: com.microsoft.azure.management.resources.implementation._resource_manager._configurable
  parent: com.microsoft.azure.management.resources.implementation
  href: com.microsoft.azure.management.resources.implementation._resource_manager._configurable.yml
  name: ResourceManager.Configurable
  fullName: com.microsoft.azure.management.resources.implementation.ResourceManager.Configurable
  type: Interface
  summary: <p>The interface allowing configurations to be set. </p>
  syntax:
    content: public interface Configurable
- uid: com.microsoft.rest.credentials._service_client_credentials
  parent: com.microsoft.rest.credentials
  href: com.microsoft.rest.credentials._service_client_credentials.yml
  name: ServiceClientCredentials
  fullName: com.microsoft.rest.credentials.ServiceClientCredentials
  type: Interface
  summary: >-
    <p>

      <xref href="com.microsoft.rest.credentials._service_client_credentials" data-throw-if-not-resolved="false"></xref> is the abstraction for credentials used by ServiceClients accessing REST services. </p>
  syntax:
    content: public interface ServiceClientCredentials
