items:
- uid: com.microsoft.azure.management.resources._deployment._update
  id: _update
  parent: com.microsoft.azure.management.resources
  href: com.microsoft.azure.management.resources._deployment._update.yml
  langs:
  - java
  name: Deployment.Update
  fullName: com.microsoft.azure.management.resources.Deployment.Update
  type: Interface
  source:
    remote:
      path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/Deployment.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/Deployment.java
    startLine: 329
  package: com.microsoft.azure.management.resources
  summary: >-
    <p>The template for a deployment update operation, containing all the settings that can be modified. </p>

    <p>Call <xref href="com.microsoft.azure.management.resources.fluentcore.model._appliable_1a644f6f9ad9fb815ebc68becb7a5e3406" data-throw-if-not-resolved="false"></xref> to apply the changes to the deployment in <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public interface Update extends Appliable< Deployment >,Deployment.UpdateStages.WithTemplate,Deployment.UpdateStages.WithParameters,Deployment.UpdateStages.WithMode
  inheritedMembers:
  - com.microsoft.azure.management.resources.fluentcore.model._appliable_1a644f6f9ad9fb815ebc68becb7a5e3406
  - com.microsoft.azure.management.resources.fluentcore.model._appliable_1a614b76a85ab8e27c82a680c826e7c293
  - com.microsoft.azure.management.resources.fluentcore.model._indexable_1ab0ae133d20d97eaee0480795ee886bde
  - com.microsoft.azure.management.resources._deployment._update_stages._with_mode_1a4c47bd1c5d498e20be15cc74957ad5d5
  - com.microsoft.azure.management.resources._deployment._update_stages._with_parameters_1a15a895e3ecc67407ec2dc96fbe4e72e5
  - com.microsoft.azure.management.resources._deployment._update_stages._with_parameters_1a49b820e6b5e5114e90206faf79d595e7
  - com.microsoft.azure.management.resources._deployment._update_stages._with_parameters_1acc6a928e52301f70ce6700624273ed6b
  - com.microsoft.azure.management.resources._deployment._update_stages._with_template_1a0c00ddcac2185ad79513bd8c9b444e26
  - com.microsoft.azure.management.resources._deployment._update_stages._with_template_1a68431f05a197d0616311ac63cb198350
  - com.microsoft.azure.management.resources._deployment._update_stages._with_template_1a3b9e91fe6e530a23e86a6b271b64b0dd
references:
- uid: com.microsoft.azure.management.resources.fluentcore.model._appliable_1a644f6f9ad9fb815ebc68becb7a5e3406
  parent: com.microsoft.azure.management.resources.fluentcore.model._appliable
  href: com.microsoft.azure.management.resources.fluentcore.model._appliable.yml
  name: apply()
  fullName: T com.microsoft.azure.management.resources.fluentcore.model.Appliable< T >.apply()
  type: Method
  summary: >-
    <p>Execute the update request.</p>

    <p></p>
  syntax:
    content: public T apply()
    return:
      type: 8ce1ecb9
      description: <p>the updated resource </p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._appliable_1a614b76a85ab8e27c82a680c826e7c293
  parent: com.microsoft.azure.management.resources.fluentcore.model._appliable
  href: com.microsoft.azure.management.resources.fluentcore.model._appliable.yml
  name: applyAsync(ServiceCallback< T > callback)
  fullName: ServiceCall com.microsoft.azure.management.resources.fluentcore.model.Appliable< T >.applyAsync(ServiceCallback< T > callback)
  type: Method
  summary: >-
    <p>Execute the update request asynchronously.</p>

    <p></p>
  syntax:
    content: public ServiceCall applyAsync(ServiceCallback< T > callback)
    parameters:
    - id: callback
      type: com.microsoft.rest._service_callback34132889
      description: <p>the callback for success and failure </p>
    return:
      type: com.microsoft.rest._service_call
      description: <p>the handle to the REST call </p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._indexable_1ab0ae133d20d97eaee0480795ee886bde
  parent: com.microsoft.azure.management.resources.fluentcore.model._indexable
  href: com.microsoft.azure.management.resources.fluentcore.model._indexable.yml
  name: key()
  fullName: String com.microsoft.azure.management.resources.fluentcore.model.Indexable.key()
  type: Method
  syntax:
    content: public String key()
    return:
      type: "26831127"
      description: <p>the index key. </p>
- uid: com.microsoft.azure.management.resources._deployment._update_stages._with_mode_1a4c47bd1c5d498e20be15cc74957ad5d5
  parent: com.microsoft.azure.management.resources._deployment._update_stages._with_mode
  href: com.microsoft.azure.management.resources._deployment._update_stages._with_mode.yml
  name: withMode(DeploymentMode mode)
  fullName: Update com.microsoft.azure.management.resources.Deployment.UpdateStages.WithMode.withMode(DeploymentMode mode)
  type: Method
  summary: >-
    <p>Specifies the deployment mode.</p>

    <p></p>
  syntax:
    content: public Update withMode(DeploymentMode mode)
    parameters:
    - id: mode
      type: com.microsoft.azure.management.resources._deployment_mode
      description: <p>the mode of the deployment </p>
    return:
      type: com.microsoft.azure.management.resources._deployment._update
      description: <p>the next stage of the deployment update </p>
- uid: com.microsoft.azure.management.resources._deployment._update_stages._with_parameters_1a15a895e3ecc67407ec2dc96fbe4e72e5
  parent: com.microsoft.azure.management.resources._deployment._update_stages._with_parameters
  href: com.microsoft.azure.management.resources._deployment._update_stages._with_parameters.yml
  name: withParameters(Object parameters)
  fullName: Update com.microsoft.azure.management.resources.Deployment.UpdateStages.WithParameters.withParameters(Object parameters)
  type: Method
  summary: >-
    <p>Specifies the parameters as a Java object.</p>

    <p></p>
  syntax:
    content: public Update withParameters(Object parameters)
    parameters:
    - id: parameters
      type: "79317049"
      description: <p>the Java object </p>
    return:
      type: com.microsoft.azure.management.resources._deployment._update
      description: <p>the next stage of the deployment update </p>
- uid: com.microsoft.azure.management.resources._deployment._update_stages._with_parameters_1a49b820e6b5e5114e90206faf79d595e7
  parent: com.microsoft.azure.management.resources._deployment._update_stages._with_parameters
  href: com.microsoft.azure.management.resources._deployment._update_stages._with_parameters.yml
  name: withParameters(String parametersJson)
  fullName: Update com.microsoft.azure.management.resources.Deployment.UpdateStages.WithParameters.withParameters(String parametersJson)
  type: Method
  summary: >-
    <p>Specifies the parameters as a JSON string.</p>

    <p></p>
  syntax:
    content: public Update withParameters(String parametersJson)
    parameters:
    - id: parametersJson
      type: "26831127"
      description: <p>the JSON string </p>
    return:
      type: com.microsoft.azure.management.resources._deployment._update
      description: <p>the next stage of the deployment update </p>
- uid: com.microsoft.azure.management.resources._deployment._update_stages._with_parameters_1acc6a928e52301f70ce6700624273ed6b
  parent: com.microsoft.azure.management.resources._deployment._update_stages._with_parameters
  href: com.microsoft.azure.management.resources._deployment._update_stages._with_parameters.yml
  name: withParametersLink(String uri, String contentVersion)
  fullName: Update com.microsoft.azure.management.resources.Deployment.UpdateStages.WithParameters.withParametersLink(String uri, String contentVersion)
  type: Method
  summary: >-
    <p>Specifies the parameters as a URL.</p>

    <p></p>
  syntax:
    content: public Update withParametersLink(String uri, String contentVersion)
    parameters:
    - id: uri
      type: "26831127"
      description: <p>the location of the remote parameters file </p>
    - id: contentVersion
      type: "26831127"
      description: <p>the version of the parameters file </p>
    return:
      type: com.microsoft.azure.management.resources._deployment._update
      description: <p>the next stage of the deployment update </p>
- uid: com.microsoft.azure.management.resources._deployment._update_stages._with_template_1a0c00ddcac2185ad79513bd8c9b444e26
  parent: com.microsoft.azure.management.resources._deployment._update_stages._with_template
  href: com.microsoft.azure.management.resources._deployment._update_stages._with_template.yml
  name: withTemplate(Object template)
  fullName: Update com.microsoft.azure.management.resources.Deployment.UpdateStages.WithTemplate.withTemplate(Object template)
  type: Method
  summary: >-
    <p>Specifies the template as a Java object.</p>

    <p></p>
  syntax:
    content: public Update withTemplate(Object template)
    parameters:
    - id: template
      type: "79317049"
      description: <p>the Java object </p>
    return:
      type: com.microsoft.azure.management.resources._deployment._update
      description: <p>the next stage of the deployment update </p>
- uid: com.microsoft.azure.management.resources._deployment._update_stages._with_template_1a68431f05a197d0616311ac63cb198350
  parent: com.microsoft.azure.management.resources._deployment._update_stages._with_template
  href: com.microsoft.azure.management.resources._deployment._update_stages._with_template.yml
  name: withTemplate(String templateJson)
  fullName: Update com.microsoft.azure.management.resources.Deployment.UpdateStages.WithTemplate.withTemplate(String templateJson)
  type: Method
  summary: >-
    <p>Specifies the template as a JSON string.</p>

    <p></p>
  syntax:
    content: public Update withTemplate(String templateJson)
    parameters:
    - id: templateJson
      type: "26831127"
      description: <p>the JSON string </p>
    return:
      type: com.microsoft.azure.management.resources._deployment._update
      description: <p>the next stage of the deployment update </p>
- uid: com.microsoft.azure.management.resources._deployment._update_stages._with_template_1a3b9e91fe6e530a23e86a6b271b64b0dd
  parent: com.microsoft.azure.management.resources._deployment._update_stages._with_template
  href: com.microsoft.azure.management.resources._deployment._update_stages._with_template.yml
  name: withTemplateLink(String uri, String contentVersion)
  fullName: Update com.microsoft.azure.management.resources.Deployment.UpdateStages.WithTemplate.withTemplateLink(String uri, String contentVersion)
  type: Method
  summary: >-
    <p>Specifies the template as a URL.</p>

    <p></p>
  syntax:
    content: public Update withTemplateLink(String uri, String contentVersion)
    parameters:
    - id: uri
      type: "26831127"
      description: <p>the location of the remote template file </p>
    - id: contentVersion
      type: "26831127"
      description: <p>the version of the template file </p>
    return:
      type: com.microsoft.azure.management.resources._deployment._update
      description: <p>the next stage of the deployment update </p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._appliable
  parent: com.microsoft.azure.management.resources.fluentcore.model
  href: com.microsoft.azure.management.resources.fluentcore.model._appliable.yml
  name: Appliable<T>
  fullName: com.microsoft.azure.management.resources.fluentcore.model.Appliable<T>
  type: Interface
  summary: >-
    <p>The base interface for all template interfaces that support update operations.</p>

    <p></p>
  syntax:
    content: public interface Appliable<T> extends Indexable
    typeParameters:
    - type: 8ce1ecb9
      description: <p>the type of the resource returned from the update. </p>
- uid: com.microsoft.azure.management.resources._deployment._update_stages._with_template
  parent: com.microsoft.azure.management.resources
  href: com.microsoft.azure.management.resources._deployment._update_stages._with_template.yml
  name: Deployment.UpdateStages.WithTemplate
  fullName: com.microsoft.azure.management.resources.Deployment.UpdateStages.WithTemplate
  type: Interface
  summary: <p>A deployment update allowing to change the template. </p>
  syntax:
    content: public interface WithTemplate
- uid: com.microsoft.azure.management.resources._deployment._update_stages._with_parameters
  parent: com.microsoft.azure.management.resources
  href: com.microsoft.azure.management.resources._deployment._update_stages._with_parameters.yml
  name: Deployment.UpdateStages.WithParameters
  fullName: com.microsoft.azure.management.resources.Deployment.UpdateStages.WithParameters
  type: Interface
  summary: <p>A deployment update allowing to change the parameters. </p>
  syntax:
    content: public interface WithParameters
- uid: com.microsoft.azure.management.resources._deployment._update_stages._with_mode
  parent: com.microsoft.azure.management.resources
  href: com.microsoft.azure.management.resources._deployment._update_stages._with_mode.yml
  name: Deployment.UpdateStages.WithMode
  fullName: com.microsoft.azure.management.resources.Deployment.UpdateStages.WithMode
  type: Interface
  summary: <p>A deployment update allowing to change the deployment mode. </p>
  syntax:
    content: public interface WithMode
- uid: com.microsoft.azure.management.resources.implementation._deployment_impl
- uid: com.microsoft.azure._azure
  parent: com.microsoft.azure
  href: com.microsoft.azure._azure.yml
  name: Azure
  fullName: com.microsoft.azure.Azure
  type: Class
  summary: <p>The entry point for accessing resource management APIs in <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class Azure
