items:
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_load_balancer
  id: _with_load_balancer
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_load_balancer.withExistingLoadBalancer(LoadBalancer)
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_load_balancer.yml
  langs:
  - java
  name: NicIpConfiguration.UpdateStages.WithLoadBalancer
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.UpdateStages.WithLoadBalancer
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
    startLine: 538
  package: com.microsoft.azure.management.network
  summary: <p>The stage of the network interface's IP configuration allowing to specify the load balancer to associate this IP configuration with. </p>
  syntax:
    content: public interface WithLoadBalancer
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_load_balancer.withExistingLoadBalancer(LoadBalancer)
  id: withExistingLoadBalancer(LoadBalancer)
  parent: com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_load_balancer
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_load_balancer.yml
  langs:
  - java
  name: withExistingLoadBalancer(LoadBalancer loadBalancer)
  fullName: WithBackendAddressPool com.microsoft.azure.management.network.NicIpConfiguration.UpdateStages.WithLoadBalancer.withExistingLoadBalancer(LoadBalancer loadBalancer)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
    startLine: 544
  package: com.microsoft.azure.management.network
  summary: <p>Specifies the load balancer to associate this IP configuration with. </p>
  syntax:
    content: public WithBackendAddressPool withExistingLoadBalancer(LoadBalancer loadBalancer)
    parameters:
    - id: loadBalancer
      type: com.microsoft.azure.management.network._load_balancer
      description: <p>an existing load balancer </p>
    return:
      type: com.microsoft.azure.management.network._nic_ip_configuration._update_7d1d94805bfe36a8463df749eca66b2b
      description: <p>the next stage of the update </p>
references:
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._nic_ip_configuration._update.yml
  name: NicIpConfiguration.Update
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.Update
  type: Interface
  summary: <p>The entirety of a network interface IP configuration update as part of a network interface update. </p>
  syntax:
    content: public interface Update extends Settable< NetworkInterface.Update >,NicIpConfiguration.UpdateStages.WithSubnet,NicIpConfiguration.UpdateStages.WithPrivateIp,NicIpConfiguration.UpdateStages.WithPublicIpAddress,NicIpConfiguration.UpdateStages.WithLoadBalancer,NicIpConfiguration.UpdateStages.WithBackendAddressPool
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_7d1d94805bfe36a8463df749eca66b2b
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_7d1d94805bfe36a8463df749eca66b2b.yml
  name: NicIpConfiguration.UpdateStages.WithBackendAddressPool
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.UpdateStages.WithBackendAddressPool
  type: Interface
  summary: <p>The stage of the network interface IP configuration update allowing to specify the load balancer back end address pool to add it to. </p>
  syntax:
    content: public interface WithBackendAddressPool
- uid: com.microsoft.azure.management.network._load_balancer
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._load_balancer.yml
  name: LoadBalancer
  fullName: com.microsoft.azure.management.network.LoadBalancer
  type: Interface
  summary: <p>Entry point for load balancer management API in <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public interface LoadBalancer extends GroupableResource,Refreshable< LoadBalancer >,Wrapper< LoadBalancerInner >,Updatable< LoadBalancer.Update >
