items:
- uid: com.microsoft.azure.management.compute.implementation.api._disk_encryption_settings
  id: _disk_encryption_settings
  parent: com.microsoft.azure.management.compute.implementation.api
  children:
  - com.microsoft.azure.management.compute.implementation.api._disk_encryption_settings_1adfdfe2eff7289e8f2740e589641e6ae9
  - com.microsoft.azure.management.compute.implementation.api._disk_encryption_settings_1ae9124cb67ddb0ec7ee22e9cf314ab060
  - com.microsoft.azure.management.compute.implementation.api._disk_encryption_settings_1a448124cd2c517ac3f9078ec226c43087
  - com.microsoft.azure.management.compute.implementation.api._disk_encryption_settings_1a4acc9f9053d7d8c36a6786c4c05a6e06
  - com.microsoft.azure.management.compute.implementation.api._disk_encryption_settings_1a5c97148d4ae6e41e1e62a58055a880a0
  - com.microsoft.azure.management.compute.implementation.api._disk_encryption_settings_1a853644013ca88f379d36ff85c3f121ac
  href: com.microsoft.azure.management.compute.implementation.api._disk_encryption_settings.yml
  langs:
  - java
  name: DiskEncryptionSettings
  fullName: com.microsoft.azure.management.compute.implementation.api.DiskEncryptionSettings
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/api/DiskEncryptionSettings.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/api/DiskEncryptionSettings.java
    startLine: 13
  package: com.microsoft.azure.management.compute.implementation.api
  summary: <p>Describes a Encryption Settings for a Disk. </p>
  syntax: &o1
    content: public class DiskEncryptionSettings
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.compute.implementation.api._disk_encryption_settings_1adfdfe2eff7289e8f2740e589641e6ae9
  id: _disk_encryption_settings_1adfdfe2eff7289e8f2740e589641e6ae9
  parent: com.microsoft.azure.management.compute.implementation.api._disk_encryption_settings
  href: com.microsoft.azure.management.compute.implementation.api._disk_encryption_settings.yml
  langs:
  - java
  name: diskEncryptionKey()
  fullName: KeyVaultSecretReference com.microsoft.azure.management.compute.implementation.api.DiskEncryptionSettings.diskEncryptionKey()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/api/DiskEncryptionSettings.java
    startLine: 36
  package: com.microsoft.azure.management.compute.implementation.api
  summary: >-
    <p>Get the diskEncryptionKey value.</p>

    <p></p>
  syntax:
    content: public KeyVaultSecretReference diskEncryptionKey()
    return:
      type: com.microsoft.azure.management.compute.implementation.api._key_vault_secret_reference
      description: <p>the diskEncryptionKey value </p>
- uid: com.microsoft.azure.management.compute.implementation.api._disk_encryption_settings_1ae9124cb67ddb0ec7ee22e9cf314ab060
  id: _disk_encryption_settings_1ae9124cb67ddb0ec7ee22e9cf314ab060
  parent: com.microsoft.azure.management.compute.implementation.api._disk_encryption_settings
  href: com.microsoft.azure.management.compute.implementation.api._disk_encryption_settings.yml
  langs:
  - java
  name: enabled()
  fullName: Boolean com.microsoft.azure.management.compute.implementation.api.DiskEncryptionSettings.enabled()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/api/DiskEncryptionSettings.java
    startLine: 76
  package: com.microsoft.azure.management.compute.implementation.api
  summary: >-
    <p>Get the enabled value.</p>

    <p></p>
  syntax:
    content: public Boolean enabled()
    return:
      type: 866c2227
      description: <p>the enabled value </p>
- uid: com.microsoft.azure.management.compute.implementation.api._disk_encryption_settings_1a448124cd2c517ac3f9078ec226c43087
  id: _disk_encryption_settings_1a448124cd2c517ac3f9078ec226c43087
  parent: com.microsoft.azure.management.compute.implementation.api._disk_encryption_settings
  href: com.microsoft.azure.management.compute.implementation.api._disk_encryption_settings.yml
  langs:
  - java
  name: keyEncryptionKey()
  fullName: KeyVaultKeyReference com.microsoft.azure.management.compute.implementation.api.DiskEncryptionSettings.keyEncryptionKey()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/api/DiskEncryptionSettings.java
    startLine: 56
  package: com.microsoft.azure.management.compute.implementation.api
  summary: >-
    <p>Get the keyEncryptionKey value.</p>

    <p></p>
  syntax:
    content: public KeyVaultKeyReference keyEncryptionKey()
    return:
      type: com.microsoft.azure.management.compute.implementation.api._key_vault_key_reference
      description: <p>the keyEncryptionKey value </p>
- uid: com.microsoft.azure.management.compute.implementation.api._disk_encryption_settings_1a4acc9f9053d7d8c36a6786c4c05a6e06
  id: _disk_encryption_settings_1a4acc9f9053d7d8c36a6786c4c05a6e06
  parent: com.microsoft.azure.management.compute.implementation.api._disk_encryption_settings
  href: com.microsoft.azure.management.compute.implementation.api._disk_encryption_settings.yml
  langs:
  - java
  name: withDiskEncryptionKey(KeyVaultSecretReference diskEncryptionKey)
  fullName: DiskEncryptionSettings com.microsoft.azure.management.compute.implementation.api.DiskEncryptionSettings.withDiskEncryptionKey(KeyVaultSecretReference diskEncryptionKey)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/api/DiskEncryptionSettings.java
    startLine: 46
  package: com.microsoft.azure.management.compute.implementation.api
  summary: >-
    <p>Set the diskEncryptionKey value.</p>

    <p></p>
  syntax:
    content: public DiskEncryptionSettings withDiskEncryptionKey(KeyVaultSecretReference diskEncryptionKey)
    parameters:
    - id: diskEncryptionKey
      type: com.microsoft.azure.management.compute.implementation.api._key_vault_secret_reference
      description: <p>the diskEncryptionKey value to set </p>
    return:
      type: com.microsoft.azure.management.compute.implementation.api._disk_encryption_settings
      description: <p>the <xref href="com.microsoft.azure.management.compute.implementation.api._disk_encryption_settings" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.compute.implementation.api._disk_encryption_settings_1a5c97148d4ae6e41e1e62a58055a880a0
  id: _disk_encryption_settings_1a5c97148d4ae6e41e1e62a58055a880a0
  parent: com.microsoft.azure.management.compute.implementation.api._disk_encryption_settings
  href: com.microsoft.azure.management.compute.implementation.api._disk_encryption_settings.yml
  langs:
  - java
  name: withEnabled(Boolean enabled)
  fullName: DiskEncryptionSettings com.microsoft.azure.management.compute.implementation.api.DiskEncryptionSettings.withEnabled(Boolean enabled)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/api/DiskEncryptionSettings.java
    startLine: 86
  package: com.microsoft.azure.management.compute.implementation.api
  summary: >-
    <p>Set the enabled value.</p>

    <p></p>
  syntax:
    content: public DiskEncryptionSettings withEnabled(Boolean enabled)
    parameters:
    - id: enabled
      type: 866c2227
      description: <p>the enabled value to set </p>
    return:
      type: com.microsoft.azure.management.compute.implementation.api._disk_encryption_settings
      description: <p>the <xref href="com.microsoft.azure.management.compute.implementation.api._disk_encryption_settings" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.compute.implementation.api._disk_encryption_settings_1a853644013ca88f379d36ff85c3f121ac
  id: _disk_encryption_settings_1a853644013ca88f379d36ff85c3f121ac
  parent: com.microsoft.azure.management.compute.implementation.api._disk_encryption_settings
  href: com.microsoft.azure.management.compute.implementation.api._disk_encryption_settings.yml
  langs:
  - java
  name: withKeyEncryptionKey(KeyVaultKeyReference keyEncryptionKey)
  fullName: DiskEncryptionSettings com.microsoft.azure.management.compute.implementation.api.DiskEncryptionSettings.withKeyEncryptionKey(KeyVaultKeyReference keyEncryptionKey)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/api/DiskEncryptionSettings.java
    startLine: 66
  package: com.microsoft.azure.management.compute.implementation.api
  summary: >-
    <p>Set the keyEncryptionKey value.</p>

    <p></p>
  syntax:
    content: public DiskEncryptionSettings withKeyEncryptionKey(KeyVaultKeyReference keyEncryptionKey)
    parameters:
    - id: keyEncryptionKey
      type: com.microsoft.azure.management.compute.implementation.api._key_vault_key_reference
      description: <p>the keyEncryptionKey value to set </p>
    return:
      type: com.microsoft.azure.management.compute.implementation.api._disk_encryption_settings
      description: <p>the <xref href="com.microsoft.azure.management.compute.implementation.api._disk_encryption_settings" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: 866c2227
  spec.java:
  - name: Boolean
    fullName: Boolean
- uid: com.microsoft.azure.management.compute.implementation.api._key_vault_secret_reference
  parent: com.microsoft.azure.management.compute.implementation.api
  href: com.microsoft.azure.management.compute.implementation.api._key_vault_secret_reference.yml
  name: KeyVaultSecretReference
  fullName: com.microsoft.azure.management.compute.implementation.api.KeyVaultSecretReference
  type: Class
  summary: <p>Describes a reference to Key Vault Secret. </p>
  syntax:
    content: public class KeyVaultSecretReference
- uid: com.microsoft.azure.management.compute.implementation.api._key_vault_key_reference
  parent: com.microsoft.azure.management.compute.implementation.api
  href: com.microsoft.azure.management.compute.implementation.api._key_vault_key_reference.yml
  name: KeyVaultKeyReference
  fullName: com.microsoft.azure.management.compute.implementation.api.KeyVaultKeyReference
  type: Class
  summary: <p>Describes a reference to Key Vault Key. </p>
  syntax:
    content: public class KeyVaultKeyReference
- uid: com.microsoft.azure.management.compute.implementation.api._disk_encryption_settings
  parent: com.microsoft.azure.management.compute.implementation.api
  href: com.microsoft.azure.management.compute.implementation.api._disk_encryption_settings.yml
  name: DiskEncryptionSettings
  fullName: com.microsoft.azure.management.compute.implementation.api.DiskEncryptionSettings
  type: Class
  summary: <p>Describes a Encryption Settings for a Disk. </p>
  syntax: *o1
