items:
- uid: com.microsoft.azure.management.website.implementation._site_logs_config_inner
  id: _site_logs_config_inner
  parent: com.microsoft.azure.management.website.implementation
  children:
  - com.microsoft.azure.management.website.implementation._site_logs_config_inner.applicationLogs()
  - com.microsoft.azure.management.website.implementation._site_logs_config_inner.detailedErrorMessages()
  - com.microsoft.azure.management.website.implementation._site_logs_config_inner.failedRequestsTracing()
  - com.microsoft.azure.management.website.implementation._site_logs_config_inner.httpLogs()
  - com.microsoft.azure.management.website.implementation._site_logs_config_inner.withApplicationLogs(ApplicationLogsConfig)
  - com.microsoft.azure.management.website.implementation._site_logs_config_inner.withDetailedErrorMessages(EnabledConfig)
  - com.microsoft.azure.management.website.implementation._site_logs_config_inner.withFailedRequestsTracing(EnabledConfig)
  - com.microsoft.azure.management.website.implementation._site_logs_config_inner.withHttpLogs(HttpLogsConfig)
  href: com.microsoft.azure.management.website.implementation._site_logs_config_inner.yml
  langs:
  - java
  name: SiteLogsConfigInner
  fullName: com.microsoft.azure.management.website.implementation.SiteLogsConfigInner
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/SiteLogsConfigInner.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/SiteLogsConfigInner.java
    startLine: 21
  package: com.microsoft.azure.management.website.implementation
  summary: <p>Configuration of <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> web site. </p>
  syntax: &o1
    content: public class SiteLogsConfigInner extends Resource
  inheritance:
  - java.lang.Object
  - com.microsoft.azure._resource
  inheritedMembers:
  - com.microsoft.azure._resource.getTags()
  - com.microsoft.azure._resource.id()
  - com.microsoft.azure._resource.location()
  - com.microsoft.azure._resource.name()
  - com.microsoft.azure._resource.type()
  - com.microsoft.azure._resource.withLocation(String)
  - com.microsoft.azure._resource.withTags(Map< String, String >)
- uid: com.microsoft.azure.management.website.implementation._site_logs_config_inner.applicationLogs()
  id: applicationLogs()
  parent: com.microsoft.azure.management.website.implementation._site_logs_config_inner
  href: com.microsoft.azure.management.website.implementation._site_logs_config_inner.yml
  langs:
  - java
  name: applicationLogs()
  fullName: ApplicationLogsConfig com.microsoft.azure.management.website.implementation.SiteLogsConfigInner.applicationLogs()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/SiteLogsConfigInner.java
    startLine: 51
  package: com.microsoft.azure.management.website.implementation
  summary: >-
    <p>Get the applicationLogs value.</p>

    <p></p>
  syntax:
    content: public ApplicationLogsConfig applicationLogs()
    return:
      type: com.microsoft.azure.management.website._application_logs_config
      description: <p>the applicationLogs value </p>
- uid: com.microsoft.azure.management.website.implementation._site_logs_config_inner.detailedErrorMessages()
  id: detailedErrorMessages()
  parent: com.microsoft.azure.management.website.implementation._site_logs_config_inner
  href: com.microsoft.azure.management.website.implementation._site_logs_config_inner.yml
  langs:
  - java
  name: detailedErrorMessages()
  fullName: EnabledConfig com.microsoft.azure.management.website.implementation.SiteLogsConfigInner.detailedErrorMessages()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/SiteLogsConfigInner.java
    startLine: 111
  package: com.microsoft.azure.management.website.implementation
  summary: >-
    <p>Get the detailedErrorMessages value.</p>

    <p></p>
  syntax:
    content: public EnabledConfig detailedErrorMessages()
    return:
      type: com.microsoft.azure.management.website._enabled_config
      description: <p>the detailedErrorMessages value </p>
- uid: com.microsoft.azure.management.website.implementation._site_logs_config_inner.failedRequestsTracing()
  id: failedRequestsTracing()
  parent: com.microsoft.azure.management.website.implementation._site_logs_config_inner
  href: com.microsoft.azure.management.website.implementation._site_logs_config_inner.yml
  langs:
  - java
  name: failedRequestsTracing()
  fullName: EnabledConfig com.microsoft.azure.management.website.implementation.SiteLogsConfigInner.failedRequestsTracing()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/SiteLogsConfigInner.java
    startLine: 91
  package: com.microsoft.azure.management.website.implementation
  summary: >-
    <p>Get the failedRequestsTracing value.</p>

    <p></p>
  syntax:
    content: public EnabledConfig failedRequestsTracing()
    return:
      type: com.microsoft.azure.management.website._enabled_config
      description: <p>the failedRequestsTracing value </p>
- uid: com.microsoft.azure.management.website.implementation._site_logs_config_inner.httpLogs()
  id: httpLogs()
  parent: com.microsoft.azure.management.website.implementation._site_logs_config_inner
  href: com.microsoft.azure.management.website.implementation._site_logs_config_inner.yml
  langs:
  - java
  name: httpLogs()
  fullName: HttpLogsConfig com.microsoft.azure.management.website.implementation.SiteLogsConfigInner.httpLogs()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/SiteLogsConfigInner.java
    startLine: 71
  package: com.microsoft.azure.management.website.implementation
  summary: >-
    <p>Get the httpLogs value.</p>

    <p></p>
  syntax:
    content: public HttpLogsConfig httpLogs()
    return:
      type: com.microsoft.azure.management.website._http_logs_config
      description: <p>the httpLogs value </p>
- uid: com.microsoft.azure.management.website.implementation._site_logs_config_inner.withApplicationLogs(ApplicationLogsConfig)
  id: withApplicationLogs(ApplicationLogsConfig)
  parent: com.microsoft.azure.management.website.implementation._site_logs_config_inner
  href: com.microsoft.azure.management.website.implementation._site_logs_config_inner.yml
  langs:
  - java
  name: withApplicationLogs(ApplicationLogsConfig applicationLogs)
  fullName: SiteLogsConfigInner com.microsoft.azure.management.website.implementation.SiteLogsConfigInner.withApplicationLogs(ApplicationLogsConfig applicationLogs)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/SiteLogsConfigInner.java
    startLine: 61
  package: com.microsoft.azure.management.website.implementation
  summary: >-
    <p>Set the applicationLogs value.</p>

    <p></p>
  syntax:
    content: public SiteLogsConfigInner withApplicationLogs(ApplicationLogsConfig applicationLogs)
    parameters:
    - id: applicationLogs
      type: com.microsoft.azure.management.website._application_logs_config
      description: <p>the applicationLogs value to set </p>
    return:
      type: com.microsoft.azure.management.website.implementation._site_logs_config_inner
      description: <p>the <xref href="com.microsoft.azure.management.website.implementation._site_logs_config_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.website.implementation._site_logs_config_inner.withDetailedErrorMessages(EnabledConfig)
  id: withDetailedErrorMessages(EnabledConfig)
  parent: com.microsoft.azure.management.website.implementation._site_logs_config_inner
  href: com.microsoft.azure.management.website.implementation._site_logs_config_inner.yml
  langs:
  - java
  name: withDetailedErrorMessages(EnabledConfig detailedErrorMessages)
  fullName: SiteLogsConfigInner com.microsoft.azure.management.website.implementation.SiteLogsConfigInner.withDetailedErrorMessages(EnabledConfig detailedErrorMessages)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/SiteLogsConfigInner.java
    startLine: 121
  package: com.microsoft.azure.management.website.implementation
  summary: >-
    <p>Set the detailedErrorMessages value.</p>

    <p></p>
  syntax:
    content: public SiteLogsConfigInner withDetailedErrorMessages(EnabledConfig detailedErrorMessages)
    parameters:
    - id: detailedErrorMessages
      type: com.microsoft.azure.management.website._enabled_config
      description: <p>the detailedErrorMessages value to set </p>
    return:
      type: com.microsoft.azure.management.website.implementation._site_logs_config_inner
      description: <p>the <xref href="com.microsoft.azure.management.website.implementation._site_logs_config_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.website.implementation._site_logs_config_inner.withFailedRequestsTracing(EnabledConfig)
  id: withFailedRequestsTracing(EnabledConfig)
  parent: com.microsoft.azure.management.website.implementation._site_logs_config_inner
  href: com.microsoft.azure.management.website.implementation._site_logs_config_inner.yml
  langs:
  - java
  name: withFailedRequestsTracing(EnabledConfig failedRequestsTracing)
  fullName: SiteLogsConfigInner com.microsoft.azure.management.website.implementation.SiteLogsConfigInner.withFailedRequestsTracing(EnabledConfig failedRequestsTracing)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/SiteLogsConfigInner.java
    startLine: 101
  package: com.microsoft.azure.management.website.implementation
  summary: >-
    <p>Set the failedRequestsTracing value.</p>

    <p></p>
  syntax:
    content: public SiteLogsConfigInner withFailedRequestsTracing(EnabledConfig failedRequestsTracing)
    parameters:
    - id: failedRequestsTracing
      type: com.microsoft.azure.management.website._enabled_config
      description: <p>the failedRequestsTracing value to set </p>
    return:
      type: com.microsoft.azure.management.website.implementation._site_logs_config_inner
      description: <p>the <xref href="com.microsoft.azure.management.website.implementation._site_logs_config_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.website.implementation._site_logs_config_inner.withHttpLogs(HttpLogsConfig)
  id: withHttpLogs(HttpLogsConfig)
  parent: com.microsoft.azure.management.website.implementation._site_logs_config_inner
  href: com.microsoft.azure.management.website.implementation._site_logs_config_inner.yml
  langs:
  - java
  name: withHttpLogs(HttpLogsConfig httpLogs)
  fullName: SiteLogsConfigInner com.microsoft.azure.management.website.implementation.SiteLogsConfigInner.withHttpLogs(HttpLogsConfig httpLogs)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/SiteLogsConfigInner.java
    startLine: 81
  package: com.microsoft.azure.management.website.implementation
  summary: >-
    <p>Set the httpLogs value.</p>

    <p></p>
  syntax:
    content: public SiteLogsConfigInner withHttpLogs(HttpLogsConfig httpLogs)
    parameters:
    - id: httpLogs
      type: com.microsoft.azure.management.website._http_logs_config
      description: <p>the httpLogs value to set </p>
    return:
      type: com.microsoft.azure.management.website.implementation._site_logs_config_inner
      description: <p>the <xref href="com.microsoft.azure.management.website.implementation._site_logs_config_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: com.microsoft.azure._resource.getTags()
  parent: com.microsoft.azure._resource
  href: com.microsoft.azure._resource.yml
  name: getTags()
  fullName: Map<String, String> com.microsoft.azure.Resource.getTags()
  type: Method
  summary: >-
    <p>Get the tags value.</p>

    <p></p>
  syntax:
    content: public Map< String, String > getTags()
    return:
      type: 805937fc
      description: <p>the tags value </p>
- uid: com.microsoft.azure._resource.id()
  parent: com.microsoft.azure._resource
  href: com.microsoft.azure._resource.yml
  name: id()
  fullName: String com.microsoft.azure.Resource.id()
  type: Method
  summary: >-
    <p>Get the id value.</p>

    <p></p>
  syntax:
    content: public String id()
    return:
      type: "26831127"
      description: <p>the id value </p>
- uid: com.microsoft.azure._resource.location()
  parent: com.microsoft.azure._resource
  href: com.microsoft.azure._resource.yml
  name: location()
  fullName: String com.microsoft.azure.Resource.location()
  type: Method
  summary: >-
    <p>Get the location value.</p>

    <p></p>
  syntax:
    content: public String location()
    return:
      type: "26831127"
      description: <p>the location value </p>
- uid: com.microsoft.azure._resource.name()
  parent: com.microsoft.azure._resource
  href: com.microsoft.azure._resource.yml
  name: name()
  fullName: String com.microsoft.azure.Resource.name()
  type: Method
  summary: >-
    <p>Get the name value.</p>

    <p></p>
  syntax:
    content: public String name()
    return:
      type: "26831127"
      description: <p>the name value </p>
- uid: com.microsoft.azure._resource.type()
  parent: com.microsoft.azure._resource
  href: com.microsoft.azure._resource.yml
  name: type()
  fullName: String com.microsoft.azure.Resource.type()
  type: Method
  summary: >-
    <p>Get the type value.</p>

    <p></p>
  syntax:
    content: public String type()
    return:
      type: "26831127"
      description: <p>the type value </p>
- uid: com.microsoft.azure._resource.withLocation(String)
  parent: com.microsoft.azure._resource
  href: com.microsoft.azure._resource.yml
  name: withLocation(String location)
  fullName: Resource com.microsoft.azure.Resource.withLocation(String location)
  type: Method
  summary: >-
    <p>Set the location value.</p>

    <p></p>
  syntax:
    content: public Resource withLocation(String location)
    parameters:
    - id: location
      type: "26831127"
      description: <p>the location value to set </p>
    return:
      type: com.microsoft.azure._resource
      description: <p>the resource itself </p>
- uid: com.microsoft.azure._resource.withTags(Map< String, String >)
  parent: com.microsoft.azure._resource
  href: com.microsoft.azure._resource.yml
  name: withTags(Map< String, String > tags)
  fullName: Resource com.microsoft.azure.Resource.withTags(Map< String, String > tags)
  type: Method
  summary: >-
    <p>Set the tags value.</p>

    <p></p>
  syntax:
    content: public Resource withTags(Map< String, String > tags)
    parameters:
    - id: tags
      type: 805937fc
      description: <p>the tags value to set </p>
    return:
      type: com.microsoft.azure._resource
      description: <p>the resource itself </p>
- uid: com.microsoft.azure._resource
  parent: com.microsoft.azure
  href: com.microsoft.azure._resource.yml
  name: Resource
  fullName: com.microsoft.azure.Resource
  type: Class
  summary: <p>The <xref href="com.microsoft.azure._resource" data-throw-if-not-resolved="false"></xref> model. </p>
  syntax:
    content: public class Resource
- uid: com.microsoft.azure.management.website._application_logs_config
  parent: com.microsoft.azure.management.website
  href: com.microsoft.azure.management.website._application_logs_config.yml
  name: ApplicationLogsConfig
  fullName: com.microsoft.azure.management.website.ApplicationLogsConfig
  type: Class
  summary: <p>Application logs configuration. </p>
  syntax:
    content: public class ApplicationLogsConfig
- uid: com.microsoft.azure.management.website._http_logs_config
  parent: com.microsoft.azure.management.website
  href: com.microsoft.azure.management.website._http_logs_config.yml
  name: HttpLogsConfig
  fullName: com.microsoft.azure.management.website.HttpLogsConfig
  type: Class
  summary: <p>Http logs configuration. </p>
  syntax:
    content: public class HttpLogsConfig
- uid: com.microsoft.azure.management.website._enabled_config
  parent: com.microsoft.azure.management.website
  href: com.microsoft.azure.management.website._enabled_config.yml
  name: EnabledConfig
  fullName: com.microsoft.azure.management.website.EnabledConfig
  type: Class
  summary: <p>Enabled configuration. </p>
  syntax:
    content: public class EnabledConfig
- uid: com.microsoft.azure.management.website.implementation._site_logs_config_inner
  parent: com.microsoft.azure.management.website.implementation
  href: com.microsoft.azure.management.website.implementation._site_logs_config_inner.yml
  name: SiteLogsConfigInner
  fullName: com.microsoft.azure.management.website.implementation.SiteLogsConfigInner
  type: Class
  summary: <p>Configuration of <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> web site. </p>
  syntax: *o1
- uid: com.microsoft.azure._azure
  parent: com.microsoft.azure
  href: com.microsoft.azure._azure.yml
  name: Azure
  fullName: com.microsoft.azure.Azure
  type: Class
  summary: <p>The entry point for accessing resource management APIs in <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class Azure
