items:
- uid: com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration
  id: _virtual_machine_scale_set_i_p_configuration
  parent: com.microsoft.azure.management.compute
  children:
  - com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration_1a1a4712c9cc140e6fd2015de020521b73
  - com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration_1a108dd4928e514165b9c67fa905246ec3
  - com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration_1a908a463a7a1ec6a7a01a270a0bd6c708
  - com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration_1ad337b430eea1349bf9a2659692373cf8
  - com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration_1a0083c47a6fe9e6b95332bd5620a61c94
  - com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration_1a9e7691a735a68b93a1987a4a28090471
  - com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration_1a3a03b7391ade57270bad55f9db0f45ba
  - com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration_1a2f9afdc63ae92beb527cd655a676b798
  - com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration_1af24c1e1b6f7637a60d53044abe96f321
  - com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration_1a302c91fb843937186c888ea920113d94
  href: com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration.yml
  langs:
  - java
  name: VirtualMachineScaleSetIPConfiguration
  fullName: com.microsoft.azure.management.compute.VirtualMachineScaleSetIPConfiguration
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineScaleSetIPConfiguration.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineScaleSetIPConfiguration.java
    startLine: 19
  package: com.microsoft.azure.management.compute
  summary: <p>Describes a virtual machine scale set network profile's IP configuration. </p>
  syntax: &o1
    content: public class VirtualMachineScaleSetIPConfiguration extends SubResource
  inheritance:
  - java.lang.Object
  - com.microsoft.azure._sub_resource
  inheritedMembers:
  - com.microsoft.azure._sub_resource_1a92e02020e7fca6a3d2284bc1db599e52
  - com.microsoft.azure._sub_resource_1a522b0146c9247308f3752dd123100d8a
- uid: com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration_1a1a4712c9cc140e6fd2015de020521b73
  id: _virtual_machine_scale_set_i_p_configuration_1a1a4712c9cc140e6fd2015de020521b73
  parent: com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration
  href: com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration.yml
  langs:
  - java
  name: applicationGatewayBackendAddressPools()
  fullName: List<SubResource> com.microsoft.azure.management.compute.VirtualMachineScaleSetIPConfiguration.applicationGatewayBackendAddressPools()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineScaleSetIPConfiguration.java
    startLine: 95
  package: com.microsoft.azure.management.compute
  summary: >-
    <p>Get the applicationGatewayBackendAddressPools value.</p>

    <p></p>
  syntax:
    content: public List< SubResource > applicationGatewayBackendAddressPools()
    return:
      type: f6a6204dcom.microsoft.azure._sub_resource9ec3e006
      description: <p>the applicationGatewayBackendAddressPools value </p>
- uid: com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration_1a108dd4928e514165b9c67fa905246ec3
  id: _virtual_machine_scale_set_i_p_configuration_1a108dd4928e514165b9c67fa905246ec3
  parent: com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration
  href: com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration.yml
  langs:
  - java
  name: loadBalancerBackendAddressPools()
  fullName: List<SubResource> com.microsoft.azure.management.compute.VirtualMachineScaleSetIPConfiguration.loadBalancerBackendAddressPools()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineScaleSetIPConfiguration.java
    startLine: 115
  package: com.microsoft.azure.management.compute
  summary: >-
    <p>Get the loadBalancerBackendAddressPools value.</p>

    <p></p>
  syntax:
    content: public List< SubResource > loadBalancerBackendAddressPools()
    return:
      type: f6a6204dcom.microsoft.azure._sub_resource9ec3e006
      description: <p>the loadBalancerBackendAddressPools value </p>
- uid: com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration_1a908a463a7a1ec6a7a01a270a0bd6c708
  id: _virtual_machine_scale_set_i_p_configuration_1a908a463a7a1ec6a7a01a270a0bd6c708
  parent: com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration
  href: com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration.yml
  langs:
  - java
  name: loadBalancerInboundNatPools()
  fullName: List<SubResource> com.microsoft.azure.management.compute.VirtualMachineScaleSetIPConfiguration.loadBalancerInboundNatPools()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineScaleSetIPConfiguration.java
    startLine: 135
  package: com.microsoft.azure.management.compute
  summary: >-
    <p>Get the loadBalancerInboundNatPools value.</p>

    <p></p>
  syntax:
    content: public List< SubResource > loadBalancerInboundNatPools()
    return:
      type: f6a6204dcom.microsoft.azure._sub_resource9ec3e006
      description: <p>the loadBalancerInboundNatPools value </p>
- uid: com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration_1ad337b430eea1349bf9a2659692373cf8
  id: _virtual_machine_scale_set_i_p_configuration_1ad337b430eea1349bf9a2659692373cf8
  parent: com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration
  href: com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration.yml
  langs:
  - java
  name: name()
  fullName: String com.microsoft.azure.management.compute.VirtualMachineScaleSetIPConfiguration.name()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineScaleSetIPConfiguration.java
    startLine: 55
  package: com.microsoft.azure.management.compute
  summary: >-
    <p>Get the name value.</p>

    <p></p>
  syntax:
    content: public String name()
    return:
      type: "26831127"
      description: <p>the name value </p>
- uid: com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration_1a0083c47a6fe9e6b95332bd5620a61c94
  id: _virtual_machine_scale_set_i_p_configuration_1a0083c47a6fe9e6b95332bd5620a61c94
  parent: com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration
  href: com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration.yml
  langs:
  - java
  name: subnet()
  fullName: ApiEntityReference com.microsoft.azure.management.compute.VirtualMachineScaleSetIPConfiguration.subnet()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineScaleSetIPConfiguration.java
    startLine: 75
  package: com.microsoft.azure.management.compute
  summary: >-
    <p>Get the subnet value.</p>

    <p></p>
  syntax:
    content: public ApiEntityReference subnet()
    return:
      type: com.microsoft.azure.management.compute._api_entity_reference
      description: <p>the subnet value </p>
- uid: com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration_1a9e7691a735a68b93a1987a4a28090471
  id: _virtual_machine_scale_set_i_p_configuration_1a9e7691a735a68b93a1987a4a28090471
  parent: com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration
  href: com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration.yml
  langs:
  - java
  name: withApplicationGatewayBackendAddressPools(List< SubResource > applicationGatewayBackendAddressPools)
  fullName: VirtualMachineScaleSetIPConfiguration com.microsoft.azure.management.compute.VirtualMachineScaleSetIPConfiguration.withApplicationGatewayBackendAddressPools(List< SubResource > applicationGatewayBackendAddressPools)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineScaleSetIPConfiguration.java
    startLine: 105
  package: com.microsoft.azure.management.compute
  summary: >-
    <p>Set the applicationGatewayBackendAddressPools value.</p>

    <p></p>
  syntax:
    content: public VirtualMachineScaleSetIPConfiguration withApplicationGatewayBackendAddressPools(List< SubResource > applicationGatewayBackendAddressPools)
    parameters:
    - id: applicationGatewayBackendAddressPools
      type: f6a6204dcom.microsoft.azure._sub_resource9ec3e006
      description: <p>the applicationGatewayBackendAddressPools value to set </p>
    return:
      type: com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration
      description: <p>the <xref href="com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration_1a3a03b7391ade57270bad55f9db0f45ba
  id: _virtual_machine_scale_set_i_p_configuration_1a3a03b7391ade57270bad55f9db0f45ba
  parent: com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration
  href: com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration.yml
  langs:
  - java
  name: withLoadBalancerBackendAddressPools(List< SubResource > loadBalancerBackendAddressPools)
  fullName: VirtualMachineScaleSetIPConfiguration com.microsoft.azure.management.compute.VirtualMachineScaleSetIPConfiguration.withLoadBalancerBackendAddressPools(List< SubResource > loadBalancerBackendAddressPools)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineScaleSetIPConfiguration.java
    startLine: 125
  package: com.microsoft.azure.management.compute
  summary: >-
    <p>Set the loadBalancerBackendAddressPools value.</p>

    <p></p>
  syntax:
    content: public VirtualMachineScaleSetIPConfiguration withLoadBalancerBackendAddressPools(List< SubResource > loadBalancerBackendAddressPools)
    parameters:
    - id: loadBalancerBackendAddressPools
      type: f6a6204dcom.microsoft.azure._sub_resource9ec3e006
      description: <p>the loadBalancerBackendAddressPools value to set </p>
    return:
      type: com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration
      description: <p>the <xref href="com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration_1a2f9afdc63ae92beb527cd655a676b798
  id: _virtual_machine_scale_set_i_p_configuration_1a2f9afdc63ae92beb527cd655a676b798
  parent: com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration
  href: com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration.yml
  langs:
  - java
  name: withLoadBalancerInboundNatPools(List< SubResource > loadBalancerInboundNatPools)
  fullName: VirtualMachineScaleSetIPConfiguration com.microsoft.azure.management.compute.VirtualMachineScaleSetIPConfiguration.withLoadBalancerInboundNatPools(List< SubResource > loadBalancerInboundNatPools)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineScaleSetIPConfiguration.java
    startLine: 145
  package: com.microsoft.azure.management.compute
  summary: >-
    <p>Set the loadBalancerInboundNatPools value.</p>

    <p></p>
  syntax:
    content: public VirtualMachineScaleSetIPConfiguration withLoadBalancerInboundNatPools(List< SubResource > loadBalancerInboundNatPools)
    parameters:
    - id: loadBalancerInboundNatPools
      type: f6a6204dcom.microsoft.azure._sub_resource9ec3e006
      description: <p>the loadBalancerInboundNatPools value to set </p>
    return:
      type: com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration
      description: <p>the <xref href="com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration_1af24c1e1b6f7637a60d53044abe96f321
  id: _virtual_machine_scale_set_i_p_configuration_1af24c1e1b6f7637a60d53044abe96f321
  parent: com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration
  href: com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration.yml
  langs:
  - java
  name: withName(String name)
  fullName: VirtualMachineScaleSetIPConfiguration com.microsoft.azure.management.compute.VirtualMachineScaleSetIPConfiguration.withName(String name)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineScaleSetIPConfiguration.java
    startLine: 65
  package: com.microsoft.azure.management.compute
  summary: >-
    <p>Set the name value.</p>

    <p></p>
  syntax:
    content: public VirtualMachineScaleSetIPConfiguration withName(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>the name value to set </p>
    return:
      type: com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration
      description: <p>the <xref href="com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration_1a302c91fb843937186c888ea920113d94
  id: _virtual_machine_scale_set_i_p_configuration_1a302c91fb843937186c888ea920113d94
  parent: com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration
  href: com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration.yml
  langs:
  - java
  name: withSubnet(ApiEntityReference subnet)
  fullName: VirtualMachineScaleSetIPConfiguration com.microsoft.azure.management.compute.VirtualMachineScaleSetIPConfiguration.withSubnet(ApiEntityReference subnet)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineScaleSetIPConfiguration.java
    startLine: 85
  package: com.microsoft.azure.management.compute
  summary: >-
    <p>Set the subnet value.</p>

    <p></p>
  syntax:
    content: public VirtualMachineScaleSetIPConfiguration withSubnet(ApiEntityReference subnet)
    parameters:
    - id: subnet
      type: com.microsoft.azure.management.compute._api_entity_reference
      description: <p>the subnet value to set </p>
    return:
      type: com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration
      description: <p>the <xref href="com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: f6a6204dcom.microsoft.azure._sub_resource9ec3e006
  spec.java:
  - name: 'List< '
    fullName: 'List< '
  - uid: com.microsoft.azure._sub_resource
    name: SubResource
    fullName: com.microsoft.azure.SubResource
    href: com.microsoft.azure._sub_resource.yml
  - name: ' >'
    fullName: ' >'
- uid: com.microsoft.azure._sub_resource_1a92e02020e7fca6a3d2284bc1db599e52
  parent: com.microsoft.azure._sub_resource
  href: com.microsoft.azure._sub_resource.yml
  name: id()
  fullName: String com.microsoft.azure.SubResource.id()
  type: Method
  summary: >-
    <p>Get the id value.</p>

    <p></p>
  syntax:
    content: public String id()
    return:
      type: "26831127"
      description: <p>the id value </p>
- uid: com.microsoft.azure._sub_resource_1a522b0146c9247308f3752dd123100d8a
  parent: com.microsoft.azure._sub_resource
  href: com.microsoft.azure._sub_resource.yml
  name: withId(String id)
  fullName: SubResource com.microsoft.azure.SubResource.withId(String id)
  type: Method
  summary: >-
    <p>Set the id value.</p>

    <p></p>
  syntax:
    content: public SubResource withId(String id)
    parameters:
    - id: id
      type: "26831127"
      description: <p>the id value to set </p>
    return:
      type: com.microsoft.azure._sub_resource
      description: <p>the sub resource itself </p>
- uid: com.microsoft.azure._sub_resource
  parent: com.microsoft.azure
  href: com.microsoft.azure._sub_resource.yml
  name: SubResource
  fullName: com.microsoft.azure.SubResource
  type: Class
  summary: <p>The <xref href="com.microsoft.azure._sub_resource" data-throw-if-not-resolved="false"></xref> model. </p>
  syntax:
    content: public class SubResource
- uid: com.microsoft.azure.management.compute._api_entity_reference
  parent: com.microsoft.azure.management.compute
  href: com.microsoft.azure.management.compute._api_entity_reference.yml
  name: ApiEntityReference
  fullName: com.microsoft.azure.management.compute.ApiEntityReference
  type: Class
  summary: <p>The API entity reference. </p>
  syntax:
    content: public class ApiEntityReference
- uid: com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration
  parent: com.microsoft.azure.management.compute
  href: com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration.yml
  name: VirtualMachineScaleSetIPConfiguration
  fullName: com.microsoft.azure.management.compute.VirtualMachineScaleSetIPConfiguration
  type: Class
  summary: <p>Describes a virtual machine scale set network profile's IP configuration. </p>
  syntax: *o1
