items:
- uid: com.microsoft.azure.credentials._azure_environment
  id: _azure_environment
  parent: com.microsoft.azure.credentials
  children:
  - com.microsoft.azure.credentials._azure_environment_1ab9ba8d013c65a5a102346f8213bdac25
  - com.microsoft.azure.credentials._azure_environment_1a8daef52c29d061be83b8a709f03ed82d
  - com.microsoft.azure.credentials._azure_environment_1ae75c2364200108704c87c5db3d55edd6
  - com.microsoft.azure.credentials._azure_environment_1aaddd3d68473cf2cf07dd9117b76bf816
  - com.microsoft.azure.credentials._azure_environment_1afe850691ba2c12114422307bc5734179
  - com.microsoft.azure.credentials._azure_environment_1a336a9ba243ee6d592b66c35d8bdbc43a
  href: com.microsoft.azure.credentials._azure_environment.yml
  langs:
  - java
  name: AzureEnvironment
  fullName: com.microsoft.azure.credentials.AzureEnvironment
  type: Class
  source:
    remote: &o0
      path: runtimes/azure-android-client-authentication/src/main/java/com/microsoft/azure/credentials/AzureEnvironment.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: runtimes/azure-android-client-authentication/src/main/java/com/microsoft/azure/credentials/AzureEnvironment.java
    startLine: 12
  package: com.microsoft.azure.credentials
  summary: <p>An instance of this class describes an environment in <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: &o1
    content: public class AzureEnvironment
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.credentials._azure_environment_1ab9ba8d013c65a5a102346f8213bdac25
  id: _azure_environment_1ab9ba8d013c65a5a102346f8213bdac25
  parent: com.microsoft.azure.credentials._azure_environment
  href: com.microsoft.azure.credentials._azure_environment.yml
  langs:
  - java
  name: AZURE
  fullName: final AzureEnvironment com.microsoft.azure.credentials.AzureEnvironment.AZURE
  type: Field
  source:
    remote: *o0
    path: runtimes/azure-android-client-authentication/src/main/java/com/microsoft/azure/credentials/AzureEnvironment.java
    startLine: 44
  package: com.microsoft.azure.credentials
  summary: <p>Provides the settings for authentication with <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: >-
      public static final AzureEnvironment AZURE= new AzureEnvironment(
                  "https://login.windows.net/",
                  "https://management.core.windows.net/",
                  true)
    return:
      type: 93de0ef9com.microsoft.azure.credentials._azure_environment
- uid: com.microsoft.azure.credentials._azure_environment_1a8daef52c29d061be83b8a709f03ed82d
  id: _azure_environment_1a8daef52c29d061be83b8a709f03ed82d
  parent: com.microsoft.azure.credentials._azure_environment
  href: com.microsoft.azure.credentials._azure_environment.yml
  langs:
  - java
  name: AZURE_CHINA
  fullName: final AzureEnvironment com.microsoft.azure.credentials.AzureEnvironment.AZURE_CHINA
  type: Field
  source:
    remote: *o0
    path: runtimes/azure-android-client-authentication/src/main/java/com/microsoft/azure/credentials/AzureEnvironment.java
    startLine: 52
  package: com.microsoft.azure.credentials
  summary: <p>Provides the settings for authentication with <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> China. </p>
  syntax:
    content: >-
      public static final AzureEnvironment AZURE_CHINA= new AzureEnvironment(
                  "https://login.chinacloudapi.cn/",
                  "https://management.core.chinacloudapi.cn/",
                  true)
    return:
      type: 93de0ef9com.microsoft.azure.credentials._azure_environment
- uid: com.microsoft.azure.credentials._azure_environment_1ae75c2364200108704c87c5db3d55edd6
  id: _azure_environment_1ae75c2364200108704c87c5db3d55edd6
  parent: com.microsoft.azure.credentials._azure_environment
  href: com.microsoft.azure.credentials._azure_environment.yml
  langs:
  - java
  name: AzureEnvironment(String authenticationEndpoint, String tokenAudience, boolean validateAuthority)
  fullName: com.microsoft.azure.credentials.AzureEnvironment.AzureEnvironment(String authenticationEndpoint, String tokenAudience, boolean validateAuthority)
  type: Constructor
  source:
    remote: *o0
    path: runtimes/azure-android-client-authentication/src/main/java/com/microsoft/azure/credentials/AzureEnvironment.java
    startLine: 35
  package: com.microsoft.azure.credentials
  summary: >-
    <p>Initializes an instance of <xref href="com.microsoft.azure.credentials._azure_environment" data-throw-if-not-resolved="false"></xref> class.</p>

    <p></p>
  syntax:
    content: public AzureEnvironment(String authenticationEndpoint, String tokenAudience, boolean validateAuthority)
    parameters:
    - id: authenticationEndpoint
      type: "26831127"
      description: <p>ActiveDirectory Endpoint for the <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> Environment. </p>
    - id: tokenAudience
      type: "26831127"
      description: <p>token audience for an endpoint. </p>
    - id: validateAuthority
      type: 4fc6e284
      description: <p>whether the authentication endpoint should be validated with <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> AD. </p>
- uid: com.microsoft.azure.credentials._azure_environment_1aaddd3d68473cf2cf07dd9117b76bf816
  id: _azure_environment_1aaddd3d68473cf2cf07dd9117b76bf816
  parent: com.microsoft.azure.credentials._azure_environment
  href: com.microsoft.azure.credentials._azure_environment.yml
  langs:
  - java
  name: getAuthenticationEndpoint()
  fullName: String com.microsoft.azure.credentials.AzureEnvironment.getAuthenticationEndpoint()
  type: Method
  source:
    remote: *o0
    path: runtimes/azure-android-client-authentication/src/main/java/com/microsoft/azure/credentials/AzureEnvironment.java
    startLine: 62
  package: com.microsoft.azure.credentials
  summary: >-
    <p>Gets the ActiveDirectory Endpoint for the <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> Environment.</p>

    <p></p>
  syntax:
    content: public String getAuthenticationEndpoint()
    return:
      type: "26831127"
      description: <p>the ActiveDirectory Endpoint for the <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> Environment. </p>
- uid: com.microsoft.azure.credentials._azure_environment_1afe850691ba2c12114422307bc5734179
  id: _azure_environment_1afe850691ba2c12114422307bc5734179
  parent: com.microsoft.azure.credentials._azure_environment
  href: com.microsoft.azure.credentials._azure_environment.yml
  langs:
  - java
  name: getTokenAudience()
  fullName: String com.microsoft.azure.credentials.AzureEnvironment.getTokenAudience()
  type: Method
  source:
    remote: *o0
    path: runtimes/azure-android-client-authentication/src/main/java/com/microsoft/azure/credentials/AzureEnvironment.java
    startLine: 71
  package: com.microsoft.azure.credentials
  summary: >-
    <p>Gets the token audience for an endpoint.</p>

    <p></p>
  syntax:
    content: public String getTokenAudience()
    return:
      type: "26831127"
      description: <p>the token audience for an endpoint. </p>
- uid: com.microsoft.azure.credentials._azure_environment_1a336a9ba243ee6d592b66c35d8bdbc43a
  id: _azure_environment_1a336a9ba243ee6d592b66c35d8bdbc43a
  parent: com.microsoft.azure.credentials._azure_environment
  href: com.microsoft.azure.credentials._azure_environment.yml
  langs:
  - java
  name: isValidateAuthority()
  fullName: boolean com.microsoft.azure.credentials.AzureEnvironment.isValidateAuthority()
  type: Method
  source:
    remote: *o0
    path: runtimes/azure-android-client-authentication/src/main/java/com/microsoft/azure/credentials/AzureEnvironment.java
    startLine: 82
  package: com.microsoft.azure.credentials
  summary: >-
    <p>Gets whether the authentication endpoint should be validated with <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> AD.</p>

    <p></p>
  syntax:
    content: public boolean isValidateAuthority()
    return:
      type: 4fc6e284
      description: <p>true if the authentication endpoint should be validated with <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> AD, false otherwise. </p>
references:
- uid: 93de0ef9com.microsoft.azure.credentials._azure_environment
  spec.java:
  - name: 'final '
    fullName: 'final '
  - uid: com.microsoft.azure.credentials._azure_environment
    name: AzureEnvironment
    fullName: com.microsoft.azure.credentials.AzureEnvironment
    href: com.microsoft.azure.credentials._azure_environment.yml
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: com.microsoft.azure._azure
  parent: com.microsoft.azure
  href: com.microsoft.azure._azure.yml
  name: Azure
  fullName: com.microsoft.azure.Azure
  type: Class
  summary: <p>The entry point for accessing resource management APIs in <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class Azure
- uid: com.microsoft.azure.credentials._azure_environment
  parent: com.microsoft.azure.credentials
  href: com.microsoft.azure.credentials._azure_environment.yml
  name: AzureEnvironment
  fullName: com.microsoft.azure.credentials.AzureEnvironment
  type: Class
  summary: <p>An instance of this class describes an environment in <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: *o1
