items:
- uid: com.microsoft.azure.management.network._application_gateway_url_path_map
  id: _application_gateway_url_path_map
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._application_gateway_url_path_map_1ab7413d163cb6376e3abd111ad8ff39c0
  - com.microsoft.azure.management.network._application_gateway_url_path_map_1af40100c1677a17b0c8ed07acc5fabd01
  - com.microsoft.azure.management.network._application_gateway_url_path_map_1a8144afc57a9034be9e6d1273f085a6de
  - com.microsoft.azure.management.network._application_gateway_url_path_map_1a997178f511730ae336aff4e5746991bf
  - com.microsoft.azure.management.network._application_gateway_url_path_map_1a91457ca6e929b4e565ba77e556f86b35
  - com.microsoft.azure.management.network._application_gateway_url_path_map_1ab2895838983a7bded1a987bfdcbd769b
  - com.microsoft.azure.management.network._application_gateway_url_path_map_1ad6b88a02d98afc4ee37b5ae4ebab4713
  - com.microsoft.azure.management.network._application_gateway_url_path_map_1a45de00b5a45513243c3622639fd8af14
  - com.microsoft.azure.management.network._application_gateway_url_path_map_1a89e1b976ce49cc77cb9de8435c7d707c
  - com.microsoft.azure.management.network._application_gateway_url_path_map_1aba662450de0bb1d17a7768c433206b8b
  - com.microsoft.azure.management.network._application_gateway_url_path_map_1a1539390048b21c4cf6b0eba7197e65ce
  - com.microsoft.azure.management.network._application_gateway_url_path_map_1a176fb8aebc9762d44aaf3f5115c346af
  href: com.microsoft.azure.management.network._application_gateway_url_path_map.yml
  langs:
  - java
  name: ApplicationGatewayUrlPathMap
  fullName: com.microsoft.azure.management.network.ApplicationGatewayUrlPathMap
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayUrlPathMap.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayUrlPathMap.java
    startLine: 19
  package: com.microsoft.azure.management.network
  summary: <p>UrlPathMap of application gateway. </p>
  syntax: &o1
    content: public class ApplicationGatewayUrlPathMap extends SubResource
  inheritance:
  - java.lang.Object
  - com.microsoft.azure._sub_resource
  inheritedMembers:
  - com.microsoft.azure._sub_resource_1a92e02020e7fca6a3d2284bc1db599e52
  - com.microsoft.azure._sub_resource_1a522b0146c9247308f3752dd123100d8a
- uid: com.microsoft.azure.management.network._application_gateway_url_path_map_1ab7413d163cb6376e3abd111ad8ff39c0
  id: _application_gateway_url_path_map_1ab7413d163cb6376e3abd111ad8ff39c0
  parent: com.microsoft.azure.management.network._application_gateway_url_path_map
  href: com.microsoft.azure.management.network._application_gateway_url_path_map.yml
  langs:
  - java
  name: defaultBackendAddressPool()
  fullName: SubResource com.microsoft.azure.management.network.ApplicationGatewayUrlPathMap.defaultBackendAddressPool()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayUrlPathMap.java
    startLine: 61
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the defaultBackendAddressPool value.</p>

    <p></p>
  syntax:
    content: public SubResource defaultBackendAddressPool()
    return:
      type: com.microsoft.azure._sub_resource
      description: <p>the defaultBackendAddressPool value </p>
- uid: com.microsoft.azure.management.network._application_gateway_url_path_map_1af40100c1677a17b0c8ed07acc5fabd01
  id: _application_gateway_url_path_map_1af40100c1677a17b0c8ed07acc5fabd01
  parent: com.microsoft.azure.management.network._application_gateway_url_path_map
  href: com.microsoft.azure.management.network._application_gateway_url_path_map.yml
  langs:
  - java
  name: defaultBackendHttpSettings()
  fullName: SubResource com.microsoft.azure.management.network.ApplicationGatewayUrlPathMap.defaultBackendHttpSettings()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayUrlPathMap.java
    startLine: 81
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the defaultBackendHttpSettings value.</p>

    <p></p>
  syntax:
    content: public SubResource defaultBackendHttpSettings()
    return:
      type: com.microsoft.azure._sub_resource
      description: <p>the defaultBackendHttpSettings value </p>
- uid: com.microsoft.azure.management.network._application_gateway_url_path_map_1a8144afc57a9034be9e6d1273f085a6de
  id: _application_gateway_url_path_map_1a8144afc57a9034be9e6d1273f085a6de
  parent: com.microsoft.azure.management.network._application_gateway_url_path_map
  href: com.microsoft.azure.management.network._application_gateway_url_path_map.yml
  langs:
  - java
  name: etag()
  fullName: String com.microsoft.azure.management.network.ApplicationGatewayUrlPathMap.etag()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayUrlPathMap.java
    startLine: 161
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the etag value.</p>

    <p></p>
  syntax:
    content: public String etag()
    return:
      type: "26831127"
      description: <p>the etag value </p>
- uid: com.microsoft.azure.management.network._application_gateway_url_path_map_1a997178f511730ae336aff4e5746991bf
  id: _application_gateway_url_path_map_1a997178f511730ae336aff4e5746991bf
  parent: com.microsoft.azure.management.network._application_gateway_url_path_map
  href: com.microsoft.azure.management.network._application_gateway_url_path_map.yml
  langs:
  - java
  name: name()
  fullName: String com.microsoft.azure.management.network.ApplicationGatewayUrlPathMap.name()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayUrlPathMap.java
    startLine: 141
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the name value.</p>

    <p></p>
  syntax:
    content: public String name()
    return:
      type: "26831127"
      description: <p>the name value </p>
- uid: com.microsoft.azure.management.network._application_gateway_url_path_map_1a91457ca6e929b4e565ba77e556f86b35
  id: _application_gateway_url_path_map_1a91457ca6e929b4e565ba77e556f86b35
  parent: com.microsoft.azure.management.network._application_gateway_url_path_map
  href: com.microsoft.azure.management.network._application_gateway_url_path_map.yml
  langs:
  - java
  name: pathRules()
  fullName: List<ApplicationGatewayPathRule> com.microsoft.azure.management.network.ApplicationGatewayUrlPathMap.pathRules()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayUrlPathMap.java
    startLine: 101
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the pathRules value.</p>

    <p></p>
  syntax:
    content: public List< ApplicationGatewayPathRule > pathRules()
    return:
      type: f6a6204dcom.microsoft.azure.management.network._application_gateway_path_rule9ec3e006
      description: <p>the pathRules value </p>
- uid: com.microsoft.azure.management.network._application_gateway_url_path_map_1ab2895838983a7bded1a987bfdcbd769b
  id: _application_gateway_url_path_map_1ab2895838983a7bded1a987bfdcbd769b
  parent: com.microsoft.azure.management.network._application_gateway_url_path_map
  href: com.microsoft.azure.management.network._application_gateway_url_path_map.yml
  langs:
  - java
  name: provisioningState()
  fullName: String com.microsoft.azure.management.network.ApplicationGatewayUrlPathMap.provisioningState()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayUrlPathMap.java
    startLine: 121
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the provisioningState value.</p>

    <p></p>
  syntax:
    content: public String provisioningState()
    return:
      type: "26831127"
      description: <p>the provisioningState value </p>
- uid: com.microsoft.azure.management.network._application_gateway_url_path_map_1ad6b88a02d98afc4ee37b5ae4ebab4713
  id: _application_gateway_url_path_map_1ad6b88a02d98afc4ee37b5ae4ebab4713
  parent: com.microsoft.azure.management.network._application_gateway_url_path_map
  href: com.microsoft.azure.management.network._application_gateway_url_path_map.yml
  langs:
  - java
  name: withDefaultBackendAddressPool(SubResource defaultBackendAddressPool)
  fullName: ApplicationGatewayUrlPathMap com.microsoft.azure.management.network.ApplicationGatewayUrlPathMap.withDefaultBackendAddressPool(SubResource defaultBackendAddressPool)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayUrlPathMap.java
    startLine: 71
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the defaultBackendAddressPool value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewayUrlPathMap withDefaultBackendAddressPool(SubResource defaultBackendAddressPool)
    parameters:
    - id: defaultBackendAddressPool
      type: com.microsoft.azure._sub_resource
      description: <p>the defaultBackendAddressPool value to set </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_url_path_map
      description: <p>the <xref href="com.microsoft.azure.management.network._application_gateway_url_path_map" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network._application_gateway_url_path_map_1a45de00b5a45513243c3622639fd8af14
  id: _application_gateway_url_path_map_1a45de00b5a45513243c3622639fd8af14
  parent: com.microsoft.azure.management.network._application_gateway_url_path_map
  href: com.microsoft.azure.management.network._application_gateway_url_path_map.yml
  langs:
  - java
  name: withDefaultBackendHttpSettings(SubResource defaultBackendHttpSettings)
  fullName: ApplicationGatewayUrlPathMap com.microsoft.azure.management.network.ApplicationGatewayUrlPathMap.withDefaultBackendHttpSettings(SubResource defaultBackendHttpSettings)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayUrlPathMap.java
    startLine: 91
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the defaultBackendHttpSettings value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewayUrlPathMap withDefaultBackendHttpSettings(SubResource defaultBackendHttpSettings)
    parameters:
    - id: defaultBackendHttpSettings
      type: com.microsoft.azure._sub_resource
      description: <p>the defaultBackendHttpSettings value to set </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_url_path_map
      description: <p>the <xref href="com.microsoft.azure.management.network._application_gateway_url_path_map" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network._application_gateway_url_path_map_1a89e1b976ce49cc77cb9de8435c7d707c
  id: _application_gateway_url_path_map_1a89e1b976ce49cc77cb9de8435c7d707c
  parent: com.microsoft.azure.management.network._application_gateway_url_path_map
  href: com.microsoft.azure.management.network._application_gateway_url_path_map.yml
  langs:
  - java
  name: withEtag(String etag)
  fullName: ApplicationGatewayUrlPathMap com.microsoft.azure.management.network.ApplicationGatewayUrlPathMap.withEtag(String etag)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayUrlPathMap.java
    startLine: 171
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the etag value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewayUrlPathMap withEtag(String etag)
    parameters:
    - id: etag
      type: "26831127"
      description: <p>the etag value to set </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_url_path_map
      description: <p>the <xref href="com.microsoft.azure.management.network._application_gateway_url_path_map" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network._application_gateway_url_path_map_1aba662450de0bb1d17a7768c433206b8b
  id: _application_gateway_url_path_map_1aba662450de0bb1d17a7768c433206b8b
  parent: com.microsoft.azure.management.network._application_gateway_url_path_map
  href: com.microsoft.azure.management.network._application_gateway_url_path_map.yml
  langs:
  - java
  name: withName(String name)
  fullName: ApplicationGatewayUrlPathMap com.microsoft.azure.management.network.ApplicationGatewayUrlPathMap.withName(String name)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayUrlPathMap.java
    startLine: 151
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the name value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewayUrlPathMap withName(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>the name value to set </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_url_path_map
      description: <p>the <xref href="com.microsoft.azure.management.network._application_gateway_url_path_map" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network._application_gateway_url_path_map_1a1539390048b21c4cf6b0eba7197e65ce
  id: _application_gateway_url_path_map_1a1539390048b21c4cf6b0eba7197e65ce
  parent: com.microsoft.azure.management.network._application_gateway_url_path_map
  href: com.microsoft.azure.management.network._application_gateway_url_path_map.yml
  langs:
  - java
  name: withPathRules(List< ApplicationGatewayPathRule > pathRules)
  fullName: ApplicationGatewayUrlPathMap com.microsoft.azure.management.network.ApplicationGatewayUrlPathMap.withPathRules(List< ApplicationGatewayPathRule > pathRules)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayUrlPathMap.java
    startLine: 111
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the pathRules value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewayUrlPathMap withPathRules(List< ApplicationGatewayPathRule > pathRules)
    parameters:
    - id: pathRules
      type: f6a6204dcom.microsoft.azure.management.network._application_gateway_path_rule9ec3e006
      description: <p>the pathRules value to set </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_url_path_map
      description: <p>the <xref href="com.microsoft.azure.management.network._application_gateway_url_path_map" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network._application_gateway_url_path_map_1a176fb8aebc9762d44aaf3f5115c346af
  id: _application_gateway_url_path_map_1a176fb8aebc9762d44aaf3f5115c346af
  parent: com.microsoft.azure.management.network._application_gateway_url_path_map
  href: com.microsoft.azure.management.network._application_gateway_url_path_map.yml
  langs:
  - java
  name: withProvisioningState(String provisioningState)
  fullName: ApplicationGatewayUrlPathMap com.microsoft.azure.management.network.ApplicationGatewayUrlPathMap.withProvisioningState(String provisioningState)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayUrlPathMap.java
    startLine: 131
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the provisioningState value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewayUrlPathMap withProvisioningState(String provisioningState)
    parameters:
    - id: provisioningState
      type: "26831127"
      description: <p>the provisioningState value to set </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_url_path_map
      description: <p>the <xref href="com.microsoft.azure.management.network._application_gateway_url_path_map" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: f6a6204dcom.microsoft.azure.management.network._application_gateway_path_rule9ec3e006
  spec.java:
  - name: 'List< '
    fullName: 'List< '
  - uid: com.microsoft.azure.management.network._application_gateway_path_rule
    name: ApplicationGatewayPathRule
    fullName: com.microsoft.azure.management.network.ApplicationGatewayPathRule
    href: com.microsoft.azure.management.network._application_gateway_path_rule.yml
  - name: ' >'
    fullName: ' >'
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure._sub_resource_1a92e02020e7fca6a3d2284bc1db599e52
  parent: com.microsoft.azure._sub_resource
  href: com.microsoft.azure._sub_resource.yml
  name: id()
  fullName: String com.microsoft.azure.SubResource.id()
  type: Method
  summary: >-
    <p>Get the id value.</p>

    <p></p>
  syntax:
    content: public String id()
    return:
      type: "26831127"
      description: <p>the id value </p>
- uid: com.microsoft.azure._sub_resource_1a522b0146c9247308f3752dd123100d8a
  parent: com.microsoft.azure._sub_resource
  href: com.microsoft.azure._sub_resource.yml
  name: withId(String id)
  fullName: SubResource com.microsoft.azure.SubResource.withId(String id)
  type: Method
  summary: >-
    <p>Set the id value.</p>

    <p></p>
  syntax:
    content: public SubResource withId(String id)
    parameters:
    - id: id
      type: "26831127"
      description: <p>the id value to set </p>
    return:
      type: com.microsoft.azure._sub_resource
      description: <p>the sub resource itself </p>
- uid: com.microsoft.azure._sub_resource
  parent: com.microsoft.azure
  href: com.microsoft.azure._sub_resource.yml
  name: SubResource
  fullName: com.microsoft.azure.SubResource
  type: Class
  summary: <p>The <xref href="com.microsoft.azure._sub_resource" data-throw-if-not-resolved="false"></xref> model. </p>
  syntax:
    content: public class SubResource
- uid: com.microsoft.azure.management.network._application_gateway_path_rule
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_path_rule.yml
  name: ApplicationGatewayPathRule
  fullName: com.microsoft.azure.management.network.ApplicationGatewayPathRule
  type: Class
  summary: <p>Path rule of URL path map of application gateway. </p>
  syntax:
    content: public class ApplicationGatewayPathRule extends SubResource
- uid: com.microsoft.azure.management.network._application_gateway_url_path_map
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_url_path_map.yml
  name: ApplicationGatewayUrlPathMap
  fullName: com.microsoft.azure.management.network.ApplicationGatewayUrlPathMap
  type: Class
  summary: <p>UrlPathMap of application gateway. </p>
  syntax: *o1
