items:
- uid: com.microsoft.azure.management.network.implementation.api._bgp_settings
  id: _bgp_settings
  parent: com.microsoft.azure.management.network.implementation.api
  children:
  - com.microsoft.azure.management.network.implementation.api._bgp_settings_1a8a479064b2b817449ac20b73f2d59fc9
  - com.microsoft.azure.management.network.implementation.api._bgp_settings_1adb5424ea821f76f6a5cd59eaf83ff76e
  - com.microsoft.azure.management.network.implementation.api._bgp_settings_1ad91aa234ac65a4efa2ae8df4d08891c5
  - com.microsoft.azure.management.network.implementation.api._bgp_settings_1abf79f8ac2df5b7c94cde64637bbe0776
  - com.microsoft.azure.management.network.implementation.api._bgp_settings_1a1b1063d59642849f11b6cca65a33a383
  - com.microsoft.azure.management.network.implementation.api._bgp_settings_1a7bb8b3a490e0a039279314be58605414
  href: com.microsoft.azure.management.network.implementation.api._bgp_settings.yml
  langs:
  - java
  name: BgpSettings
  fullName: com.microsoft.azure.management.network.implementation.api.BgpSettings
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/api/BgpSettings.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/api/BgpSettings.java
    startLine: 12
  assemblies:
  - com.microsoft.azure.management.network.implementation.api
  package: com.microsoft.azure.management.network.implementation.api
  summary: <p>The <xref href="com.microsoft.azure.management.network.implementation.api._bgp_settings" data-throw-if-not-resolved="false"></xref> model. </p>
  syntax: &o1
    content: public class BgpSettings
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.network.implementation.api._bgp_settings_1a8a479064b2b817449ac20b73f2d59fc9
  id: _bgp_settings_1a8a479064b2b817449ac20b73f2d59fc9
  parent: com.microsoft.azure.management.network.implementation.api._bgp_settings
  href: com.microsoft.azure.management.network.implementation.api._bgp_settings.yml
  langs:
  - java
  name: asn()
  fullName: Long com.microsoft.azure.management.network.implementation.api.BgpSettings.asn()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/api/BgpSettings.java
    startLine: 34
  assemblies:
  - com.microsoft.azure.management.network.implementation.api
  package: com.microsoft.azure.management.network.implementation.api
  summary: >-
    <p>Get the asn value.</p>

    <p></p>
  syntax:
    content: public Long asn()
    return:
      type: 34f09483
      description: <p>the asn value </p>
- uid: com.microsoft.azure.management.network.implementation.api._bgp_settings_1adb5424ea821f76f6a5cd59eaf83ff76e
  id: _bgp_settings_1adb5424ea821f76f6a5cd59eaf83ff76e
  parent: com.microsoft.azure.management.network.implementation.api._bgp_settings
  href: com.microsoft.azure.management.network.implementation.api._bgp_settings.yml
  langs:
  - java
  name: bgpPeeringAddress()
  fullName: String com.microsoft.azure.management.network.implementation.api.BgpSettings.bgpPeeringAddress()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/api/BgpSettings.java
    startLine: 54
  assemblies:
  - com.microsoft.azure.management.network.implementation.api
  package: com.microsoft.azure.management.network.implementation.api
  summary: >-
    <p>Get the bgpPeeringAddress value.</p>

    <p></p>
  syntax:
    content: public String bgpPeeringAddress()
    return:
      type: "26831127"
      description: <p>the bgpPeeringAddress value </p>
- uid: com.microsoft.azure.management.network.implementation.api._bgp_settings_1ad91aa234ac65a4efa2ae8df4d08891c5
  id: _bgp_settings_1ad91aa234ac65a4efa2ae8df4d08891c5
  parent: com.microsoft.azure.management.network.implementation.api._bgp_settings
  href: com.microsoft.azure.management.network.implementation.api._bgp_settings.yml
  langs:
  - java
  name: peerWeight()
  fullName: Integer com.microsoft.azure.management.network.implementation.api.BgpSettings.peerWeight()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/api/BgpSettings.java
    startLine: 74
  assemblies:
  - com.microsoft.azure.management.network.implementation.api
  package: com.microsoft.azure.management.network.implementation.api
  summary: >-
    <p>Get the peerWeight value.</p>

    <p></p>
  syntax:
    content: public Integer peerWeight()
    return:
      type: 08effaa0
      description: <p>the peerWeight value </p>
- uid: com.microsoft.azure.management.network.implementation.api._bgp_settings_1abf79f8ac2df5b7c94cde64637bbe0776
  id: _bgp_settings_1abf79f8ac2df5b7c94cde64637bbe0776
  parent: com.microsoft.azure.management.network.implementation.api._bgp_settings
  href: com.microsoft.azure.management.network.implementation.api._bgp_settings.yml
  langs:
  - java
  name: withAsn(Long asn)
  fullName: BgpSettings com.microsoft.azure.management.network.implementation.api.BgpSettings.withAsn(Long asn)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/api/BgpSettings.java
    startLine: 44
  assemblies:
  - com.microsoft.azure.management.network.implementation.api
  package: com.microsoft.azure.management.network.implementation.api
  summary: >-
    <p>Set the asn value.</p>

    <p></p>
  syntax:
    content: public BgpSettings withAsn(Long asn)
    parameters:
    - id: asn
      type: 34f09483
      description: <p>the asn value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation.api._bgp_settings
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation.api._bgp_settings" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network.implementation.api._bgp_settings_1a1b1063d59642849f11b6cca65a33a383
  id: _bgp_settings_1a1b1063d59642849f11b6cca65a33a383
  parent: com.microsoft.azure.management.network.implementation.api._bgp_settings
  href: com.microsoft.azure.management.network.implementation.api._bgp_settings.yml
  langs:
  - java
  name: withBgpPeeringAddress(String bgpPeeringAddress)
  fullName: BgpSettings com.microsoft.azure.management.network.implementation.api.BgpSettings.withBgpPeeringAddress(String bgpPeeringAddress)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/api/BgpSettings.java
    startLine: 64
  assemblies:
  - com.microsoft.azure.management.network.implementation.api
  package: com.microsoft.azure.management.network.implementation.api
  summary: >-
    <p>Set the bgpPeeringAddress value.</p>

    <p></p>
  syntax:
    content: public BgpSettings withBgpPeeringAddress(String bgpPeeringAddress)
    parameters:
    - id: bgpPeeringAddress
      type: "26831127"
      description: <p>the bgpPeeringAddress value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation.api._bgp_settings
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation.api._bgp_settings" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network.implementation.api._bgp_settings_1a7bb8b3a490e0a039279314be58605414
  id: _bgp_settings_1a7bb8b3a490e0a039279314be58605414
  parent: com.microsoft.azure.management.network.implementation.api._bgp_settings
  href: com.microsoft.azure.management.network.implementation.api._bgp_settings.yml
  langs:
  - java
  name: withPeerWeight(Integer peerWeight)
  fullName: BgpSettings com.microsoft.azure.management.network.implementation.api.BgpSettings.withPeerWeight(Integer peerWeight)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/api/BgpSettings.java
    startLine: 84
  assemblies:
  - com.microsoft.azure.management.network.implementation.api
  package: com.microsoft.azure.management.network.implementation.api
  summary: >-
    <p>Set the peerWeight value.</p>

    <p></p>
  syntax:
    content: public BgpSettings withPeerWeight(Integer peerWeight)
    parameters:
    - id: peerWeight
      type: 08effaa0
      description: <p>the peerWeight value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation.api._bgp_settings
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation.api._bgp_settings" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: 34f09483
  spec.java:
  - name: Long
    fullName: Long
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 08effaa0
  spec.java:
  - name: Integer
    fullName: Integer
- uid: com.microsoft.azure.management.network.implementation.api._bgp_settings
  parent: com.microsoft.azure.management.network.implementation.api
  href: com.microsoft.azure.management.network.implementation.api._bgp_settings.yml
  name: BgpSettings
  fullName: com.microsoft.azure.management.network.implementation.api.BgpSettings
  type: Class
  summary: <p>The <xref href="com.microsoft.azure.management.network.implementation.api._bgp_settings" data-throw-if-not-resolved="false"></xref> model. </p>
  syntax: *o1
