items:
- uid: com.microsoft.azure.management.compute._linux_configuration
  id: _linux_configuration
  parent: com.microsoft.azure.management.compute
  children:
  - com.microsoft.azure.management.compute._linux_configuration_1a9a01f18989fadd7330e4674c08152e8b
  - com.microsoft.azure.management.compute._linux_configuration_1a8fe4998bc6154fa885024f10c127044f
  - com.microsoft.azure.management.compute._linux_configuration_1acdee918e29e0821d340c5d3a2dda0e56
  - com.microsoft.azure.management.compute._linux_configuration_1a2327919ddd1e07b4a37d7cc553b4aa16
  href: com.microsoft.azure.management.compute._linux_configuration.yml
  langs:
  - java
  name: LinuxConfiguration
  fullName: com.microsoft.azure.management.compute.LinuxConfiguration
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/LinuxConfiguration.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/LinuxConfiguration.java
    startLine: 14
  package: com.microsoft.azure.management.compute
  summary: <p>Describes Windows Configuration of the OS Profile. </p>
  syntax: &o1
    content: public class LinuxConfiguration
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.compute._linux_configuration_1a9a01f18989fadd7330e4674c08152e8b
  id: _linux_configuration_1a9a01f18989fadd7330e4674c08152e8b
  parent: com.microsoft.azure.management.compute._linux_configuration
  href: com.microsoft.azure.management.compute._linux_configuration.yml
  langs:
  - java
  name: disablePasswordAuthentication()
  fullName: Boolean com.microsoft.azure.management.compute.LinuxConfiguration.disablePasswordAuthentication()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/LinuxConfiguration.java
    startLine: 30
  package: com.microsoft.azure.management.compute
  summary: >-
    <p>Get the disablePasswordAuthentication value.</p>

    <p></p>
  syntax:
    content: public Boolean disablePasswordAuthentication()
    return:
      type: 866c2227
      description: <p>the disablePasswordAuthentication value </p>
- uid: com.microsoft.azure.management.compute._linux_configuration_1a8fe4998bc6154fa885024f10c127044f
  id: _linux_configuration_1a8fe4998bc6154fa885024f10c127044f
  parent: com.microsoft.azure.management.compute._linux_configuration
  href: com.microsoft.azure.management.compute._linux_configuration.yml
  langs:
  - java
  name: ssh()
  fullName: SshConfiguration com.microsoft.azure.management.compute.LinuxConfiguration.ssh()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/LinuxConfiguration.java
    startLine: 50
  package: com.microsoft.azure.management.compute
  summary: >-
    <p>Get the ssh value.</p>

    <p></p>
  syntax:
    content: public SshConfiguration ssh()
    return:
      type: com.microsoft.azure.management.compute._ssh_configuration
      description: <p>the ssh value </p>
- uid: com.microsoft.azure.management.compute._linux_configuration_1acdee918e29e0821d340c5d3a2dda0e56
  id: _linux_configuration_1acdee918e29e0821d340c5d3a2dda0e56
  parent: com.microsoft.azure.management.compute._linux_configuration
  href: com.microsoft.azure.management.compute._linux_configuration.yml
  langs:
  - java
  name: withDisablePasswordAuthentication(Boolean disablePasswordAuthentication)
  fullName: LinuxConfiguration com.microsoft.azure.management.compute.LinuxConfiguration.withDisablePasswordAuthentication(Boolean disablePasswordAuthentication)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/LinuxConfiguration.java
    startLine: 40
  package: com.microsoft.azure.management.compute
  summary: >-
    <p>Set the disablePasswordAuthentication value.</p>

    <p></p>
  syntax:
    content: public LinuxConfiguration withDisablePasswordAuthentication(Boolean disablePasswordAuthentication)
    parameters:
    - id: disablePasswordAuthentication
      type: 866c2227
      description: <p>the disablePasswordAuthentication value to set </p>
    return:
      type: com.microsoft.azure.management.compute._linux_configuration
      description: <p>the <xref href="com.microsoft.azure.management.compute._linux_configuration" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.compute._linux_configuration_1a2327919ddd1e07b4a37d7cc553b4aa16
  id: _linux_configuration_1a2327919ddd1e07b4a37d7cc553b4aa16
  parent: com.microsoft.azure.management.compute._linux_configuration
  href: com.microsoft.azure.management.compute._linux_configuration.yml
  langs:
  - java
  name: withSsh(SshConfiguration ssh)
  fullName: LinuxConfiguration com.microsoft.azure.management.compute.LinuxConfiguration.withSsh(SshConfiguration ssh)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/LinuxConfiguration.java
    startLine: 60
  package: com.microsoft.azure.management.compute
  summary: >-
    <p>Set the ssh value.</p>

    <p></p>
  syntax:
    content: public LinuxConfiguration withSsh(SshConfiguration ssh)
    parameters:
    - id: ssh
      type: com.microsoft.azure.management.compute._ssh_configuration
      description: <p>the ssh value to set </p>
    return:
      type: com.microsoft.azure.management.compute._linux_configuration
      description: <p>the <xref href="com.microsoft.azure.management.compute._linux_configuration" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: 866c2227
  spec.java:
  - name: Boolean
    fullName: Boolean
- uid: com.microsoft.azure.management.compute._ssh_configuration
  parent: com.microsoft.azure.management.compute
  href: com.microsoft.azure.management.compute._ssh_configuration.yml
  name: SshConfiguration
  fullName: com.microsoft.azure.management.compute.SshConfiguration
  type: Class
  summary: <p>SSH configuration for Linux based VMs running on <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class SshConfiguration
- uid: com.microsoft.azure.management.compute._linux_configuration
  parent: com.microsoft.azure.management.compute
  href: com.microsoft.azure.management.compute._linux_configuration.yml
  name: LinuxConfiguration
  fullName: com.microsoft.azure.management.compute.LinuxConfiguration
  type: Class
  summary: <p>Describes Windows Configuration of the OS Profile. </p>
  syntax: *o1
