items:
- uid: com.microsoft.azure.batch.protocol.models._cloud_service_configuration
  id: _cloud_service_configuration
  parent: com.microsoft.azure.batch.protocol.models
  children:
  - com.microsoft.azure.batch.protocol.models._cloud_service_configuration.currentOSVersion()
  - com.microsoft.azure.batch.protocol.models._cloud_service_configuration.osFamily()
  - com.microsoft.azure.batch.protocol.models._cloud_service_configuration.targetOSVersion()
  - com.microsoft.azure.batch.protocol.models._cloud_service_configuration.withCurrentOSVersion(String)
  - com.microsoft.azure.batch.protocol.models._cloud_service_configuration.withOsFamily(String)
  - com.microsoft.azure.batch.protocol.models._cloud_service_configuration.withTargetOSVersion(String)
  href: com.microsoft.azure.batch.protocol.models._cloud_service_configuration.yml
  langs:
  - java
  name: CloudServiceConfiguration
  fullName: com.microsoft.azure.batch.protocol.models.CloudServiceConfiguration
  type: Class
  source:
    remote: &o0
      path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/CloudServiceConfiguration.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/CloudServiceConfiguration.java
    startLine: 16
  package: com.microsoft.azure.batch.protocol.models
  summary: <p>The configuration for nodes in a pool based on the <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> Cloud Services platform. </p>
  syntax: &o1
    content: public class CloudServiceConfiguration
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.batch.protocol.models._cloud_service_configuration.currentOSVersion()
  id: currentOSVersion()
  parent: com.microsoft.azure.batch.protocol.models._cloud_service_configuration
  href: com.microsoft.azure.batch.protocol.models._cloud_service_configuration.yml
  langs:
  - java
  name: currentOSVersion()
  fullName: String com.microsoft.azure.batch.protocol.models.CloudServiceConfiguration.currentOSVersion()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/CloudServiceConfiguration.java
    startLine: 84
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the currentOSVersion value.</p>

    <p></p>
  syntax:
    content: public String currentOSVersion()
    return:
      type: "26831127"
      description: <p>the currentOSVersion value </p>
- uid: com.microsoft.azure.batch.protocol.models._cloud_service_configuration.osFamily()
  id: osFamily()
  parent: com.microsoft.azure.batch.protocol.models._cloud_service_configuration
  href: com.microsoft.azure.batch.protocol.models._cloud_service_configuration.yml
  langs:
  - java
  name: osFamily()
  fullName: String com.microsoft.azure.batch.protocol.models.CloudServiceConfiguration.osFamily()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/CloudServiceConfiguration.java
    startLine: 44
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the osFamily value.</p>

    <p></p>
  syntax:
    content: public String osFamily()
    return:
      type: "26831127"
      description: <p>the osFamily value </p>
- uid: com.microsoft.azure.batch.protocol.models._cloud_service_configuration.targetOSVersion()
  id: targetOSVersion()
  parent: com.microsoft.azure.batch.protocol.models._cloud_service_configuration
  href: com.microsoft.azure.batch.protocol.models._cloud_service_configuration.yml
  langs:
  - java
  name: targetOSVersion()
  fullName: String com.microsoft.azure.batch.protocol.models.CloudServiceConfiguration.targetOSVersion()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/CloudServiceConfiguration.java
    startLine: 64
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the targetOSVersion value.</p>

    <p></p>
  syntax:
    content: public String targetOSVersion()
    return:
      type: "26831127"
      description: <p>the targetOSVersion value </p>
- uid: com.microsoft.azure.batch.protocol.models._cloud_service_configuration.withCurrentOSVersion(String)
  id: withCurrentOSVersion(String)
  parent: com.microsoft.azure.batch.protocol.models._cloud_service_configuration
  href: com.microsoft.azure.batch.protocol.models._cloud_service_configuration.yml
  langs:
  - java
  name: withCurrentOSVersion(String currentOSVersion)
  fullName: CloudServiceConfiguration com.microsoft.azure.batch.protocol.models.CloudServiceConfiguration.withCurrentOSVersion(String currentOSVersion)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/CloudServiceConfiguration.java
    startLine: 94
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the currentOSVersion value.</p>

    <p></p>
  syntax:
    content: public CloudServiceConfiguration withCurrentOSVersion(String currentOSVersion)
    parameters:
    - id: currentOSVersion
      type: "26831127"
      description: <p>the currentOSVersion value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._cloud_service_configuration
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._cloud_service_configuration" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.batch.protocol.models._cloud_service_configuration.withOsFamily(String)
  id: withOsFamily(String)
  parent: com.microsoft.azure.batch.protocol.models._cloud_service_configuration
  href: com.microsoft.azure.batch.protocol.models._cloud_service_configuration.yml
  langs:
  - java
  name: withOsFamily(String osFamily)
  fullName: CloudServiceConfiguration com.microsoft.azure.batch.protocol.models.CloudServiceConfiguration.withOsFamily(String osFamily)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/CloudServiceConfiguration.java
    startLine: 54
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the osFamily value.</p>

    <p></p>
  syntax:
    content: public CloudServiceConfiguration withOsFamily(String osFamily)
    parameters:
    - id: osFamily
      type: "26831127"
      description: <p>the osFamily value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._cloud_service_configuration
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._cloud_service_configuration" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.batch.protocol.models._cloud_service_configuration.withTargetOSVersion(String)
  id: withTargetOSVersion(String)
  parent: com.microsoft.azure.batch.protocol.models._cloud_service_configuration
  href: com.microsoft.azure.batch.protocol.models._cloud_service_configuration.yml
  langs:
  - java
  name: withTargetOSVersion(String targetOSVersion)
  fullName: CloudServiceConfiguration com.microsoft.azure.batch.protocol.models.CloudServiceConfiguration.withTargetOSVersion(String targetOSVersion)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/CloudServiceConfiguration.java
    startLine: 74
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the targetOSVersion value.</p>

    <p></p>
  syntax:
    content: public CloudServiceConfiguration withTargetOSVersion(String targetOSVersion)
    parameters:
    - id: targetOSVersion
      type: "26831127"
      description: <p>the targetOSVersion value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._cloud_service_configuration
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._cloud_service_configuration" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure._azure
  parent: com.microsoft.azure
  href: com.microsoft.azure._azure.yml
  name: Azure
  fullName: com.microsoft.azure.Azure
  type: Class
  summary: <p>The entry point for accessing resource management APIs in <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class Azure
- uid: com.microsoft.azure.batch.protocol.models._cloud_service_configuration
  parent: com.microsoft.azure.batch.protocol.models
  href: com.microsoft.azure.batch.protocol.models._cloud_service_configuration.yml
  name: CloudServiceConfiguration
  fullName: com.microsoft.azure.batch.protocol.models.CloudServiceConfiguration
  type: Class
  summary: <p>The configuration for nodes in a pool based on the <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> Cloud Services platform. </p>
  syntax: *o1
