items:
- uid: com.microsoft.azure.management.website.implementation._hosting_environment_collection_inner
  id: _hosting_environment_collection_inner
  parent: com.microsoft.azure.management.website.implementation
  children:
  - com.microsoft.azure.management.website.implementation._hosting_environment_collection_inner_1a658a2df0fd25a604a32d1323df2b3e44
  - com.microsoft.azure.management.website.implementation._hosting_environment_collection_inner_1a7ac4ce71a85e52259ba041d88f09c437
  - com.microsoft.azure.management.website.implementation._hosting_environment_collection_inner_1a5e1e267668c47f6b9c6c96b72a86cd1a
  - com.microsoft.azure.management.website.implementation._hosting_environment_collection_inner_1adeb03b513c8b6306e12e1758107f2053
  href: com.microsoft.azure.management.website.implementation._hosting_environment_collection_inner.yml
  langs:
  - java
  name: HostingEnvironmentCollectionInner
  fullName: com.microsoft.azure.management.website.implementation.HostingEnvironmentCollectionInner
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/HostingEnvironmentCollectionInner.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/HostingEnvironmentCollectionInner.java
    startLine: 15
  package: com.microsoft.azure.management.website.implementation
  summary: <p>Collection of hosting environments (App Service Environments). </p>
  syntax: &o1
    content: public class HostingEnvironmentCollectionInner
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.website.implementation._hosting_environment_collection_inner_1a658a2df0fd25a604a32d1323df2b3e44
  id: _hosting_environment_collection_inner_1a658a2df0fd25a604a32d1323df2b3e44
  parent: com.microsoft.azure.management.website.implementation._hosting_environment_collection_inner
  href: com.microsoft.azure.management.website.implementation._hosting_environment_collection_inner.yml
  langs:
  - java
  name: nextLink()
  fullName: String com.microsoft.azure.management.website.implementation.HostingEnvironmentCollectionInner.nextLink()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/HostingEnvironmentCollectionInner.java
    startLine: 51
  package: com.microsoft.azure.management.website.implementation
  summary: >-
    <p>Get the nextLink value.</p>

    <p></p>
  syntax:
    content: public String nextLink()
    return:
      type: "26831127"
      description: <p>the nextLink value </p>
- uid: com.microsoft.azure.management.website.implementation._hosting_environment_collection_inner_1a7ac4ce71a85e52259ba041d88f09c437
  id: _hosting_environment_collection_inner_1a7ac4ce71a85e52259ba041d88f09c437
  parent: com.microsoft.azure.management.website.implementation._hosting_environment_collection_inner
  href: com.microsoft.azure.management.website.implementation._hosting_environment_collection_inner.yml
  langs:
  - java
  name: value()
  fullName: List<HostingEnvironmentInner> com.microsoft.azure.management.website.implementation.HostingEnvironmentCollectionInner.value()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/HostingEnvironmentCollectionInner.java
    startLine: 31
  package: com.microsoft.azure.management.website.implementation
  summary: >-
    <p>Get the value value.</p>

    <p></p>
  syntax:
    content: public List< HostingEnvironmentInner > value()
    return:
      type: f6a6204dcom.microsoft.azure.management.website.implementation._hosting_environment_inner9ec3e006
      description: <p>the value value </p>
- uid: com.microsoft.azure.management.website.implementation._hosting_environment_collection_inner_1a5e1e267668c47f6b9c6c96b72a86cd1a
  id: _hosting_environment_collection_inner_1a5e1e267668c47f6b9c6c96b72a86cd1a
  parent: com.microsoft.azure.management.website.implementation._hosting_environment_collection_inner
  href: com.microsoft.azure.management.website.implementation._hosting_environment_collection_inner.yml
  langs:
  - java
  name: withNextLink(String nextLink)
  fullName: HostingEnvironmentCollectionInner com.microsoft.azure.management.website.implementation.HostingEnvironmentCollectionInner.withNextLink(String nextLink)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/HostingEnvironmentCollectionInner.java
    startLine: 61
  package: com.microsoft.azure.management.website.implementation
  summary: >-
    <p>Set the nextLink value.</p>

    <p></p>
  syntax:
    content: public HostingEnvironmentCollectionInner withNextLink(String nextLink)
    parameters:
    - id: nextLink
      type: "26831127"
      description: <p>the nextLink value to set </p>
    return:
      type: com.microsoft.azure.management.website.implementation._hosting_environment_collection_inner
      description: <p>the <xref href="com.microsoft.azure.management.website.implementation._hosting_environment_collection_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.website.implementation._hosting_environment_collection_inner_1adeb03b513c8b6306e12e1758107f2053
  id: _hosting_environment_collection_inner_1adeb03b513c8b6306e12e1758107f2053
  parent: com.microsoft.azure.management.website.implementation._hosting_environment_collection_inner
  href: com.microsoft.azure.management.website.implementation._hosting_environment_collection_inner.yml
  langs:
  - java
  name: withValue(List< HostingEnvironmentInner > value)
  fullName: HostingEnvironmentCollectionInner com.microsoft.azure.management.website.implementation.HostingEnvironmentCollectionInner.withValue(List< HostingEnvironmentInner > value)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/HostingEnvironmentCollectionInner.java
    startLine: 41
  package: com.microsoft.azure.management.website.implementation
  summary: >-
    <p>Set the value value.</p>

    <p></p>
  syntax:
    content: public HostingEnvironmentCollectionInner withValue(List< HostingEnvironmentInner > value)
    parameters:
    - id: value
      type: f6a6204dcom.microsoft.azure.management.website.implementation._hosting_environment_inner9ec3e006
      description: <p>the value value to set </p>
    return:
      type: com.microsoft.azure.management.website.implementation._hosting_environment_collection_inner
      description: <p>the <xref href="com.microsoft.azure.management.website.implementation._hosting_environment_collection_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: f6a6204dcom.microsoft.azure.management.website.implementation._hosting_environment_inner9ec3e006
  spec.java:
  - name: 'List< '
    fullName: 'List< '
  - uid: com.microsoft.azure.management.website.implementation._hosting_environment_inner
    name: HostingEnvironmentInner
    fullName: com.microsoft.azure.management.website.implementation.HostingEnvironmentInner
    href: com.microsoft.azure.management.website.implementation._hosting_environment_inner.yml
  - name: ' >'
    fullName: ' >'
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.management.website.implementation._hosting_environment_inner
  parent: com.microsoft.azure.management.website.implementation
  href: com.microsoft.azure.management.website.implementation._hosting_environment_inner.yml
  name: HostingEnvironmentInner
  fullName: com.microsoft.azure.management.website.implementation.HostingEnvironmentInner
  type: Class
  summary: <p>Description of an hostingEnvironment (App Service Environment). </p>
  syntax:
    content: public class HostingEnvironmentInner
- uid: com.microsoft.azure.management.website.implementation._hosting_environment_collection_inner
  parent: com.microsoft.azure.management.website.implementation
  href: com.microsoft.azure.management.website.implementation._hosting_environment_collection_inner.yml
  name: HostingEnvironmentCollectionInner
  fullName: com.microsoft.azure.management.website.implementation.HostingEnvironmentCollectionInner
  type: Class
  summary: <p>Collection of hosting environments (App Service Environments). </p>
  syntax: *o1
