items:
- uid: com.microsoft.azure.batch.protocol.implementation._applications_impl._applications_service
  id: _applications_service
  parent: com.microsoft.azure.batch.protocol.implementation
  children:
  - com.microsoft.azure.batch.protocol.implementation._applications_impl._applications_service_1ab49bc8e785bcaf401a0969be483efe35
  - com.microsoft.azure.batch.protocol.implementation._applications_impl._applications_service_1a64b1cde9ce4c80b44193c5183e474389
  - com.microsoft.azure.batch.protocol.implementation._applications_impl._applications_service_1a430176185f4fe14a44e192fe2a6a3bad
  href: com.microsoft.azure.batch.protocol.implementation._applications_impl._applications_service.yml
  langs:
  - java
  name: ApplicationsImpl.ApplicationsService
  fullName: com.microsoft.azure.batch.protocol.implementation.ApplicationsImpl.ApplicationsService
  type: Interface
  source:
    remote: &o0
      path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/implementation/ApplicationsImpl.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/implementation/ApplicationsImpl.java
    startLine: 67
  package: com.microsoft.azure.batch.protocol.implementation
  summary: 'The interface defining all the services for Applications to be used by Retrofit to perform actually REST calls. '
  syntax:
    content: interface ApplicationsImpl.ApplicationsService
- uid: com.microsoft.azure.batch.protocol.implementation._applications_impl._applications_service_1ab49bc8e785bcaf401a0969be483efe35
  id: _applications_service_1ab49bc8e785bcaf401a0969be483efe35
  parent: com.microsoft.azure.batch.protocol.implementation._applications_impl._applications_service
  href: com.microsoft.azure.batch.protocol.implementation._applications_impl._applications_service.yml
  langs:
  - java
  name: list(@Query("api-version") String apiVersion,@Header("accept-language") String acceptLanguage,@Query("maxresults") Integer maxResults,@Query("timeout") Integer timeout,@Header("client-request-id") String clientRequestId,@Header("return-client-request-id") Boolean returnClientRequestId,@Header("ocp-date") DateTimeRfc1123 ocpDate,@Header("User-Agent") String userAgent)
  fullName: Call<ResponseBody> com.microsoft.azure.batch.protocol.implementation.ApplicationsImpl.ApplicationsService.list(@Query("api-version") String apiVersion,@Header("accept-language") String acceptLanguage,@Query("maxresults") Integer maxResults,@Query("timeout") Integer timeout,@Header("client-request-id") String clientRequestId,@Header("return-client-request-id") Boolean returnClientRequestId,@Header("ocp-date") DateTimeRfc1123 ocpDate,@Header("User-Agent") String userAgent)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/implementation/ApplicationsImpl.java
    startLine: 70
  package: com.microsoft.azure.batch.protocol.implementation
  syntax:
    content: public Call< ResponseBody > list(@Query("api-version") String apiVersion,@Header("accept-language") String acceptLanguage,@Query("maxresults") Integer maxResults,@Query("timeout") Integer timeout,@Header("client-request-id") String clientRequestId,@Header("return-client-request-id") Boolean returnClientRequestId,@Header("ocp-date") DateTimeRfc1123 ocpDate,@Header("User-Agent") String userAgent)
    parameters:
    - id: apiVersion
      type: bc99c6f7
    - id: acceptLanguage
      type: 70efd141
    - id: maxResults
      type: b86c3b3e
    - id: timeout
      type: e90f45ef
    - id: clientRequestId
      type: 74e7aeab
    - id: returnClientRequestId
      type: 08b12507
    - id: ocpDate
      type: 5bec6339
    - id: userAgent
      type: 63ee51da
    return:
      type: 827d4009
- uid: com.microsoft.azure.batch.protocol.implementation._applications_impl._applications_service_1a64b1cde9ce4c80b44193c5183e474389
  id: _applications_service_1a64b1cde9ce4c80b44193c5183e474389
  parent: com.microsoft.azure.batch.protocol.implementation._applications_impl._applications_service
  href: com.microsoft.azure.batch.protocol.implementation._applications_impl._applications_service.yml
  langs:
  - java
  name: get(@Path("applicationId") String applicationId,@Query("api-version") String apiVersion,@Header("accept-language") String acceptLanguage,@Query("timeout") Integer timeout,@Header("client-request-id") String clientRequestId,@Header("return-client-request-id") Boolean returnClientRequestId,@Header("ocp-date") DateTimeRfc1123 ocpDate,@Header("User-Agent") String userAgent)
  fullName: Call<ResponseBody> com.microsoft.azure.batch.protocol.implementation.ApplicationsImpl.ApplicationsService.get(@Path("applicationId") String applicationId,@Query("api-version") String apiVersion,@Header("accept-language") String acceptLanguage,@Query("timeout") Integer timeout,@Header("client-request-id") String clientRequestId,@Header("return-client-request-id") Boolean returnClientRequestId,@Header("ocp-date") DateTimeRfc1123 ocpDate,@Header("User-Agent") String userAgent)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/implementation/ApplicationsImpl.java
    startLine: 74
  package: com.microsoft.azure.batch.protocol.implementation
  syntax:
    content: public Call< ResponseBody > get(@Path("applicationId") String applicationId,@Query("api-version") String apiVersion,@Header("accept-language") String acceptLanguage,@Query("timeout") Integer timeout,@Header("client-request-id") String clientRequestId,@Header("return-client-request-id") Boolean returnClientRequestId,@Header("ocp-date") DateTimeRfc1123 ocpDate,@Header("User-Agent") String userAgent)
    parameters:
    - id: applicationId
      type: 3c9ef565
    - id: apiVersion
      type: bc99c6f7
    - id: acceptLanguage
      type: 70efd141
    - id: timeout
      type: e90f45ef
    - id: clientRequestId
      type: 74e7aeab
    - id: returnClientRequestId
      type: 08b12507
    - id: ocpDate
      type: 5bec6339
    - id: userAgent
      type: 63ee51da
    return:
      type: 827d4009
- uid: com.microsoft.azure.batch.protocol.implementation._applications_impl._applications_service_1a430176185f4fe14a44e192fe2a6a3bad
  id: _applications_service_1a430176185f4fe14a44e192fe2a6a3bad
  parent: com.microsoft.azure.batch.protocol.implementation._applications_impl._applications_service
  href: com.microsoft.azure.batch.protocol.implementation._applications_impl._applications_service.yml
  langs:
  - java
  name: listNext(@Url String nextPageLink,@Header("accept-language") String acceptLanguage,@Header("client-request-id") String clientRequestId,@Header("return-client-request-id") Boolean returnClientRequestId,@Header("ocp-date") DateTimeRfc1123 ocpDate,@Header("User-Agent") String userAgent)
  fullName: Call<ResponseBody> com.microsoft.azure.batch.protocol.implementation.ApplicationsImpl.ApplicationsService.listNext(@Url String nextPageLink,@Header("accept-language") String acceptLanguage,@Header("client-request-id") String clientRequestId,@Header("return-client-request-id") Boolean returnClientRequestId,@Header("ocp-date") DateTimeRfc1123 ocpDate,@Header("User-Agent") String userAgent)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/implementation/ApplicationsImpl.java
    startLine: 78
  package: com.microsoft.azure.batch.protocol.implementation
  syntax:
    content: public Call< ResponseBody > listNext(@Url String nextPageLink,@Header("accept-language") String acceptLanguage,@Header("client-request-id") String clientRequestId,@Header("return-client-request-id") Boolean returnClientRequestId,@Header("ocp-date") DateTimeRfc1123 ocpDate,@Header("User-Agent") String userAgent)
    parameters:
    - id: nextPageLink
      type: 3cd827cc
    - id: acceptLanguage
      type: 70efd141
    - id: clientRequestId
      type: 74e7aeab
    - id: returnClientRequestId
      type: 08b12507
    - id: ocpDate
      type: 5bec6339
    - id: userAgent
      type: 63ee51da
    return:
      type: 827d4009
references:
- uid: bc99c6f7
  spec.java:
  - name: '@Query("api-version") String'
    fullName: '@Query("api-version") String'
- uid: 70efd141
  spec.java:
  - name: '@Header("accept-language") String'
    fullName: '@Header("accept-language") String'
- uid: b86c3b3e
  spec.java:
  - name: '@Query("maxresults") Integer'
    fullName: '@Query("maxresults") Integer'
- uid: e90f45ef
  spec.java:
  - name: '@Query("timeout") Integer'
    fullName: '@Query("timeout") Integer'
- uid: 74e7aeab
  spec.java:
  - name: '@Header("client-request-id") String'
    fullName: '@Header("client-request-id") String'
- uid: 08b12507
  spec.java:
  - name: '@Header("return-client-request-id") Boolean'
    fullName: '@Header("return-client-request-id") Boolean'
- uid: 5bec6339
  spec.java:
  - name: '@Header("ocp-date") DateTimeRfc1123'
    fullName: '@Header("ocp-date") DateTimeRfc1123'
- uid: 63ee51da
  spec.java:
  - name: '@Header("User-Agent") String'
    fullName: '@Header("User-Agent") String'
- uid: 827d4009
  spec.java:
  - name: Call< ResponseBody >
    fullName: Call< ResponseBody >
- uid: 3c9ef565
  spec.java:
  - name: '@Path("applicationId") String'
    fullName: '@Path("applicationId") String'
- uid: 3cd827cc
  spec.java:
  - name: '@Url String'
    fullName: '@Url String'
- uid: com.microsoft.azure.batch.protocol._applications
  parent: com.microsoft.azure.batch.protocol
  href: com.microsoft.azure.batch.protocol._applications.yml
  name: Applications
  fullName: com.microsoft.azure.batch.protocol.Applications
  type: Interface
  summary: 'An instance of this class provides access to all the operations defined in Applications. '
  syntax:
    content: public interface Applications
