items:
- uid: com.microsoft.azure.management.network.implementation.api._application_gateway_sku
  id: _application_gateway_sku
  parent: com.microsoft.azure.management.network.implementation.api
  children:
  - com.microsoft.azure.management.network.implementation.api._application_gateway_sku_1a799a066f1dd3e6009166b7ce5a0775e8
  - com.microsoft.azure.management.network.implementation.api._application_gateway_sku_1a2498d824b2acaf1f3e416a61edd5690a
  - com.microsoft.azure.management.network.implementation.api._application_gateway_sku_1a1731f8932e464095d1bc4399d3db1032
  - com.microsoft.azure.management.network.implementation.api._application_gateway_sku_1a2539a2c2360afc983f91d7cb463fa568
  - com.microsoft.azure.management.network.implementation.api._application_gateway_sku_1abf2b9af0fe0621b9efcf0a6df9c9fc69
  - com.microsoft.azure.management.network.implementation.api._application_gateway_sku_1a747f618d7000b1ea8b31c7ee22ead1ea
  href: com.microsoft.azure.management.network.implementation.api._application_gateway_sku.yml
  langs:
  - java
  name: ApplicationGatewaySku
  fullName: com.microsoft.azure.management.network.implementation.api.ApplicationGatewaySku
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/api/ApplicationGatewaySku.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/api/ApplicationGatewaySku.java
    startLine: 12
  assemblies:
  - com.microsoft.azure.management.network.implementation.api
  package: com.microsoft.azure.management.network.implementation.api
  summary: <p>SKU of application gateway. </p>
  syntax: &o1
    content: public class ApplicationGatewaySku
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.network.implementation.api._application_gateway_sku_1a799a066f1dd3e6009166b7ce5a0775e8
  id: _application_gateway_sku_1a799a066f1dd3e6009166b7ce5a0775e8
  parent: com.microsoft.azure.management.network.implementation.api._application_gateway_sku
  href: com.microsoft.azure.management.network.implementation.api._application_gateway_sku.yml
  langs:
  - java
  name: capacity()
  fullName: Integer com.microsoft.azure.management.network.implementation.api.ApplicationGatewaySku.capacity()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/api/ApplicationGatewaySku.java
    startLine: 75
  assemblies:
  - com.microsoft.azure.management.network.implementation.api
  package: com.microsoft.azure.management.network.implementation.api
  summary: >-
    <p>Get the capacity value.</p>

    <p></p>
  syntax:
    content: public Integer capacity()
    return:
      type: 08effaa0
      description: <p>the capacity value </p>
- uid: com.microsoft.azure.management.network.implementation.api._application_gateway_sku_1a2498d824b2acaf1f3e416a61edd5690a
  id: _application_gateway_sku_1a2498d824b2acaf1f3e416a61edd5690a
  parent: com.microsoft.azure.management.network.implementation.api._application_gateway_sku
  href: com.microsoft.azure.management.network.implementation.api._application_gateway_sku.yml
  langs:
  - java
  name: name()
  fullName: String com.microsoft.azure.management.network.implementation.api.ApplicationGatewaySku.name()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/api/ApplicationGatewaySku.java
    startLine: 35
  assemblies:
  - com.microsoft.azure.management.network.implementation.api
  package: com.microsoft.azure.management.network.implementation.api
  summary: >-
    <p>Get the name value.</p>

    <p></p>
  syntax:
    content: public String name()
    return:
      type: "26831127"
      description: <p>the name value </p>
- uid: com.microsoft.azure.management.network.implementation.api._application_gateway_sku_1a1731f8932e464095d1bc4399d3db1032
  id: _application_gateway_sku_1a1731f8932e464095d1bc4399d3db1032
  parent: com.microsoft.azure.management.network.implementation.api._application_gateway_sku
  href: com.microsoft.azure.management.network.implementation.api._application_gateway_sku.yml
  langs:
  - java
  name: tier()
  fullName: String com.microsoft.azure.management.network.implementation.api.ApplicationGatewaySku.tier()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/api/ApplicationGatewaySku.java
    startLine: 55
  assemblies:
  - com.microsoft.azure.management.network.implementation.api
  package: com.microsoft.azure.management.network.implementation.api
  summary: >-
    <p>Get the tier value.</p>

    <p></p>
  syntax:
    content: public String tier()
    return:
      type: "26831127"
      description: <p>the tier value </p>
- uid: com.microsoft.azure.management.network.implementation.api._application_gateway_sku_1a2539a2c2360afc983f91d7cb463fa568
  id: _application_gateway_sku_1a2539a2c2360afc983f91d7cb463fa568
  parent: com.microsoft.azure.management.network.implementation.api._application_gateway_sku
  href: com.microsoft.azure.management.network.implementation.api._application_gateway_sku.yml
  langs:
  - java
  name: withCapacity(Integer capacity)
  fullName: ApplicationGatewaySku com.microsoft.azure.management.network.implementation.api.ApplicationGatewaySku.withCapacity(Integer capacity)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/api/ApplicationGatewaySku.java
    startLine: 85
  assemblies:
  - com.microsoft.azure.management.network.implementation.api
  package: com.microsoft.azure.management.network.implementation.api
  summary: >-
    <p>Set the capacity value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewaySku withCapacity(Integer capacity)
    parameters:
    - id: capacity
      type: 08effaa0
      description: <p>the capacity value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation.api._application_gateway_sku
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation.api._application_gateway_sku" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network.implementation.api._application_gateway_sku_1abf2b9af0fe0621b9efcf0a6df9c9fc69
  id: _application_gateway_sku_1abf2b9af0fe0621b9efcf0a6df9c9fc69
  parent: com.microsoft.azure.management.network.implementation.api._application_gateway_sku
  href: com.microsoft.azure.management.network.implementation.api._application_gateway_sku.yml
  langs:
  - java
  name: withName(String name)
  fullName: ApplicationGatewaySku com.microsoft.azure.management.network.implementation.api.ApplicationGatewaySku.withName(String name)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/api/ApplicationGatewaySku.java
    startLine: 45
  assemblies:
  - com.microsoft.azure.management.network.implementation.api
  package: com.microsoft.azure.management.network.implementation.api
  summary: >-
    <p>Set the name value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewaySku withName(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>the name value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation.api._application_gateway_sku
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation.api._application_gateway_sku" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network.implementation.api._application_gateway_sku_1a747f618d7000b1ea8b31c7ee22ead1ea
  id: _application_gateway_sku_1a747f618d7000b1ea8b31c7ee22ead1ea
  parent: com.microsoft.azure.management.network.implementation.api._application_gateway_sku
  href: com.microsoft.azure.management.network.implementation.api._application_gateway_sku.yml
  langs:
  - java
  name: withTier(String tier)
  fullName: ApplicationGatewaySku com.microsoft.azure.management.network.implementation.api.ApplicationGatewaySku.withTier(String tier)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/api/ApplicationGatewaySku.java
    startLine: 65
  assemblies:
  - com.microsoft.azure.management.network.implementation.api
  package: com.microsoft.azure.management.network.implementation.api
  summary: >-
    <p>Set the tier value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewaySku withTier(String tier)
    parameters:
    - id: tier
      type: "26831127"
      description: <p>the tier value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation.api._application_gateway_sku
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation.api._application_gateway_sku" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 08effaa0
  spec.java:
  - name: Integer
    fullName: Integer
- uid: com.microsoft.azure.management.network.implementation.api._application_gateway_sku
  parent: com.microsoft.azure.management.network.implementation.api
  href: com.microsoft.azure.management.network.implementation.api._application_gateway_sku.yml
  name: ApplicationGatewaySku
  fullName: com.microsoft.azure.management.network.implementation.api.ApplicationGatewaySku
  type: Class
  summary: <p>SKU of application gateway. </p>
  syntax: *o1
