items:
- uid: com.microsoft.azure.management.network._application_gateway_sku
  id: _application_gateway_sku
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._application_gateway_sku_1a8033b9c0b445ab8b7f3081fe990c6bef
  - com.microsoft.azure.management.network._application_gateway_sku_1a6309f3ae459dae5719756d3bb8d9d140
  - com.microsoft.azure.management.network._application_gateway_sku_1af25b5f343e1cdf862943d0956a1b6a23
  - com.microsoft.azure.management.network._application_gateway_sku_1acc7fe5049881c5030acf4ca23cb81c10
  - com.microsoft.azure.management.network._application_gateway_sku_1ae8f57e7f4b1c010bda8e5939fe20f3f5
  - com.microsoft.azure.management.network._application_gateway_sku_1a30b60ddb4c05e3c3d3e75f0f9a2c5890
  href: com.microsoft.azure.management.network._application_gateway_sku.yml
  langs:
  - java
  name: ApplicationGatewaySku
  fullName: com.microsoft.azure.management.network.ApplicationGatewaySku
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySku.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySku.java
    startLine: 14
  package: com.microsoft.azure.management.network
  summary: <p>SKU of application gateway. </p>
  syntax: &o1
    content: public class ApplicationGatewaySku
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.network._application_gateway_sku_1a8033b9c0b445ab8b7f3081fe990c6bef
  id: _application_gateway_sku_1a8033b9c0b445ab8b7f3081fe990c6bef
  parent: com.microsoft.azure.management.network._application_gateway_sku
  href: com.microsoft.azure.management.network._application_gateway_sku.yml
  langs:
  - java
  name: capacity()
  fullName: Integer com.microsoft.azure.management.network.ApplicationGatewaySku.capacity()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySku.java
    startLine: 77
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the capacity value.</p>

    <p></p>
  syntax:
    content: public Integer capacity()
    return:
      type: 08effaa0
      description: <p>the capacity value </p>
- uid: com.microsoft.azure.management.network._application_gateway_sku_1a6309f3ae459dae5719756d3bb8d9d140
  id: _application_gateway_sku_1a6309f3ae459dae5719756d3bb8d9d140
  parent: com.microsoft.azure.management.network._application_gateway_sku
  href: com.microsoft.azure.management.network._application_gateway_sku.yml
  langs:
  - java
  name: name()
  fullName: String com.microsoft.azure.management.network.ApplicationGatewaySku.name()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySku.java
    startLine: 37
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the name value.</p>

    <p></p>
  syntax:
    content: public String name()
    return:
      type: "26831127"
      description: <p>the name value </p>
- uid: com.microsoft.azure.management.network._application_gateway_sku_1af25b5f343e1cdf862943d0956a1b6a23
  id: _application_gateway_sku_1af25b5f343e1cdf862943d0956a1b6a23
  parent: com.microsoft.azure.management.network._application_gateway_sku
  href: com.microsoft.azure.management.network._application_gateway_sku.yml
  langs:
  - java
  name: tier()
  fullName: String com.microsoft.azure.management.network.ApplicationGatewaySku.tier()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySku.java
    startLine: 57
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the tier value.</p>

    <p></p>
  syntax:
    content: public String tier()
    return:
      type: "26831127"
      description: <p>the tier value </p>
- uid: com.microsoft.azure.management.network._application_gateway_sku_1acc7fe5049881c5030acf4ca23cb81c10
  id: _application_gateway_sku_1acc7fe5049881c5030acf4ca23cb81c10
  parent: com.microsoft.azure.management.network._application_gateway_sku
  href: com.microsoft.azure.management.network._application_gateway_sku.yml
  langs:
  - java
  name: withCapacity(Integer capacity)
  fullName: ApplicationGatewaySku com.microsoft.azure.management.network.ApplicationGatewaySku.withCapacity(Integer capacity)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySku.java
    startLine: 87
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the capacity value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewaySku withCapacity(Integer capacity)
    parameters:
    - id: capacity
      type: 08effaa0
      description: <p>the capacity value to set </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_sku
      description: <p>the <xref href="com.microsoft.azure.management.network._application_gateway_sku" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network._application_gateway_sku_1ae8f57e7f4b1c010bda8e5939fe20f3f5
  id: _application_gateway_sku_1ae8f57e7f4b1c010bda8e5939fe20f3f5
  parent: com.microsoft.azure.management.network._application_gateway_sku
  href: com.microsoft.azure.management.network._application_gateway_sku.yml
  langs:
  - java
  name: withName(String name)
  fullName: ApplicationGatewaySku com.microsoft.azure.management.network.ApplicationGatewaySku.withName(String name)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySku.java
    startLine: 47
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the name value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewaySku withName(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>the name value to set </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_sku
      description: <p>the <xref href="com.microsoft.azure.management.network._application_gateway_sku" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network._application_gateway_sku_1a30b60ddb4c05e3c3d3e75f0f9a2c5890
  id: _application_gateway_sku_1a30b60ddb4c05e3c3d3e75f0f9a2c5890
  parent: com.microsoft.azure.management.network._application_gateway_sku
  href: com.microsoft.azure.management.network._application_gateway_sku.yml
  langs:
  - java
  name: withTier(String tier)
  fullName: ApplicationGatewaySku com.microsoft.azure.management.network.ApplicationGatewaySku.withTier(String tier)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySku.java
    startLine: 67
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the tier value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewaySku withTier(String tier)
    parameters:
    - id: tier
      type: "26831127"
      description: <p>the tier value to set </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_sku
      description: <p>the <xref href="com.microsoft.azure.management.network._application_gateway_sku" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 08effaa0
  spec.java:
  - name: Integer
    fullName: Integer
- uid: com.microsoft.azure.management.network._application_gateway_sku
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_sku.yml
  name: ApplicationGatewaySku
  fullName: com.microsoft.azure.management.network.ApplicationGatewaySku
  type: Class
  summary: <p>SKU of application gateway. </p>
  syntax: *o1
