items:
- uid: com.microsoft.azure.management.compute.implementation.api._linux_configuration
  id: _linux_configuration
  parent: com.microsoft.azure.management.compute.implementation.api
  children:
  - com.microsoft.azure.management.compute.implementation.api._linux_configuration_1af952aec558f956ee5669282d63152884
  - com.microsoft.azure.management.compute.implementation.api._linux_configuration_1a354a2e20f13d3e5908c5f38892095a59
  - com.microsoft.azure.management.compute.implementation.api._linux_configuration_1ad3b553ade12bed5efe581156a3f47f1b
  - com.microsoft.azure.management.compute.implementation.api._linux_configuration_1a6870646e430b234b11b1e816035d911a
  href: com.microsoft.azure.management.compute.implementation.api._linux_configuration.yml
  langs:
  - java
  name: LinuxConfiguration
  fullName: com.microsoft.azure.management.compute.implementation.api.LinuxConfiguration
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/api/LinuxConfiguration.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/api/LinuxConfiguration.java
    startLine: 12
  assemblies:
  - com.microsoft.azure.management.compute.implementation.api
  package: com.microsoft.azure.management.compute.implementation.api
  summary: <p>Describes Windows Configuration of the OS Profile. </p>
  syntax: &o1
    content: public class LinuxConfiguration
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.compute.implementation.api._linux_configuration_1af952aec558f956ee5669282d63152884
  id: _linux_configuration_1af952aec558f956ee5669282d63152884
  parent: com.microsoft.azure.management.compute.implementation.api._linux_configuration
  href: com.microsoft.azure.management.compute.implementation.api._linux_configuration.yml
  langs:
  - java
  name: disablePasswordAuthentication()
  fullName: Boolean com.microsoft.azure.management.compute.implementation.api.LinuxConfiguration.disablePasswordAuthentication()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/api/LinuxConfiguration.java
    startLine: 29
  assemblies:
  - com.microsoft.azure.management.compute.implementation.api
  package: com.microsoft.azure.management.compute.implementation.api
  summary: >-
    <p>Get the disablePasswordAuthentication value.</p>

    <p></p>
  syntax:
    content: public Boolean disablePasswordAuthentication()
    return:
      type: 866c2227
      description: <p>the disablePasswordAuthentication value </p>
- uid: com.microsoft.azure.management.compute.implementation.api._linux_configuration_1a354a2e20f13d3e5908c5f38892095a59
  id: _linux_configuration_1a354a2e20f13d3e5908c5f38892095a59
  parent: com.microsoft.azure.management.compute.implementation.api._linux_configuration
  href: com.microsoft.azure.management.compute.implementation.api._linux_configuration.yml
  langs:
  - java
  name: ssh()
  fullName: SshConfiguration com.microsoft.azure.management.compute.implementation.api.LinuxConfiguration.ssh()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/api/LinuxConfiguration.java
    startLine: 49
  assemblies:
  - com.microsoft.azure.management.compute.implementation.api
  package: com.microsoft.azure.management.compute.implementation.api
  summary: >-
    <p>Get the ssh value.</p>

    <p></p>
  syntax:
    content: public SshConfiguration ssh()
    return:
      type: com.microsoft.azure.management.compute.implementation.api._ssh_configuration
      description: <p>the ssh value </p>
- uid: com.microsoft.azure.management.compute.implementation.api._linux_configuration_1ad3b553ade12bed5efe581156a3f47f1b
  id: _linux_configuration_1ad3b553ade12bed5efe581156a3f47f1b
  parent: com.microsoft.azure.management.compute.implementation.api._linux_configuration
  href: com.microsoft.azure.management.compute.implementation.api._linux_configuration.yml
  langs:
  - java
  name: withDisablePasswordAuthentication(Boolean disablePasswordAuthentication)
  fullName: LinuxConfiguration com.microsoft.azure.management.compute.implementation.api.LinuxConfiguration.withDisablePasswordAuthentication(Boolean disablePasswordAuthentication)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/api/LinuxConfiguration.java
    startLine: 39
  assemblies:
  - com.microsoft.azure.management.compute.implementation.api
  package: com.microsoft.azure.management.compute.implementation.api
  summary: >-
    <p>Set the disablePasswordAuthentication value.</p>

    <p></p>
  syntax:
    content: public LinuxConfiguration withDisablePasswordAuthentication(Boolean disablePasswordAuthentication)
    parameters:
    - id: disablePasswordAuthentication
      type: 866c2227
      description: <p>the disablePasswordAuthentication value to set </p>
    return:
      type: com.microsoft.azure.management.compute.implementation.api._linux_configuration
      description: <p>the <xref href="com.microsoft.azure.management.compute.implementation.api._linux_configuration" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.compute.implementation.api._linux_configuration_1a6870646e430b234b11b1e816035d911a
  id: _linux_configuration_1a6870646e430b234b11b1e816035d911a
  parent: com.microsoft.azure.management.compute.implementation.api._linux_configuration
  href: com.microsoft.azure.management.compute.implementation.api._linux_configuration.yml
  langs:
  - java
  name: withSsh(SshConfiguration ssh)
  fullName: LinuxConfiguration com.microsoft.azure.management.compute.implementation.api.LinuxConfiguration.withSsh(SshConfiguration ssh)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/api/LinuxConfiguration.java
    startLine: 59
  assemblies:
  - com.microsoft.azure.management.compute.implementation.api
  package: com.microsoft.azure.management.compute.implementation.api
  summary: >-
    <p>Set the ssh value.</p>

    <p></p>
  syntax:
    content: public LinuxConfiguration withSsh(SshConfiguration ssh)
    parameters:
    - id: ssh
      type: com.microsoft.azure.management.compute.implementation.api._ssh_configuration
      description: <p>the ssh value to set </p>
    return:
      type: com.microsoft.azure.management.compute.implementation.api._linux_configuration
      description: <p>the <xref href="com.microsoft.azure.management.compute.implementation.api._linux_configuration" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: 866c2227
  spec.java:
  - name: Boolean
    fullName: Boolean
- uid: com.microsoft.azure.management.compute.implementation.api._ssh_configuration
  parent: com.microsoft.azure.management.compute.implementation.api
  href: com.microsoft.azure.management.compute.implementation.api._ssh_configuration.yml
  name: SshConfiguration
  fullName: com.microsoft.azure.management.compute.implementation.api.SshConfiguration
  type: Class
  summary: <p>SSH configuration for Linux based VMs running on <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class SshConfiguration
- uid: com.microsoft.azure.management.compute.implementation.api._linux_configuration
  parent: com.microsoft.azure.management.compute.implementation.api
  href: com.microsoft.azure.management.compute.implementation.api._linux_configuration.yml
  name: LinuxConfiguration
  fullName: com.microsoft.azure.management.compute.implementation.api.LinuxConfiguration
  type: Class
  summary: <p>Describes Windows Configuration of the OS Profile. </p>
  syntax: *o1
