items:
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_4d4942651fb5f90938036133fce17248
  id: _update_4d4942651fb5f90938036133fce17248
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._nic_ip_configuration._update_4d4942651fb5f90938036133fce17248_1ac25f24fb9fdd36dac3c71baae55ac68d
  - com.microsoft.azure.management.network._nic_ip_configuration._update_4d4942651fb5f90938036133fce17248_1a7eb55ba63c5b2f5a56ab0c4c69203565
  - com.microsoft.azure.management.network._nic_ip_configuration._update_4d4942651fb5f90938036133fce17248_1a0bbc14932b6117d6bbcecad0671cd734
  - com.microsoft.azure.management.network._nic_ip_configuration._update_4d4942651fb5f90938036133fce17248_1a67181f492d6544385ad18a9d33d4b513
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_4d4942651fb5f90938036133fce17248.yml
  langs:
  - java
  name: NicIpConfiguration.UpdateDefinitionStages.WithNetwork<ParentT>
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.UpdateDefinitionStages.WithNetwork<ParentT>
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
    startLine: 274
  package: com.microsoft.azure.management.network
  summary: >-
    <p>The stage of the network interface IP configuration definition allowing to specify the virtual network.</p>

    <p></p>
  syntax:
    content: public interface WithNetwork<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable_1a92836b66fb83b831c1470a093c42d42d" data-throw-if-not-resolved="false"></xref></p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_4d4942651fb5f90938036133fce17248_1ac25f24fb9fdd36dac3c71baae55ac68d
  id: _update_4d4942651fb5f90938036133fce17248_1ac25f24fb9fdd36dac3c71baae55ac68d
  parent: com.microsoft.azure.management.network._nic_ip_configuration._update_4d4942651fb5f90938036133fce17248
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_4d4942651fb5f90938036133fce17248.yml
  langs:
  - java
  name: withExistingNetwork(Network network)
  fullName: WithSubnet<ParentT> com.microsoft.azure.management.network.NicIpConfiguration.UpdateDefinitionStages.WithNetwork< ParentT >.withExistingNetwork(Network network)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
    startLine: 315
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Associate an existing virtual network with the network interface IP configuration.</p>

    <p></p>
  syntax:
    content: public WithSubnet< ParentT > withExistingNetwork(Network network)
    parameters:
    - id: network
      type: com.microsoft.azure.management.network._network
      description: <p>an existing virtual network </p>
    return:
      type: com.microsoft.azure.management.network._nic_ip_configuration._update_0c219f411cd16a2405d14265ba10c9a6a6da57ba
      description: <p>the next stage of the network interface IP configuration definition </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_4d4942651fb5f90938036133fce17248_1a7eb55ba63c5b2f5a56ab0c4c69203565
  id: _update_4d4942651fb5f90938036133fce17248_1a7eb55ba63c5b2f5a56ab0c4c69203565
  parent: com.microsoft.azure.management.network._nic_ip_configuration._update_4d4942651fb5f90938036133fce17248
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_4d4942651fb5f90938036133fce17248.yml
  langs:
  - java
  name: withNewNetwork(Creatable< Network > creatable)
  fullName: WithPrivateIp<ParentT> com.microsoft.azure.management.network.NicIpConfiguration.UpdateDefinitionStages.WithNetwork< ParentT >.withNewNetwork(Creatable< Network > creatable)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
    startLine: 282
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Create a new virtual network to associate with the network interface IP configuration, based on the provided definition.</p>

    <p></p>
  syntax:
    content: public WithPrivateIp< ParentT > withNewNetwork(Creatable< Network > creatable)
    parameters:
    - id: creatable
      type: com.microsoft.azure.management.resources.fluentcore.model._creatable151dc42ccom.microsoft.azure.management.network._network9ec3e006
      description: <p>a creatable definition for a new virtual network </p>
    return:
      type: com.microsoft.azure.management.network._nic_ip_configuration._update_ac39f7ab2f23f0c3db8049ad3667081ea6da57ba
      description: <p>the next stage of the network interface IP configuration definition </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_4d4942651fb5f90938036133fce17248_1a0bbc14932b6117d6bbcecad0671cd734
  id: _update_4d4942651fb5f90938036133fce17248_1a0bbc14932b6117d6bbcecad0671cd734
  parent: com.microsoft.azure.management.network._nic_ip_configuration._update_4d4942651fb5f90938036133fce17248
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_4d4942651fb5f90938036133fce17248.yml
  langs:
  - java
  name: withNewNetwork(String addressSpace)
  fullName: WithPrivateIp<ParentT> com.microsoft.azure.management.network.NicIpConfiguration.UpdateDefinitionStages.WithNetwork< ParentT >.withNewNetwork(String addressSpace)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
    startLine: 307
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Creates a new virtual network to associate with the network interface IP configuration. </p>

    <p>the virtual network will be created in the same resource group and region as of parent network interface, it will be created with the specified address space and a default subnet covering the entirety of the network IP address space.</p>

    <p></p>
  syntax:
    content: public WithPrivateIp< ParentT > withNewNetwork(String addressSpace)
    parameters:
    - id: addressSpace
      type: "26831127"
      description: <p>the address space for the virtual network </p>
    return:
      type: com.microsoft.azure.management.network._nic_ip_configuration._update_ac39f7ab2f23f0c3db8049ad3667081ea6da57ba
      description: <p>the next stage of the network interface IP configuration definition </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_4d4942651fb5f90938036133fce17248_1a67181f492d6544385ad18a9d33d4b513
  id: _update_4d4942651fb5f90938036133fce17248_1a67181f492d6544385ad18a9d33d4b513
  parent: com.microsoft.azure.management.network._nic_ip_configuration._update_4d4942651fb5f90938036133fce17248
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_4d4942651fb5f90938036133fce17248.yml
  langs:
  - java
  name: withNewNetwork(String name, String addressSpace)
  fullName: WithPrivateIp<ParentT> com.microsoft.azure.management.network.NicIpConfiguration.UpdateDefinitionStages.WithNetwork< ParentT >.withNewNetwork(String name, String addressSpace)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
    startLine: 295
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Creates a new virtual network to associate with the network interface IP configuration. </p>

    <p>the virtual network will be created in the same resource group and region as of parent network interface, it will be created with the specified address space and a default subnet covering the entirety of the network IP address space.</p>

    <p></p>
  syntax:
    content: public WithPrivateIp< ParentT > withNewNetwork(String name, String addressSpace)
    parameters:
    - id: name
      type: "26831127"
      description: <p>the name of the new virtual network </p>
    - id: addressSpace
      type: "26831127"
      description: <p>the address space for rhe virtual network </p>
    return:
      type: com.microsoft.azure.management.network._nic_ip_configuration._update_ac39f7ab2f23f0c3db8049ad3667081ea6da57ba
      description: <p>the next stage of the network interface IP configuration definition </p>
references:
- uid: 18a275b1
  spec.java:
  - name: ParentT
    fullName: ParentT
- uid: com.microsoft.azure.management.resources.fluentcore.model._creatable151dc42ccom.microsoft.azure.management.network._network9ec3e006
  spec.java:
  - uid: com.microsoft.azure.management.resources.fluentcore.model._creatable
    name: Creatable<T>
    fullName: com.microsoft.azure.management.resources.fluentcore.model.Creatable<T>
    href: com.microsoft.azure.management.resources.fluentcore.model._creatable.yml
  - name: '< '
    fullName: '< '
  - uid: com.microsoft.azure.management.network._network
    name: Network
    fullName: com.microsoft.azure.management.network.Network
    href: com.microsoft.azure.management.network._network.yml
  - name: ' >'
    fullName: ' >'
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_ac39f7ab2f23f0c3db8049ad3667081ea6da57ba
  spec.java:
  - uid: com.microsoft.azure.management.network._nic_ip_configuration._update_ac39f7ab2f23f0c3db8049ad3667081e
    name: NicIpConfiguration.UpdateDefinitionStages.WithPrivateIp<ParentT>
    fullName: com.microsoft.azure.management.network.NicIpConfiguration.UpdateDefinitionStages.WithPrivateIp<ParentT>
    href: com.microsoft.azure.management.network._nic_ip_configuration._update_ac39f7ab2f23f0c3db8049ad3667081e.yml
  - name: < ParentT >
    fullName: < ParentT >
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_0c219f411cd16a2405d14265ba10c9a6a6da57ba
  spec.java:
  - uid: com.microsoft.azure.management.network._nic_ip_configuration._update_0c219f411cd16a2405d14265ba10c9a6
    name: NicIpConfiguration.UpdateDefinitionStages.WithSubnet<ParentT>
    fullName: com.microsoft.azure.management.network.NicIpConfiguration.UpdateDefinitionStages.WithSubnet<ParentT>
    href: com.microsoft.azure.management.network._nic_ip_configuration._update_0c219f411cd16a2405d14265ba10c9a6.yml
  - name: < ParentT >
    fullName: < ParentT >
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_definition
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_definition.yml
  name: NicIpConfiguration.UpdateDefinition<ParentT>
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.UpdateDefinition<ParentT>
  type: Interface
  summary: <p>The entirety of a network interface IP configuration definition as part of a network interface update. </p>
  syntax:
    content: public interface UpdateDefinition<ParentT> extends NicIpConfiguration.UpdateDefinitionStages.Blank< ParentT >,NicIpConfiguration.UpdateDefinitionStages.WithAttach< ParentT >,NicIpConfiguration.UpdateDefinitionStages.WithNetwork< ParentT >,NicIpConfiguration.UpdateDefinitionStages.WithPrivateIp< ParentT >,NicIpConfiguration.UpdateDefinitionStages.WithSubnet< ParentT >,NicIpConfiguration.UpdateDefinitionStages.WithPublicIpAddress< ParentT >
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <ref refid="" kindref="compound">UpdateDefinitionStages.WithAttach#attach()</ref></p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_definition_stages._blank
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_definition_stages._blank.yml
  name: NicIpConfiguration.UpdateDefinitionStages.Blank<ParentT>
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.UpdateDefinitionStages.Blank<ParentT>
  type: Interface
  summary: >-
    <p>The first stage of network interface IP configuration definition.</p>

    <p></p>
  syntax:
    content: public interface Blank<ParentT> extends NicIpConfiguration.UpdateDefinitionStages.WithNetwork< ParentT >
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable_1a92836b66fb83b831c1470a093c42d42d" data-throw-if-not-resolved="false"></xref></p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_ac39f7ab2f23f0c3db8049ad3667081e
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_ac39f7ab2f23f0c3db8049ad3667081e.yml
  name: NicIpConfiguration.UpdateDefinitionStages.WithPrivateIp<ParentT>
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.UpdateDefinitionStages.WithPrivateIp<ParentT>
  type: Interface
  summary: >-
    <p>The stage of the network interface IP configuration definition allowing to specify private IP address within a virtual network subnet.</p>

    <p></p>
  syntax:
    content: public interface WithPrivateIp<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable_1a92836b66fb83b831c1470a093c42d42d" data-throw-if-not-resolved="false"></xref></p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._creatable
  parent: com.microsoft.azure.management.resources.fluentcore.model
  href: com.microsoft.azure.management.resources.fluentcore.model._creatable.yml
  name: Creatable<T>
  fullName: com.microsoft.azure.management.resources.fluentcore.model.Creatable<T>
  type: Interface
  summary: >-
    <p>The final stage of the resource definition, at which it can be create, using <xref href="com.microsoft.azure.management.resources.fluentcore.model._creatable_1acf3889a24f1bb5e64f8e6a751397f991" data-throw-if-not-resolved="false"></xref>.</p>

    <p></p>
  syntax:
    content: public interface Creatable<T> extends Indexable
    typeParameters:
    - type: 8ce1ecb9
      description: <p>the fluent type of the resource to be created </p>
- uid: com.microsoft.azure.management.network._network
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._network.yml
  name: Network
  fullName: com.microsoft.azure.management.network.Network
  type: Interface
  summary: <p>Entry point for Virtual <xref href="com.microsoft.azure.management.network._network" data-throw-if-not-resolved="false"></xref> management API in <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public interface Network extends GroupableResource,Refreshable< Network >,Wrapper< VirtualNetworkInner >,Updatable< Network.Update >
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_0c219f411cd16a2405d14265ba10c9a6
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_0c219f411cd16a2405d14265ba10c9a6.yml
  name: NicIpConfiguration.UpdateDefinitionStages.WithSubnet<ParentT>
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.UpdateDefinitionStages.WithSubnet<ParentT>
  type: Interface
  summary: >-
    <p>The stage of the network interface IP configuration definition allowing to specify subnet.</p>

    <p></p>
  syntax:
    content: public interface WithSubnet<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable_1a92836b66fb83b831c1470a093c42d42d" data-throw-if-not-resolved="false"></xref></p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._attachable_1a92836b66fb83b831c1470a093c42d42d
  parent: com.microsoft.azure.management.resources.fluentcore.model._attachable
  href: com.microsoft.azure.management.resources.fluentcore.model._attachable.yml
  name: attach()
  fullName: ParentT com.microsoft.azure.management.resources.fluentcore.model.Attachable< ParentT >.attach()
  type: Method
  summary: <p>Attaches this child object's definition to its parent's definition. </p>
  syntax:
    content: public ParentT attach()
    return:
      type: 18a275b1
      description: <p>the next stage of the parent object's definition </p>
