items:
- uid: com.microsoft.azure.management.network._application_gateway_request_routing_rule_type
  id: _application_gateway_request_routing_rule_type
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._application_gateway_request_routing_rule_type_1a1f3887a5326e8605153cc98a1c056cc3
  - com.microsoft.azure.management.network._application_gateway_request_routing_rule_type_1af1acfaa7a6370de161f9bad6288b4576
  href: com.microsoft.azure.management.network._application_gateway_request_routing_rule_type.yml
  langs:
  - java
  name: ApplicationGatewayRequestRoutingRuleType
  fullName: com.microsoft.azure.management.network.ApplicationGatewayRequestRoutingRuleType
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayRequestRoutingRuleType.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayRequestRoutingRuleType.java
    startLine: 13
  package: com.microsoft.azure.management.network
  summary: <p>Defines values for <xref href="com.microsoft.azure.management.network._application_gateway_request_routing_rule_type" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: &o1
    content: public class ApplicationGatewayRequestRoutingRuleType
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.network._application_gateway_request_routing_rule_type_1a1f3887a5326e8605153cc98a1c056cc3
  id: _application_gateway_request_routing_rule_type_1a1f3887a5326e8605153cc98a1c056cc3
  parent: com.microsoft.azure.management.network._application_gateway_request_routing_rule_type
  href: com.microsoft.azure.management.network._application_gateway_request_routing_rule_type.yml
  langs:
  - java
  name: BASIC
  fullName: final String com.microsoft.azure.management.network.ApplicationGatewayRequestRoutingRuleType.BASIC
  type: Field
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayRequestRoutingRuleType.java
    startLine: 15
  package: com.microsoft.azure.management.network
  summary: <p>Static value Basic for <xref href="com.microsoft.azure.management.network._application_gateway_request_routing_rule_type" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public static final String BASIC= "Basic"
    return:
      type: 3d93591e
- uid: com.microsoft.azure.management.network._application_gateway_request_routing_rule_type_1af1acfaa7a6370de161f9bad6288b4576
  id: _application_gateway_request_routing_rule_type_1af1acfaa7a6370de161f9bad6288b4576
  parent: com.microsoft.azure.management.network._application_gateway_request_routing_rule_type
  href: com.microsoft.azure.management.network._application_gateway_request_routing_rule_type.yml
  langs:
  - java
  name: PATH_BASED_ROUTING
  fullName: final String com.microsoft.azure.management.network.ApplicationGatewayRequestRoutingRuleType.PATH_BASED_ROUTING
  type: Field
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayRequestRoutingRuleType.java
    startLine: 18
  package: com.microsoft.azure.management.network
  summary: <p>Static value PathBasedRouting for <xref href="com.microsoft.azure.management.network._application_gateway_request_routing_rule_type" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public static final String PATH_BASED_ROUTING= "PathBasedRouting"
    return:
      type: 3d93591e
references:
- uid: 3d93591e
  spec.java:
  - name: final String
    fullName: final String
- uid: com.microsoft.azure.management.network._application_gateway_request_routing_rule_type
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_request_routing_rule_type.yml
  name: ApplicationGatewayRequestRoutingRuleType
  fullName: com.microsoft.azure.management.network.ApplicationGatewayRequestRoutingRuleType
  type: Class
  summary: <p>Defines values for <xref href="com.microsoft.azure.management.network._application_gateway_request_routing_rule_type" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: *o1
