items:
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update
  id: _update
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._nic_ip_configuration._update.yml
  langs:
  - java
  name: NicIpConfiguration.Update
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.Update
  type: Interface
  source:
    remote:
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
    startLine: 424
  package: com.microsoft.azure.management.network
  summary: <p>The entirety of a network interface IP configuration update as part of a network interface update. </p>
  syntax:
    content: public interface Update extends Settable< NetworkInterface.Update >,NicIpConfiguration.UpdateStages.WithSubnet,NicIpConfiguration.UpdateStages.WithPrivateIp,NicIpConfiguration.UpdateStages.WithPublicIpAddress,NicIpConfiguration.UpdateStages.WithLoadBalancer,NicIpConfiguration.UpdateStages.WithBackendAddressPool
  inheritedMembers:
  - com.microsoft.azure.management.resources.fluentcore.model._settable.parent()
  - com.microsoft.azure.management.network._nic_ip_configuration._update_7d1d94805bfe36a8463df749eca66b2b.withBackendAddressPool(String)
  - com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_load_balancer.withExistingLoadBalancer(LoadBalancer)
  - com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672.withNewPublicIpAddress(Creatable< PublicIpAddress >)
  - com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672.withNewPublicIpAddress()
  - com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672.withNewPublicIpAddress(String)
  - com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672.withoutPublicIpAddress()
  - com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_private_ip.withPrivateIpAddressDynamic()
  - com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_private_ip.withPrivateIpAddressStatic(String)
  - com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_subnet.withSubnet(String)
references:
- uid: com.microsoft.azure.management.resources.fluentcore.model._settable.parent()
  parent: com.microsoft.azure.management.resources.fluentcore.model._settable
  href: com.microsoft.azure.management.resources.fluentcore.model._settable.yml
  name: parent()
  fullName: ParentT com.microsoft.azure.management.resources.fluentcore.model.Settable< ParentT >.parent()
  type: Method
  summary: >-
    <p>Begins an update for a child resource. </p>

    <p>This is the beginning of the builder pattern used to update child resources The final method completing the update and continue the actual parent resource update process in <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> is <xref href="com.microsoft.azure.management.resources.fluentcore.model._settable.parent()" data-throw-if-not-resolved="false"></xref>.</p>

    <p></p>
  syntax:
    content: public ParentT parent()
    return:
      type: 18a275b1
      description: <p>the stage of parent resource update </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_7d1d94805bfe36a8463df749eca66b2b.withBackendAddressPool(String)
  parent: com.microsoft.azure.management.network._nic_ip_configuration._update_7d1d94805bfe36a8463df749eca66b2b
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_7d1d94805bfe36a8463df749eca66b2b.yml
  name: withBackendAddressPool(String name)
  fullName: Update com.microsoft.azure.management.network.NicIpConfiguration.UpdateStages.WithBackendAddressPool.withBackendAddressPool(String name)
  type: Method
  summary: <p>Adds this network interface's IP configuration to the provided back end address pool of the specified load balancer. </p>
  syntax:
    content: public Update withBackendAddressPool(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>the name of an existing load balancer back end address pool </p>
    return:
      type: com.microsoft.azure.management.network._nic_ip_configuration._update
      description: <p>the next stage of the update </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_load_balancer.withExistingLoadBalancer(LoadBalancer)
  parent: com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_load_balancer
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_load_balancer.yml
  name: withExistingLoadBalancer(LoadBalancer loadBalancer)
  fullName: WithBackendAddressPool com.microsoft.azure.management.network.NicIpConfiguration.UpdateStages.WithLoadBalancer.withExistingLoadBalancer(LoadBalancer loadBalancer)
  type: Method
  summary: <p>Specifies the load balancer to associate this IP configuration with. </p>
  syntax:
    content: public WithBackendAddressPool withExistingLoadBalancer(LoadBalancer loadBalancer)
    parameters:
    - id: loadBalancer
      type: com.microsoft.azure.management.network._load_balancer
      description: <p>an existing load balancer </p>
    return:
      type: com.microsoft.azure.management.network._nic_ip_configuration._update_7d1d94805bfe36a8463df749eca66b2b
      description: <p>the next stage of the update </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672.withNewPublicIpAddress(Creatable< PublicIpAddress >)
  parent: com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672.yml
  name: withNewPublicIpAddress(Creatable< PublicIpAddress > creatable)
  fullName: Update com.microsoft.azure.management.network.NicIpConfiguration.UpdateStages.WithPublicIpAddress.withNewPublicIpAddress(Creatable< PublicIpAddress > creatable)
  type: Method
  summary: >-
    <p>Create a new public IP address to associate the network interface IP configuration with, based on the provided definition. </p>

    <p>If there is public IP associated with the IP configuration then that will be removed in favour of this.</p>

    <p></p>
  syntax:
    content: public Update withNewPublicIpAddress(Creatable< PublicIpAddress > creatable)
    parameters:
    - id: creatable
      type: com.microsoft.azure.management.resources.fluentcore.model._creatable151dc42ccom.microsoft.azure.management.network._public_ip_address9ec3e006
      description: <p>a creatable definition for a new public IP </p>
    return:
      type: com.microsoft.azure.management.network._nic_ip_configuration._update
      description: <p>the next stage of the network interface IP configuration update </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672.withNewPublicIpAddress()
  parent: com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672.yml
  name: withNewPublicIpAddress()
  fullName: Update com.microsoft.azure.management.network.NicIpConfiguration.UpdateStages.WithPublicIpAddress.withNewPublicIpAddress()
  type: Method
  summary: >-
    <p>Creates a new public IP address in the same region and group as the resource and associate it with the IP configuration. </p>

    <p>The internal name and DNS label for the public IP address will be derived from the network interface name, if there is an existing public IP association then that will be removed in favour of this.</p>

    <p></p>
  syntax:
    content: public Update withNewPublicIpAddress()
    return:
      type: com.microsoft.azure.management.network._nic_ip_configuration._update
      description: <p>the next stage of the network interface IP configuration update </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672.withNewPublicIpAddress(String)
  parent: com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672.yml
  name: withNewPublicIpAddress(String leafDnsLabel)
  fullName: Update com.microsoft.azure.management.network.NicIpConfiguration.UpdateStages.WithPublicIpAddress.withNewPublicIpAddress(String leafDnsLabel)
  type: Method
  summary: >-
    <p>Creates a new public IP address in the same region and group as the resource, with the specified DNS label and associate it with the IP configuration. </p>

    <p>The internal name for the public IP address will be derived from the DNS label, if there is an existing public IP association then that will be removed in favour of this</p>

    <p></p>
  syntax:
    content: public Update withNewPublicIpAddress(String leafDnsLabel)
    parameters:
    - id: leafDnsLabel
      type: "26831127"
      description: <p>the leaf domain label </p>
    return:
      type: com.microsoft.azure.management.network._nic_ip_configuration._update
      description: <p>the next stage of the network interface IP configuration update </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672.withoutPublicIpAddress()
  parent: com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672.yml
  name: withoutPublicIpAddress()
  fullName: Update com.microsoft.azure.management.network.NicIpConfiguration.UpdateStages.WithPublicIpAddress.withoutPublicIpAddress()
  type: Method
  summary: >-
    <p>Specifies that remove any public IP associated with the IP configuration.</p>

    <p></p>
  syntax:
    content: public Update withoutPublicIpAddress()
    return:
      type: com.microsoft.azure.management.network._nic_ip_configuration._update
      description: <p>the next stage of the network interface IP configuration update </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_private_ip.withPrivateIpAddressDynamic()
  parent: com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_private_ip
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_private_ip.yml
  name: withPrivateIpAddressDynamic()
  fullName: Update com.microsoft.azure.management.network.NicIpConfiguration.UpdateStages.WithPrivateIp.withPrivateIpAddressDynamic()
  type: Method
  summary: >-
    <p>Enables dynamic private IP address allocation within the specified existing virtual network subnet to the network interface IP configuration.</p>

    <p></p>
  syntax:
    content: public Update withPrivateIpAddressDynamic()
    return:
      type: com.microsoft.azure.management.network._nic_ip_configuration._update
      description: <p>the next stage of the network interface IP configuration update </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_private_ip.withPrivateIpAddressStatic(String)
  parent: com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_private_ip
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_private_ip.yml
  name: withPrivateIpAddressStatic(String staticPrivateIpAddress)
  fullName: Update com.microsoft.azure.management.network.NicIpConfiguration.UpdateStages.WithPrivateIp.withPrivateIpAddressStatic(String staticPrivateIpAddress)
  type: Method
  summary: >-
    <p>Assigns the specified static private IP address within the specified existing virtual network subnet to the network interface IP configuration.</p>

    <p></p>
  syntax:
    content: public Update withPrivateIpAddressStatic(String staticPrivateIpAddress)
    parameters:
    - id: staticPrivateIpAddress
      type: "26831127"
      description: <p>the static IP address within the specified subnet to assign to the IP configuration </p>
    return:
      type: com.microsoft.azure.management.network._nic_ip_configuration._update
      description: <p>the next stage of the network interface IP configuration update </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_subnet.withSubnet(String)
  parent: com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_subnet
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_subnet.yml
  name: withSubnet(String name)
  fullName: Update com.microsoft.azure.management.network.NicIpConfiguration.UpdateStages.WithSubnet.withSubnet(String name)
  type: Method
  summary: >-
    <p>Associate a subnet with the network interface IP configuration.</p>

    <p></p>
  syntax:
    content: public Update withSubnet(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>the subnet name </p>
    return:
      type: com.microsoft.azure.management.network._nic_ip_configuration._update
      description: <p>the next stage of the network interface IP configuration update </p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._settable
  parent: com.microsoft.azure.management.resources.fluentcore.model
  href: com.microsoft.azure.management.resources.fluentcore.model._settable.yml
  name: Settable<ParentT>
  fullName: com.microsoft.azure.management.resources.fluentcore.model.Settable<ParentT>
  type: Interface
  summary: >-
    <p>The base interface for all template interfaces for child resources that support update operations.</p>

    <p></p>
  syntax:
    content: public interface Settable<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the parent definition <xref href="com.microsoft.azure.management.resources.fluentcore.model._settable.parent()" data-throw-if-not-resolved="false"></xref> returns to </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_subnet
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_subnet.yml
  name: NicIpConfiguration.UpdateStages.WithSubnet
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.UpdateStages.WithSubnet
  type: Interface
  summary: <p>The stage of the network interface IP configuration update allowing to specify subnet. </p>
  syntax:
    content: public interface WithSubnet
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_private_ip
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_private_ip.yml
  name: NicIpConfiguration.UpdateStages.WithPrivateIp
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.UpdateStages.WithPrivateIp
  type: Interface
  summary: <p>The stage of the network interface IP configuration update allowing to specify private IP. </p>
  syntax:
    content: public interface WithPrivateIp
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_f68ea101757e880e58df31ecebf76672.yml
  name: NicIpConfiguration.UpdateStages.WithPublicIpAddress
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.UpdateStages.WithPublicIpAddress
  type: Interface
  summary: <p>The stage of the network interface IP configuration update allowing to specify public IP address. </p>
  syntax:
    content: public interface WithPublicIpAddress
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_load_balancer
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_load_balancer.yml
  name: NicIpConfiguration.UpdateStages.WithLoadBalancer
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.UpdateStages.WithLoadBalancer
  type: Interface
  summary: <p>The stage of the network interface's IP configuration allowing to specify the load balancer to associate this IP configuration with. </p>
  syntax:
    content: public interface WithLoadBalancer
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_7d1d94805bfe36a8463df749eca66b2b
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_7d1d94805bfe36a8463df749eca66b2b.yml
  name: NicIpConfiguration.UpdateStages.WithBackendAddressPool
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.UpdateStages.WithBackendAddressPool
  type: Interface
  summary: <p>The stage of the network interface IP configuration update allowing to specify the load balancer back end address pool to add it to. </p>
  syntax:
    content: public interface WithBackendAddressPool
- uid: com.microsoft.azure.management.network.implementation._nic_ip_configuration_impl
