items:
- uid: com.microsoft.azure.management.network._application_gateway_operational_state
  id: _application_gateway_operational_state
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._application_gateway_operational_state_1abbb621da24591f5bf365301e69bdecd9
  - com.microsoft.azure.management.network._application_gateway_operational_state_1abcdb3aff4f19f83bd8a1225eadb9f8a8
  - com.microsoft.azure.management.network._application_gateway_operational_state_1a3f4afdba2cbb0d76bf3f171695a81af7
  - com.microsoft.azure.management.network._application_gateway_operational_state_1a52d79a36683d1610c3e533ae4afe3404
  href: com.microsoft.azure.management.network._application_gateway_operational_state.yml
  langs:
  - java
  name: ApplicationGatewayOperationalState
  fullName: com.microsoft.azure.management.network.ApplicationGatewayOperationalState
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayOperationalState.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayOperationalState.java
    startLine: 13
  package: com.microsoft.azure.management.network
  summary: <p>Defines values for <xref href="com.microsoft.azure.management.network._application_gateway_operational_state" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: &o1
    content: public class ApplicationGatewayOperationalState
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.network._application_gateway_operational_state_1abbb621da24591f5bf365301e69bdecd9
  id: _application_gateway_operational_state_1abbb621da24591f5bf365301e69bdecd9
  parent: com.microsoft.azure.management.network._application_gateway_operational_state
  href: com.microsoft.azure.management.network._application_gateway_operational_state.yml
  langs:
  - java
  name: RUNNING
  fullName: final String com.microsoft.azure.management.network.ApplicationGatewayOperationalState.RUNNING
  type: Field
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayOperationalState.java
    startLine: 21
  package: com.microsoft.azure.management.network
  summary: <p>Static value Running for <xref href="com.microsoft.azure.management.network._application_gateway_operational_state" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public static final String RUNNING= "Running"
    return:
      type: 3d93591e
- uid: com.microsoft.azure.management.network._application_gateway_operational_state_1abcdb3aff4f19f83bd8a1225eadb9f8a8
  id: _application_gateway_operational_state_1abcdb3aff4f19f83bd8a1225eadb9f8a8
  parent: com.microsoft.azure.management.network._application_gateway_operational_state
  href: com.microsoft.azure.management.network._application_gateway_operational_state.yml
  langs:
  - java
  name: STARTING
  fullName: final String com.microsoft.azure.management.network.ApplicationGatewayOperationalState.STARTING
  type: Field
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayOperationalState.java
    startLine: 18
  package: com.microsoft.azure.management.network
  summary: <p>Static value Starting for <xref href="com.microsoft.azure.management.network._application_gateway_operational_state" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public static final String STARTING= "Starting"
    return:
      type: 3d93591e
- uid: com.microsoft.azure.management.network._application_gateway_operational_state_1a3f4afdba2cbb0d76bf3f171695a81af7
  id: _application_gateway_operational_state_1a3f4afdba2cbb0d76bf3f171695a81af7
  parent: com.microsoft.azure.management.network._application_gateway_operational_state
  href: com.microsoft.azure.management.network._application_gateway_operational_state.yml
  langs:
  - java
  name: STOPPED
  fullName: final String com.microsoft.azure.management.network.ApplicationGatewayOperationalState.STOPPED
  type: Field
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayOperationalState.java
    startLine: 15
  package: com.microsoft.azure.management.network
  summary: <p>Static value Stopped for <xref href="com.microsoft.azure.management.network._application_gateway_operational_state" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public static final String STOPPED= "Stopped"
    return:
      type: 3d93591e
- uid: com.microsoft.azure.management.network._application_gateway_operational_state_1a52d79a36683d1610c3e533ae4afe3404
  id: _application_gateway_operational_state_1a52d79a36683d1610c3e533ae4afe3404
  parent: com.microsoft.azure.management.network._application_gateway_operational_state
  href: com.microsoft.azure.management.network._application_gateway_operational_state.yml
  langs:
  - java
  name: STOPPING
  fullName: final String com.microsoft.azure.management.network.ApplicationGatewayOperationalState.STOPPING
  type: Field
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayOperationalState.java
    startLine: 24
  package: com.microsoft.azure.management.network
  summary: <p>Static value Stopping for <xref href="com.microsoft.azure.management.network._application_gateway_operational_state" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public static final String STOPPING= "Stopping"
    return:
      type: 3d93591e
references:
- uid: 3d93591e
  spec.java:
  - name: final String
    fullName: final String
- uid: com.microsoft.azure.management.network._application_gateway_operational_state
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_operational_state.yml
  name: ApplicationGatewayOperationalState
  fullName: com.microsoft.azure.management.network.ApplicationGatewayOperationalState
  type: Class
  summary: <p>Defines values for <xref href="com.microsoft.azure.management.network._application_gateway_operational_state" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: *o1
