items:
- uid: com.microsoft.azure.management.compute.implementation.api._windows_configuration
  id: _windows_configuration
  parent: com.microsoft.azure.management.compute.implementation.api
  children:
  - com.microsoft.azure.management.compute.implementation.api._windows_configuration_1a274955932b826c650f340286ed54222b
  - com.microsoft.azure.management.compute.implementation.api._windows_configuration_1a911fc2d81932d5a31e4124ae0716afe6
  - com.microsoft.azure.management.compute.implementation.api._windows_configuration_1a79d5f4ec9f291ee1163e9944d081b503
  - com.microsoft.azure.management.compute.implementation.api._windows_configuration_1a304b7210f1f0c88b6a9bcba05cc7e46e
  - com.microsoft.azure.management.compute.implementation.api._windows_configuration_1a1e284153956d411574e3b0573ddbd36b
  - com.microsoft.azure.management.compute.implementation.api._windows_configuration_1a8a7cf4ae1000445044708a77db755060
  - com.microsoft.azure.management.compute.implementation.api._windows_configuration_1ae40a8b14357cc2ebe4da7787b55f7a46
  - com.microsoft.azure.management.compute.implementation.api._windows_configuration_1a51f89a9a0c311cc0842af3cee01f7f0f
  - com.microsoft.azure.management.compute.implementation.api._windows_configuration_1ac5f89ac2c2e36abebdee1c06b06e122f
  - com.microsoft.azure.management.compute.implementation.api._windows_configuration_1a82675abb87b9e3b8f4adf7e53e971fa7
  href: com.microsoft.azure.management.compute.implementation.api._windows_configuration.yml
  langs:
  - java
  name: WindowsConfiguration
  fullName: com.microsoft.azure.management.compute.implementation.api.WindowsConfiguration
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/api/WindowsConfiguration.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/api/WindowsConfiguration.java
    startLine: 13
  package: com.microsoft.azure.management.compute.implementation.api
  summary: <p>Describes Windows Configuration of the OS Profile. </p>
  syntax: &o1
    content: public class WindowsConfiguration
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.compute.implementation.api._windows_configuration_1a274955932b826c650f340286ed54222b
  id: _windows_configuration_1a274955932b826c650f340286ed54222b
  parent: com.microsoft.azure.management.compute.implementation.api._windows_configuration
  href: com.microsoft.azure.management.compute.implementation.api._windows_configuration.yml
  langs:
  - java
  name: additionalUnattendContent()
  fullName: List<AdditionalUnattendContent> com.microsoft.azure.management.compute.implementation.api.WindowsConfiguration.additionalUnattendContent()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/api/WindowsConfiguration.java
    startLine: 107
  package: com.microsoft.azure.management.compute.implementation.api
  summary: >-
    <p>Get the additionalUnattendContent value.</p>

    <p></p>
  syntax:
    content: public List< AdditionalUnattendContent > additionalUnattendContent()
    return:
      type: f6a6204dcom.microsoft.azure.management.compute.implementation.api._additional_unattend_content9ec3e006
      description: <p>the additionalUnattendContent value </p>
- uid: com.microsoft.azure.management.compute.implementation.api._windows_configuration_1a911fc2d81932d5a31e4124ae0716afe6
  id: _windows_configuration_1a911fc2d81932d5a31e4124ae0716afe6
  parent: com.microsoft.azure.management.compute.implementation.api._windows_configuration
  href: com.microsoft.azure.management.compute.implementation.api._windows_configuration.yml
  langs:
  - java
  name: enableAutomaticUpdates()
  fullName: Boolean com.microsoft.azure.management.compute.implementation.api.WindowsConfiguration.enableAutomaticUpdates()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/api/WindowsConfiguration.java
    startLine: 67
  package: com.microsoft.azure.management.compute.implementation.api
  summary: >-
    <p>Get the enableAutomaticUpdates value.</p>

    <p></p>
  syntax:
    content: public Boolean enableAutomaticUpdates()
    return:
      type: 866c2227
      description: <p>the enableAutomaticUpdates value </p>
- uid: com.microsoft.azure.management.compute.implementation.api._windows_configuration_1a79d5f4ec9f291ee1163e9944d081b503
  id: _windows_configuration_1a79d5f4ec9f291ee1163e9944d081b503
  parent: com.microsoft.azure.management.compute.implementation.api._windows_configuration
  href: com.microsoft.azure.management.compute.implementation.api._windows_configuration.yml
  langs:
  - java
  name: provisionVMAgent()
  fullName: Boolean com.microsoft.azure.management.compute.implementation.api.WindowsConfiguration.provisionVMAgent()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/api/WindowsConfiguration.java
    startLine: 47
  package: com.microsoft.azure.management.compute.implementation.api
  summary: >-
    <p>Get the provisionVMAgent value.</p>

    <p></p>
  syntax:
    content: public Boolean provisionVMAgent()
    return:
      type: 866c2227
      description: <p>the provisionVMAgent value </p>
- uid: com.microsoft.azure.management.compute.implementation.api._windows_configuration_1a304b7210f1f0c88b6a9bcba05cc7e46e
  id: _windows_configuration_1a304b7210f1f0c88b6a9bcba05cc7e46e
  parent: com.microsoft.azure.management.compute.implementation.api._windows_configuration
  href: com.microsoft.azure.management.compute.implementation.api._windows_configuration.yml
  langs:
  - java
  name: timeZone()
  fullName: String com.microsoft.azure.management.compute.implementation.api.WindowsConfiguration.timeZone()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/api/WindowsConfiguration.java
    startLine: 87
  package: com.microsoft.azure.management.compute.implementation.api
  summary: >-
    <p>Get the timeZone value.</p>

    <p></p>
  syntax:
    content: public String timeZone()
    return:
      type: "26831127"
      description: <p>the timeZone value </p>
- uid: com.microsoft.azure.management.compute.implementation.api._windows_configuration_1a1e284153956d411574e3b0573ddbd36b
  id: _windows_configuration_1a1e284153956d411574e3b0573ddbd36b
  parent: com.microsoft.azure.management.compute.implementation.api._windows_configuration
  href: com.microsoft.azure.management.compute.implementation.api._windows_configuration.yml
  langs:
  - java
  name: winRM()
  fullName: WinRMConfiguration com.microsoft.azure.management.compute.implementation.api.WindowsConfiguration.winRM()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/api/WindowsConfiguration.java
    startLine: 127
  package: com.microsoft.azure.management.compute.implementation.api
  summary: >-
    <p>Get the winRM value.</p>

    <p></p>
  syntax:
    content: public WinRMConfiguration winRM()
    return:
      type: com.microsoft.azure.management.compute.implementation.api._win_r_m_configuration
      description: <p>the winRM value </p>
- uid: com.microsoft.azure.management.compute.implementation.api._windows_configuration_1a8a7cf4ae1000445044708a77db755060
  id: _windows_configuration_1a8a7cf4ae1000445044708a77db755060
  parent: com.microsoft.azure.management.compute.implementation.api._windows_configuration
  href: com.microsoft.azure.management.compute.implementation.api._windows_configuration.yml
  langs:
  - java
  name: withAdditionalUnattendContent(List< AdditionalUnattendContent > additionalUnattendContent)
  fullName: WindowsConfiguration com.microsoft.azure.management.compute.implementation.api.WindowsConfiguration.withAdditionalUnattendContent(List< AdditionalUnattendContent > additionalUnattendContent)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/api/WindowsConfiguration.java
    startLine: 117
  package: com.microsoft.azure.management.compute.implementation.api
  summary: >-
    <p>Set the additionalUnattendContent value.</p>

    <p></p>
  syntax:
    content: public WindowsConfiguration withAdditionalUnattendContent(List< AdditionalUnattendContent > additionalUnattendContent)
    parameters:
    - id: additionalUnattendContent
      type: f6a6204dcom.microsoft.azure.management.compute.implementation.api._additional_unattend_content9ec3e006
      description: <p>the additionalUnattendContent value to set </p>
    return:
      type: com.microsoft.azure.management.compute.implementation.api._windows_configuration
      description: <p>the <xref href="com.microsoft.azure.management.compute.implementation.api._windows_configuration" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.compute.implementation.api._windows_configuration_1ae40a8b14357cc2ebe4da7787b55f7a46
  id: _windows_configuration_1ae40a8b14357cc2ebe4da7787b55f7a46
  parent: com.microsoft.azure.management.compute.implementation.api._windows_configuration
  href: com.microsoft.azure.management.compute.implementation.api._windows_configuration.yml
  langs:
  - java
  name: withEnableAutomaticUpdates(Boolean enableAutomaticUpdates)
  fullName: WindowsConfiguration com.microsoft.azure.management.compute.implementation.api.WindowsConfiguration.withEnableAutomaticUpdates(Boolean enableAutomaticUpdates)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/api/WindowsConfiguration.java
    startLine: 77
  package: com.microsoft.azure.management.compute.implementation.api
  summary: >-
    <p>Set the enableAutomaticUpdates value.</p>

    <p></p>
  syntax:
    content: public WindowsConfiguration withEnableAutomaticUpdates(Boolean enableAutomaticUpdates)
    parameters:
    - id: enableAutomaticUpdates
      type: 866c2227
      description: <p>the enableAutomaticUpdates value to set </p>
    return:
      type: com.microsoft.azure.management.compute.implementation.api._windows_configuration
      description: <p>the <xref href="com.microsoft.azure.management.compute.implementation.api._windows_configuration" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.compute.implementation.api._windows_configuration_1a51f89a9a0c311cc0842af3cee01f7f0f
  id: _windows_configuration_1a51f89a9a0c311cc0842af3cee01f7f0f
  parent: com.microsoft.azure.management.compute.implementation.api._windows_configuration
  href: com.microsoft.azure.management.compute.implementation.api._windows_configuration.yml
  langs:
  - java
  name: withProvisionVMAgent(Boolean provisionVMAgent)
  fullName: WindowsConfiguration com.microsoft.azure.management.compute.implementation.api.WindowsConfiguration.withProvisionVMAgent(Boolean provisionVMAgent)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/api/WindowsConfiguration.java
    startLine: 57
  package: com.microsoft.azure.management.compute.implementation.api
  summary: >-
    <p>Set the provisionVMAgent value.</p>

    <p></p>
  syntax:
    content: public WindowsConfiguration withProvisionVMAgent(Boolean provisionVMAgent)
    parameters:
    - id: provisionVMAgent
      type: 866c2227
      description: <p>the provisionVMAgent value to set </p>
    return:
      type: com.microsoft.azure.management.compute.implementation.api._windows_configuration
      description: <p>the <xref href="com.microsoft.azure.management.compute.implementation.api._windows_configuration" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.compute.implementation.api._windows_configuration_1ac5f89ac2c2e36abebdee1c06b06e122f
  id: _windows_configuration_1ac5f89ac2c2e36abebdee1c06b06e122f
  parent: com.microsoft.azure.management.compute.implementation.api._windows_configuration
  href: com.microsoft.azure.management.compute.implementation.api._windows_configuration.yml
  langs:
  - java
  name: withTimeZone(String timeZone)
  fullName: WindowsConfiguration com.microsoft.azure.management.compute.implementation.api.WindowsConfiguration.withTimeZone(String timeZone)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/api/WindowsConfiguration.java
    startLine: 97
  package: com.microsoft.azure.management.compute.implementation.api
  summary: >-
    <p>Set the timeZone value.</p>

    <p></p>
  syntax:
    content: public WindowsConfiguration withTimeZone(String timeZone)
    parameters:
    - id: timeZone
      type: "26831127"
      description: <p>the timeZone value to set </p>
    return:
      type: com.microsoft.azure.management.compute.implementation.api._windows_configuration
      description: <p>the <xref href="com.microsoft.azure.management.compute.implementation.api._windows_configuration" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.compute.implementation.api._windows_configuration_1a82675abb87b9e3b8f4adf7e53e971fa7
  id: _windows_configuration_1a82675abb87b9e3b8f4adf7e53e971fa7
  parent: com.microsoft.azure.management.compute.implementation.api._windows_configuration
  href: com.microsoft.azure.management.compute.implementation.api._windows_configuration.yml
  langs:
  - java
  name: withWinRM(WinRMConfiguration winRM)
  fullName: WindowsConfiguration com.microsoft.azure.management.compute.implementation.api.WindowsConfiguration.withWinRM(WinRMConfiguration winRM)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/api/WindowsConfiguration.java
    startLine: 137
  package: com.microsoft.azure.management.compute.implementation.api
  summary: >-
    <p>Set the winRM value.</p>

    <p></p>
  syntax:
    content: public WindowsConfiguration withWinRM(WinRMConfiguration winRM)
    parameters:
    - id: winRM
      type: com.microsoft.azure.management.compute.implementation.api._win_r_m_configuration
      description: <p>the winRM value to set </p>
    return:
      type: com.microsoft.azure.management.compute.implementation.api._windows_configuration
      description: <p>the <xref href="com.microsoft.azure.management.compute.implementation.api._windows_configuration" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: 866c2227
  spec.java:
  - name: Boolean
    fullName: Boolean
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: f6a6204dcom.microsoft.azure.management.compute.implementation.api._additional_unattend_content9ec3e006
  spec.java:
  - name: 'List< '
    fullName: 'List< '
  - uid: com.microsoft.azure.management.compute.implementation.api._additional_unattend_content
    name: AdditionalUnattendContent
    fullName: com.microsoft.azure.management.compute.implementation.api.AdditionalUnattendContent
    href: com.microsoft.azure.management.compute.implementation.api._additional_unattend_content.yml
  - name: ' >'
    fullName: ' >'
- uid: com.microsoft.azure.management.compute.implementation.api._additional_unattend_content
  parent: com.microsoft.azure.management.compute.implementation.api
  href: com.microsoft.azure.management.compute.implementation.api._additional_unattend_content.yml
  name: AdditionalUnattendContent
  fullName: com.microsoft.azure.management.compute.implementation.api.AdditionalUnattendContent
  type: Class
  summary: <p>Gets or sets additional XML formatted information that can be included in the Unattend.xml file, which is used by Windows Setup. Contents are defined by setting name, component name, and the pass in which the content is a applied. </p>
  syntax:
    content: public class AdditionalUnattendContent
- uid: com.microsoft.azure.management.compute.implementation.api._win_r_m_configuration
  parent: com.microsoft.azure.management.compute.implementation.api
  href: com.microsoft.azure.management.compute.implementation.api._win_r_m_configuration.yml
  name: WinRMConfiguration
  fullName: com.microsoft.azure.management.compute.implementation.api.WinRMConfiguration
  type: Class
  summary: <p>Describes Windows Remote Management configuration of the VM. </p>
  syntax:
    content: public class WinRMConfiguration
- uid: com.microsoft.azure.management.compute.implementation.api._windows_configuration
  parent: com.microsoft.azure.management.compute.implementation.api
  href: com.microsoft.azure.management.compute.implementation.api._windows_configuration.yml
  name: WindowsConfiguration
  fullName: com.microsoft.azure.management.compute.implementation.api.WindowsConfiguration
  type: Class
  summary: <p>Describes Windows Configuration of the OS Profile. </p>
  syntax: *o1
