items:
- uid: com.microsoft.azure.management.network._application_gateway_ssl_certificate
  id: _application_gateway_ssl_certificate
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._application_gateway_ssl_certificate_1aea94936082608f410c3f289222b991d4
  - com.microsoft.azure.management.network._application_gateway_ssl_certificate_1a666cfc604eb71536c0952df4104f02dc
  - com.microsoft.azure.management.network._application_gateway_ssl_certificate_1ada248cd5ad100b8d084b283da3b7faf6
  - com.microsoft.azure.management.network._application_gateway_ssl_certificate_1a9b4a6826fa4adb4274d6e7ecd10de505
  - com.microsoft.azure.management.network._application_gateway_ssl_certificate_1a0fb42191ec4dcd781cd3ac8db77c9084
  - com.microsoft.azure.management.network._application_gateway_ssl_certificate_1ad7e963544153c7786e6b322eaf09d17c
  - com.microsoft.azure.management.network._application_gateway_ssl_certificate_1a434ec3db28014fb4115eea16961f191f
  - com.microsoft.azure.management.network._application_gateway_ssl_certificate_1aaa131314eefc2bbef28a63b8cb39088b
  - com.microsoft.azure.management.network._application_gateway_ssl_certificate_1a8f7be07f090f89933fc2eeed8309e8af
  - com.microsoft.azure.management.network._application_gateway_ssl_certificate_1ab9cf580ee4b2373dc852745d6425b3a8
  - com.microsoft.azure.management.network._application_gateway_ssl_certificate_1ac61509c70f4ef42620b27032f5e5ed3b
  - com.microsoft.azure.management.network._application_gateway_ssl_certificate_1aae765ec29ed1ff0bd41e8c8b7af05bd8
  href: com.microsoft.azure.management.network._application_gateway_ssl_certificate.yml
  langs:
  - java
  name: ApplicationGatewaySslCertificate
  fullName: com.microsoft.azure.management.network.ApplicationGatewaySslCertificate
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySslCertificate.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySslCertificate.java
    startLine: 18
  package: com.microsoft.azure.management.network
  summary: <p>SSL certificates of application gateway. </p>
  syntax: &o1
    content: public class ApplicationGatewaySslCertificate extends SubResource
  inheritance:
  - java.lang.Object
  - com.microsoft.azure._sub_resource
  inheritedMembers:
  - com.microsoft.azure._sub_resource_1a92e02020e7fca6a3d2284bc1db599e52
  - com.microsoft.azure._sub_resource_1a522b0146c9247308f3752dd123100d8a
- uid: com.microsoft.azure.management.network._application_gateway_ssl_certificate_1aea94936082608f410c3f289222b991d4
  id: _application_gateway_ssl_certificate_1aea94936082608f410c3f289222b991d4
  parent: com.microsoft.azure.management.network._application_gateway_ssl_certificate
  href: com.microsoft.azure.management.network._application_gateway_ssl_certificate.yml
  langs:
  - java
  name: data()
  fullName: String com.microsoft.azure.management.network.ApplicationGatewaySslCertificate.data()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySslCertificate.java
    startLine: 60
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the data value.</p>

    <p></p>
  syntax:
    content: public String data()
    return:
      type: "26831127"
      description: <p>the data value </p>
- uid: com.microsoft.azure.management.network._application_gateway_ssl_certificate_1a666cfc604eb71536c0952df4104f02dc
  id: _application_gateway_ssl_certificate_1a666cfc604eb71536c0952df4104f02dc
  parent: com.microsoft.azure.management.network._application_gateway_ssl_certificate
  href: com.microsoft.azure.management.network._application_gateway_ssl_certificate.yml
  langs:
  - java
  name: etag()
  fullName: String com.microsoft.azure.management.network.ApplicationGatewaySslCertificate.etag()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySslCertificate.java
    startLine: 160
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the etag value.</p>

    <p></p>
  syntax:
    content: public String etag()
    return:
      type: "26831127"
      description: <p>the etag value </p>
- uid: com.microsoft.azure.management.network._application_gateway_ssl_certificate_1ada248cd5ad100b8d084b283da3b7faf6
  id: _application_gateway_ssl_certificate_1ada248cd5ad100b8d084b283da3b7faf6
  parent: com.microsoft.azure.management.network._application_gateway_ssl_certificate
  href: com.microsoft.azure.management.network._application_gateway_ssl_certificate.yml
  langs:
  - java
  name: name()
  fullName: String com.microsoft.azure.management.network.ApplicationGatewaySslCertificate.name()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySslCertificate.java
    startLine: 140
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the name value.</p>

    <p></p>
  syntax:
    content: public String name()
    return:
      type: "26831127"
      description: <p>the name value </p>
- uid: com.microsoft.azure.management.network._application_gateway_ssl_certificate_1a9b4a6826fa4adb4274d6e7ecd10de505
  id: _application_gateway_ssl_certificate_1a9b4a6826fa4adb4274d6e7ecd10de505
  parent: com.microsoft.azure.management.network._application_gateway_ssl_certificate
  href: com.microsoft.azure.management.network._application_gateway_ssl_certificate.yml
  langs:
  - java
  name: password()
  fullName: String com.microsoft.azure.management.network.ApplicationGatewaySslCertificate.password()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySslCertificate.java
    startLine: 80
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the password value.</p>

    <p></p>
  syntax:
    content: public String password()
    return:
      type: "26831127"
      description: <p>the password value </p>
- uid: com.microsoft.azure.management.network._application_gateway_ssl_certificate_1a0fb42191ec4dcd781cd3ac8db77c9084
  id: _application_gateway_ssl_certificate_1a0fb42191ec4dcd781cd3ac8db77c9084
  parent: com.microsoft.azure.management.network._application_gateway_ssl_certificate
  href: com.microsoft.azure.management.network._application_gateway_ssl_certificate.yml
  langs:
  - java
  name: provisioningState()
  fullName: String com.microsoft.azure.management.network.ApplicationGatewaySslCertificate.provisioningState()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySslCertificate.java
    startLine: 120
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the provisioningState value.</p>

    <p></p>
  syntax:
    content: public String provisioningState()
    return:
      type: "26831127"
      description: <p>the provisioningState value </p>
- uid: com.microsoft.azure.management.network._application_gateway_ssl_certificate_1ad7e963544153c7786e6b322eaf09d17c
  id: _application_gateway_ssl_certificate_1ad7e963544153c7786e6b322eaf09d17c
  parent: com.microsoft.azure.management.network._application_gateway_ssl_certificate
  href: com.microsoft.azure.management.network._application_gateway_ssl_certificate.yml
  langs:
  - java
  name: publicCertData()
  fullName: String com.microsoft.azure.management.network.ApplicationGatewaySslCertificate.publicCertData()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySslCertificate.java
    startLine: 100
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the publicCertData value.</p>

    <p></p>
  syntax:
    content: public String publicCertData()
    return:
      type: "26831127"
      description: <p>the publicCertData value </p>
- uid: com.microsoft.azure.management.network._application_gateway_ssl_certificate_1a434ec3db28014fb4115eea16961f191f
  id: _application_gateway_ssl_certificate_1a434ec3db28014fb4115eea16961f191f
  parent: com.microsoft.azure.management.network._application_gateway_ssl_certificate
  href: com.microsoft.azure.management.network._application_gateway_ssl_certificate.yml
  langs:
  - java
  name: withData(String data)
  fullName: ApplicationGatewaySslCertificate com.microsoft.azure.management.network.ApplicationGatewaySslCertificate.withData(String data)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySslCertificate.java
    startLine: 70
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the data value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewaySslCertificate withData(String data)
    parameters:
    - id: data
      type: "26831127"
      description: <p>the data value to set </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_ssl_certificate
      description: <p>the <xref href="com.microsoft.azure.management.network._application_gateway_ssl_certificate" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network._application_gateway_ssl_certificate_1aaa131314eefc2bbef28a63b8cb39088b
  id: _application_gateway_ssl_certificate_1aaa131314eefc2bbef28a63b8cb39088b
  parent: com.microsoft.azure.management.network._application_gateway_ssl_certificate
  href: com.microsoft.azure.management.network._application_gateway_ssl_certificate.yml
  langs:
  - java
  name: withEtag(String etag)
  fullName: ApplicationGatewaySslCertificate com.microsoft.azure.management.network.ApplicationGatewaySslCertificate.withEtag(String etag)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySslCertificate.java
    startLine: 170
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the etag value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewaySslCertificate withEtag(String etag)
    parameters:
    - id: etag
      type: "26831127"
      description: <p>the etag value to set </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_ssl_certificate
      description: <p>the <xref href="com.microsoft.azure.management.network._application_gateway_ssl_certificate" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network._application_gateway_ssl_certificate_1a8f7be07f090f89933fc2eeed8309e8af
  id: _application_gateway_ssl_certificate_1a8f7be07f090f89933fc2eeed8309e8af
  parent: com.microsoft.azure.management.network._application_gateway_ssl_certificate
  href: com.microsoft.azure.management.network._application_gateway_ssl_certificate.yml
  langs:
  - java
  name: withName(String name)
  fullName: ApplicationGatewaySslCertificate com.microsoft.azure.management.network.ApplicationGatewaySslCertificate.withName(String name)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySslCertificate.java
    startLine: 150
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the name value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewaySslCertificate withName(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>the name value to set </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_ssl_certificate
      description: <p>the <xref href="com.microsoft.azure.management.network._application_gateway_ssl_certificate" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network._application_gateway_ssl_certificate_1ab9cf580ee4b2373dc852745d6425b3a8
  id: _application_gateway_ssl_certificate_1ab9cf580ee4b2373dc852745d6425b3a8
  parent: com.microsoft.azure.management.network._application_gateway_ssl_certificate
  href: com.microsoft.azure.management.network._application_gateway_ssl_certificate.yml
  langs:
  - java
  name: withPassword(String password)
  fullName: ApplicationGatewaySslCertificate com.microsoft.azure.management.network.ApplicationGatewaySslCertificate.withPassword(String password)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySslCertificate.java
    startLine: 90
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the password value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewaySslCertificate withPassword(String password)
    parameters:
    - id: password
      type: "26831127"
      description: <p>the password value to set </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_ssl_certificate
      description: <p>the <xref href="com.microsoft.azure.management.network._application_gateway_ssl_certificate" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network._application_gateway_ssl_certificate_1ac61509c70f4ef42620b27032f5e5ed3b
  id: _application_gateway_ssl_certificate_1ac61509c70f4ef42620b27032f5e5ed3b
  parent: com.microsoft.azure.management.network._application_gateway_ssl_certificate
  href: com.microsoft.azure.management.network._application_gateway_ssl_certificate.yml
  langs:
  - java
  name: withProvisioningState(String provisioningState)
  fullName: ApplicationGatewaySslCertificate com.microsoft.azure.management.network.ApplicationGatewaySslCertificate.withProvisioningState(String provisioningState)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySslCertificate.java
    startLine: 130
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the provisioningState value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewaySslCertificate withProvisioningState(String provisioningState)
    parameters:
    - id: provisioningState
      type: "26831127"
      description: <p>the provisioningState value to set </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_ssl_certificate
      description: <p>the <xref href="com.microsoft.azure.management.network._application_gateway_ssl_certificate" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network._application_gateway_ssl_certificate_1aae765ec29ed1ff0bd41e8c8b7af05bd8
  id: _application_gateway_ssl_certificate_1aae765ec29ed1ff0bd41e8c8b7af05bd8
  parent: com.microsoft.azure.management.network._application_gateway_ssl_certificate
  href: com.microsoft.azure.management.network._application_gateway_ssl_certificate.yml
  langs:
  - java
  name: withPublicCertData(String publicCertData)
  fullName: ApplicationGatewaySslCertificate com.microsoft.azure.management.network.ApplicationGatewaySslCertificate.withPublicCertData(String publicCertData)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySslCertificate.java
    startLine: 110
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the publicCertData value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewaySslCertificate withPublicCertData(String publicCertData)
    parameters:
    - id: publicCertData
      type: "26831127"
      description: <p>the publicCertData value to set </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_ssl_certificate
      description: <p>the <xref href="com.microsoft.azure.management.network._application_gateway_ssl_certificate" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure._sub_resource_1a92e02020e7fca6a3d2284bc1db599e52
  parent: com.microsoft.azure._sub_resource
  href: com.microsoft.azure._sub_resource.yml
  name: id()
  fullName: String com.microsoft.azure.SubResource.id()
  type: Method
  summary: >-
    <p>Get the id value.</p>

    <p></p>
  syntax:
    content: public String id()
    return:
      type: "26831127"
      description: <p>the id value </p>
- uid: com.microsoft.azure._sub_resource_1a522b0146c9247308f3752dd123100d8a
  parent: com.microsoft.azure._sub_resource
  href: com.microsoft.azure._sub_resource.yml
  name: withId(String id)
  fullName: SubResource com.microsoft.azure.SubResource.withId(String id)
  type: Method
  summary: >-
    <p>Set the id value.</p>

    <p></p>
  syntax:
    content: public SubResource withId(String id)
    parameters:
    - id: id
      type: "26831127"
      description: <p>the id value to set </p>
    return:
      type: com.microsoft.azure._sub_resource
      description: <p>the sub resource itself </p>
- uid: com.microsoft.azure._sub_resource
  parent: com.microsoft.azure
  href: com.microsoft.azure._sub_resource.yml
  name: SubResource
  fullName: com.microsoft.azure.SubResource
  type: Class
  summary: <p>The <xref href="com.microsoft.azure._sub_resource" data-throw-if-not-resolved="false"></xref> model. </p>
  syntax:
    content: public class SubResource
- uid: com.microsoft.azure.management.network._application_gateway_ssl_certificate
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_ssl_certificate.yml
  name: ApplicationGatewaySslCertificate
  fullName: com.microsoft.azure.management.network.ApplicationGatewaySslCertificate
  type: Class
  summary: <p>SSL certificates of application gateway. </p>
  syntax: *o1
