items:
- uid: com.microsoft.azure.management.network._application_gateway_cookie_based_affinity
  id: _application_gateway_cookie_based_affinity
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._application_gateway_cookie_based_affinity_1a6260f0ee38f403057c1de494e1100923
  - com.microsoft.azure.management.network._application_gateway_cookie_based_affinity_1ad7c8e994bb93a92ee5c374aee62364dd
  href: com.microsoft.azure.management.network._application_gateway_cookie_based_affinity.yml
  langs:
  - java
  name: ApplicationGatewayCookieBasedAffinity
  fullName: com.microsoft.azure.management.network.ApplicationGatewayCookieBasedAffinity
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayCookieBasedAffinity.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayCookieBasedAffinity.java
    startLine: 13
  package: com.microsoft.azure.management.network
  summary: <p>Defines values for <xref href="com.microsoft.azure.management.network._application_gateway_cookie_based_affinity" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: &o1
    content: public class ApplicationGatewayCookieBasedAffinity
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.network._application_gateway_cookie_based_affinity_1a6260f0ee38f403057c1de494e1100923
  id: _application_gateway_cookie_based_affinity_1a6260f0ee38f403057c1de494e1100923
  parent: com.microsoft.azure.management.network._application_gateway_cookie_based_affinity
  href: com.microsoft.azure.management.network._application_gateway_cookie_based_affinity.yml
  langs:
  - java
  name: DISABLED
  fullName: final String com.microsoft.azure.management.network.ApplicationGatewayCookieBasedAffinity.DISABLED
  type: Field
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayCookieBasedAffinity.java
    startLine: 18
  package: com.microsoft.azure.management.network
  summary: <p>Static value Disabled for <xref href="com.microsoft.azure.management.network._application_gateway_cookie_based_affinity" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public static final String DISABLED= "Disabled"
    return:
      type: 3d93591e
- uid: com.microsoft.azure.management.network._application_gateway_cookie_based_affinity_1ad7c8e994bb93a92ee5c374aee62364dd
  id: _application_gateway_cookie_based_affinity_1ad7c8e994bb93a92ee5c374aee62364dd
  parent: com.microsoft.azure.management.network._application_gateway_cookie_based_affinity
  href: com.microsoft.azure.management.network._application_gateway_cookie_based_affinity.yml
  langs:
  - java
  name: ENABLED
  fullName: final String com.microsoft.azure.management.network.ApplicationGatewayCookieBasedAffinity.ENABLED
  type: Field
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayCookieBasedAffinity.java
    startLine: 15
  package: com.microsoft.azure.management.network
  summary: <p>Static value Enabled for <xref href="com.microsoft.azure.management.network._application_gateway_cookie_based_affinity" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public static final String ENABLED= "Enabled"
    return:
      type: 3d93591e
references:
- uid: 3d93591e
  spec.java:
  - name: final String
    fullName: final String
- uid: com.microsoft.azure.management.network._application_gateway_cookie_based_affinity
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_cookie_based_affinity.yml
  name: ApplicationGatewayCookieBasedAffinity
  fullName: com.microsoft.azure.management.network.ApplicationGatewayCookieBasedAffinity
  type: Class
  summary: <p>Defines values for <xref href="com.microsoft.azure.management.network._application_gateway_cookie_based_affinity" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: *o1
