items:
- uid: com.microsoft.azure.management.network._nic_ip_configuration
  id: _nic_ip_configuration
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._nic_ip_configuration_1a0ae8aa383be44cae8a9fab4996a05642
  - com.microsoft.azure.management.network._nic_ip_configuration_1a48c47f493a4270b15c0d03712c32702c
  - com.microsoft.azure.management.network._nic_ip_configuration_1a925fe54c796f2702a9f16fc1a7689d5c
  - com.microsoft.azure.management.network._nic_ip_configuration_1a01ad2e7d537bfd0f0d35878f64d0bb29
  - com.microsoft.azure.management.network._nic_ip_configuration_1a0f55170ea4df62421b0235974ba1264d
  - com.microsoft.azure.management.network._nic_ip_configuration_1a7750d5f0b73395e352ed495c4a0aff70
  href: com.microsoft.azure.management.network._nic_ip_configuration.yml
  langs:
  - java
  name: NicIpConfiguration
  fullName: com.microsoft.azure.management.network.NicIpConfiguration
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
    startLine: 14
  package: com.microsoft.azure.management.network
  summary: <p>An Ip configuration in a network interface. </p>
  syntax:
    content: public interface NicIpConfiguration extends Wrapper<T>,ChildResource
  inheritance:
  - com.microsoft.azure.management.resources.fluentcore.model._wrapper
  inheritedMembers:
  - com.microsoft.azure.management.resources.fluentcore.model._wrapper_1abc55ed091c6359eabd413c60b0d3c7fb
  - com.microsoft.azure.management.resources.fluentcore.model._indexable_1ab0ae133d20d97eaee0480795ee886bde
  - com.microsoft.azure.management.resources.fluentcore.arm.models._child_resource_1a384971adbe954cdc27906f16028e22d3
- uid: com.microsoft.azure.management.network._nic_ip_configuration_1a0ae8aa383be44cae8a9fab4996a05642
  id: _nic_ip_configuration_1a0ae8aa383be44cae8a9fab4996a05642
  parent: com.microsoft.azure.management.network._nic_ip_configuration
  href: com.microsoft.azure.management.network._nic_ip_configuration.yml
  langs:
  - java
  name: network()
  fullName: Network com.microsoft.azure.management.network.NicIpConfiguration.network()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
    startLine: 66
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Gets the virtual network associated with this Ip configuration. </p>

    <p>note that this method makes a rest API call to fetch the public IP</p>

    <p></p>
  syntax:
    content: public Network network()
    return:
      type: com.microsoft.azure.management.network._network
      description: <p>the virtual network associated with this this Ip configuration. </p>
  exceptions:
  - type: com.microsoft.azure._cloud_exception
    description: <p>exceptions thrown from the cloud. </p>
  - type: cbf33bbe
    description: <p>exceptions thrown from serialization/deserialization. </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration_1a48c47f493a4270b15c0d03712c32702c
  id: _nic_ip_configuration_1a48c47f493a4270b15c0d03712c32702c
  parent: com.microsoft.azure.management.network._nic_ip_configuration
  href: com.microsoft.azure.management.network._nic_ip_configuration.yml
  langs:
  - java
  name: privateIp()
  fullName: String com.microsoft.azure.management.network.NicIpConfiguration.privateIp()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
    startLine: 75
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Gets the private IP address allocated to this Ip configuration. </p>

    <p>the private IP will be within the virtual network subnet of this Ip configuration</p>

    <p></p>
  syntax:
    content: public String privateIp()
    return:
      type: "26831127"
      description: <p>the private IP addresses </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration_1a925fe54c796f2702a9f16fc1a7689d5c
  id: _nic_ip_configuration_1a925fe54c796f2702a9f16fc1a7689d5c
  parent: com.microsoft.azure.management.network._nic_ip_configuration
  href: com.microsoft.azure.management.network._nic_ip_configuration.yml
  langs:
  - java
  name: privateIpAllocationMethod()
  fullName: String com.microsoft.azure.management.network.NicIpConfiguration.privateIpAllocationMethod()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
    startLine: 80
  package: com.microsoft.azure.management.network
  syntax:
    content: public String privateIpAllocationMethod()
    return:
      type: "26831127"
      description: <p>the private IP allocation method (Dynamic, Static) </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration_1a01ad2e7d537bfd0f0d35878f64d0bb29
  id: _nic_ip_configuration_1a01ad2e7d537bfd0f0d35878f64d0bb29
  parent: com.microsoft.azure.management.network._nic_ip_configuration
  href: com.microsoft.azure.management.network._nic_ip_configuration.yml
  langs:
  - java
  name: publicIpAddress()
  fullName: PublicIpAddress com.microsoft.azure.management.network.NicIpConfiguration.publicIpAddress()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
    startLine: 50
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Gets the public IP address associated with this Ip configuration. </p>

    <p>note that this method makes a rest API call to fetch the public IP</p>

    <p></p>
  syntax:
    content: public PublicIpAddress publicIpAddress()
    return:
      type: com.microsoft.azure.management.network._public_ip_address
      description: <p>the public IP associated with this Ip configuration. </p>
  exceptions:
  - type: com.microsoft.azure._cloud_exception
    description: <p>exceptions thrown from the cloud. </p>
  - type: cbf33bbe
    description: <p>exceptions thrown from serialization/deserialization. </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration_1a0f55170ea4df62421b0235974ba1264d
  id: _nic_ip_configuration_1a0f55170ea4df62421b0235974ba1264d
  parent: com.microsoft.azure.management.network._nic_ip_configuration
  href: com.microsoft.azure.management.network._nic_ip_configuration.yml
  langs:
  - java
  name: publicIpAddressId()
  fullName: String com.microsoft.azure.management.network.NicIpConfiguration.publicIpAddressId()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
    startLine: 39
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Gets the resource id of the public IP address associated with this Ip configuration. </p>

    <p>returns null if there is no public IP associated</p>

    <p></p>
  syntax:
    content: public String publicIpAddressId()
    return:
      type: "26831127"
      description: <p>public ip resource id </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration_1a7750d5f0b73395e352ed495c4a0aff70
  id: _nic_ip_configuration_1a7750d5f0b73395e352ed495c4a0aff70
  parent: com.microsoft.azure.management.network._nic_ip_configuration
  href: com.microsoft.azure.management.network._nic_ip_configuration.yml
  langs:
  - java
  name: subnetId()
  fullName: String com.microsoft.azure.management.network.NicIpConfiguration.subnetId()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
    startLine: 55
  package: com.microsoft.azure.management.network
  syntax:
    content: public String subnetId()
    return:
      type: "26831127"
      description: <p>the resource id of the virtual network subnet associated with this Ip configuration. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: cbf33bbe
  spec.java:
  - name: IOException
    fullName: IOException
- uid: com.microsoft.azure.management.resources.fluentcore.model._wrapper_1abc55ed091c6359eabd413c60b0d3c7fb
  parent: com.microsoft.azure.management.resources.fluentcore.model._wrapper
  href: com.microsoft.azure.management.resources.fluentcore.model._wrapper.yml
  name: inner()
  fullName: T com.microsoft.azure.management.resources.fluentcore.model.Wrapper< T >.inner()
  type: Method
  syntax:
    content: public T inner()
    return:
      type: 8ce1ecb9
      description: <p>wrapped inner object providing direct access to the underlying auto-generated API implementation, based on <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> REST API </p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._indexable_1ab0ae133d20d97eaee0480795ee886bde
  parent: com.microsoft.azure.management.resources.fluentcore.model._indexable
  href: com.microsoft.azure.management.resources.fluentcore.model._indexable.yml
  name: key()
  fullName: String com.microsoft.azure.management.resources.fluentcore.model.Indexable.key()
  type: Method
  syntax:
    content: public String key()
    return:
      type: "26831127"
      description: <p>the index key. </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm.models._child_resource_1a384971adbe954cdc27906f16028e22d3
  parent: com.microsoft.azure.management.resources.fluentcore.arm.models._child_resource
  href: com.microsoft.azure.management.resources.fluentcore.arm.models._child_resource.yml
  name: name()
  fullName: String com.microsoft.azure.management.resources.fluentcore.arm.models.ChildResource.name()
  type: Method
  syntax:
    content: public String name()
    return:
      type: "26831127"
      description: <p>the name of the child resource </p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._wrapper
  parent: com.microsoft.azure.management.resources.fluentcore.model
  href: com.microsoft.azure.management.resources.fluentcore.model._wrapper.yml
  name: Wrapper<T>
  fullName: com.microsoft.azure.management.resources.fluentcore.model.Wrapper<T>
  type: Interface
  summary: >-
    <p>The wrapper around an inner object providing extended functionalities.</p>

    <p></p>
  syntax:
    content: public interface Wrapper<T>
    typeParameters:
    - type: 8ce1ecb9
      description: <p>the type of the inner object. </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm.models._child_resource
  parent: com.microsoft.azure.management.resources.fluentcore.arm.models
  href: com.microsoft.azure.management.resources.fluentcore.arm.models._child_resource.yml
  name: ChildResource
  fullName: com.microsoft.azure.management.resources.fluentcore.arm.models.ChildResource
  type: Interface
  summary: <p>Base interface used by child resources. </p>
  syntax:
    content: public interface ChildResource extends Indexable
- uid: com.microsoft.azure.management.network.implementation._nic_ip_configuration_impl
- uid: com.microsoft.azure.management.network._public_ip_address
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._public_ip_address.yml
  name: PublicIpAddress
  fullName: com.microsoft.azure.management.network.PublicIpAddress
  type: Interface
  summary: <p>Public IP address. </p>
  syntax:
    content: public interface PublicIpAddress
- uid: com.microsoft.azure._cloud_exception
  parent: com.microsoft.azure
  href: com.microsoft.azure._cloud_exception.yml
  name: CloudException
  fullName: com.microsoft.azure.CloudException
  type: Class
  summary: <p>Exception thrown for an invalid response with custom error information. </p>
  syntax:
    content: public class CloudException extends RestException
- uid: com.microsoft.azure.management.network._network
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._network.yml
  name: Network
  fullName: com.microsoft.azure.management.network.Network
  type: Interface
  summary: <p>Entry point for Virtual <xref href="com.microsoft.azure.management.network._network" data-throw-if-not-resolved="false"></xref> management API in <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public interface Network extends GroupableResource,Refreshable<T>,Wrapper<T>,Updatable<T>
