items:
- uid: com.microsoft.azure.management.compute._disk_encryption_settings
  id: _disk_encryption_settings
  parent: com.microsoft.azure.management.compute
  children:
  - com.microsoft.azure.management.compute._disk_encryption_settings_1a68132de35ec8bf6ef79cd8e8e39238c2
  - com.microsoft.azure.management.compute._disk_encryption_settings_1a05c8fd1edc4a9e74cdc7f63697304038
  - com.microsoft.azure.management.compute._disk_encryption_settings_1a241b85508a88bcf14432018e2e3b3f3c
  - com.microsoft.azure.management.compute._disk_encryption_settings_1a9f21eb37a1c327bf30701049fb6dfd7f
  - com.microsoft.azure.management.compute._disk_encryption_settings_1ae1c262b3317e8a58f7a55aad20f62572
  - com.microsoft.azure.management.compute._disk_encryption_settings_1a4360f670d080f4c2969b13bb8bdbd336
  href: com.microsoft.azure.management.compute._disk_encryption_settings.yml
  langs:
  - java
  name: DiskEncryptionSettings
  fullName: com.microsoft.azure.management.compute.DiskEncryptionSettings
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/DiskEncryptionSettings.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/DiskEncryptionSettings.java
    startLine: 14
  package: com.microsoft.azure.management.compute
  summary: <p>Describes a Encryption Settings for a Disk. </p>
  syntax: &o1
    content: public class DiskEncryptionSettings
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.compute._disk_encryption_settings_1a68132de35ec8bf6ef79cd8e8e39238c2
  id: _disk_encryption_settings_1a68132de35ec8bf6ef79cd8e8e39238c2
  parent: com.microsoft.azure.management.compute._disk_encryption_settings
  href: com.microsoft.azure.management.compute._disk_encryption_settings.yml
  langs:
  - java
  name: diskEncryptionKey()
  fullName: KeyVaultSecretReference com.microsoft.azure.management.compute.DiskEncryptionSettings.diskEncryptionKey()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/DiskEncryptionSettings.java
    startLine: 35
  package: com.microsoft.azure.management.compute
  summary: >-
    <p>Get the diskEncryptionKey value.</p>

    <p></p>
  syntax:
    content: public KeyVaultSecretReference diskEncryptionKey()
    return:
      type: com.microsoft.azure.management.compute._key_vault_secret_reference
      description: <p>the diskEncryptionKey value </p>
- uid: com.microsoft.azure.management.compute._disk_encryption_settings_1a05c8fd1edc4a9e74cdc7f63697304038
  id: _disk_encryption_settings_1a05c8fd1edc4a9e74cdc7f63697304038
  parent: com.microsoft.azure.management.compute._disk_encryption_settings
  href: com.microsoft.azure.management.compute._disk_encryption_settings.yml
  langs:
  - java
  name: enabled()
  fullName: Boolean com.microsoft.azure.management.compute.DiskEncryptionSettings.enabled()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/DiskEncryptionSettings.java
    startLine: 75
  package: com.microsoft.azure.management.compute
  summary: >-
    <p>Get the enabled value.</p>

    <p></p>
  syntax:
    content: public Boolean enabled()
    return:
      type: 866c2227
      description: <p>the enabled value </p>
- uid: com.microsoft.azure.management.compute._disk_encryption_settings_1a241b85508a88bcf14432018e2e3b3f3c
  id: _disk_encryption_settings_1a241b85508a88bcf14432018e2e3b3f3c
  parent: com.microsoft.azure.management.compute._disk_encryption_settings
  href: com.microsoft.azure.management.compute._disk_encryption_settings.yml
  langs:
  - java
  name: keyEncryptionKey()
  fullName: KeyVaultKeyReference com.microsoft.azure.management.compute.DiskEncryptionSettings.keyEncryptionKey()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/DiskEncryptionSettings.java
    startLine: 55
  package: com.microsoft.azure.management.compute
  summary: >-
    <p>Get the keyEncryptionKey value.</p>

    <p></p>
  syntax:
    content: public KeyVaultKeyReference keyEncryptionKey()
    return:
      type: com.microsoft.azure.management.compute._key_vault_key_reference
      description: <p>the keyEncryptionKey value </p>
- uid: com.microsoft.azure.management.compute._disk_encryption_settings_1a9f21eb37a1c327bf30701049fb6dfd7f
  id: _disk_encryption_settings_1a9f21eb37a1c327bf30701049fb6dfd7f
  parent: com.microsoft.azure.management.compute._disk_encryption_settings
  href: com.microsoft.azure.management.compute._disk_encryption_settings.yml
  langs:
  - java
  name: withDiskEncryptionKey(KeyVaultSecretReference diskEncryptionKey)
  fullName: DiskEncryptionSettings com.microsoft.azure.management.compute.DiskEncryptionSettings.withDiskEncryptionKey(KeyVaultSecretReference diskEncryptionKey)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/DiskEncryptionSettings.java
    startLine: 45
  package: com.microsoft.azure.management.compute
  summary: >-
    <p>Set the diskEncryptionKey value.</p>

    <p></p>
  syntax:
    content: public DiskEncryptionSettings withDiskEncryptionKey(KeyVaultSecretReference diskEncryptionKey)
    parameters:
    - id: diskEncryptionKey
      type: com.microsoft.azure.management.compute._key_vault_secret_reference
      description: <p>the diskEncryptionKey value to set </p>
    return:
      type: com.microsoft.azure.management.compute._disk_encryption_settings
      description: <p>the <xref href="com.microsoft.azure.management.compute._disk_encryption_settings" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.compute._disk_encryption_settings_1ae1c262b3317e8a58f7a55aad20f62572
  id: _disk_encryption_settings_1ae1c262b3317e8a58f7a55aad20f62572
  parent: com.microsoft.azure.management.compute._disk_encryption_settings
  href: com.microsoft.azure.management.compute._disk_encryption_settings.yml
  langs:
  - java
  name: withEnabled(Boolean enabled)
  fullName: DiskEncryptionSettings com.microsoft.azure.management.compute.DiskEncryptionSettings.withEnabled(Boolean enabled)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/DiskEncryptionSettings.java
    startLine: 85
  package: com.microsoft.azure.management.compute
  summary: >-
    <p>Set the enabled value.</p>

    <p></p>
  syntax:
    content: public DiskEncryptionSettings withEnabled(Boolean enabled)
    parameters:
    - id: enabled
      type: 866c2227
      description: <p>the enabled value to set </p>
    return:
      type: com.microsoft.azure.management.compute._disk_encryption_settings
      description: <p>the <xref href="com.microsoft.azure.management.compute._disk_encryption_settings" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.compute._disk_encryption_settings_1a4360f670d080f4c2969b13bb8bdbd336
  id: _disk_encryption_settings_1a4360f670d080f4c2969b13bb8bdbd336
  parent: com.microsoft.azure.management.compute._disk_encryption_settings
  href: com.microsoft.azure.management.compute._disk_encryption_settings.yml
  langs:
  - java
  name: withKeyEncryptionKey(KeyVaultKeyReference keyEncryptionKey)
  fullName: DiskEncryptionSettings com.microsoft.azure.management.compute.DiskEncryptionSettings.withKeyEncryptionKey(KeyVaultKeyReference keyEncryptionKey)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/DiskEncryptionSettings.java
    startLine: 65
  package: com.microsoft.azure.management.compute
  summary: >-
    <p>Set the keyEncryptionKey value.</p>

    <p></p>
  syntax:
    content: public DiskEncryptionSettings withKeyEncryptionKey(KeyVaultKeyReference keyEncryptionKey)
    parameters:
    - id: keyEncryptionKey
      type: com.microsoft.azure.management.compute._key_vault_key_reference
      description: <p>the keyEncryptionKey value to set </p>
    return:
      type: com.microsoft.azure.management.compute._disk_encryption_settings
      description: <p>the <xref href="com.microsoft.azure.management.compute._disk_encryption_settings" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: 866c2227
  spec.java:
  - name: Boolean
    fullName: Boolean
- uid: com.microsoft.azure.management.compute._key_vault_secret_reference
  parent: com.microsoft.azure.management.compute
  href: com.microsoft.azure.management.compute._key_vault_secret_reference.yml
  name: KeyVaultSecretReference
  fullName: com.microsoft.azure.management.compute.KeyVaultSecretReference
  type: Class
  summary: <p>Describes a reference to Key Vault Secret. </p>
  syntax:
    content: public class KeyVaultSecretReference
- uid: com.microsoft.azure.management.compute._key_vault_key_reference
  parent: com.microsoft.azure.management.compute
  href: com.microsoft.azure.management.compute._key_vault_key_reference.yml
  name: KeyVaultKeyReference
  fullName: com.microsoft.azure.management.compute.KeyVaultKeyReference
  type: Class
  summary: <p>Describes a reference to Key Vault Key. </p>
  syntax:
    content: public class KeyVaultKeyReference
- uid: com.microsoft.azure.management.compute._disk_encryption_settings
  parent: com.microsoft.azure.management.compute
  href: com.microsoft.azure.management.compute._disk_encryption_settings.yml
  name: DiskEncryptionSettings
  fullName: com.microsoft.azure.management.compute.DiskEncryptionSettings
  type: Class
  summary: <p>Describes a Encryption Settings for a Disk. </p>
  syntax: *o1
