items:
- uid: com.microsoft.azure.management.network._application_gateway_i_p_configuration
  id: _application_gateway_i_p_configuration
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._application_gateway_i_p_configuration_1aa90a89077f995bc085b8101cdb6d0388
  - com.microsoft.azure.management.network._application_gateway_i_p_configuration_1aa6d3fe9477ac05c18167ee73b0c17b98
  - com.microsoft.azure.management.network._application_gateway_i_p_configuration_1a37c75d13e2e7d358a5415e00d35a96c1
  - com.microsoft.azure.management.network._application_gateway_i_p_configuration_1a5bd82be32e5ce387dcb4e607a5175cda
  - com.microsoft.azure.management.network._application_gateway_i_p_configuration_1a7b74f4f63d230d42f895bbca50273421
  - com.microsoft.azure.management.network._application_gateway_i_p_configuration_1af3411baf76ba4ec6e65cef0ce80b7c20
  - com.microsoft.azure.management.network._application_gateway_i_p_configuration_1a20bafe40a1971697ba1c3770ac4d6be4
  - com.microsoft.azure.management.network._application_gateway_i_p_configuration_1a71d9d157d29eb85001c90672f41609aa
  href: com.microsoft.azure.management.network._application_gateway_i_p_configuration.yml
  langs:
  - java
  name: ApplicationGatewayIPConfiguration
  fullName: com.microsoft.azure.management.network.ApplicationGatewayIPConfiguration
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayIPConfiguration.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayIPConfiguration.java
    startLine: 18
  package: com.microsoft.azure.management.network
  summary: <p>IP configuration of application gateway. </p>
  syntax: &o1
    content: public class ApplicationGatewayIPConfiguration extends SubResource
  inheritance:
  - java.lang.Object
  - com.microsoft.azure._sub_resource
  inheritedMembers:
  - com.microsoft.azure._sub_resource_1a92e02020e7fca6a3d2284bc1db599e52
  - com.microsoft.azure._sub_resource_1a522b0146c9247308f3752dd123100d8a
- uid: com.microsoft.azure.management.network._application_gateway_i_p_configuration_1aa90a89077f995bc085b8101cdb6d0388
  id: _application_gateway_i_p_configuration_1aa90a89077f995bc085b8101cdb6d0388
  parent: com.microsoft.azure.management.network._application_gateway_i_p_configuration
  href: com.microsoft.azure.management.network._application_gateway_i_p_configuration.yml
  langs:
  - java
  name: etag()
  fullName: String com.microsoft.azure.management.network.ApplicationGatewayIPConfiguration.etag()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayIPConfiguration.java
    startLine: 109
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the etag value.</p>

    <p></p>
  syntax:
    content: public String etag()
    return:
      type: "26831127"
      description: <p>the etag value </p>
- uid: com.microsoft.azure.management.network._application_gateway_i_p_configuration_1aa6d3fe9477ac05c18167ee73b0c17b98
  id: _application_gateway_i_p_configuration_1aa6d3fe9477ac05c18167ee73b0c17b98
  parent: com.microsoft.azure.management.network._application_gateway_i_p_configuration
  href: com.microsoft.azure.management.network._application_gateway_i_p_configuration.yml
  langs:
  - java
  name: name()
  fullName: String com.microsoft.azure.management.network.ApplicationGatewayIPConfiguration.name()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayIPConfiguration.java
    startLine: 89
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the name value.</p>

    <p></p>
  syntax:
    content: public String name()
    return:
      type: "26831127"
      description: <p>the name value </p>
- uid: com.microsoft.azure.management.network._application_gateway_i_p_configuration_1a37c75d13e2e7d358a5415e00d35a96c1
  id: _application_gateway_i_p_configuration_1a37c75d13e2e7d358a5415e00d35a96c1
  parent: com.microsoft.azure.management.network._application_gateway_i_p_configuration
  href: com.microsoft.azure.management.network._application_gateway_i_p_configuration.yml
  langs:
  - java
  name: provisioningState()
  fullName: String com.microsoft.azure.management.network.ApplicationGatewayIPConfiguration.provisioningState()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayIPConfiguration.java
    startLine: 69
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the provisioningState value.</p>

    <p></p>
  syntax:
    content: public String provisioningState()
    return:
      type: "26831127"
      description: <p>the provisioningState value </p>
- uid: com.microsoft.azure.management.network._application_gateway_i_p_configuration_1a5bd82be32e5ce387dcb4e607a5175cda
  id: _application_gateway_i_p_configuration_1a5bd82be32e5ce387dcb4e607a5175cda
  parent: com.microsoft.azure.management.network._application_gateway_i_p_configuration
  href: com.microsoft.azure.management.network._application_gateway_i_p_configuration.yml
  langs:
  - java
  name: subnet()
  fullName: SubResource com.microsoft.azure.management.network.ApplicationGatewayIPConfiguration.subnet()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayIPConfiguration.java
    startLine: 49
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the subnet value.</p>

    <p></p>
  syntax:
    content: public SubResource subnet()
    return:
      type: com.microsoft.azure._sub_resource
      description: <p>the subnet value </p>
- uid: com.microsoft.azure.management.network._application_gateway_i_p_configuration_1a7b74f4f63d230d42f895bbca50273421
  id: _application_gateway_i_p_configuration_1a7b74f4f63d230d42f895bbca50273421
  parent: com.microsoft.azure.management.network._application_gateway_i_p_configuration
  href: com.microsoft.azure.management.network._application_gateway_i_p_configuration.yml
  langs:
  - java
  name: withEtag(String etag)
  fullName: ApplicationGatewayIPConfiguration com.microsoft.azure.management.network.ApplicationGatewayIPConfiguration.withEtag(String etag)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayIPConfiguration.java
    startLine: 119
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the etag value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewayIPConfiguration withEtag(String etag)
    parameters:
    - id: etag
      type: "26831127"
      description: <p>the etag value to set </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_i_p_configuration
      description: <p>the <xref href="com.microsoft.azure.management.network._application_gateway_i_p_configuration" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network._application_gateway_i_p_configuration_1af3411baf76ba4ec6e65cef0ce80b7c20
  id: _application_gateway_i_p_configuration_1af3411baf76ba4ec6e65cef0ce80b7c20
  parent: com.microsoft.azure.management.network._application_gateway_i_p_configuration
  href: com.microsoft.azure.management.network._application_gateway_i_p_configuration.yml
  langs:
  - java
  name: withName(String name)
  fullName: ApplicationGatewayIPConfiguration com.microsoft.azure.management.network.ApplicationGatewayIPConfiguration.withName(String name)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayIPConfiguration.java
    startLine: 99
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the name value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewayIPConfiguration withName(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>the name value to set </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_i_p_configuration
      description: <p>the <xref href="com.microsoft.azure.management.network._application_gateway_i_p_configuration" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network._application_gateway_i_p_configuration_1a20bafe40a1971697ba1c3770ac4d6be4
  id: _application_gateway_i_p_configuration_1a20bafe40a1971697ba1c3770ac4d6be4
  parent: com.microsoft.azure.management.network._application_gateway_i_p_configuration
  href: com.microsoft.azure.management.network._application_gateway_i_p_configuration.yml
  langs:
  - java
  name: withProvisioningState(String provisioningState)
  fullName: ApplicationGatewayIPConfiguration com.microsoft.azure.management.network.ApplicationGatewayIPConfiguration.withProvisioningState(String provisioningState)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayIPConfiguration.java
    startLine: 79
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the provisioningState value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewayIPConfiguration withProvisioningState(String provisioningState)
    parameters:
    - id: provisioningState
      type: "26831127"
      description: <p>the provisioningState value to set </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_i_p_configuration
      description: <p>the <xref href="com.microsoft.azure.management.network._application_gateway_i_p_configuration" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network._application_gateway_i_p_configuration_1a71d9d157d29eb85001c90672f41609aa
  id: _application_gateway_i_p_configuration_1a71d9d157d29eb85001c90672f41609aa
  parent: com.microsoft.azure.management.network._application_gateway_i_p_configuration
  href: com.microsoft.azure.management.network._application_gateway_i_p_configuration.yml
  langs:
  - java
  name: withSubnet(SubResource subnet)
  fullName: ApplicationGatewayIPConfiguration com.microsoft.azure.management.network.ApplicationGatewayIPConfiguration.withSubnet(SubResource subnet)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayIPConfiguration.java
    startLine: 59
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the subnet value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewayIPConfiguration withSubnet(SubResource subnet)
    parameters:
    - id: subnet
      type: com.microsoft.azure._sub_resource
      description: <p>the subnet value to set </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_i_p_configuration
      description: <p>the <xref href="com.microsoft.azure.management.network._application_gateway_i_p_configuration" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure._sub_resource_1a92e02020e7fca6a3d2284bc1db599e52
  parent: com.microsoft.azure._sub_resource
  href: com.microsoft.azure._sub_resource.yml
  name: id()
  fullName: String com.microsoft.azure.SubResource.id()
  type: Method
  summary: >-
    <p>Get the id value.</p>

    <p></p>
  syntax:
    content: public String id()
    return:
      type: "26831127"
      description: <p>the id value </p>
- uid: com.microsoft.azure._sub_resource_1a522b0146c9247308f3752dd123100d8a
  parent: com.microsoft.azure._sub_resource
  href: com.microsoft.azure._sub_resource.yml
  name: withId(String id)
  fullName: SubResource com.microsoft.azure.SubResource.withId(String id)
  type: Method
  summary: >-
    <p>Set the id value.</p>

    <p></p>
  syntax:
    content: public SubResource withId(String id)
    parameters:
    - id: id
      type: "26831127"
      description: <p>the id value to set </p>
    return:
      type: com.microsoft.azure._sub_resource
      description: <p>the sub resource itself </p>
- uid: com.microsoft.azure._sub_resource
  parent: com.microsoft.azure
  href: com.microsoft.azure._sub_resource.yml
  name: SubResource
  fullName: com.microsoft.azure.SubResource
  type: Class
  summary: <p>The <xref href="com.microsoft.azure._sub_resource" data-throw-if-not-resolved="false"></xref> model. </p>
  syntax:
    content: public class SubResource
- uid: com.microsoft.azure.management.network._application_gateway_i_p_configuration
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_i_p_configuration.yml
  name: ApplicationGatewayIPConfiguration
  fullName: com.microsoft.azure.management.network.ApplicationGatewayIPConfiguration
  type: Class
  summary: <p>IP configuration of application gateway. </p>
  syntax: *o1
