items:
- uid: com.microsoft.azure.batch.protocol.models._application_list_options
  id: _application_list_options
  parent: com.microsoft.azure.batch.protocol.models
  children:
  - com.microsoft.azure.batch.protocol.models._application_list_options_1a07aa3b091198e08d9ad2ab5a210d282f
  - com.microsoft.azure.batch.protocol.models._application_list_options_1aee911a0caba9e5438edb941baee66f2c
  - com.microsoft.azure.batch.protocol.models._application_list_options_1a6d29631afcf6126d7ebe2de16888f227
  - com.microsoft.azure.batch.protocol.models._application_list_options_1a30d46a980879baeab4e96287645e454a
  - com.microsoft.azure.batch.protocol.models._application_list_options_1ab54a3473bb165f3569acab3bff2b1fa3
  - com.microsoft.azure.batch.protocol.models._application_list_options_1a3c87a7548fdf24d1530fa2f932e044f8
  - com.microsoft.azure.batch.protocol.models._application_list_options_1a224b241f16493235567a354869d971ac
  - com.microsoft.azure.batch.protocol.models._application_list_options_1a14f306f87e7002af5a67deda059052ca
  - com.microsoft.azure.batch.protocol.models._application_list_options_1a850e3f003c7979adfd25d4fb33773b27
  - com.microsoft.azure.batch.protocol.models._application_list_options_1aec7fa8ed9e6dc1630fca9586404804c6
  href: com.microsoft.azure.batch.protocol.models._application_list_options.yml
  langs:
  - java
  name: ApplicationListOptions
  fullName: com.microsoft.azure.batch.protocol.models.ApplicationListOptions
  type: Class
  source:
    remote: &o0
      path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationListOptions.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationListOptions.java
    startLine: 17
  package: com.microsoft.azure.batch.protocol.models
  summary: <p>Additional parameters for the Application_List operation. </p>
  syntax: &o1
    content: public class ApplicationListOptions
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.batch.protocol.models._application_list_options_1a07aa3b091198e08d9ad2ab5a210d282f
  id: _application_list_options_1a07aa3b091198e08d9ad2ab5a210d282f
  parent: com.microsoft.azure.batch.protocol.models._application_list_options
  href: com.microsoft.azure.batch.protocol.models._application_list_options.yml
  langs:
  - java
  name: clientRequestId()
  fullName: String com.microsoft.azure.batch.protocol.models.ApplicationListOptions.clientRequestId()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationListOptions.java
    startLine: 98
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the clientRequestId value.</p>

    <p></p>
  syntax:
    content: public String clientRequestId()
    return:
      type: "26831127"
      description: <p>the clientRequestId value </p>
- uid: com.microsoft.azure.batch.protocol.models._application_list_options_1aee911a0caba9e5438edb941baee66f2c
  id: _application_list_options_1aee911a0caba9e5438edb941baee66f2c
  parent: com.microsoft.azure.batch.protocol.models._application_list_options
  href: com.microsoft.azure.batch.protocol.models._application_list_options.yml
  langs:
  - java
  name: maxResults()
  fullName: Integer com.microsoft.azure.batch.protocol.models.ApplicationListOptions.maxResults()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationListOptions.java
    startLine: 58
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the maxResults value.</p>

    <p></p>
  syntax:
    content: public Integer maxResults()
    return:
      type: 08effaa0
      description: <p>the maxResults value </p>
- uid: com.microsoft.azure.batch.protocol.models._application_list_options_1a6d29631afcf6126d7ebe2de16888f227
  id: _application_list_options_1a6d29631afcf6126d7ebe2de16888f227
  parent: com.microsoft.azure.batch.protocol.models._application_list_options
  href: com.microsoft.azure.batch.protocol.models._application_list_options.yml
  langs:
  - java
  name: ocpDate()
  fullName: DateTime com.microsoft.azure.batch.protocol.models.ApplicationListOptions.ocpDate()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationListOptions.java
    startLine: 138
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the ocpDate value.</p>

    <p></p>
  syntax:
    content: public DateTime ocpDate()
    return:
      type: 230df18c
      description: <p>the ocpDate value </p>
- uid: com.microsoft.azure.batch.protocol.models._application_list_options_1a30d46a980879baeab4e96287645e454a
  id: _application_list_options_1a30d46a980879baeab4e96287645e454a
  parent: com.microsoft.azure.batch.protocol.models._application_list_options
  href: com.microsoft.azure.batch.protocol.models._application_list_options.yml
  langs:
  - java
  name: returnClientRequestId()
  fullName: Boolean com.microsoft.azure.batch.protocol.models.ApplicationListOptions.returnClientRequestId()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationListOptions.java
    startLine: 118
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the returnClientRequestId value.</p>

    <p></p>
  syntax:
    content: public Boolean returnClientRequestId()
    return:
      type: 866c2227
      description: <p>the returnClientRequestId value </p>
- uid: com.microsoft.azure.batch.protocol.models._application_list_options_1ab54a3473bb165f3569acab3bff2b1fa3
  id: _application_list_options_1ab54a3473bb165f3569acab3bff2b1fa3
  parent: com.microsoft.azure.batch.protocol.models._application_list_options
  href: com.microsoft.azure.batch.protocol.models._application_list_options.yml
  langs:
  - java
  name: timeout()
  fullName: Integer com.microsoft.azure.batch.protocol.models.ApplicationListOptions.timeout()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationListOptions.java
    startLine: 78
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the timeout value.</p>

    <p></p>
  syntax:
    content: public Integer timeout()
    return:
      type: 08effaa0
      description: <p>the timeout value </p>
- uid: com.microsoft.azure.batch.protocol.models._application_list_options_1a3c87a7548fdf24d1530fa2f932e044f8
  id: _application_list_options_1a3c87a7548fdf24d1530fa2f932e044f8
  parent: com.microsoft.azure.batch.protocol.models._application_list_options
  href: com.microsoft.azure.batch.protocol.models._application_list_options.yml
  langs:
  - java
  name: withClientRequestId(String clientRequestId)
  fullName: ApplicationListOptions com.microsoft.azure.batch.protocol.models.ApplicationListOptions.withClientRequestId(String clientRequestId)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationListOptions.java
    startLine: 108
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the clientRequestId value.</p>

    <p></p>
  syntax:
    content: public ApplicationListOptions withClientRequestId(String clientRequestId)
    parameters:
    - id: clientRequestId
      type: "26831127"
      description: <p>the clientRequestId value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._application_list_options
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._application_list_options" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.batch.protocol.models._application_list_options_1a224b241f16493235567a354869d971ac
  id: _application_list_options_1a224b241f16493235567a354869d971ac
  parent: com.microsoft.azure.batch.protocol.models._application_list_options
  href: com.microsoft.azure.batch.protocol.models._application_list_options.yml
  langs:
  - java
  name: withMaxResults(Integer maxResults)
  fullName: ApplicationListOptions com.microsoft.azure.batch.protocol.models.ApplicationListOptions.withMaxResults(Integer maxResults)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationListOptions.java
    startLine: 68
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the maxResults value.</p>

    <p></p>
  syntax:
    content: public ApplicationListOptions withMaxResults(Integer maxResults)
    parameters:
    - id: maxResults
      type: 08effaa0
      description: <p>the maxResults value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._application_list_options
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._application_list_options" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.batch.protocol.models._application_list_options_1a14f306f87e7002af5a67deda059052ca
  id: _application_list_options_1a14f306f87e7002af5a67deda059052ca
  parent: com.microsoft.azure.batch.protocol.models._application_list_options
  href: com.microsoft.azure.batch.protocol.models._application_list_options.yml
  langs:
  - java
  name: withOcpDate(DateTime ocpDate)
  fullName: ApplicationListOptions com.microsoft.azure.batch.protocol.models.ApplicationListOptions.withOcpDate(DateTime ocpDate)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationListOptions.java
    startLine: 151
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the ocpDate value.</p>

    <p></p>
  syntax:
    content: public ApplicationListOptions withOcpDate(DateTime ocpDate)
    parameters:
    - id: ocpDate
      type: 230df18c
      description: <p>the ocpDate value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._application_list_options
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._application_list_options" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.batch.protocol.models._application_list_options_1a850e3f003c7979adfd25d4fb33773b27
  id: _application_list_options_1a850e3f003c7979adfd25d4fb33773b27
  parent: com.microsoft.azure.batch.protocol.models._application_list_options
  href: com.microsoft.azure.batch.protocol.models._application_list_options.yml
  langs:
  - java
  name: withReturnClientRequestId(Boolean returnClientRequestId)
  fullName: ApplicationListOptions com.microsoft.azure.batch.protocol.models.ApplicationListOptions.withReturnClientRequestId(Boolean returnClientRequestId)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationListOptions.java
    startLine: 128
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the returnClientRequestId value.</p>

    <p></p>
  syntax:
    content: public ApplicationListOptions withReturnClientRequestId(Boolean returnClientRequestId)
    parameters:
    - id: returnClientRequestId
      type: 866c2227
      description: <p>the returnClientRequestId value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._application_list_options
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._application_list_options" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.batch.protocol.models._application_list_options_1aec7fa8ed9e6dc1630fca9586404804c6
  id: _application_list_options_1aec7fa8ed9e6dc1630fca9586404804c6
  parent: com.microsoft.azure.batch.protocol.models._application_list_options
  href: com.microsoft.azure.batch.protocol.models._application_list_options.yml
  langs:
  - java
  name: withTimeout(Integer timeout)
  fullName: ApplicationListOptions com.microsoft.azure.batch.protocol.models.ApplicationListOptions.withTimeout(Integer timeout)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationListOptions.java
    startLine: 88
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the timeout value.</p>

    <p></p>
  syntax:
    content: public ApplicationListOptions withTimeout(Integer timeout)
    parameters:
    - id: timeout
      type: 08effaa0
      description: <p>the timeout value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._application_list_options
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._application_list_options" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: 08effaa0
  spec.java:
  - name: Integer
    fullName: Integer
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 866c2227
  spec.java:
  - name: Boolean
    fullName: Boolean
- uid: 230df18c
  spec.java:
  - name: DateTime
    fullName: DateTime
- uid: com.microsoft.rest._date_time_rfc1123
  parent: com.microsoft.rest
  href: com.microsoft.rest._date_time_rfc1123.yml
  name: DateTimeRfc1123
  fullName: com.microsoft.rest.DateTimeRfc1123
  type: Class
  summary: <p>Simple wrapper over joda.time.DateTime used for specifying RFC1123 format during serialization/deserialization. </p>
  syntax:
    content: public class DateTimeRfc1123
- uid: com.microsoft.azure.batch.protocol.models._application_list_options
  parent: com.microsoft.azure.batch.protocol.models
  href: com.microsoft.azure.batch.protocol.models._application_list_options.yml
  name: ApplicationListOptions
  fullName: com.microsoft.azure.batch.protocol.models.ApplicationListOptions
  type: Class
  summary: <p>Additional parameters for the Application_List operation. </p>
  syntax: *o1
