items:
- uid: com.microsoft.azure.management.network.implementation._application_gateway_i_p_configuration_inner
  id: _application_gateway_i_p_configuration_inner
  parent: com.microsoft.azure.management.network.implementation
  children:
  - com.microsoft.azure.management.network.implementation._application_gateway_i_p_configuration_inner.etag()
  - com.microsoft.azure.management.network.implementation._application_gateway_i_p_configuration_inner.name()
  - com.microsoft.azure.management.network.implementation._application_gateway_i_p_configuration_inner.provisioningState()
  - com.microsoft.azure.management.network.implementation._application_gateway_i_p_configuration_inner.subnet()
  - com.microsoft.azure.management.network.implementation._application_gateway_i_p_configuration_inner.withEtag(String)
  - com.microsoft.azure.management.network.implementation._application_gateway_i_p_configuration_inner.withName(String)
  - com.microsoft.azure.management.network.implementation._application_gateway_i_p_configuration_inner.withProvisioningState(String)
  - com.microsoft.azure.management.network.implementation._application_gateway_i_p_configuration_inner.withSubnet(SubResource)
  href: com.microsoft.azure.management.network.implementation._application_gateway_i_p_configuration_inner.yml
  langs:
  - java
  name: ApplicationGatewayIPConfigurationInner
  fullName: com.microsoft.azure.management.network.implementation.ApplicationGatewayIPConfigurationInner
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayIPConfigurationInner.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayIPConfigurationInner.java
    startLine: 18
  package: com.microsoft.azure.management.network.implementation
  summary: <p>IP configuration of application gateway. </p>
  syntax: &o1
    content: public class ApplicationGatewayIPConfigurationInner extends SubResource
  inheritance:
  - java.lang.Object
  - com.microsoft.azure._sub_resource
  inheritedMembers:
  - com.microsoft.azure._sub_resource.id()
  - com.microsoft.azure._sub_resource.withId(String)
- uid: com.microsoft.azure.management.network.implementation._application_gateway_i_p_configuration_inner.etag()
  id: etag()
  parent: com.microsoft.azure.management.network.implementation._application_gateway_i_p_configuration_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_i_p_configuration_inner.yml
  langs:
  - java
  name: etag()
  fullName: String com.microsoft.azure.management.network.implementation.ApplicationGatewayIPConfigurationInner.etag()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayIPConfigurationInner.java
    startLine: 109
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Get the etag value.</p>

    <p></p>
  syntax:
    content: public String etag()
    return:
      type: "26831127"
      description: <p>the etag value </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_i_p_configuration_inner.name()
  id: name()
  parent: com.microsoft.azure.management.network.implementation._application_gateway_i_p_configuration_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_i_p_configuration_inner.yml
  langs:
  - java
  name: name()
  fullName: String com.microsoft.azure.management.network.implementation.ApplicationGatewayIPConfigurationInner.name()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayIPConfigurationInner.java
    startLine: 89
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Get the name value.</p>

    <p></p>
  syntax:
    content: public String name()
    return:
      type: "26831127"
      description: <p>the name value </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_i_p_configuration_inner.provisioningState()
  id: provisioningState()
  parent: com.microsoft.azure.management.network.implementation._application_gateway_i_p_configuration_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_i_p_configuration_inner.yml
  langs:
  - java
  name: provisioningState()
  fullName: String com.microsoft.azure.management.network.implementation.ApplicationGatewayIPConfigurationInner.provisioningState()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayIPConfigurationInner.java
    startLine: 69
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Get the provisioningState value.</p>

    <p></p>
  syntax:
    content: public String provisioningState()
    return:
      type: "26831127"
      description: <p>the provisioningState value </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_i_p_configuration_inner.subnet()
  id: subnet()
  parent: com.microsoft.azure.management.network.implementation._application_gateway_i_p_configuration_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_i_p_configuration_inner.yml
  langs:
  - java
  name: subnet()
  fullName: SubResource com.microsoft.azure.management.network.implementation.ApplicationGatewayIPConfigurationInner.subnet()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayIPConfigurationInner.java
    startLine: 49
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Get the subnet value.</p>

    <p></p>
  syntax:
    content: public SubResource subnet()
    return:
      type: com.microsoft.azure._sub_resource
      description: <p>the subnet value </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_i_p_configuration_inner.withEtag(String)
  id: withEtag(String)
  parent: com.microsoft.azure.management.network.implementation._application_gateway_i_p_configuration_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_i_p_configuration_inner.yml
  langs:
  - java
  name: withEtag(String etag)
  fullName: ApplicationGatewayIPConfigurationInner com.microsoft.azure.management.network.implementation.ApplicationGatewayIPConfigurationInner.withEtag(String etag)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayIPConfigurationInner.java
    startLine: 119
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Set the etag value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewayIPConfigurationInner withEtag(String etag)
    parameters:
    - id: etag
      type: "26831127"
      description: <p>the etag value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation._application_gateway_i_p_configuration_inner
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation._application_gateway_i_p_configuration_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_i_p_configuration_inner.withName(String)
  id: withName(String)
  parent: com.microsoft.azure.management.network.implementation._application_gateway_i_p_configuration_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_i_p_configuration_inner.yml
  langs:
  - java
  name: withName(String name)
  fullName: ApplicationGatewayIPConfigurationInner com.microsoft.azure.management.network.implementation.ApplicationGatewayIPConfigurationInner.withName(String name)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayIPConfigurationInner.java
    startLine: 99
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Set the name value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewayIPConfigurationInner withName(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>the name value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation._application_gateway_i_p_configuration_inner
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation._application_gateway_i_p_configuration_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_i_p_configuration_inner.withProvisioningState(String)
  id: withProvisioningState(String)
  parent: com.microsoft.azure.management.network.implementation._application_gateway_i_p_configuration_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_i_p_configuration_inner.yml
  langs:
  - java
  name: withProvisioningState(String provisioningState)
  fullName: ApplicationGatewayIPConfigurationInner com.microsoft.azure.management.network.implementation.ApplicationGatewayIPConfigurationInner.withProvisioningState(String provisioningState)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayIPConfigurationInner.java
    startLine: 79
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Set the provisioningState value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewayIPConfigurationInner withProvisioningState(String provisioningState)
    parameters:
    - id: provisioningState
      type: "26831127"
      description: <p>the provisioningState value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation._application_gateway_i_p_configuration_inner
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation._application_gateway_i_p_configuration_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_i_p_configuration_inner.withSubnet(SubResource)
  id: withSubnet(SubResource)
  parent: com.microsoft.azure.management.network.implementation._application_gateway_i_p_configuration_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_i_p_configuration_inner.yml
  langs:
  - java
  name: withSubnet(SubResource subnet)
  fullName: ApplicationGatewayIPConfigurationInner com.microsoft.azure.management.network.implementation.ApplicationGatewayIPConfigurationInner.withSubnet(SubResource subnet)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayIPConfigurationInner.java
    startLine: 59
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Set the subnet value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewayIPConfigurationInner withSubnet(SubResource subnet)
    parameters:
    - id: subnet
      type: com.microsoft.azure._sub_resource
      description: <p>the subnet value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation._application_gateway_i_p_configuration_inner
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation._application_gateway_i_p_configuration_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure._sub_resource.id()
  parent: com.microsoft.azure._sub_resource
  href: com.microsoft.azure._sub_resource.yml
  name: id()
  fullName: String com.microsoft.azure.SubResource.id()
  type: Method
  summary: >-
    <p>Get the id value.</p>

    <p></p>
  syntax:
    content: public String id()
    return:
      type: "26831127"
      description: <p>the id value </p>
- uid: com.microsoft.azure._sub_resource.withId(String)
  parent: com.microsoft.azure._sub_resource
  href: com.microsoft.azure._sub_resource.yml
  name: withId(String id)
  fullName: SubResource com.microsoft.azure.SubResource.withId(String id)
  type: Method
  summary: >-
    <p>Set the id value.</p>

    <p></p>
  syntax:
    content: public SubResource withId(String id)
    parameters:
    - id: id
      type: "26831127"
      description: <p>the id value to set </p>
    return:
      type: com.microsoft.azure._sub_resource
      description: <p>the sub resource itself </p>
- uid: com.microsoft.azure._sub_resource
  parent: com.microsoft.azure
  href: com.microsoft.azure._sub_resource.yml
  name: SubResource
  fullName: com.microsoft.azure.SubResource
  type: Class
  summary: <p>The <xref href="com.microsoft.azure._sub_resource" data-throw-if-not-resolved="false"></xref> model. </p>
  syntax:
    content: public class SubResource
- uid: com.microsoft.azure.management.network.implementation._application_gateway_i_p_configuration_inner
  parent: com.microsoft.azure.management.network.implementation
  href: com.microsoft.azure.management.network.implementation._application_gateway_i_p_configuration_inner.yml
  name: ApplicationGatewayIPConfigurationInner
  fullName: com.microsoft.azure.management.network.implementation.ApplicationGatewayIPConfigurationInner
  type: Class
  summary: <p>IP configuration of application gateway. </p>
  syntax: *o1
