items:
- uid: com.microsoft.azure.management.website._azure_blob_storage_http_logs_config
  id: _azure_blob_storage_http_logs_config
  parent: com.microsoft.azure.management.website
  children:
  - com.microsoft.azure.management.website._azure_blob_storage_http_logs_config_1a5d1e808f713020aef763f4caeffb60ba
  - com.microsoft.azure.management.website._azure_blob_storage_http_logs_config_1a8c5dce0eee963b04dbfeaacf9cc58cd6
  - com.microsoft.azure.management.website._azure_blob_storage_http_logs_config_1a62bab3a73648100a1f1a33b5bc0c1866
  - com.microsoft.azure.management.website._azure_blob_storage_http_logs_config_1a7cc71f2b01ddf644509238049c819731
  - com.microsoft.azure.management.website._azure_blob_storage_http_logs_config_1a4230fae0816cf425e2609e18f3fd009c
  - com.microsoft.azure.management.website._azure_blob_storage_http_logs_config_1a9d6faf21dcfc8ad8cf07b37557128277
  href: com.microsoft.azure.management.website._azure_blob_storage_http_logs_config.yml
  langs:
  - java
  name: AzureBlobStorageHttpLogsConfig
  fullName: com.microsoft.azure.management.website.AzureBlobStorageHttpLogsConfig
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/AzureBlobStorageHttpLogsConfig.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/AzureBlobStorageHttpLogsConfig.java
    startLine: 14
  package: com.microsoft.azure.management.website
  summary: <p>Http logs to azure blob storage configuration. </p>
  syntax: &o1
    content: public class AzureBlobStorageHttpLogsConfig
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.website._azure_blob_storage_http_logs_config_1a5d1e808f713020aef763f4caeffb60ba
  id: _azure_blob_storage_http_logs_config_1a5d1e808f713020aef763f4caeffb60ba
  parent: com.microsoft.azure.management.website._azure_blob_storage_http_logs_config
  href: com.microsoft.azure.management.website._azure_blob_storage_http_logs_config.yml
  langs:
  - java
  name: enabled()
  fullName: Boolean com.microsoft.azure.management.website.AzureBlobStorageHttpLogsConfig.enabled()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/AzureBlobStorageHttpLogsConfig.java
    startLine: 78
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Get the enabled value.</p>

    <p></p>
  syntax:
    content: public Boolean enabled()
    return:
      type: 866c2227
      description: <p>the enabled value </p>
- uid: com.microsoft.azure.management.website._azure_blob_storage_http_logs_config_1a8c5dce0eee963b04dbfeaacf9cc58cd6
  id: _azure_blob_storage_http_logs_config_1a8c5dce0eee963b04dbfeaacf9cc58cd6
  parent: com.microsoft.azure.management.website._azure_blob_storage_http_logs_config
  href: com.microsoft.azure.management.website._azure_blob_storage_http_logs_config.yml
  langs:
  - java
  name: retentionInDays()
  fullName: Integer com.microsoft.azure.management.website.AzureBlobStorageHttpLogsConfig.retentionInDays()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/AzureBlobStorageHttpLogsConfig.java
    startLine: 58
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Get the retentionInDays value.</p>

    <p></p>
  syntax:
    content: public Integer retentionInDays()
    return:
      type: 08effaa0
      description: <p>the retentionInDays value </p>
- uid: com.microsoft.azure.management.website._azure_blob_storage_http_logs_config_1a62bab3a73648100a1f1a33b5bc0c1866
  id: _azure_blob_storage_http_logs_config_1a62bab3a73648100a1f1a33b5bc0c1866
  parent: com.microsoft.azure.management.website._azure_blob_storage_http_logs_config
  href: com.microsoft.azure.management.website._azure_blob_storage_http_logs_config.yml
  langs:
  - java
  name: sasUrl()
  fullName: String com.microsoft.azure.management.website.AzureBlobStorageHttpLogsConfig.sasUrl()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/AzureBlobStorageHttpLogsConfig.java
    startLine: 38
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Get the sasUrl value.</p>

    <p></p>
  syntax:
    content: public String sasUrl()
    return:
      type: "26831127"
      description: <p>the sasUrl value </p>
- uid: com.microsoft.azure.management.website._azure_blob_storage_http_logs_config_1a7cc71f2b01ddf644509238049c819731
  id: _azure_blob_storage_http_logs_config_1a7cc71f2b01ddf644509238049c819731
  parent: com.microsoft.azure.management.website._azure_blob_storage_http_logs_config
  href: com.microsoft.azure.management.website._azure_blob_storage_http_logs_config.yml
  langs:
  - java
  name: withEnabled(Boolean enabled)
  fullName: AzureBlobStorageHttpLogsConfig com.microsoft.azure.management.website.AzureBlobStorageHttpLogsConfig.withEnabled(Boolean enabled)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/AzureBlobStorageHttpLogsConfig.java
    startLine: 88
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Set the enabled value.</p>

    <p></p>
  syntax:
    content: public AzureBlobStorageHttpLogsConfig withEnabled(Boolean enabled)
    parameters:
    - id: enabled
      type: 866c2227
      description: <p>the enabled value to set </p>
    return:
      type: com.microsoft.azure.management.website._azure_blob_storage_http_logs_config
      description: <p>the <xref href="com.microsoft.azure.management.website._azure_blob_storage_http_logs_config" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.website._azure_blob_storage_http_logs_config_1a4230fae0816cf425e2609e18f3fd009c
  id: _azure_blob_storage_http_logs_config_1a4230fae0816cf425e2609e18f3fd009c
  parent: com.microsoft.azure.management.website._azure_blob_storage_http_logs_config
  href: com.microsoft.azure.management.website._azure_blob_storage_http_logs_config.yml
  langs:
  - java
  name: withRetentionInDays(Integer retentionInDays)
  fullName: AzureBlobStorageHttpLogsConfig com.microsoft.azure.management.website.AzureBlobStorageHttpLogsConfig.withRetentionInDays(Integer retentionInDays)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/AzureBlobStorageHttpLogsConfig.java
    startLine: 68
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Set the retentionInDays value.</p>

    <p></p>
  syntax:
    content: public AzureBlobStorageHttpLogsConfig withRetentionInDays(Integer retentionInDays)
    parameters:
    - id: retentionInDays
      type: 08effaa0
      description: <p>the retentionInDays value to set </p>
    return:
      type: com.microsoft.azure.management.website._azure_blob_storage_http_logs_config
      description: <p>the <xref href="com.microsoft.azure.management.website._azure_blob_storage_http_logs_config" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.website._azure_blob_storage_http_logs_config_1a9d6faf21dcfc8ad8cf07b37557128277
  id: _azure_blob_storage_http_logs_config_1a9d6faf21dcfc8ad8cf07b37557128277
  parent: com.microsoft.azure.management.website._azure_blob_storage_http_logs_config
  href: com.microsoft.azure.management.website._azure_blob_storage_http_logs_config.yml
  langs:
  - java
  name: withSasUrl(String sasUrl)
  fullName: AzureBlobStorageHttpLogsConfig com.microsoft.azure.management.website.AzureBlobStorageHttpLogsConfig.withSasUrl(String sasUrl)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/AzureBlobStorageHttpLogsConfig.java
    startLine: 48
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Set the sasUrl value.</p>

    <p></p>
  syntax:
    content: public AzureBlobStorageHttpLogsConfig withSasUrl(String sasUrl)
    parameters:
    - id: sasUrl
      type: "26831127"
      description: <p>the sasUrl value to set </p>
    return:
      type: com.microsoft.azure.management.website._azure_blob_storage_http_logs_config
      description: <p>the <xref href="com.microsoft.azure.management.website._azure_blob_storage_http_logs_config" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 08effaa0
  spec.java:
  - name: Integer
    fullName: Integer
- uid: 866c2227
  spec.java:
  - name: Boolean
    fullName: Boolean
- uid: com.microsoft.azure.management.website._azure_blob_storage_http_logs_config
  parent: com.microsoft.azure.management.website
  href: com.microsoft.azure.management.website._azure_blob_storage_http_logs_config.yml
  name: AzureBlobStorageHttpLogsConfig
  fullName: com.microsoft.azure.management.website.AzureBlobStorageHttpLogsConfig
  type: Class
  summary: <p>Http logs to azure blob storage configuration. </p>
  syntax: *o1
