items:
- uid: com.microsoft.azure.management.network.implementation.api._application_gateway_protocol
  id: _application_gateway_protocol
  parent: com.microsoft.azure.management.network.implementation.api
  children:
  - com.microsoft.azure.management.network.implementation.api._application_gateway_protocol_1a0bbf1eec3b57bad5546e6dc5b7d4cb3d
  - com.microsoft.azure.management.network.implementation.api._application_gateway_protocol_1afa01fc7829a83810b160e112e6877158
  href: com.microsoft.azure.management.network.implementation.api._application_gateway_protocol.yml
  langs:
  - java
  name: ApplicationGatewayProtocol
  fullName: com.microsoft.azure.management.network.implementation.api.ApplicationGatewayProtocol
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/api/ApplicationGatewayProtocol.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/api/ApplicationGatewayProtocol.java
    startLine: 11
  package: com.microsoft.azure.management.network.implementation.api
  summary: <p>Defines values for <xref href="com.microsoft.azure.management.network.implementation.api._application_gateway_protocol" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: &o1
    content: public class ApplicationGatewayProtocol
- uid: com.microsoft.azure.management.network.implementation.api._application_gateway_protocol_1a0bbf1eec3b57bad5546e6dc5b7d4cb3d
  id: _application_gateway_protocol_1a0bbf1eec3b57bad5546e6dc5b7d4cb3d
  parent: com.microsoft.azure.management.network.implementation.api._application_gateway_protocol
  href: com.microsoft.azure.management.network.implementation.api._application_gateway_protocol.yml
  langs:
  - java
  name: HTTP
  fullName: final String com.microsoft.azure.management.network.implementation.api.ApplicationGatewayProtocol.HTTP
  type: Field
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/api/ApplicationGatewayProtocol.java
    startLine: 13
  package: com.microsoft.azure.management.network.implementation.api
  summary: <p>Static value Http for <xref href="com.microsoft.azure.management.network.implementation.api._application_gateway_protocol" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public static final String HTTP= "Http"
    return:
      type: 3d93591e
- uid: com.microsoft.azure.management.network.implementation.api._application_gateway_protocol_1afa01fc7829a83810b160e112e6877158
  id: _application_gateway_protocol_1afa01fc7829a83810b160e112e6877158
  parent: com.microsoft.azure.management.network.implementation.api._application_gateway_protocol
  href: com.microsoft.azure.management.network.implementation.api._application_gateway_protocol.yml
  langs:
  - java
  name: HTTPS
  fullName: final String com.microsoft.azure.management.network.implementation.api.ApplicationGatewayProtocol.HTTPS
  type: Field
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/api/ApplicationGatewayProtocol.java
    startLine: 16
  package: com.microsoft.azure.management.network.implementation.api
  summary: <p>Static value Https for <xref href="com.microsoft.azure.management.network.implementation.api._application_gateway_protocol" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public static final String HTTPS= "Https"
    return:
      type: 3d93591e
references:
- uid: 3d93591e
  spec.java:
  - name: final String
    fullName: final String
- uid: com.microsoft.azure.management.network.implementation.api._application_gateway_protocol
  parent: com.microsoft.azure.management.network.implementation.api
  href: com.microsoft.azure.management.network.implementation.api._application_gateway_protocol.yml
  name: ApplicationGatewayProtocol
  fullName: com.microsoft.azure.management.network.implementation.api.ApplicationGatewayProtocol
  type: Class
  summary: <p>Defines values for <xref href="com.microsoft.azure.management.network.implementation.api._application_gateway_protocol" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: *o1
