items:
- uid: com.microsoft.azure.management.compute._windows_configuration
  id: _windows_configuration
  parent: com.microsoft.azure.management.compute
  children:
  - com.microsoft.azure.management.compute._windows_configuration_1ab1039af81a59eacbb3ac4e9252ab5ee5
  - com.microsoft.azure.management.compute._windows_configuration_1ae41409867e7ae9fa154e4f51b92f37a5
  - com.microsoft.azure.management.compute._windows_configuration_1a64deaadf53ae230ba5b879382cfc865c
  - com.microsoft.azure.management.compute._windows_configuration_1a98412b73b52c1d3fce39f0e6543e4335
  - com.microsoft.azure.management.compute._windows_configuration_1ac456b4d6b752c145b53d0ef367aa19df
  - com.microsoft.azure.management.compute._windows_configuration_1a2ae3ff0e6382d69020419b74cf8724e3
  - com.microsoft.azure.management.compute._windows_configuration_1a23e1afdee0f4c5b37a71e902d8117dfd
  - com.microsoft.azure.management.compute._windows_configuration_1aa5137ea2edaf9f7aaa2b79e086b420cf
  - com.microsoft.azure.management.compute._windows_configuration_1adb80ebc0e149fa078e2b75c06ef6f1ce
  - com.microsoft.azure.management.compute._windows_configuration_1a95683ba9a7fd528b27bece536329dfea
  href: com.microsoft.azure.management.compute._windows_configuration.yml
  langs:
  - java
  name: WindowsConfiguration
  fullName: com.microsoft.azure.management.compute.WindowsConfiguration
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/WindowsConfiguration.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/WindowsConfiguration.java
    startLine: 15
  package: com.microsoft.azure.management.compute
  summary: <p>Describes Windows Configuration of the OS Profile. </p>
  syntax: &o1
    content: public class WindowsConfiguration
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.compute._windows_configuration_1ab1039af81a59eacbb3ac4e9252ab5ee5
  id: _windows_configuration_1ab1039af81a59eacbb3ac4e9252ab5ee5
  parent: com.microsoft.azure.management.compute._windows_configuration
  href: com.microsoft.azure.management.compute._windows_configuration.yml
  langs:
  - java
  name: additionalUnattendContent()
  fullName: List<AdditionalUnattendContent> com.microsoft.azure.management.compute.WindowsConfiguration.additionalUnattendContent()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/WindowsConfiguration.java
    startLine: 107
  package: com.microsoft.azure.management.compute
  summary: >-
    <p>Get the additionalUnattendContent value.</p>

    <p></p>
  syntax:
    content: public List< AdditionalUnattendContent > additionalUnattendContent()
    return:
      type: f6a6204dcom.microsoft.azure.management.compute._additional_unattend_content9ec3e006
      description: <p>the additionalUnattendContent value </p>
- uid: com.microsoft.azure.management.compute._windows_configuration_1ae41409867e7ae9fa154e4f51b92f37a5
  id: _windows_configuration_1ae41409867e7ae9fa154e4f51b92f37a5
  parent: com.microsoft.azure.management.compute._windows_configuration
  href: com.microsoft.azure.management.compute._windows_configuration.yml
  langs:
  - java
  name: enableAutomaticUpdates()
  fullName: Boolean com.microsoft.azure.management.compute.WindowsConfiguration.enableAutomaticUpdates()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/WindowsConfiguration.java
    startLine: 67
  package: com.microsoft.azure.management.compute
  summary: >-
    <p>Get the enableAutomaticUpdates value.</p>

    <p></p>
  syntax:
    content: public Boolean enableAutomaticUpdates()
    return:
      type: 866c2227
      description: <p>the enableAutomaticUpdates value </p>
- uid: com.microsoft.azure.management.compute._windows_configuration_1a64deaadf53ae230ba5b879382cfc865c
  id: _windows_configuration_1a64deaadf53ae230ba5b879382cfc865c
  parent: com.microsoft.azure.management.compute._windows_configuration
  href: com.microsoft.azure.management.compute._windows_configuration.yml
  langs:
  - java
  name: provisionVMAgent()
  fullName: Boolean com.microsoft.azure.management.compute.WindowsConfiguration.provisionVMAgent()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/WindowsConfiguration.java
    startLine: 47
  package: com.microsoft.azure.management.compute
  summary: >-
    <p>Get the provisionVMAgent value.</p>

    <p></p>
  syntax:
    content: public Boolean provisionVMAgent()
    return:
      type: 866c2227
      description: <p>the provisionVMAgent value </p>
- uid: com.microsoft.azure.management.compute._windows_configuration_1a98412b73b52c1d3fce39f0e6543e4335
  id: _windows_configuration_1a98412b73b52c1d3fce39f0e6543e4335
  parent: com.microsoft.azure.management.compute._windows_configuration
  href: com.microsoft.azure.management.compute._windows_configuration.yml
  langs:
  - java
  name: timeZone()
  fullName: String com.microsoft.azure.management.compute.WindowsConfiguration.timeZone()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/WindowsConfiguration.java
    startLine: 87
  package: com.microsoft.azure.management.compute
  summary: >-
    <p>Get the timeZone value.</p>

    <p></p>
  syntax:
    content: public String timeZone()
    return:
      type: "26831127"
      description: <p>the timeZone value </p>
- uid: com.microsoft.azure.management.compute._windows_configuration_1ac456b4d6b752c145b53d0ef367aa19df
  id: _windows_configuration_1ac456b4d6b752c145b53d0ef367aa19df
  parent: com.microsoft.azure.management.compute._windows_configuration
  href: com.microsoft.azure.management.compute._windows_configuration.yml
  langs:
  - java
  name: winRM()
  fullName: WinRMConfiguration com.microsoft.azure.management.compute.WindowsConfiguration.winRM()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/WindowsConfiguration.java
    startLine: 127
  package: com.microsoft.azure.management.compute
  summary: >-
    <p>Get the winRM value.</p>

    <p></p>
  syntax:
    content: public WinRMConfiguration winRM()
    return:
      type: com.microsoft.azure.management.compute._win_r_m_configuration
      description: <p>the winRM value </p>
- uid: com.microsoft.azure.management.compute._windows_configuration_1a2ae3ff0e6382d69020419b74cf8724e3
  id: _windows_configuration_1a2ae3ff0e6382d69020419b74cf8724e3
  parent: com.microsoft.azure.management.compute._windows_configuration
  href: com.microsoft.azure.management.compute._windows_configuration.yml
  langs:
  - java
  name: withAdditionalUnattendContent(List< AdditionalUnattendContent > additionalUnattendContent)
  fullName: WindowsConfiguration com.microsoft.azure.management.compute.WindowsConfiguration.withAdditionalUnattendContent(List< AdditionalUnattendContent > additionalUnattendContent)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/WindowsConfiguration.java
    startLine: 117
  package: com.microsoft.azure.management.compute
  summary: >-
    <p>Set the additionalUnattendContent value.</p>

    <p></p>
  syntax:
    content: public WindowsConfiguration withAdditionalUnattendContent(List< AdditionalUnattendContent > additionalUnattendContent)
    parameters:
    - id: additionalUnattendContent
      type: f6a6204dcom.microsoft.azure.management.compute._additional_unattend_content9ec3e006
      description: <p>the additionalUnattendContent value to set </p>
    return:
      type: com.microsoft.azure.management.compute._windows_configuration
      description: <p>the <xref href="com.microsoft.azure.management.compute._windows_configuration" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.compute._windows_configuration_1a23e1afdee0f4c5b37a71e902d8117dfd
  id: _windows_configuration_1a23e1afdee0f4c5b37a71e902d8117dfd
  parent: com.microsoft.azure.management.compute._windows_configuration
  href: com.microsoft.azure.management.compute._windows_configuration.yml
  langs:
  - java
  name: withEnableAutomaticUpdates(Boolean enableAutomaticUpdates)
  fullName: WindowsConfiguration com.microsoft.azure.management.compute.WindowsConfiguration.withEnableAutomaticUpdates(Boolean enableAutomaticUpdates)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/WindowsConfiguration.java
    startLine: 77
  package: com.microsoft.azure.management.compute
  summary: >-
    <p>Set the enableAutomaticUpdates value.</p>

    <p></p>
  syntax:
    content: public WindowsConfiguration withEnableAutomaticUpdates(Boolean enableAutomaticUpdates)
    parameters:
    - id: enableAutomaticUpdates
      type: 866c2227
      description: <p>the enableAutomaticUpdates value to set </p>
    return:
      type: com.microsoft.azure.management.compute._windows_configuration
      description: <p>the <xref href="com.microsoft.azure.management.compute._windows_configuration" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.compute._windows_configuration_1aa5137ea2edaf9f7aaa2b79e086b420cf
  id: _windows_configuration_1aa5137ea2edaf9f7aaa2b79e086b420cf
  parent: com.microsoft.azure.management.compute._windows_configuration
  href: com.microsoft.azure.management.compute._windows_configuration.yml
  langs:
  - java
  name: withProvisionVMAgent(Boolean provisionVMAgent)
  fullName: WindowsConfiguration com.microsoft.azure.management.compute.WindowsConfiguration.withProvisionVMAgent(Boolean provisionVMAgent)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/WindowsConfiguration.java
    startLine: 57
  package: com.microsoft.azure.management.compute
  summary: >-
    <p>Set the provisionVMAgent value.</p>

    <p></p>
  syntax:
    content: public WindowsConfiguration withProvisionVMAgent(Boolean provisionVMAgent)
    parameters:
    - id: provisionVMAgent
      type: 866c2227
      description: <p>the provisionVMAgent value to set </p>
    return:
      type: com.microsoft.azure.management.compute._windows_configuration
      description: <p>the <xref href="com.microsoft.azure.management.compute._windows_configuration" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.compute._windows_configuration_1adb80ebc0e149fa078e2b75c06ef6f1ce
  id: _windows_configuration_1adb80ebc0e149fa078e2b75c06ef6f1ce
  parent: com.microsoft.azure.management.compute._windows_configuration
  href: com.microsoft.azure.management.compute._windows_configuration.yml
  langs:
  - java
  name: withTimeZone(String timeZone)
  fullName: WindowsConfiguration com.microsoft.azure.management.compute.WindowsConfiguration.withTimeZone(String timeZone)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/WindowsConfiguration.java
    startLine: 97
  package: com.microsoft.azure.management.compute
  summary: >-
    <p>Set the timeZone value.</p>

    <p></p>
  syntax:
    content: public WindowsConfiguration withTimeZone(String timeZone)
    parameters:
    - id: timeZone
      type: "26831127"
      description: <p>the timeZone value to set </p>
    return:
      type: com.microsoft.azure.management.compute._windows_configuration
      description: <p>the <xref href="com.microsoft.azure.management.compute._windows_configuration" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.compute._windows_configuration_1a95683ba9a7fd528b27bece536329dfea
  id: _windows_configuration_1a95683ba9a7fd528b27bece536329dfea
  parent: com.microsoft.azure.management.compute._windows_configuration
  href: com.microsoft.azure.management.compute._windows_configuration.yml
  langs:
  - java
  name: withWinRM(WinRMConfiguration winRM)
  fullName: WindowsConfiguration com.microsoft.azure.management.compute.WindowsConfiguration.withWinRM(WinRMConfiguration winRM)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/WindowsConfiguration.java
    startLine: 137
  package: com.microsoft.azure.management.compute
  summary: >-
    <p>Set the winRM value.</p>

    <p></p>
  syntax:
    content: public WindowsConfiguration withWinRM(WinRMConfiguration winRM)
    parameters:
    - id: winRM
      type: com.microsoft.azure.management.compute._win_r_m_configuration
      description: <p>the winRM value to set </p>
    return:
      type: com.microsoft.azure.management.compute._windows_configuration
      description: <p>the <xref href="com.microsoft.azure.management.compute._windows_configuration" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: 866c2227
  spec.java:
  - name: Boolean
    fullName: Boolean
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: f6a6204dcom.microsoft.azure.management.compute._additional_unattend_content9ec3e006
  spec.java:
  - name: 'List< '
    fullName: 'List< '
  - uid: com.microsoft.azure.management.compute._additional_unattend_content
    name: AdditionalUnattendContent
    fullName: com.microsoft.azure.management.compute.AdditionalUnattendContent
    href: com.microsoft.azure.management.compute._additional_unattend_content.yml
  - name: " >"
    fullName: " >"
- uid: com.microsoft.azure.management.compute._additional_unattend_content
  parent: com.microsoft.azure.management.compute
  href: com.microsoft.azure.management.compute._additional_unattend_content.yml
  name: AdditionalUnattendContent
  fullName: com.microsoft.azure.management.compute.AdditionalUnattendContent
  type: Class
  summary: <p>additional XML formatted information that can be included in the Unattend.xml file, which is used by Windows Setup. Contents are defined by setting name, component name, and the pass in which the content is a applied. </p>
  syntax:
    content: public class AdditionalUnattendContent
- uid: com.microsoft.azure.management.compute._win_r_m_configuration
  parent: com.microsoft.azure.management.compute
  href: com.microsoft.azure.management.compute._win_r_m_configuration.yml
  name: WinRMConfiguration
  fullName: com.microsoft.azure.management.compute.WinRMConfiguration
  type: Class
  summary: <p>Describes Windows Remote Management configuration of the VM. </p>
  syntax:
    content: public class WinRMConfiguration
- uid: com.microsoft.azure.management.compute._windows_configuration
  parent: com.microsoft.azure.management.compute
  href: com.microsoft.azure.management.compute._windows_configuration.yml
  name: WindowsConfiguration
  fullName: com.microsoft.azure.management.compute.WindowsConfiguration
  type: Class
  summary: <p>Describes Windows Configuration of the OS Profile. </p>
  syntax: *o1
