items:
- uid: com.microsoft.azure.management.website.implementation.api._hosting_environment_diagnostics_inner
  id: _hosting_environment_diagnostics_inner
  parent: com.microsoft.azure.management.website.implementation.api
  children:
  - com.microsoft.azure.management.website.implementation.api._hosting_environment_diagnostics_inner_1a19c20629b808df2af7504278efbe6a72
  - com.microsoft.azure.management.website.implementation.api._hosting_environment_diagnostics_inner_1a596593b43a2a893813635a5084b2400f
  - com.microsoft.azure.management.website.implementation.api._hosting_environment_diagnostics_inner_1a310d4cb9905c43a91fd0631c3686591a
  - com.microsoft.azure.management.website.implementation.api._hosting_environment_diagnostics_inner_1afd6625b58cff744c51670c7e0346beaf
  href: com.microsoft.azure.management.website.implementation.api._hosting_environment_diagnostics_inner.yml
  langs:
  - java
  name: HostingEnvironmentDiagnosticsInner
  fullName: com.microsoft.azure.management.website.implementation.api.HostingEnvironmentDiagnosticsInner
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/HostingEnvironmentDiagnosticsInner.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/HostingEnvironmentDiagnosticsInner.java
    startLine: 12
  package: com.microsoft.azure.management.website.implementation.api
  summary: <p>Diagnostics for a hosting environment (App Service Environment). </p>
  syntax: &o1
    content: public class HostingEnvironmentDiagnosticsInner
- uid: com.microsoft.azure.management.website.implementation.api._hosting_environment_diagnostics_inner_1a19c20629b808df2af7504278efbe6a72
  id: _hosting_environment_diagnostics_inner_1a19c20629b808df2af7504278efbe6a72
  parent: com.microsoft.azure.management.website.implementation.api._hosting_environment_diagnostics_inner
  href: com.microsoft.azure.management.website.implementation.api._hosting_environment_diagnostics_inner.yml
  langs:
  - java
  name: diagnosicsOutput()
  fullName: String com.microsoft.azure.management.website.implementation.api.HostingEnvironmentDiagnosticsInner.diagnosicsOutput()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/HostingEnvironmentDiagnosticsInner.java
    startLine: 48
  package: com.microsoft.azure.management.website.implementation.api
  summary: >-
    <p>Get the diagnosicsOutput value.</p>

    <p></p>
  syntax:
    content: public String diagnosicsOutput()
    return:
      type: "26831127"
      description: <p>the diagnosicsOutput value </p>
- uid: com.microsoft.azure.management.website.implementation.api._hosting_environment_diagnostics_inner_1a596593b43a2a893813635a5084b2400f
  id: _hosting_environment_diagnostics_inner_1a596593b43a2a893813635a5084b2400f
  parent: com.microsoft.azure.management.website.implementation.api._hosting_environment_diagnostics_inner
  href: com.microsoft.azure.management.website.implementation.api._hosting_environment_diagnostics_inner.yml
  langs:
  - java
  name: name()
  fullName: String com.microsoft.azure.management.website.implementation.api.HostingEnvironmentDiagnosticsInner.name()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/HostingEnvironmentDiagnosticsInner.java
    startLine: 28
  package: com.microsoft.azure.management.website.implementation.api
  summary: >-
    <p>Get the name value.</p>

    <p></p>
  syntax:
    content: public String name()
    return:
      type: "26831127"
      description: <p>the name value </p>
- uid: com.microsoft.azure.management.website.implementation.api._hosting_environment_diagnostics_inner_1a310d4cb9905c43a91fd0631c3686591a
  id: _hosting_environment_diagnostics_inner_1a310d4cb9905c43a91fd0631c3686591a
  parent: com.microsoft.azure.management.website.implementation.api._hosting_environment_diagnostics_inner
  href: com.microsoft.azure.management.website.implementation.api._hosting_environment_diagnostics_inner.yml
  langs:
  - java
  name: withDiagnosicsOutput(String diagnosicsOutput)
  fullName: HostingEnvironmentDiagnosticsInner com.microsoft.azure.management.website.implementation.api.HostingEnvironmentDiagnosticsInner.withDiagnosicsOutput(String diagnosicsOutput)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/HostingEnvironmentDiagnosticsInner.java
    startLine: 58
  package: com.microsoft.azure.management.website.implementation.api
  summary: >-
    <p>Set the diagnosicsOutput value.</p>

    <p></p>
  syntax:
    content: public HostingEnvironmentDiagnosticsInner withDiagnosicsOutput(String diagnosicsOutput)
    parameters:
    - id: diagnosicsOutput
      type: "26831127"
      description: <p>the diagnosicsOutput value to set </p>
    return:
      type: com.microsoft.azure.management.website.implementation.api._hosting_environment_diagnostics_inner
      description: <p>the <xref href="com.microsoft.azure.management.website.implementation.api._hosting_environment_diagnostics_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.website.implementation.api._hosting_environment_diagnostics_inner_1afd6625b58cff744c51670c7e0346beaf
  id: _hosting_environment_diagnostics_inner_1afd6625b58cff744c51670c7e0346beaf
  parent: com.microsoft.azure.management.website.implementation.api._hosting_environment_diagnostics_inner
  href: com.microsoft.azure.management.website.implementation.api._hosting_environment_diagnostics_inner.yml
  langs:
  - java
  name: withName(String name)
  fullName: HostingEnvironmentDiagnosticsInner com.microsoft.azure.management.website.implementation.api.HostingEnvironmentDiagnosticsInner.withName(String name)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/HostingEnvironmentDiagnosticsInner.java
    startLine: 38
  package: com.microsoft.azure.management.website.implementation.api
  summary: >-
    <p>Set the name value.</p>

    <p></p>
  syntax:
    content: public HostingEnvironmentDiagnosticsInner withName(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>the name value to set </p>
    return:
      type: com.microsoft.azure.management.website.implementation.api._hosting_environment_diagnostics_inner
      description: <p>the <xref href="com.microsoft.azure.management.website.implementation.api._hosting_environment_diagnostics_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.management.website.implementation.api._hosting_environment_diagnostics_inner
  parent: com.microsoft.azure.management.website.implementation.api
  href: com.microsoft.azure.management.website.implementation.api._hosting_environment_diagnostics_inner.yml
  name: HostingEnvironmentDiagnosticsInner
  fullName: com.microsoft.azure.management.website.implementation.api.HostingEnvironmentDiagnosticsInner
  type: Class
  summary: <p>Diagnostics for a hosting environment (App Service Environment). </p>
  syntax: *o1
