items:
- uid: com.microsoft.azure.management.network._nic_ip_configuration._definition_stages
  id: _definition_stages
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._nic_ip_configuration._definition_stages.yml
  langs:
  - java
  name: NicIpConfiguration.DefinitionStages
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.DefinitionStages
  type: Interface
  source:
    remote:
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
    startLine: 86
  package: com.microsoft.azure.management.network
  summary: <p>Grouping of network interface IP configuration definition stages applicable as part of a network interface update. </p>
  syntax:
    content: public interface DefinitionStages
references: []
