items:
- uid: com.microsoft.azure.management.website.implementation.api._cors_settings
  id: _cors_settings
  parent: com.microsoft.azure.management.website.implementation.api
  children:
  - com.microsoft.azure.management.website.implementation.api._cors_settings_1a6fff44919ffc72c27bf0da38322ab543
  - com.microsoft.azure.management.website.implementation.api._cors_settings_1a0a2ec4cbfa11076e757d980a0fa5078d
  href: com.microsoft.azure.management.website.implementation.api._cors_settings.yml
  langs:
  - java
  name: CorsSettings
  fullName: com.microsoft.azure.management.website.implementation.api.CorsSettings
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/CorsSettings.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/CorsSettings.java
    startLine: 13
  assemblies:
  - com.microsoft.azure.management.website.implementation.api
  package: com.microsoft.azure.management.website.implementation.api
  summary: <p>Cross-Origin <xref href="com.microsoft.azure._resource" data-throw-if-not-resolved="false"></xref> Sharing (CORS) settings for the web app. </p>
  syntax: &o1
    content: public class CorsSettings
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.website.implementation.api._cors_settings_1a6fff44919ffc72c27bf0da38322ab543
  id: _cors_settings_1a6fff44919ffc72c27bf0da38322ab543
  parent: com.microsoft.azure.management.website.implementation.api._cors_settings
  href: com.microsoft.azure.management.website.implementation.api._cors_settings.yml
  langs:
  - java
  name: allowedOrigins()
  fullName: List<String> com.microsoft.azure.management.website.implementation.api.CorsSettings.allowedOrigins()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/CorsSettings.java
    startLine: 27
  assemblies:
  - com.microsoft.azure.management.website.implementation.api
  package: com.microsoft.azure.management.website.implementation.api
  summary: >-
    <p>Get the allowedOrigins value.</p>

    <p></p>
  syntax:
    content: public List< String > allowedOrigins()
    return:
      type: f35af49b
      description: <p>the allowedOrigins value </p>
- uid: com.microsoft.azure.management.website.implementation.api._cors_settings_1a0a2ec4cbfa11076e757d980a0fa5078d
  id: _cors_settings_1a0a2ec4cbfa11076e757d980a0fa5078d
  parent: com.microsoft.azure.management.website.implementation.api._cors_settings
  href: com.microsoft.azure.management.website.implementation.api._cors_settings.yml
  langs:
  - java
  name: withAllowedOrigins(List< String > allowedOrigins)
  fullName: CorsSettings com.microsoft.azure.management.website.implementation.api.CorsSettings.withAllowedOrigins(List< String > allowedOrigins)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/CorsSettings.java
    startLine: 37
  assemblies:
  - com.microsoft.azure.management.website.implementation.api
  package: com.microsoft.azure.management.website.implementation.api
  summary: >-
    <p>Set the allowedOrigins value.</p>

    <p></p>
  syntax:
    content: public CorsSettings withAllowedOrigins(List< String > allowedOrigins)
    parameters:
    - id: allowedOrigins
      type: f35af49b
      description: <p>the allowedOrigins value to set </p>
    return:
      type: com.microsoft.azure.management.website.implementation.api._cors_settings
      description: <p>the <xref href="com.microsoft.azure.management.website.implementation.api._cors_settings" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: f35af49b
  spec.java:
  - name: List< String >
    fullName: List< String >
- uid: com.microsoft.azure.management.website.implementation.api._cors_settings
  parent: com.microsoft.azure.management.website.implementation.api
  href: com.microsoft.azure.management.website.implementation.api._cors_settings.yml
  name: CorsSettings
  fullName: com.microsoft.azure.management.website.implementation.api.CorsSettings
  type: Class
  summary: <p>Cross-Origin <xref href="com.microsoft.azure._resource" data-throw-if-not-resolved="false"></xref> Sharing (CORS) settings for the web app. </p>
  syntax: *o1
- uid: com.microsoft.azure._resource
  parent: com.microsoft.azure
  href: com.microsoft.azure._resource.yml
  name: Resource
  fullName: com.microsoft.azure.Resource
  type: Class
  summary: <p>The <xref href="com.microsoft.azure._resource" data-throw-if-not-resolved="false"></xref> model. </p>
  syntax:
    content: public class Resource
