items:
- uid: com.microsoft.azure.management.compute._win_r_m_configuration
  id: _win_r_m_configuration
  parent: com.microsoft.azure.management.compute
  children:
  - com.microsoft.azure.management.compute._win_r_m_configuration.listeners()
  - com.microsoft.azure.management.compute._win_r_m_configuration.withListeners(List< WinRMListener >)
  href: com.microsoft.azure.management.compute._win_r_m_configuration.yml
  langs:
  - java
  name: WinRMConfiguration
  fullName: com.microsoft.azure.management.compute.WinRMConfiguration
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/WinRMConfiguration.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/WinRMConfiguration.java
    startLine: 15
  package: com.microsoft.azure.management.compute
  summary: <p>Describes Windows Remote Management configuration of the VM. </p>
  syntax: &o1
    content: public class WinRMConfiguration
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.compute._win_r_m_configuration.listeners()
  id: listeners()
  parent: com.microsoft.azure.management.compute._win_r_m_configuration
  href: com.microsoft.azure.management.compute._win_r_m_configuration.yml
  langs:
  - java
  name: listeners()
  fullName: List<WinRMListener> com.microsoft.azure.management.compute.WinRMConfiguration.listeners()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/WinRMConfiguration.java
    startLine: 26
  package: com.microsoft.azure.management.compute
  summary: >-
    <p>Get the listeners value.</p>

    <p></p>
  syntax:
    content: public List< WinRMListener > listeners()
    return:
      type: f6a6204dcom.microsoft.azure.management.compute._win_r_m_listener9ec3e006
      description: <p>the listeners value </p>
- uid: com.microsoft.azure.management.compute._win_r_m_configuration.withListeners(List< WinRMListener >)
  id: withListeners(List< WinRMListener >)
  parent: com.microsoft.azure.management.compute._win_r_m_configuration
  href: com.microsoft.azure.management.compute._win_r_m_configuration.yml
  langs:
  - java
  name: withListeners(List< WinRMListener > listeners)
  fullName: WinRMConfiguration com.microsoft.azure.management.compute.WinRMConfiguration.withListeners(List< WinRMListener > listeners)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/WinRMConfiguration.java
    startLine: 36
  package: com.microsoft.azure.management.compute
  summary: >-
    <p>Set the listeners value.</p>

    <p></p>
  syntax:
    content: public WinRMConfiguration withListeners(List< WinRMListener > listeners)
    parameters:
    - id: listeners
      type: f6a6204dcom.microsoft.azure.management.compute._win_r_m_listener9ec3e006
      description: <p>the listeners value to set </p>
    return:
      type: com.microsoft.azure.management.compute._win_r_m_configuration
      description: <p>the <xref href="com.microsoft.azure.management.compute._win_r_m_configuration" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: f6a6204dcom.microsoft.azure.management.compute._win_r_m_listener9ec3e006
  spec.java:
  - name: 'List< '
    fullName: 'List< '
  - uid: com.microsoft.azure.management.compute._win_r_m_listener
    name: WinRMListener
    fullName: com.microsoft.azure.management.compute.WinRMListener
    href: com.microsoft.azure.management.compute._win_r_m_listener.yml
  - name: " >"
    fullName: " >"
- uid: com.microsoft.azure.management.compute._win_r_m_listener
  parent: com.microsoft.azure.management.compute
  href: com.microsoft.azure.management.compute._win_r_m_listener.yml
  name: WinRMListener
  fullName: com.microsoft.azure.management.compute.WinRMListener
  type: Class
  summary: <p>Describes Protocol and thumbprint of Windows Remote Management listener. </p>
  syntax:
    content: public class WinRMListener
- uid: com.microsoft.azure.management.compute._win_r_m_configuration
  parent: com.microsoft.azure.management.compute
  href: com.microsoft.azure.management.compute._win_r_m_configuration.yml
  name: WinRMConfiguration
  fullName: com.microsoft.azure.management.compute.WinRMConfiguration
  type: Class
  summary: <p>Describes Windows Remote Management configuration of the VM. </p>
  syntax: *o1
