items:
- uid: com.microsoft.azure.management.network._application_gateway_backend_address_pool
  id: _application_gateway_backend_address_pool
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._application_gateway_backend_address_pool_1a2ffb0443cc766a47640423735cdd466c
  - com.microsoft.azure.management.network._application_gateway_backend_address_pool_1a79055e8e3c8897bb5a3af3a89915adef
  - com.microsoft.azure.management.network._application_gateway_backend_address_pool_1af0ecd77134f160ca7793f6ff23de19af
  - com.microsoft.azure.management.network._application_gateway_backend_address_pool_1a90fb9add70d51eeaecd4aa5b4984cafd
  - com.microsoft.azure.management.network._application_gateway_backend_address_pool_1a0bfcba8d532da221f36f33c9b5bbee43
  - com.microsoft.azure.management.network._application_gateway_backend_address_pool_1a4f14db3168f68c8181fda5380a2a3766
  - com.microsoft.azure.management.network._application_gateway_backend_address_pool_1a7bd75878c34381e577f6f7eb545496f4
  - com.microsoft.azure.management.network._application_gateway_backend_address_pool_1a0b0bff3843db90e97a7454ce2a27bb80
  - com.microsoft.azure.management.network._application_gateway_backend_address_pool_1a7c9c0c609e22cb7ea598ee0a036c98ba
  - com.microsoft.azure.management.network._application_gateway_backend_address_pool_1a561db893a06fa9464c4b935e336e2e4e
  href: com.microsoft.azure.management.network._application_gateway_backend_address_pool.yml
  langs:
  - java
  name: ApplicationGatewayBackendAddressPool
  fullName: com.microsoft.azure.management.network.ApplicationGatewayBackendAddressPool
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayBackendAddressPool.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayBackendAddressPool.java
    startLine: 19
  package: com.microsoft.azure.management.network
  summary: <p>Backend Address Pool of application gateway. </p>
  syntax: &o1
    content: public class ApplicationGatewayBackendAddressPool extends SubResource
  inheritance:
  - java.lang.Object
  - com.microsoft.azure._sub_resource
  inheritedMembers:
  - com.microsoft.azure._sub_resource_1a92e02020e7fca6a3d2284bc1db599e52
  - com.microsoft.azure._sub_resource_1a522b0146c9247308f3752dd123100d8a
- uid: com.microsoft.azure.management.network._application_gateway_backend_address_pool_1a2ffb0443cc766a47640423735cdd466c
  id: _application_gateway_backend_address_pool_1a2ffb0443cc766a47640423735cdd466c
  parent: com.microsoft.azure.management.network._application_gateway_backend_address_pool
  href: com.microsoft.azure.management.network._application_gateway_backend_address_pool.yml
  langs:
  - java
  name: backendAddresses()
  fullName: List<ApplicationGatewayBackendAddress> com.microsoft.azure.management.network.ApplicationGatewayBackendAddressPool.backendAddresses()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayBackendAddressPool.java
    startLine: 75
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the backendAddresses value.</p>

    <p></p>
  syntax:
    content: public List< ApplicationGatewayBackendAddress > backendAddresses()
    return:
      type: f6a6204dcom.microsoft.azure.management.network._application_gateway_backend_address9ec3e006
      description: <p>the backendAddresses value </p>
- uid: com.microsoft.azure.management.network._application_gateway_backend_address_pool_1a79055e8e3c8897bb5a3af3a89915adef
  id: _application_gateway_backend_address_pool_1a79055e8e3c8897bb5a3af3a89915adef
  parent: com.microsoft.azure.management.network._application_gateway_backend_address_pool
  href: com.microsoft.azure.management.network._application_gateway_backend_address_pool.yml
  langs:
  - java
  name: backendIPConfigurations()
  fullName: List<SubResource> com.microsoft.azure.management.network.ApplicationGatewayBackendAddressPool.backendIPConfigurations()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayBackendAddressPool.java
    startLine: 55
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the backendIPConfigurations value.</p>

    <p></p>
  syntax:
    content: public List< SubResource > backendIPConfigurations()
    return:
      type: f6a6204dcom.microsoft.azure._sub_resource9ec3e006
      description: <p>the backendIPConfigurations value </p>
- uid: com.microsoft.azure.management.network._application_gateway_backend_address_pool_1af0ecd77134f160ca7793f6ff23de19af
  id: _application_gateway_backend_address_pool_1af0ecd77134f160ca7793f6ff23de19af
  parent: com.microsoft.azure.management.network._application_gateway_backend_address_pool
  href: com.microsoft.azure.management.network._application_gateway_backend_address_pool.yml
  langs:
  - java
  name: etag()
  fullName: String com.microsoft.azure.management.network.ApplicationGatewayBackendAddressPool.etag()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayBackendAddressPool.java
    startLine: 135
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the etag value.</p>

    <p></p>
  syntax:
    content: public String etag()
    return:
      type: "26831127"
      description: <p>the etag value </p>
- uid: com.microsoft.azure.management.network._application_gateway_backend_address_pool_1a90fb9add70d51eeaecd4aa5b4984cafd
  id: _application_gateway_backend_address_pool_1a90fb9add70d51eeaecd4aa5b4984cafd
  parent: com.microsoft.azure.management.network._application_gateway_backend_address_pool
  href: com.microsoft.azure.management.network._application_gateway_backend_address_pool.yml
  langs:
  - java
  name: name()
  fullName: String com.microsoft.azure.management.network.ApplicationGatewayBackendAddressPool.name()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayBackendAddressPool.java
    startLine: 115
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the name value.</p>

    <p></p>
  syntax:
    content: public String name()
    return:
      type: "26831127"
      description: <p>the name value </p>
- uid: com.microsoft.azure.management.network._application_gateway_backend_address_pool_1a0bfcba8d532da221f36f33c9b5bbee43
  id: _application_gateway_backend_address_pool_1a0bfcba8d532da221f36f33c9b5bbee43
  parent: com.microsoft.azure.management.network._application_gateway_backend_address_pool
  href: com.microsoft.azure.management.network._application_gateway_backend_address_pool.yml
  langs:
  - java
  name: provisioningState()
  fullName: String com.microsoft.azure.management.network.ApplicationGatewayBackendAddressPool.provisioningState()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayBackendAddressPool.java
    startLine: 95
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the provisioningState value.</p>

    <p></p>
  syntax:
    content: public String provisioningState()
    return:
      type: "26831127"
      description: <p>the provisioningState value </p>
- uid: com.microsoft.azure.management.network._application_gateway_backend_address_pool_1a4f14db3168f68c8181fda5380a2a3766
  id: _application_gateway_backend_address_pool_1a4f14db3168f68c8181fda5380a2a3766
  parent: com.microsoft.azure.management.network._application_gateway_backend_address_pool
  href: com.microsoft.azure.management.network._application_gateway_backend_address_pool.yml
  langs:
  - java
  name: withBackendAddresses(List< ApplicationGatewayBackendAddress > backendAddresses)
  fullName: ApplicationGatewayBackendAddressPool com.microsoft.azure.management.network.ApplicationGatewayBackendAddressPool.withBackendAddresses(List< ApplicationGatewayBackendAddress > backendAddresses)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayBackendAddressPool.java
    startLine: 85
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the backendAddresses value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewayBackendAddressPool withBackendAddresses(List< ApplicationGatewayBackendAddress > backendAddresses)
    parameters:
    - id: backendAddresses
      type: f6a6204dcom.microsoft.azure.management.network._application_gateway_backend_address9ec3e006
      description: <p>the backendAddresses value to set </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_backend_address_pool
      description: <p>the <xref href="com.microsoft.azure.management.network._application_gateway_backend_address_pool" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network._application_gateway_backend_address_pool_1a7bd75878c34381e577f6f7eb545496f4
  id: _application_gateway_backend_address_pool_1a7bd75878c34381e577f6f7eb545496f4
  parent: com.microsoft.azure.management.network._application_gateway_backend_address_pool
  href: com.microsoft.azure.management.network._application_gateway_backend_address_pool.yml
  langs:
  - java
  name: withBackendIPConfigurations(List< SubResource > backendIPConfigurations)
  fullName: ApplicationGatewayBackendAddressPool com.microsoft.azure.management.network.ApplicationGatewayBackendAddressPool.withBackendIPConfigurations(List< SubResource > backendIPConfigurations)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayBackendAddressPool.java
    startLine: 65
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the backendIPConfigurations value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewayBackendAddressPool withBackendIPConfigurations(List< SubResource > backendIPConfigurations)
    parameters:
    - id: backendIPConfigurations
      type: f6a6204dcom.microsoft.azure._sub_resource9ec3e006
      description: <p>the backendIPConfigurations value to set </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_backend_address_pool
      description: <p>the <xref href="com.microsoft.azure.management.network._application_gateway_backend_address_pool" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network._application_gateway_backend_address_pool_1a0b0bff3843db90e97a7454ce2a27bb80
  id: _application_gateway_backend_address_pool_1a0b0bff3843db90e97a7454ce2a27bb80
  parent: com.microsoft.azure.management.network._application_gateway_backend_address_pool
  href: com.microsoft.azure.management.network._application_gateway_backend_address_pool.yml
  langs:
  - java
  name: withEtag(String etag)
  fullName: ApplicationGatewayBackendAddressPool com.microsoft.azure.management.network.ApplicationGatewayBackendAddressPool.withEtag(String etag)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayBackendAddressPool.java
    startLine: 145
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the etag value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewayBackendAddressPool withEtag(String etag)
    parameters:
    - id: etag
      type: "26831127"
      description: <p>the etag value to set </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_backend_address_pool
      description: <p>the <xref href="com.microsoft.azure.management.network._application_gateway_backend_address_pool" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network._application_gateway_backend_address_pool_1a7c9c0c609e22cb7ea598ee0a036c98ba
  id: _application_gateway_backend_address_pool_1a7c9c0c609e22cb7ea598ee0a036c98ba
  parent: com.microsoft.azure.management.network._application_gateway_backend_address_pool
  href: com.microsoft.azure.management.network._application_gateway_backend_address_pool.yml
  langs:
  - java
  name: withName(String name)
  fullName: ApplicationGatewayBackendAddressPool com.microsoft.azure.management.network.ApplicationGatewayBackendAddressPool.withName(String name)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayBackendAddressPool.java
    startLine: 125
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the name value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewayBackendAddressPool withName(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>the name value to set </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_backend_address_pool
      description: <p>the <xref href="com.microsoft.azure.management.network._application_gateway_backend_address_pool" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network._application_gateway_backend_address_pool_1a561db893a06fa9464c4b935e336e2e4e
  id: _application_gateway_backend_address_pool_1a561db893a06fa9464c4b935e336e2e4e
  parent: com.microsoft.azure.management.network._application_gateway_backend_address_pool
  href: com.microsoft.azure.management.network._application_gateway_backend_address_pool.yml
  langs:
  - java
  name: withProvisioningState(String provisioningState)
  fullName: ApplicationGatewayBackendAddressPool com.microsoft.azure.management.network.ApplicationGatewayBackendAddressPool.withProvisioningState(String provisioningState)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayBackendAddressPool.java
    startLine: 105
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the provisioningState value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewayBackendAddressPool withProvisioningState(String provisioningState)
    parameters:
    - id: provisioningState
      type: "26831127"
      description: <p>the provisioningState value to set </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_backend_address_pool
      description: <p>the <xref href="com.microsoft.azure.management.network._application_gateway_backend_address_pool" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: f6a6204dcom.microsoft.azure._sub_resource9ec3e006
  spec.java:
  - name: 'List< '
    fullName: 'List< '
  - uid: com.microsoft.azure._sub_resource
    name: SubResource
    fullName: com.microsoft.azure.SubResource
    href: com.microsoft.azure._sub_resource.yml
  - name: ' >'
    fullName: ' >'
- uid: f6a6204dcom.microsoft.azure.management.network._application_gateway_backend_address9ec3e006
  spec.java:
  - name: 'List< '
    fullName: 'List< '
  - uid: com.microsoft.azure.management.network._application_gateway_backend_address
    name: ApplicationGatewayBackendAddress
    fullName: com.microsoft.azure.management.network.ApplicationGatewayBackendAddress
    href: com.microsoft.azure.management.network._application_gateway_backend_address.yml
  - name: ' >'
    fullName: ' >'
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure._sub_resource_1a92e02020e7fca6a3d2284bc1db599e52
  parent: com.microsoft.azure._sub_resource
  href: com.microsoft.azure._sub_resource.yml
  name: id()
  fullName: String com.microsoft.azure.SubResource.id()
  type: Method
  summary: >-
    <p>Get the id value.</p>

    <p></p>
  syntax:
    content: public String id()
    return:
      type: "26831127"
      description: <p>the id value </p>
- uid: com.microsoft.azure._sub_resource_1a522b0146c9247308f3752dd123100d8a
  parent: com.microsoft.azure._sub_resource
  href: com.microsoft.azure._sub_resource.yml
  name: withId(String id)
  fullName: SubResource com.microsoft.azure.SubResource.withId(String id)
  type: Method
  summary: >-
    <p>Set the id value.</p>

    <p></p>
  syntax:
    content: public SubResource withId(String id)
    parameters:
    - id: id
      type: "26831127"
      description: <p>the id value to set </p>
    return:
      type: com.microsoft.azure._sub_resource
      description: <p>the sub resource itself </p>
- uid: com.microsoft.azure._sub_resource
  parent: com.microsoft.azure
  href: com.microsoft.azure._sub_resource.yml
  name: SubResource
  fullName: com.microsoft.azure.SubResource
  type: Class
  summary: <p>The <xref href="com.microsoft.azure._sub_resource" data-throw-if-not-resolved="false"></xref> model. </p>
  syntax:
    content: public class SubResource
- uid: com.microsoft.azure.management.network._application_gateway_backend_address
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_backend_address.yml
  name: ApplicationGatewayBackendAddress
  fullName: com.microsoft.azure.management.network.ApplicationGatewayBackendAddress
  type: Class
  summary: <p>Backend Address of application gateway. </p>
  syntax:
    content: public class ApplicationGatewayBackendAddress
- uid: com.microsoft.azure.management.network._application_gateway_backend_address_pool
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_backend_address_pool.yml
  name: ApplicationGatewayBackendAddressPool
  fullName: com.microsoft.azure.management.network.ApplicationGatewayBackendAddressPool
  type: Class
  summary: <p>Backend Address Pool of application gateway. </p>
  syntax: *o1
