items:
- uid: com.microsoft.azure.management.network._application_gateway_backend_address
  id: _application_gateway_backend_address
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._application_gateway_backend_address_1ab86bdf41b8606f9af092c513d3d2d5c4
  - com.microsoft.azure.management.network._application_gateway_backend_address_1a5ec25043ce8cc212f1c8972977b3285a
  - com.microsoft.azure.management.network._application_gateway_backend_address_1acd1368ab723384449d1f5c6b4945b290
  - com.microsoft.azure.management.network._application_gateway_backend_address_1afc1c91a34e62b2308cc3267b892630c4
  href: com.microsoft.azure.management.network._application_gateway_backend_address.yml
  langs:
  - java
  name: ApplicationGatewayBackendAddress
  fullName: com.microsoft.azure.management.network.ApplicationGatewayBackendAddress
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayBackendAddress.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayBackendAddress.java
    startLine: 14
  package: com.microsoft.azure.management.network
  summary: <p>Backend Address of application gateway. </p>
  syntax: &o1
    content: public class ApplicationGatewayBackendAddress
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.network._application_gateway_backend_address_1ab86bdf41b8606f9af092c513d3d2d5c4
  id: _application_gateway_backend_address_1ab86bdf41b8606f9af092c513d3d2d5c4
  parent: com.microsoft.azure.management.network._application_gateway_backend_address
  href: com.microsoft.azure.management.network._application_gateway_backend_address.yml
  langs:
  - java
  name: fqdn()
  fullName: String com.microsoft.azure.management.network.ApplicationGatewayBackendAddress.fqdn()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayBackendAddress.java
    startLine: 30
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the fqdn value.</p>

    <p></p>
  syntax:
    content: public String fqdn()
    return:
      type: "26831127"
      description: <p>the fqdn value </p>
- uid: com.microsoft.azure.management.network._application_gateway_backend_address_1a5ec25043ce8cc212f1c8972977b3285a
  id: _application_gateway_backend_address_1a5ec25043ce8cc212f1c8972977b3285a
  parent: com.microsoft.azure.management.network._application_gateway_backend_address
  href: com.microsoft.azure.management.network._application_gateway_backend_address.yml
  langs:
  - java
  name: ipAddress()
  fullName: String com.microsoft.azure.management.network.ApplicationGatewayBackendAddress.ipAddress()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayBackendAddress.java
    startLine: 50
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the ipAddress value.</p>

    <p></p>
  syntax:
    content: public String ipAddress()
    return:
      type: "26831127"
      description: <p>the ipAddress value </p>
- uid: com.microsoft.azure.management.network._application_gateway_backend_address_1acd1368ab723384449d1f5c6b4945b290
  id: _application_gateway_backend_address_1acd1368ab723384449d1f5c6b4945b290
  parent: com.microsoft.azure.management.network._application_gateway_backend_address
  href: com.microsoft.azure.management.network._application_gateway_backend_address.yml
  langs:
  - java
  name: withFqdn(String fqdn)
  fullName: ApplicationGatewayBackendAddress com.microsoft.azure.management.network.ApplicationGatewayBackendAddress.withFqdn(String fqdn)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayBackendAddress.java
    startLine: 40
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the fqdn value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewayBackendAddress withFqdn(String fqdn)
    parameters:
    - id: fqdn
      type: "26831127"
      description: <p>the fqdn value to set </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_backend_address
      description: <p>the <xref href="com.microsoft.azure.management.network._application_gateway_backend_address" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network._application_gateway_backend_address_1afc1c91a34e62b2308cc3267b892630c4
  id: _application_gateway_backend_address_1afc1c91a34e62b2308cc3267b892630c4
  parent: com.microsoft.azure.management.network._application_gateway_backend_address
  href: com.microsoft.azure.management.network._application_gateway_backend_address.yml
  langs:
  - java
  name: withIpAddress(String ipAddress)
  fullName: ApplicationGatewayBackendAddress com.microsoft.azure.management.network.ApplicationGatewayBackendAddress.withIpAddress(String ipAddress)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayBackendAddress.java
    startLine: 60
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the ipAddress value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewayBackendAddress withIpAddress(String ipAddress)
    parameters:
    - id: ipAddress
      type: "26831127"
      description: <p>the ipAddress value to set </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_backend_address
      description: <p>the <xref href="com.microsoft.azure.management.network._application_gateway_backend_address" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.management.network._application_gateway_backend_address
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_backend_address.yml
  name: ApplicationGatewayBackendAddress
  fullName: com.microsoft.azure.management.network.ApplicationGatewayBackendAddress
  type: Class
  summary: <p>Backend Address of application gateway. </p>
  syntax: *o1
