items:
- uid: com.microsoft.azure.credentials._application_token_credentials._credential_settings
  id: _credential_settings
  parent: com.microsoft.azure.credentials
  children:
  - com.microsoft.azure.credentials._application_token_credentials._credential_settings_1a40d279f6e16d19aa6d68411bcc249ec9
  - com.microsoft.azure.credentials._application_token_credentials._credential_settings_1a81e88e153b01af8f91061bb987bdd5ae
  - com.microsoft.azure.credentials._application_token_credentials._credential_settings_1a56270368d0cf594530b49e1fd679a10a
  - com.microsoft.azure.credentials._application_token_credentials._credential_settings_1a0b1f815a223e85792dffa172b19167cd
  - com.microsoft.azure.credentials._application_token_credentials._credential_settings_1a15205465a2950ee94adcf97fd4a221b1
  - com.microsoft.azure.credentials._application_token_credentials._credential_settings_1ae6967f60c0aa238d3c0a0f6e0b0d16e5
  - com.microsoft.azure.credentials._application_token_credentials._credential_settings_1a82944ca0d062d362e377ac94f9627eba
  - com.microsoft.azure.credentials._application_token_credentials._credential_settings_1a5032c259533bb859d9892d8b4ee05b55
  - com.microsoft.azure.credentials._application_token_credentials._credential_settings_1a67149432cdfc4241214130fb2d879c0f
  href: com.microsoft.azure.credentials._application_token_credentials._credential_settings.yml
  langs:
  - java
  name: ApplicationTokenCredentials.CredentialSettings
  fullName: com.microsoft.azure.credentials.ApplicationTokenCredentials.CredentialSettings
  type: Enum
  source:
    remote: &o0
      path: runtimes/azure-client-authentication/src/main/java/com/microsoft/azure/credentials/ApplicationTokenCredentials.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: runtimes/azure-client-authentication/src/main/java/com/microsoft/azure/credentials/ApplicationTokenCredentials.java
    startLine: 63
  package: com.microsoft.azure.credentials
  summary: <p>Contains the keys of the settings in a Properties file to read credentials from. </p>
  syntax:
    content: private enum CredentialSettings
- uid: com.microsoft.azure.credentials._application_token_credentials._credential_settings_1a40d279f6e16d19aa6d68411bcc249ec9
  id: _credential_settings_1a40d279f6e16d19aa6d68411bcc249ec9
  parent: com.microsoft.azure.credentials._application_token_credentials._credential_settings
  href: com.microsoft.azure.credentials._application_token_credentials._credential_settings.yml
  langs:
  - java
  name: AUTH_URL
  fullName: com.microsoft.azure.credentials.ApplicationTokenCredentials.CredentialSettings.AUTH_URL
  type: Field
  source:
    remote: *o0
    path: runtimes/azure-client-authentication/src/main/java/com/microsoft/azure/credentials/ApplicationTokenCredentials.java
    startLine: 77
  package: com.microsoft.azure.credentials
  summary: <p>The URL to Active Directory authentication. </p>
  syntax:
    content: public AUTH_URL=("authURL")
- uid: com.microsoft.azure.credentials._application_token_credentials._credential_settings_1a81e88e153b01af8f91061bb987bdd5ae
  id: _credential_settings_1a81e88e153b01af8f91061bb987bdd5ae
  parent: com.microsoft.azure.credentials._application_token_credentials._credential_settings
  href: com.microsoft.azure.credentials._application_token_credentials._credential_settings.yml
  langs:
  - java
  name: BASE_URL
  fullName: com.microsoft.azure.credentials.ApplicationTokenCredentials.CredentialSettings.BASE_URL
  type: Field
  source:
    remote: *o0
    path: runtimes/azure-client-authentication/src/main/java/com/microsoft/azure/credentials/ApplicationTokenCredentials.java
    startLine: 75
  package: com.microsoft.azure.credentials
  summary: <p>The base URL to the current <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> environment. </p>
  syntax:
    content: public BASE_URL=("baseURL")
- uid: com.microsoft.azure.credentials._application_token_credentials._credential_settings_1a56270368d0cf594530b49e1fd679a10a
  id: _credential_settings_1a56270368d0cf594530b49e1fd679a10a
  parent: com.microsoft.azure.credentials._application_token_credentials._credential_settings
  href: com.microsoft.azure.credentials._application_token_credentials._credential_settings.yml
  langs:
  - java
  name: CLIENT_ID
  fullName: com.microsoft.azure.credentials.ApplicationTokenCredentials.CredentialSettings.CLIENT_ID
  type: Field
  source:
    remote: *o0
    path: runtimes/azure-client-authentication/src/main/java/com/microsoft/azure/credentials/ApplicationTokenCredentials.java
    startLine: 69
  package: com.microsoft.azure.credentials
  summary: <p>The client id for the client application. </p>
  syntax:
    content: public CLIENT_ID=("client")
- uid: com.microsoft.azure.credentials._application_token_credentials._credential_settings_1a0b1f815a223e85792dffa172b19167cd
  id: _credential_settings_1a0b1f815a223e85792dffa172b19167cd
  parent: com.microsoft.azure.credentials._application_token_credentials._credential_settings
  href: com.microsoft.azure.credentials._application_token_credentials._credential_settings.yml
  langs:
  - java
  name: CLIENT_KEY
  fullName: com.microsoft.azure.credentials.ApplicationTokenCredentials.CredentialSettings.CLIENT_KEY
  type: Field
  source:
    remote: *o0
    path: runtimes/azure-client-authentication/src/main/java/com/microsoft/azure/credentials/ApplicationTokenCredentials.java
    startLine: 71
  package: com.microsoft.azure.credentials
  summary: <p>The client secret for the service principal. </p>
  syntax:
    content: public CLIENT_KEY=("key")
- uid: com.microsoft.azure.credentials._application_token_credentials._credential_settings_1a15205465a2950ee94adcf97fd4a221b1
  id: _credential_settings_1a15205465a2950ee94adcf97fd4a221b1
  parent: com.microsoft.azure.credentials._application_token_credentials._credential_settings
  href: com.microsoft.azure.credentials._application_token_credentials._credential_settings.yml
  langs:
  - java
  name: CredentialSettings(String name)
  fullName: com.microsoft.azure.credentials.ApplicationTokenCredentials.CredentialSettings.CredentialSettings(String name)
  type: Method
  source:
    remote: *o0
    path: runtimes/azure-client-authentication/src/main/java/com/microsoft/azure/credentials/ApplicationTokenCredentials.java
    startLine: 82
  package: com.microsoft.azure.credentials
  syntax:
    content: public CredentialSettings(String name)
    parameters:
    - id: name
      type: "26831127"
- uid: com.microsoft.azure.credentials._application_token_credentials._credential_settings_1ae6967f60c0aa238d3c0a0f6e0b0d16e5
  id: _credential_settings_1ae6967f60c0aa238d3c0a0f6e0b0d16e5
  parent: com.microsoft.azure.credentials._application_token_credentials._credential_settings
  href: com.microsoft.azure.credentials._application_token_credentials._credential_settings.yml
  langs:
  - java
  name: MANAGEMENT_URI
  fullName: com.microsoft.azure.credentials.ApplicationTokenCredentials.CredentialSettings.MANAGEMENT_URI
  type: Field
  source:
    remote: *o0
    path: runtimes/azure-client-authentication/src/main/java/com/microsoft/azure/credentials/ApplicationTokenCredentials.java
    startLine: 73
  package: com.microsoft.azure.credentials
  summary: <p>The management endpoint. </p>
  syntax:
    content: public MANAGEMENT_URI=("managementURI")
- uid: com.microsoft.azure.credentials._application_token_credentials._credential_settings_1a82944ca0d062d362e377ac94f9627eba
  id: _credential_settings_1a82944ca0d062d362e377ac94f9627eba
  parent: com.microsoft.azure.credentials._application_token_credentials._credential_settings
  href: com.microsoft.azure.credentials._application_token_credentials._credential_settings.yml
  langs:
  - java
  name: SUBSCRIPTION_ID
  fullName: com.microsoft.azure.credentials.ApplicationTokenCredentials.CredentialSettings.SUBSCRIPTION_ID
  type: Field
  source:
    remote: *o0
    path: runtimes/azure-client-authentication/src/main/java/com/microsoft/azure/credentials/ApplicationTokenCredentials.java
    startLine: 65
  package: com.microsoft.azure.credentials
  summary: <p>The subscription GUID. </p>
  syntax:
    content: public SUBSCRIPTION_ID=("subscription")
- uid: com.microsoft.azure.credentials._application_token_credentials._credential_settings_1a5032c259533bb859d9892d8b4ee05b55
  id: _credential_settings_1a5032c259533bb859d9892d8b4ee05b55
  parent: com.microsoft.azure.credentials._application_token_credentials._credential_settings
  href: com.microsoft.azure.credentials._application_token_credentials._credential_settings.yml
  langs:
  - java
  name: TENANT_ID
  fullName: com.microsoft.azure.credentials.ApplicationTokenCredentials.CredentialSettings.TENANT_ID
  type: Field
  source:
    remote: *o0
    path: runtimes/azure-client-authentication/src/main/java/com/microsoft/azure/credentials/ApplicationTokenCredentials.java
    startLine: 67
  package: com.microsoft.azure.credentials
  summary: <p>The tenant GUID or domain. </p>
  syntax:
    content: public TENANT_ID=("tenant")
- uid: com.microsoft.azure.credentials._application_token_credentials._credential_settings_1a67149432cdfc4241214130fb2d879c0f
  id: _credential_settings_1a67149432cdfc4241214130fb2d879c0f
  parent: com.microsoft.azure.credentials._application_token_credentials._credential_settings
  href: com.microsoft.azure.credentials._application_token_credentials._credential_settings.yml
  langs:
  - java
  name: toString()
  fullName: String com.microsoft.azure.credentials.ApplicationTokenCredentials.CredentialSettings.toString()
  type: Method
  source:
    remote: *o0
    path: runtimes/azure-client-authentication/src/main/java/com/microsoft/azure/credentials/ApplicationTokenCredentials.java
    startLine: 87
  package: com.microsoft.azure.credentials
  syntax:
    content: public String toString()
    return:
      type: "26831127"
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure._azure
  parent: com.microsoft.azure
  href: com.microsoft.azure._azure.yml
  name: Azure
  fullName: com.microsoft.azure.Azure
  type: Class
  summary: <p>The entry point for accessing resource management APIs in <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class Azure
