items:
- uid: com.microsoft.azure.management.website._azure_blob_storage_application_logs_config
  id: _azure_blob_storage_application_logs_config
  parent: com.microsoft.azure.management.website
  children:
  - com.microsoft.azure.management.website._azure_blob_storage_application_logs_config.level()
  - com.microsoft.azure.management.website._azure_blob_storage_application_logs_config.retentionInDays()
  - com.microsoft.azure.management.website._azure_blob_storage_application_logs_config.sasUrl()
  - com.microsoft.azure.management.website._azure_blob_storage_application_logs_config.withLevel(LogLevel)
  - com.microsoft.azure.management.website._azure_blob_storage_application_logs_config.withRetentionInDays(Integer)
  - com.microsoft.azure.management.website._azure_blob_storage_application_logs_config.withSasUrl(String)
  href: com.microsoft.azure.management.website._azure_blob_storage_application_logs_config.yml
  langs:
  - java
  name: AzureBlobStorageApplicationLogsConfig
  fullName: com.microsoft.azure.management.website.AzureBlobStorageApplicationLogsConfig
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/AzureBlobStorageApplicationLogsConfig.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/AzureBlobStorageApplicationLogsConfig.java
    startLine: 14
  package: com.microsoft.azure.management.website
  summary: <p>Application logs azure blob storage configuration. </p>
  syntax: &o1
    content: public class AzureBlobStorageApplicationLogsConfig
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.website._azure_blob_storage_application_logs_config.level()
  id: level()
  parent: com.microsoft.azure.management.website._azure_blob_storage_application_logs_config
  href: com.microsoft.azure.management.website._azure_blob_storage_application_logs_config.yml
  langs:
  - java
  name: level()
  fullName: LogLevel com.microsoft.azure.management.website.AzureBlobStorageApplicationLogsConfig.level()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/AzureBlobStorageApplicationLogsConfig.java
    startLine: 39
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Get the level value.</p>

    <p></p>
  syntax:
    content: public LogLevel level()
    return:
      type: com.microsoft.azure.management.website._log_level
      description: <p>the level value </p>
- uid: com.microsoft.azure.management.website._azure_blob_storage_application_logs_config.retentionInDays()
  id: retentionInDays()
  parent: com.microsoft.azure.management.website._azure_blob_storage_application_logs_config
  href: com.microsoft.azure.management.website._azure_blob_storage_application_logs_config.yml
  langs:
  - java
  name: retentionInDays()
  fullName: Integer com.microsoft.azure.management.website.AzureBlobStorageApplicationLogsConfig.retentionInDays()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/AzureBlobStorageApplicationLogsConfig.java
    startLine: 79
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Get the retentionInDays value.</p>

    <p></p>
  syntax:
    content: public Integer retentionInDays()
    return:
      type: 08effaa0
      description: <p>the retentionInDays value </p>
- uid: com.microsoft.azure.management.website._azure_blob_storage_application_logs_config.sasUrl()
  id: sasUrl()
  parent: com.microsoft.azure.management.website._azure_blob_storage_application_logs_config
  href: com.microsoft.azure.management.website._azure_blob_storage_application_logs_config.yml
  langs:
  - java
  name: sasUrl()
  fullName: String com.microsoft.azure.management.website.AzureBlobStorageApplicationLogsConfig.sasUrl()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/AzureBlobStorageApplicationLogsConfig.java
    startLine: 59
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Get the sasUrl value.</p>

    <p></p>
  syntax:
    content: public String sasUrl()
    return:
      type: "26831127"
      description: <p>the sasUrl value </p>
- uid: com.microsoft.azure.management.website._azure_blob_storage_application_logs_config.withLevel(LogLevel)
  id: withLevel(LogLevel)
  parent: com.microsoft.azure.management.website._azure_blob_storage_application_logs_config
  href: com.microsoft.azure.management.website._azure_blob_storage_application_logs_config.yml
  langs:
  - java
  name: withLevel(LogLevel level)
  fullName: AzureBlobStorageApplicationLogsConfig com.microsoft.azure.management.website.AzureBlobStorageApplicationLogsConfig.withLevel(LogLevel level)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/AzureBlobStorageApplicationLogsConfig.java
    startLine: 49
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Set the level value.</p>

    <p></p>
  syntax:
    content: public AzureBlobStorageApplicationLogsConfig withLevel(LogLevel level)
    parameters:
    - id: level
      type: com.microsoft.azure.management.website._log_level
      description: <p>the level value to set </p>
    return:
      type: com.microsoft.azure.management.website._azure_blob_storage_application_logs_config
      description: <p>the <xref href="com.microsoft.azure.management.website._azure_blob_storage_application_logs_config" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.website._azure_blob_storage_application_logs_config.withRetentionInDays(Integer)
  id: withRetentionInDays(Integer)
  parent: com.microsoft.azure.management.website._azure_blob_storage_application_logs_config
  href: com.microsoft.azure.management.website._azure_blob_storage_application_logs_config.yml
  langs:
  - java
  name: withRetentionInDays(Integer retentionInDays)
  fullName: AzureBlobStorageApplicationLogsConfig com.microsoft.azure.management.website.AzureBlobStorageApplicationLogsConfig.withRetentionInDays(Integer retentionInDays)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/AzureBlobStorageApplicationLogsConfig.java
    startLine: 89
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Set the retentionInDays value.</p>

    <p></p>
  syntax:
    content: public AzureBlobStorageApplicationLogsConfig withRetentionInDays(Integer retentionInDays)
    parameters:
    - id: retentionInDays
      type: 08effaa0
      description: <p>the retentionInDays value to set </p>
    return:
      type: com.microsoft.azure.management.website._azure_blob_storage_application_logs_config
      description: <p>the <xref href="com.microsoft.azure.management.website._azure_blob_storage_application_logs_config" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.website._azure_blob_storage_application_logs_config.withSasUrl(String)
  id: withSasUrl(String)
  parent: com.microsoft.azure.management.website._azure_blob_storage_application_logs_config
  href: com.microsoft.azure.management.website._azure_blob_storage_application_logs_config.yml
  langs:
  - java
  name: withSasUrl(String sasUrl)
  fullName: AzureBlobStorageApplicationLogsConfig com.microsoft.azure.management.website.AzureBlobStorageApplicationLogsConfig.withSasUrl(String sasUrl)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/AzureBlobStorageApplicationLogsConfig.java
    startLine: 69
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Set the sasUrl value.</p>

    <p></p>
  syntax:
    content: public AzureBlobStorageApplicationLogsConfig withSasUrl(String sasUrl)
    parameters:
    - id: sasUrl
      type: "26831127"
      description: <p>the sasUrl value to set </p>
    return:
      type: com.microsoft.azure.management.website._azure_blob_storage_application_logs_config
      description: <p>the <xref href="com.microsoft.azure.management.website._azure_blob_storage_application_logs_config" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 08effaa0
  spec.java:
  - name: Integer
    fullName: Integer
- uid: com.microsoft.azure.management.website._log_level
  parent: com.microsoft.azure.management.website
  href: com.microsoft.azure.management.website._log_level.yml
  name: LogLevel
  fullName: com.microsoft.azure.management.website.LogLevel
  type: Enum
  summary: <p>Defines values for <xref href="com.microsoft.azure.management.website._log_level" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public enum LogLevel
- uid: com.microsoft.azure.management.website._azure_blob_storage_application_logs_config
  parent: com.microsoft.azure.management.website
  href: com.microsoft.azure.management.website._azure_blob_storage_application_logs_config.yml
  name: AzureBlobStorageApplicationLogsConfig
  fullName: com.microsoft.azure.management.website.AzureBlobStorageApplicationLogsConfig
  type: Class
  summary: <p>Application logs azure blob storage configuration. </p>
  syntax: *o1
