items:
- uid: com.microsoft.azure.management.network._nic_ip_configuration._definition_with_subnet
  id: _definition_with_subnet
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._nic_ip_configuration._definition_with_subnet_1adfe5cdc34179e1f479901424ab596db6
  href: com.microsoft.azure.management.network._nic_ip_configuration._definition_with_subnet.yml
  langs:
  - java
  name: NicIpConfiguration.DefinitionWithSubnet<ParentT>
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.DefinitionWithSubnet<ParentT>
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
    startLine: 169
  package: com.microsoft.azure.management.network
  summary: >-
    <p>The stage of the Ip configuration definition allowing to specify subnet.</p>

    <p></p>
  syntax:
    content: public interface DefinitionWithSubnet<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the next stage after setting the subnet </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._definition_with_subnet_1adfe5cdc34179e1f479901424ab596db6
  id: _definition_with_subnet_1adfe5cdc34179e1f479901424ab596db6
  parent: com.microsoft.azure.management.network._nic_ip_configuration._definition_with_subnet
  href: com.microsoft.azure.management.network._nic_ip_configuration._definition_with_subnet.yml
  langs:
  - java
  name: withSubnet(String name)
  fullName: DefinitionWithPrivateIp<ParentT> com.microsoft.azure.management.network.NicIpConfiguration.DefinitionWithSubnet< ParentT >.withSubnet(String name)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
    startLine: 176
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Associate a subnet with the Ip configuration.</p>

    <p></p>
  syntax:
    content: public DefinitionWithPrivateIp< ParentT > withSubnet(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>the subnet name </p>
    return:
      type: com.microsoft.azure.management.network._nic_ip_configuration._definition_with_private_ipa6da57ba
      description: <p>the next stage of the Ip configuration definition </p>
references:
- uid: 18a275b1
  spec.java:
  - name: ParentT
    fullName: ParentT
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.management.network._nic_ip_configuration._definition_with_private_ipa6da57ba
  spec.java:
  - uid: com.microsoft.azure.management.network._nic_ip_configuration._definition_with_private_ip
    name: NicIpConfiguration.DefinitionWithPrivateIp<ParentT>
    fullName: com.microsoft.azure.management.network.NicIpConfiguration.DefinitionWithPrivateIp<ParentT>
    href: com.microsoft.azure.management.network._nic_ip_configuration._definition_with_private_ip.yml
  - name: < ParentT >
    fullName: < ParentT >
- uid: com.microsoft.azure.management.network._nic_ip_configuration._definitions
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._nic_ip_configuration._definitions.yml
  name: NicIpConfiguration.Definitions<ParentT>
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.Definitions<ParentT>
  type: Interface
  summary: >-
    <p>Container interface for all the definitions.</p>

    <p></p>
  syntax:
    content: public interface Definitions<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable_1a92836b66fb83b831c1470a093c42d42d" data-throw-if-not-resolved="false"></xref></p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._definition_with_private_ip
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._nic_ip_configuration._definition_with_private_ip.yml
  name: NicIpConfiguration.DefinitionWithPrivateIp<ParentT>
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.DefinitionWithPrivateIp<ParentT>
  type: Interface
  summary: >-
    <p>The stage of the Ip configuration definition allowing to specify private IP address within a virtual network subnet.</p>

    <p></p>
  syntax:
    content: public interface DefinitionWithPrivateIp<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable_1a92836b66fb83b831c1470a093c42d42d" data-throw-if-not-resolved="false"></xref></p>
