items:
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_subnet
  id: _with_subnet
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_subnet_1ae952abf7216f9d158315c701273ed1e2
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_subnet.yml
  langs:
  - java
  name: NicIpConfiguration.UpdateStages.WithSubnet
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.UpdateStages.WithSubnet
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
    startLine: 440
  package: com.microsoft.azure.management.network
  summary: <p>The stage of the network interface IP configuration update allowing to specify subnet. </p>
  syntax:
    content: public interface WithSubnet
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_subnet_1ae952abf7216f9d158315c701273ed1e2
  id: _with_subnet_1ae952abf7216f9d158315c701273ed1e2
  parent: com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_subnet
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_stages._with_subnet.yml
  langs:
  - java
  name: withSubnet(String name)
  fullName: Update com.microsoft.azure.management.network.NicIpConfiguration.UpdateStages.WithSubnet.withSubnet(String name)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
    startLine: 447
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Associate a subnet with the network interface IP configuration.</p>

    <p></p>
  syntax:
    content: public Update withSubnet(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>the subnet name </p>
    return:
      type: com.microsoft.azure.management.network._nic_ip_configuration._update
      description: <p>the next stage of the network interface IP configuration update </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._nic_ip_configuration._update.yml
  name: NicIpConfiguration.Update
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.Update
  type: Interface
  summary: <p>The entirety of a network interface IP configuration update as part of a network interface update. </p>
  syntax:
    content: public interface Update extends Settable< NetworkInterface.Update >,NicIpConfiguration.UpdateStages.WithSubnet,NicIpConfiguration.UpdateStages.WithPrivateIp,NicIpConfiguration.UpdateStages.WithPublicIpAddress,NicIpConfiguration.UpdateStages.WithLoadBalancer,NicIpConfiguration.UpdateStages.WithBackendAddressPool
