items:
- uid: com.microsoft.azure.management.resources._deployment._definition_stages._with_group
  id: _with_group
  parent: com.microsoft.azure.management.resources
  children:
  - com.microsoft.azure.management.resources._deployment._definition_stages._with_group_1a73bf2f834ecbfe3cb26db0aa1a8bb847
  - com.microsoft.azure.management.resources._deployment._definition_stages._with_group_1ad0634c750f26d06b89c4910f3d934d21
  href: com.microsoft.azure.management.resources._deployment._definition_stages._with_group.yml
  langs:
  - java
  name: Deployment.DefinitionStages.WithGroup
  fullName: com.microsoft.azure.management.resources.Deployment.DefinitionStages.WithGroup
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/Deployment.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/Deployment.java
    startLine: 143
  package: com.microsoft.azure.management.resources
  summary: <p>A deployment definition allowing resource group to be specified. </p>
  syntax:
    content: public interface WithGroup extends GroupableResource.DefinitionStages.WithExistingResourceGroup< WithTemplate >
  inheritedMembers:
  - com.microsoft.azure.management.resources.fluentcore.arm.models.8840de0f1834fe83a2ad6c366b5a0555_1a0013a67ceee0f87c3029562d74f5f8e6
  - com.microsoft.azure.management.resources.fluentcore.arm.models.8840de0f1834fe83a2ad6c366b5a0555_1adbaff62ad5fe1174484a9aa82f29e48e
- uid: com.microsoft.azure.management.resources._deployment._definition_stages._with_group_1a73bf2f834ecbfe3cb26db0aa1a8bb847
  id: _with_group_1a73bf2f834ecbfe3cb26db0aa1a8bb847
  parent: com.microsoft.azure.management.resources._deployment._definition_stages._with_group
  href: com.microsoft.azure.management.resources._deployment._definition_stages._with_group.yml
  langs:
  - java
  name: withNewResourceGroup(Creatable< ResourceGroup > groupDefinition)
  fullName: WithTemplate com.microsoft.azure.management.resources.Deployment.DefinitionStages.WithGroup.withNewResourceGroup(Creatable< ResourceGroup > groupDefinition)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/Deployment.java
    startLine: 157
  package: com.microsoft.azure.management.resources
  summary: <p>Creates a new resource group to put the resource in, based on the definition specified. </p>
  syntax:
    content: public WithTemplate withNewResourceGroup(Creatable< ResourceGroup > groupDefinition)
    parameters:
    - id: groupDefinition
      type: com.microsoft.azure.management.resources.fluentcore.model._creatable151dc42ccom.microsoft.azure.management.resources._resource_group9ec3e006
      description: <p>a creatable definition for a new resource group </p>
    return:
      type: com.microsoft.azure.management.resources._deployment._definition_stages._with_template
      description: <p>the next stage of the deployment definition </p>
- uid: com.microsoft.azure.management.resources._deployment._definition_stages._with_group_1ad0634c750f26d06b89c4910f3d934d21
  id: _with_group_1ad0634c750f26d06b89c4910f3d934d21
  parent: com.microsoft.azure.management.resources._deployment._definition_stages._with_group
  href: com.microsoft.azure.management.resources._deployment._definition_stages._with_group.yml
  langs:
  - java
  name: withNewResourceGroup(String name, Region region)
  fullName: WithTemplate com.microsoft.azure.management.resources.Deployment.DefinitionStages.WithGroup.withNewResourceGroup(String name, Region region)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/Deployment.java
    startLine: 150
  package: com.microsoft.azure.management.resources
  summary: <p>Creates a new resource group to put the deployment in. </p>
  syntax:
    content: public WithTemplate withNewResourceGroup(String name, Region region)
    parameters:
    - id: name
      type: "26831127"
      description: <p>the name of the new group </p>
    - id: region
      type: com.microsoft.azure.management.resources.fluentcore.arm._region
      description: <p>the region to create the resource group in </p>
    return:
      type: com.microsoft.azure.management.resources._deployment._definition_stages._with_template
      description: <p>the next stage of the deployment definition </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.management.resources.fluentcore.model._creatable151dc42ccom.microsoft.azure.management.resources._resource_group9ec3e006
  spec.java:
  - uid: com.microsoft.azure.management.resources.fluentcore.model._creatable
    name: Creatable
    fullName: com.microsoft.azure.management.resources.fluentcore.model.Creatable
    href: com.microsoft.azure.management.resources.fluentcore.model._creatable.yml
  - name: '< '
    fullName: '< '
  - uid: com.microsoft.azure.management.resources._resource_group
    name: ResourceGroup
    fullName: com.microsoft.azure.management.resources.ResourceGroup
    href: com.microsoft.azure.management.resources._resource_group.yml
  - name: ' >'
    fullName: ' >'
- uid: com.microsoft.azure.management.resources.fluentcore.arm.models.8840de0f1834fe83a2ad6c366b5a0555_1a0013a67ceee0f87c3029562d74f5f8e6
  parent: com.microsoft.azure.management.resources.fluentcore.arm.models.8840de0f1834fe83a2ad6c366b5a0555
  href: com.microsoft.azure.management.resources.fluentcore.arm.models.8840de0f1834fe83a2ad6c366b5a0555.yml
  name: withExistingResourceGroup(String groupName)
  fullName: T com.microsoft.azure.management.resources.fluentcore.arm.models.GroupableResource.DefinitionStages.WithExistingResourceGroup< T >.withExistingResourceGroup(String groupName)
  type: Method
  summary: <p>Associates the resource with an existing resource group. </p>
  syntax:
    content: public T withExistingResourceGroup(String groupName)
    parameters:
    - id: groupName
      type: "26831127"
      description: <p>the name of an existing resource group to put this resource in. </p>
    return:
      type: 8ce1ecb9
      description: <p>the next stage of the resource definition </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm.models.8840de0f1834fe83a2ad6c366b5a0555_1adbaff62ad5fe1174484a9aa82f29e48e
  parent: com.microsoft.azure.management.resources.fluentcore.arm.models.8840de0f1834fe83a2ad6c366b5a0555
  href: com.microsoft.azure.management.resources.fluentcore.arm.models.8840de0f1834fe83a2ad6c366b5a0555.yml
  name: withExistingResourceGroup(ResourceGroup group)
  fullName: T com.microsoft.azure.management.resources.fluentcore.arm.models.GroupableResource.DefinitionStages.WithExistingResourceGroup< T >.withExistingResourceGroup(ResourceGroup group)
  type: Method
  summary: <p>Associates the resource with an existing resource group. </p>
  syntax:
    content: public T withExistingResourceGroup(ResourceGroup group)
    parameters:
    - id: group
      type: com.microsoft.azure.management.resources._resource_group
      description: <p>an existing resource group to put the resource in </p>
    return:
      type: 8ce1ecb9
      description: <p>the next stage of the resource definition </p>
- uid: com.microsoft.azure.management.resources.fluentcore.arm.models.8840de0f1834fe83a2ad6c366b5a0555
  parent: com.microsoft.azure.management.resources.fluentcore.arm.models
  href: com.microsoft.azure.management.resources.fluentcore.arm.models.8840de0f1834fe83a2ad6c366b5a0555.yml
  name: GroupableResource.DefinitionStages.WithExistingResourceGroup<T>
  fullName: com.microsoft.azure.management.resources.fluentcore.arm.models.GroupableResource.DefinitionStages.WithExistingResourceGroup<T>
  type: Interface
  summary: >-
    <p>A resource definition allowing an existing resource group to be selected.</p>

    <p></p>
  syntax:
    content: public interface WithExistingResourceGroup<T>
    typeParameters:
    - type: 8ce1ecb9
      description: <p>the next stage of the resource definition </p>
- uid: com.microsoft.azure.management.resources._deployment._definition
  parent: com.microsoft.azure.management.resources
  href: com.microsoft.azure.management.resources._deployment._definition.yml
  name: Deployment.Definition
  fullName: com.microsoft.azure.management.resources.Deployment.Definition
  type: Interface
  summary: <p>Container interface for all the deployment definitions. </p>
  syntax:
    content: public interface Definition extends Deployment.DefinitionStages.Blank,Deployment.DefinitionStages.WithGroup,Deployment.DefinitionStages.WithTemplate,Deployment.DefinitionStages.WithParameters,Deployment.DefinitionStages.WithMode,Deployment.DefinitionStages.WithCreate
- uid: com.microsoft.azure.management.resources._deployment._definition_stages._blank
  parent: com.microsoft.azure.management.resources
  href: com.microsoft.azure.management.resources._deployment._definition_stages._blank.yml
  name: Deployment.DefinitionStages.Blank
  fullName: com.microsoft.azure.management.resources.Deployment.DefinitionStages.Blank
  type: Interface
  summary: <p>The first stage of deployment definition. </p>
  syntax:
    content: public interface Blank extends Deployment.DefinitionStages.WithGroup
- uid: com.microsoft.azure.management.resources._deployment._definition_stages._with_template
  parent: com.microsoft.azure.management.resources
  href: com.microsoft.azure.management.resources._deployment._definition_stages._with_template.yml
  name: Deployment.DefinitionStages.WithTemplate
  fullName: com.microsoft.azure.management.resources.Deployment.DefinitionStages.WithTemplate
  type: Interface
  summary: <p>A deployment definition allowing the template to be specified. </p>
  syntax:
    content: public interface WithTemplate
- uid: com.microsoft.azure.management.resources.fluentcore.arm._region
  parent: com.microsoft.azure.management.resources.fluentcore.arm
  href: com.microsoft.azure.management.resources.fluentcore.arm._region.yml
  name: Region
  fullName: com.microsoft.azure.management.resources.fluentcore.arm.Region
  type: Enum
  summary: <p>Enumeration of the <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> datacenter regions. See <ulink url="https://azure.microsoft.com/regions/">https://azure.microsoft.com/regions/</ulink></p>
  syntax:
    content: public enum Region
- uid: com.microsoft.azure.management.resources.fluentcore.model._creatable
  parent: com.microsoft.azure.management.resources.fluentcore.model
  href: com.microsoft.azure.management.resources.fluentcore.model._creatable.yml
  name: Creatable<T>
  fullName: com.microsoft.azure.management.resources.fluentcore.model.Creatable<T>
  type: Interface
  summary: >-
    <p>The final stage of the resource definition, at which it can be create, using <xref href="com.microsoft.azure.management.resources.fluentcore.model._creatable_1acf3889a24f1bb5e64f8e6a751397f991" data-throw-if-not-resolved="false"></xref>.</p>

    <p></p>
  syntax:
    content: public interface Creatable<T> extends Indexable
    typeParameters:
    - type: 8ce1ecb9
      description: <p>the fluent type of the resource to be created </p>
- uid: com.microsoft.azure.management.resources._resource_group
  parent: com.microsoft.azure.management.resources
  href: com.microsoft.azure.management.resources._resource_group.yml
  name: ResourceGroup
  fullName: com.microsoft.azure.management.resources.ResourceGroup
  type: Interface
  summary: <p>An immutable client-side representation of an <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> resource group. </p>
  syntax:
    content: public interface ResourceGroup extends Indexable,Resource,Refreshable< ResourceGroup >,Wrapper< ResourceGroupInner >,Updatable< ResourceGroup.Update >
