items:
- uid: com.microsoft.azure.management.network._application_gateway_operational_state
  id: _application_gateway_operational_state
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._application_gateway_operational_state_1ae78aab53aef29c07186360f0f6ee4089
  - com.microsoft.azure.management.network._application_gateway_operational_state_1a54e229d20f7514eedddb25c852896f91
  - com.microsoft.azure.management.network._application_gateway_operational_state_1ac30b96b4eac8606d9d9ef29ac53b92af
  - com.microsoft.azure.management.network._application_gateway_operational_state_1aa4c6821cd43b7fe34ae1cd01099a6b7b
  - com.microsoft.azure.management.network._application_gateway_operational_state_1a75014fd4b3510d2bf9a443cef883bca5
  - com.microsoft.azure.management.network._application_gateway_operational_state_1a37039a8dfb676fe83acd775d2e45100d
  - com.microsoft.azure.management.network._application_gateway_operational_state_1ae3ccf627eaf67776354897b608cb2c3d
  - com.microsoft.azure.management.network._application_gateway_operational_state_1a6e998532dd68a7d39b18f6c8f90b6c3f
  href: com.microsoft.azure.management.network._application_gateway_operational_state.yml
  langs:
  - java
  name: ApplicationGatewayOperationalState
  fullName: com.microsoft.azure.management.network.ApplicationGatewayOperationalState
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayOperationalState.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayOperationalState.java
    startLine: 15
  package: com.microsoft.azure.management.network
  summary: <p>Defines values for <xref href="com.microsoft.azure.management.network._application_gateway_operational_state" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: &o1
    content: public class ApplicationGatewayOperationalState
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.network._application_gateway_operational_state_1ae78aab53aef29c07186360f0f6ee4089
  id: _application_gateway_operational_state_1ae78aab53aef29c07186360f0f6ee4089
  parent: com.microsoft.azure.management.network._application_gateway_operational_state
  href: com.microsoft.azure.management.network._application_gateway_operational_state.yml
  langs:
  - java
  name: ApplicationGatewayOperationalState(String value)
  fullName: com.microsoft.azure.management.network.ApplicationGatewayOperationalState.ApplicationGatewayOperationalState(String value)
  type: Constructor
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayOperationalState.java
    startLine: 34
  package: com.microsoft.azure.management.network
  summary: <p>Creates a custom value for <xref href="com.microsoft.azure.management.network._application_gateway_operational_state" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public ApplicationGatewayOperationalState(String value)
    parameters:
    - id: value
      type: "26831127"
      description: <p>the custom value </p>
- uid: com.microsoft.azure.management.network._application_gateway_operational_state_1a54e229d20f7514eedddb25c852896f91
  id: _application_gateway_operational_state_1a54e229d20f7514eedddb25c852896f91
  parent: com.microsoft.azure.management.network._application_gateway_operational_state
  href: com.microsoft.azure.management.network._application_gateway_operational_state.yml
  langs:
  - java
  name: equals(Object obj)
  fullName: boolean com.microsoft.azure.management.network.ApplicationGatewayOperationalState.equals(Object obj)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayOperationalState.java
    startLine: 50
  package: com.microsoft.azure.management.network
  syntax:
    content: public boolean equals(Object obj)
    parameters:
    - id: obj
      type: "79317049"
    return:
      type: 4fc6e284
- uid: com.microsoft.azure.management.network._application_gateway_operational_state_1ac30b96b4eac8606d9d9ef29ac53b92af
  id: _application_gateway_operational_state_1ac30b96b4eac8606d9d9ef29ac53b92af
  parent: com.microsoft.azure.management.network._application_gateway_operational_state
  href: com.microsoft.azure.management.network._application_gateway_operational_state.yml
  langs:
  - java
  name: hashCode()
  fullName: int com.microsoft.azure.management.network.ApplicationGatewayOperationalState.hashCode()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayOperationalState.java
    startLine: 45
  package: com.microsoft.azure.management.network
  syntax:
    content: public int hashCode()
    return:
      type: f75371fa
- uid: com.microsoft.azure.management.network._application_gateway_operational_state_1aa4c6821cd43b7fe34ae1cd01099a6b7b
  id: _application_gateway_operational_state_1aa4c6821cd43b7fe34ae1cd01099a6b7b
  parent: com.microsoft.azure.management.network._application_gateway_operational_state
  href: com.microsoft.azure.management.network._application_gateway_operational_state.yml
  langs:
  - java
  name: RUNNING
  fullName: final ApplicationGatewayOperationalState com.microsoft.azure.management.network.ApplicationGatewayOperationalState.RUNNING
  type: Field
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayOperationalState.java
    startLine: 23
  package: com.microsoft.azure.management.network
  summary: <p>Static value Running for <xref href="com.microsoft.azure.management.network._application_gateway_operational_state" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public static final ApplicationGatewayOperationalState RUNNING= new ApplicationGatewayOperationalState("Running")
    return:
      type: 93de0ef9com.microsoft.azure.management.network._application_gateway_operational_state
- uid: com.microsoft.azure.management.network._application_gateway_operational_state_1a75014fd4b3510d2bf9a443cef883bca5
  id: _application_gateway_operational_state_1a75014fd4b3510d2bf9a443cef883bca5
  parent: com.microsoft.azure.management.network._application_gateway_operational_state
  href: com.microsoft.azure.management.network._application_gateway_operational_state.yml
  langs:
  - java
  name: STARTING
  fullName: final ApplicationGatewayOperationalState com.microsoft.azure.management.network.ApplicationGatewayOperationalState.STARTING
  type: Field
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayOperationalState.java
    startLine: 20
  package: com.microsoft.azure.management.network
  summary: <p>Static value Starting for <xref href="com.microsoft.azure.management.network._application_gateway_operational_state" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public static final ApplicationGatewayOperationalState STARTING= new ApplicationGatewayOperationalState("Starting")
    return:
      type: 93de0ef9com.microsoft.azure.management.network._application_gateway_operational_state
- uid: com.microsoft.azure.management.network._application_gateway_operational_state_1a37039a8dfb676fe83acd775d2e45100d
  id: _application_gateway_operational_state_1a37039a8dfb676fe83acd775d2e45100d
  parent: com.microsoft.azure.management.network._application_gateway_operational_state
  href: com.microsoft.azure.management.network._application_gateway_operational_state.yml
  langs:
  - java
  name: STOPPED
  fullName: final ApplicationGatewayOperationalState com.microsoft.azure.management.network.ApplicationGatewayOperationalState.STOPPED
  type: Field
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayOperationalState.java
    startLine: 17
  package: com.microsoft.azure.management.network
  summary: <p>Static value Stopped for <xref href="com.microsoft.azure.management.network._application_gateway_operational_state" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public static final ApplicationGatewayOperationalState STOPPED= new ApplicationGatewayOperationalState("Stopped")
    return:
      type: 93de0ef9com.microsoft.azure.management.network._application_gateway_operational_state
- uid: com.microsoft.azure.management.network._application_gateway_operational_state_1ae3ccf627eaf67776354897b608cb2c3d
  id: _application_gateway_operational_state_1ae3ccf627eaf67776354897b608cb2c3d
  parent: com.microsoft.azure.management.network._application_gateway_operational_state
  href: com.microsoft.azure.management.network._application_gateway_operational_state.yml
  langs:
  - java
  name: STOPPING
  fullName: final ApplicationGatewayOperationalState com.microsoft.azure.management.network.ApplicationGatewayOperationalState.STOPPING
  type: Field
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayOperationalState.java
    startLine: 26
  package: com.microsoft.azure.management.network
  summary: <p>Static value Stopping for <xref href="com.microsoft.azure.management.network._application_gateway_operational_state" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public static final ApplicationGatewayOperationalState STOPPING= new ApplicationGatewayOperationalState("Stopping")
    return:
      type: 93de0ef9com.microsoft.azure.management.network._application_gateway_operational_state
- uid: com.microsoft.azure.management.network._application_gateway_operational_state_1a6e998532dd68a7d39b18f6c8f90b6c3f
  id: _application_gateway_operational_state_1a6e998532dd68a7d39b18f6c8f90b6c3f
  parent: com.microsoft.azure.management.network._application_gateway_operational_state
  href: com.microsoft.azure.management.network._application_gateway_operational_state.yml
  langs:
  - java
  name: toString()
  fullName: String com.microsoft.azure.management.network.ApplicationGatewayOperationalState.toString()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayOperationalState.java
    startLine: 40
  package: com.microsoft.azure.management.network
  syntax:
    content: public String toString()
    return:
      type: "26831127"
references:
- uid: 93de0ef9com.microsoft.azure.management.network._application_gateway_operational_state
  spec.java:
  - name: 'final '
    fullName: 'final '
  - uid: com.microsoft.azure.management.network._application_gateway_operational_state
    name: ApplicationGatewayOperationalState
    fullName: com.microsoft.azure.management.network.ApplicationGatewayOperationalState
    href: com.microsoft.azure.management.network._application_gateway_operational_state.yml
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
- uid: "79317049"
  spec.java:
  - name: Object
    fullName: Object
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: com.microsoft.azure.management.network._application_gateway_operational_state
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_operational_state.yml
  name: ApplicationGatewayOperationalState
  fullName: com.microsoft.azure.management.network.ApplicationGatewayOperationalState
  type: Class
  summary: <p>Defines values for <xref href="com.microsoft.azure.management.network._application_gateway_operational_state" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: *o1
