items:
- uid: com.microsoft.azure.management.network.implementation.api._application_gateway_tier
  id: _application_gateway_tier
  parent: com.microsoft.azure.management.network.implementation.api
  children:
  - com.microsoft.azure.management.network.implementation.api._application_gateway_tier_1ae6785d35a7bb1bf31e38fbb9bd04591d
  href: com.microsoft.azure.management.network.implementation.api._application_gateway_tier.yml
  langs:
  - java
  name: ApplicationGatewayTier
  fullName: com.microsoft.azure.management.network.implementation.api.ApplicationGatewayTier
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/api/ApplicationGatewayTier.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/api/ApplicationGatewayTier.java
    startLine: 11
  package: com.microsoft.azure.management.network.implementation.api
  summary: <p>Defines values for <xref href="com.microsoft.azure.management.network.implementation.api._application_gateway_tier" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: &o1
    content: public class ApplicationGatewayTier
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.network.implementation.api._application_gateway_tier_1ae6785d35a7bb1bf31e38fbb9bd04591d
  id: _application_gateway_tier_1ae6785d35a7bb1bf31e38fbb9bd04591d
  parent: com.microsoft.azure.management.network.implementation.api._application_gateway_tier
  href: com.microsoft.azure.management.network.implementation.api._application_gateway_tier.yml
  langs:
  - java
  name: STANDARD
  fullName: final String com.microsoft.azure.management.network.implementation.api.ApplicationGatewayTier.STANDARD
  type: Field
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/api/ApplicationGatewayTier.java
    startLine: 13
  package: com.microsoft.azure.management.network.implementation.api
  summary: <p>Static value Standard for <xref href="com.microsoft.azure.management.network.implementation.api._application_gateway_tier" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public static final String STANDARD= "Standard"
    return:
      type: 3d93591e
references:
- uid: 3d93591e
  spec.java:
  - name: final String
    fullName: final String
- uid: com.microsoft.azure.management.network.implementation.api._application_gateway_tier
  parent: com.microsoft.azure.management.network.implementation.api
  href: com.microsoft.azure.management.network.implementation.api._application_gateway_tier.yml
  name: ApplicationGatewayTier
  fullName: com.microsoft.azure.management.network.implementation.api.ApplicationGatewayTier
  type: Class
  summary: <p>Defines values for <xref href="com.microsoft.azure.management.network.implementation.api._application_gateway_tier" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: *o1
