items:
- uid: com.microsoft.azure.management.network._vpn_client_configuration
  id: _vpn_client_configuration
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._vpn_client_configuration_1a4827a919736655f156e0525d923369e6
  - com.microsoft.azure.management.network._vpn_client_configuration_1ad3bb73654c144120028689f9c4c05c45
  - com.microsoft.azure.management.network._vpn_client_configuration_1a1be1ba084362f35951002a8c791d981a
  - com.microsoft.azure.management.network._vpn_client_configuration_1ac231e8bdd2510078b1d657697e40e118
  - com.microsoft.azure.management.network._vpn_client_configuration_1aaf9b70b9dfdbc61b3af559a7c4ca96d3
  - com.microsoft.azure.management.network._vpn_client_configuration_1a9751b78de972cedce05e0ea755acfec5
  href: com.microsoft.azure.management.network._vpn_client_configuration.yml
  langs:
  - java
  name: VpnClientConfiguration
  fullName: com.microsoft.azure.management.network.VpnClientConfiguration
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/VpnClientConfiguration.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/VpnClientConfiguration.java
    startLine: 15
  package: com.microsoft.azure.management.network
  summary: >-
    <p>

      <xref href="com.microsoft.azure.management.network._vpn_client_configuration" data-throw-if-not-resolved="false"></xref> for P2S client. </p>
  syntax: &o1
    content: public class VpnClientConfiguration
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.network._vpn_client_configuration_1a4827a919736655f156e0525d923369e6
  id: _vpn_client_configuration_1a4827a919736655f156e0525d923369e6
  parent: com.microsoft.azure.management.network._vpn_client_configuration
  href: com.microsoft.azure.management.network._vpn_client_configuration.yml
  langs:
  - java
  name: vpnClientAddressPool()
  fullName: AddressSpace com.microsoft.azure.management.network.VpnClientConfiguration.vpnClientAddressPool()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/VpnClientConfiguration.java
    startLine: 37
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the vpnClientAddressPool value.</p>

    <p></p>
  syntax:
    content: public AddressSpace vpnClientAddressPool()
    return:
      type: com.microsoft.azure.management.network._address_space
      description: <p>the vpnClientAddressPool value </p>
- uid: com.microsoft.azure.management.network._vpn_client_configuration_1ad3bb73654c144120028689f9c4c05c45
  id: _vpn_client_configuration_1ad3bb73654c144120028689f9c4c05c45
  parent: com.microsoft.azure.management.network._vpn_client_configuration
  href: com.microsoft.azure.management.network._vpn_client_configuration.yml
  langs:
  - java
  name: vpnClientRevokedCertificates()
  fullName: List<VpnClientRevokedCertificate> com.microsoft.azure.management.network.VpnClientConfiguration.vpnClientRevokedCertificates()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/VpnClientConfiguration.java
    startLine: 77
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the vpnClientRevokedCertificates value.</p>

    <p></p>
  syntax:
    content: public List< VpnClientRevokedCertificate > vpnClientRevokedCertificates()
    return:
      type: f6a6204dcom.microsoft.azure.management.network._vpn_client_revoked_certificate9ec3e006
      description: <p>the vpnClientRevokedCertificates value </p>
- uid: com.microsoft.azure.management.network._vpn_client_configuration_1a1be1ba084362f35951002a8c791d981a
  id: _vpn_client_configuration_1a1be1ba084362f35951002a8c791d981a
  parent: com.microsoft.azure.management.network._vpn_client_configuration
  href: com.microsoft.azure.management.network._vpn_client_configuration.yml
  langs:
  - java
  name: vpnClientRootCertificates()
  fullName: List<VpnClientRootCertificate> com.microsoft.azure.management.network.VpnClientConfiguration.vpnClientRootCertificates()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/VpnClientConfiguration.java
    startLine: 57
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the vpnClientRootCertificates value.</p>

    <p></p>
  syntax:
    content: public List< VpnClientRootCertificate > vpnClientRootCertificates()
    return:
      type: f6a6204dcom.microsoft.azure.management.network._vpn_client_root_certificate9ec3e006
      description: <p>the vpnClientRootCertificates value </p>
- uid: com.microsoft.azure.management.network._vpn_client_configuration_1ac231e8bdd2510078b1d657697e40e118
  id: _vpn_client_configuration_1ac231e8bdd2510078b1d657697e40e118
  parent: com.microsoft.azure.management.network._vpn_client_configuration
  href: com.microsoft.azure.management.network._vpn_client_configuration.yml
  langs:
  - java
  name: withVpnClientAddressPool(AddressSpace vpnClientAddressPool)
  fullName: VpnClientConfiguration com.microsoft.azure.management.network.VpnClientConfiguration.withVpnClientAddressPool(AddressSpace vpnClientAddressPool)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/VpnClientConfiguration.java
    startLine: 47
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the vpnClientAddressPool value.</p>

    <p></p>
  syntax:
    content: public VpnClientConfiguration withVpnClientAddressPool(AddressSpace vpnClientAddressPool)
    parameters:
    - id: vpnClientAddressPool
      type: com.microsoft.azure.management.network._address_space
      description: <p>the vpnClientAddressPool value to set </p>
    return:
      type: com.microsoft.azure.management.network._vpn_client_configuration
      description: <p>the <xref href="com.microsoft.azure.management.network._vpn_client_configuration" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network._vpn_client_configuration_1aaf9b70b9dfdbc61b3af559a7c4ca96d3
  id: _vpn_client_configuration_1aaf9b70b9dfdbc61b3af559a7c4ca96d3
  parent: com.microsoft.azure.management.network._vpn_client_configuration
  href: com.microsoft.azure.management.network._vpn_client_configuration.yml
  langs:
  - java
  name: withVpnClientRevokedCertificates(List< VpnClientRevokedCertificate > vpnClientRevokedCertificates)
  fullName: VpnClientConfiguration com.microsoft.azure.management.network.VpnClientConfiguration.withVpnClientRevokedCertificates(List< VpnClientRevokedCertificate > vpnClientRevokedCertificates)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/VpnClientConfiguration.java
    startLine: 87
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the vpnClientRevokedCertificates value.</p>

    <p></p>
  syntax:
    content: public VpnClientConfiguration withVpnClientRevokedCertificates(List< VpnClientRevokedCertificate > vpnClientRevokedCertificates)
    parameters:
    - id: vpnClientRevokedCertificates
      type: f6a6204dcom.microsoft.azure.management.network._vpn_client_revoked_certificate9ec3e006
      description: <p>the vpnClientRevokedCertificates value to set </p>
    return:
      type: com.microsoft.azure.management.network._vpn_client_configuration
      description: <p>the <xref href="com.microsoft.azure.management.network._vpn_client_configuration" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network._vpn_client_configuration_1a9751b78de972cedce05e0ea755acfec5
  id: _vpn_client_configuration_1a9751b78de972cedce05e0ea755acfec5
  parent: com.microsoft.azure.management.network._vpn_client_configuration
  href: com.microsoft.azure.management.network._vpn_client_configuration.yml
  langs:
  - java
  name: withVpnClientRootCertificates(List< VpnClientRootCertificate > vpnClientRootCertificates)
  fullName: VpnClientConfiguration com.microsoft.azure.management.network.VpnClientConfiguration.withVpnClientRootCertificates(List< VpnClientRootCertificate > vpnClientRootCertificates)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/VpnClientConfiguration.java
    startLine: 67
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the vpnClientRootCertificates value.</p>

    <p></p>
  syntax:
    content: public VpnClientConfiguration withVpnClientRootCertificates(List< VpnClientRootCertificate > vpnClientRootCertificates)
    parameters:
    - id: vpnClientRootCertificates
      type: f6a6204dcom.microsoft.azure.management.network._vpn_client_root_certificate9ec3e006
      description: <p>the vpnClientRootCertificates value to set </p>
    return:
      type: com.microsoft.azure.management.network._vpn_client_configuration
      description: <p>the <xref href="com.microsoft.azure.management.network._vpn_client_configuration" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: f6a6204dcom.microsoft.azure.management.network._vpn_client_root_certificate9ec3e006
  spec.java:
  - name: 'List< '
    fullName: 'List< '
  - uid: com.microsoft.azure.management.network._vpn_client_root_certificate
    name: VpnClientRootCertificate
    fullName: com.microsoft.azure.management.network.VpnClientRootCertificate
    href: com.microsoft.azure.management.network._vpn_client_root_certificate.yml
  - name: ' >'
    fullName: ' >'
- uid: f6a6204dcom.microsoft.azure.management.network._vpn_client_revoked_certificate9ec3e006
  spec.java:
  - name: 'List< '
    fullName: 'List< '
  - uid: com.microsoft.azure.management.network._vpn_client_revoked_certificate
    name: VpnClientRevokedCertificate
    fullName: com.microsoft.azure.management.network.VpnClientRevokedCertificate
    href: com.microsoft.azure.management.network._vpn_client_revoked_certificate.yml
  - name: ' >'
    fullName: ' >'
- uid: com.microsoft.azure.management.network._address_space
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._address_space.yml
  name: AddressSpace
  fullName: com.microsoft.azure.management.network.AddressSpace
  type: Class
  summary: >-
    <p>

      <xref href="com.microsoft.azure.management.network._address_space" data-throw-if-not-resolved="false"></xref> contains an array of IP address ranges that can be used by subnets. </p>
  syntax:
    content: public class AddressSpace
- uid: com.microsoft.azure.management.network._vpn_client_root_certificate
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._vpn_client_root_certificate.yml
  name: VpnClientRootCertificate
  fullName: com.microsoft.azure.management.network.VpnClientRootCertificate
  type: Class
  summary: <p>VPN client root certificate of virtual network gateway. </p>
  syntax:
    content: public class VpnClientRootCertificate
- uid: com.microsoft.azure.management.network._vpn_client_revoked_certificate
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._vpn_client_revoked_certificate.yml
  name: VpnClientRevokedCertificate
  fullName: com.microsoft.azure.management.network.VpnClientRevokedCertificate
  type: Class
  summary: <p>VPN client revoked certificate of virtual network gateway. </p>
  syntax:
    content: public class VpnClientRevokedCertificate
- uid: com.microsoft.azure.management.network._vpn_client_configuration
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._vpn_client_configuration.yml
  name: VpnClientConfiguration
  fullName: com.microsoft.azure.management.network.VpnClientConfiguration
  type: Class
  summary: >-
    <p>

      <xref href="com.microsoft.azure.management.network._vpn_client_configuration" data-throw-if-not-resolved="false"></xref> for P2S client. </p>
  syntax: *o1
