items:
- uid: com.microsoft.azure.batch.protocol.models._application_package_reference
  id: _application_package_reference
  parent: com.microsoft.azure.batch.protocol.models
  children:
  - com.microsoft.azure.batch.protocol.models._application_package_reference.applicationId()
  - com.microsoft.azure.batch.protocol.models._application_package_reference.version()
  - com.microsoft.azure.batch.protocol.models._application_package_reference.withApplicationId(String)
  - com.microsoft.azure.batch.protocol.models._application_package_reference.withVersion(String)
  href: com.microsoft.azure.batch.protocol.models._application_package_reference.yml
  langs:
  - java
  name: ApplicationPackageReference
  fullName: com.microsoft.azure.batch.protocol.models.ApplicationPackageReference
  type: Class
  source:
    remote: &o0
      path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationPackageReference.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationPackageReference.java
    startLine: 15
  package: com.microsoft.azure.batch.protocol.models
  summary: <p>A reference to an application package to be deployed to compute nodes. </p>
  syntax: &o1
    content: public class ApplicationPackageReference
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.batch.protocol.models._application_package_reference.applicationId()
  id: applicationId()
  parent: com.microsoft.azure.batch.protocol.models._application_package_reference
  href: com.microsoft.azure.batch.protocol.models._application_package_reference.yml
  langs:
  - java
  name: applicationId()
  fullName: String com.microsoft.azure.batch.protocol.models.ApplicationPackageReference.applicationId()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationPackageReference.java
    startLine: 33
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the applicationId value.</p>

    <p></p>
  syntax:
    content: public String applicationId()
    return:
      type: "26831127"
      description: <p>the applicationId value </p>
- uid: com.microsoft.azure.batch.protocol.models._application_package_reference.version()
  id: version()
  parent: com.microsoft.azure.batch.protocol.models._application_package_reference
  href: com.microsoft.azure.batch.protocol.models._application_package_reference.yml
  langs:
  - java
  name: version()
  fullName: String com.microsoft.azure.batch.protocol.models.ApplicationPackageReference.version()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationPackageReference.java
    startLine: 53
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the version value.</p>

    <p></p>
  syntax:
    content: public String version()
    return:
      type: "26831127"
      description: <p>the version value </p>
- uid: com.microsoft.azure.batch.protocol.models._application_package_reference.withApplicationId(String)
  id: withApplicationId(String)
  parent: com.microsoft.azure.batch.protocol.models._application_package_reference
  href: com.microsoft.azure.batch.protocol.models._application_package_reference.yml
  langs:
  - java
  name: withApplicationId(String applicationId)
  fullName: ApplicationPackageReference com.microsoft.azure.batch.protocol.models.ApplicationPackageReference.withApplicationId(String applicationId)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationPackageReference.java
    startLine: 43
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the applicationId value.</p>

    <p></p>
  syntax:
    content: public ApplicationPackageReference withApplicationId(String applicationId)
    parameters:
    - id: applicationId
      type: "26831127"
      description: <p>the applicationId value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._application_package_reference
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._application_package_reference" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.batch.protocol.models._application_package_reference.withVersion(String)
  id: withVersion(String)
  parent: com.microsoft.azure.batch.protocol.models._application_package_reference
  href: com.microsoft.azure.batch.protocol.models._application_package_reference.yml
  langs:
  - java
  name: withVersion(String version)
  fullName: ApplicationPackageReference com.microsoft.azure.batch.protocol.models.ApplicationPackageReference.withVersion(String version)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ApplicationPackageReference.java
    startLine: 63
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the version value.</p>

    <p></p>
  syntax:
    content: public ApplicationPackageReference withVersion(String version)
    parameters:
    - id: version
      type: "26831127"
      description: <p>the version value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._application_package_reference
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._application_package_reference" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.batch.protocol.models._application_package_reference
  parent: com.microsoft.azure.batch.protocol.models
  href: com.microsoft.azure.batch.protocol.models._application_package_reference.yml
  name: ApplicationPackageReference
  fullName: com.microsoft.azure.batch.protocol.models.ApplicationPackageReference
  type: Class
  summary: <p>A reference to an application package to be deployed to compute nodes. </p>
  syntax: *o1
