items:
- uid: com.example.jianghlu.azureresourcerunner._application_test
  id: _application_test
  parent: com.example.jianghlu.azureresourcerunner
  children:
  - com.example.jianghlu.azureresourcerunner._application_test_1a5eaa04bfa69cbb03e238a5e0b897cffd
  href: com.example.jianghlu.azureresourcerunner._application_test.yml
  langs:
  - java
  name: ApplicationTest
  fullName: com.example.jianghlu.azureresourcerunner.ApplicationTest
  type: Class
  source:
    remote: &o0
      path: examples/AzureResourceRunner/app/src/androidTest/java/com/example/jianghlu/azureresourcerunner/ApplicationTest.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: examples/AzureResourceRunner/app/src/androidTest/java/com/example/jianghlu/azureresourcerunner/ApplicationTest.java
    startLine: 8
  assemblies:
  - com.example.jianghlu.azureresourcerunner
  package: com.example.jianghlu.azureresourcerunner
  summary: >-
    <p>

      <ulink url="http://d.android.com/tools/testing/testing_android.html">Testing Fundamentals</ulink>

    </p>
  syntax:
    content: public class ApplicationTest
  inheritance:
  - java.lang.Object
  - android.test.ApplicationTestCase< Application >
- uid: com.example.jianghlu.azureresourcerunner._application_test_1a5eaa04bfa69cbb03e238a5e0b897cffd
  id: _application_test_1a5eaa04bfa69cbb03e238a5e0b897cffd
  parent: com.example.jianghlu.azureresourcerunner._application_test
  href: com.example.jianghlu.azureresourcerunner._application_test.yml
  langs:
  - java
  name: ApplicationTest()
  fullName: com.example.jianghlu.azureresourcerunner.ApplicationTest.ApplicationTest()
  type: Constructor
  source:
    remote: *o0
    path: examples/AzureResourceRunner/app/src/androidTest/java/com/example/jianghlu/azureresourcerunner/ApplicationTest.java
    startLine: 9
  assemblies:
  - com.example.jianghlu.azureresourcerunner
  package: com.example.jianghlu.azureresourcerunner
  syntax:
    content: public ApplicationTest()
references: []
