items:
- uid: com.microsoft.azure.management.network.implementation.api._public_i_p_address_dns_settings
  id: _public_i_p_address_dns_settings
  parent: com.microsoft.azure.management.network.implementation.api
  children:
  - com.microsoft.azure.management.network.implementation.api._public_i_p_address_dns_settings_1ab68f21b89f3321dad2a1943ef9d0a1b7
  - com.microsoft.azure.management.network.implementation.api._public_i_p_address_dns_settings_1aebbb3a6c6fc2b0b4dbf6ff3b57cd2d22
  - com.microsoft.azure.management.network.implementation.api._public_i_p_address_dns_settings_1a4151acb60c6ff88c6cae77e39f3df963
  - com.microsoft.azure.management.network.implementation.api._public_i_p_address_dns_settings_1a9aeb71c33f053d6f3f4f7e8f38a3bf2b
  - com.microsoft.azure.management.network.implementation.api._public_i_p_address_dns_settings_1a32e803e434326ab1623197342bfef102
  - com.microsoft.azure.management.network.implementation.api._public_i_p_address_dns_settings_1a3d3c850e00cf145a033e8d14b087cb8f
  href: com.microsoft.azure.management.network.implementation.api._public_i_p_address_dns_settings.yml
  langs:
  - java
  name: PublicIPAddressDnsSettings
  fullName: com.microsoft.azure.management.network.implementation.api.PublicIPAddressDnsSettings
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/api/PublicIPAddressDnsSettings.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/api/PublicIPAddressDnsSettings.java
    startLine: 12
  package: com.microsoft.azure.management.network.implementation.api
  summary: <p>Contains FQDN of the DNS record associated with the public IP address. </p>
  syntax: &o1
    content: public class PublicIPAddressDnsSettings
- uid: com.microsoft.azure.management.network.implementation.api._public_i_p_address_dns_settings_1ab68f21b89f3321dad2a1943ef9d0a1b7
  id: _public_i_p_address_dns_settings_1ab68f21b89f3321dad2a1943ef9d0a1b7
  parent: com.microsoft.azure.management.network.implementation.api._public_i_p_address_dns_settings
  href: com.microsoft.azure.management.network.implementation.api._public_i_p_address_dns_settings.yml
  langs:
  - java
  name: domainNameLabel()
  fullName: String com.microsoft.azure.management.network.implementation.api.PublicIPAddressDnsSettings.domainNameLabel()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/api/PublicIPAddressDnsSettings.java
    startLine: 42
  package: com.microsoft.azure.management.network.implementation.api
  summary: >-
    <p>Get the domainNameLabel value.</p>

    <p></p>
  syntax:
    content: public String domainNameLabel()
    return:
      type: "26831127"
      description: <p>the domainNameLabel value </p>
- uid: com.microsoft.azure.management.network.implementation.api._public_i_p_address_dns_settings_1aebbb3a6c6fc2b0b4dbf6ff3b57cd2d22
  id: _public_i_p_address_dns_settings_1aebbb3a6c6fc2b0b4dbf6ff3b57cd2d22
  parent: com.microsoft.azure.management.network.implementation.api._public_i_p_address_dns_settings
  href: com.microsoft.azure.management.network.implementation.api._public_i_p_address_dns_settings.yml
  langs:
  - java
  name: fqdn()
  fullName: String com.microsoft.azure.management.network.implementation.api.PublicIPAddressDnsSettings.fqdn()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/api/PublicIPAddressDnsSettings.java
    startLine: 62
  package: com.microsoft.azure.management.network.implementation.api
  summary: >-
    <p>Get the fqdn value.</p>

    <p></p>
  syntax:
    content: public String fqdn()
    return:
      type: "26831127"
      description: <p>the fqdn value </p>
- uid: com.microsoft.azure.management.network.implementation.api._public_i_p_address_dns_settings_1a4151acb60c6ff88c6cae77e39f3df963
  id: _public_i_p_address_dns_settings_1a4151acb60c6ff88c6cae77e39f3df963
  parent: com.microsoft.azure.management.network.implementation.api._public_i_p_address_dns_settings
  href: com.microsoft.azure.management.network.implementation.api._public_i_p_address_dns_settings.yml
  langs:
  - java
  name: reverseFqdn()
  fullName: String com.microsoft.azure.management.network.implementation.api.PublicIPAddressDnsSettings.reverseFqdn()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/api/PublicIPAddressDnsSettings.java
    startLine: 82
  package: com.microsoft.azure.management.network.implementation.api
  summary: >-
    <p>Get the reverseFqdn value.</p>

    <p></p>
  syntax:
    content: public String reverseFqdn()
    return:
      type: "26831127"
      description: <p>the reverseFqdn value </p>
- uid: com.microsoft.azure.management.network.implementation.api._public_i_p_address_dns_settings_1a9aeb71c33f053d6f3f4f7e8f38a3bf2b
  id: _public_i_p_address_dns_settings_1a9aeb71c33f053d6f3f4f7e8f38a3bf2b
  parent: com.microsoft.azure.management.network.implementation.api._public_i_p_address_dns_settings
  href: com.microsoft.azure.management.network.implementation.api._public_i_p_address_dns_settings.yml
  langs:
  - java
  name: withDomainNameLabel(String domainNameLabel)
  fullName: PublicIPAddressDnsSettings com.microsoft.azure.management.network.implementation.api.PublicIPAddressDnsSettings.withDomainNameLabel(String domainNameLabel)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/api/PublicIPAddressDnsSettings.java
    startLine: 52
  package: com.microsoft.azure.management.network.implementation.api
  summary: >-
    <p>Set the domainNameLabel value.</p>

    <p></p>
  syntax:
    content: public PublicIPAddressDnsSettings withDomainNameLabel(String domainNameLabel)
    parameters:
    - id: domainNameLabel
      type: "26831127"
      description: <p>the domainNameLabel value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation.api._public_i_p_address_dns_settings
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation.api._public_i_p_address_dns_settings" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network.implementation.api._public_i_p_address_dns_settings_1a32e803e434326ab1623197342bfef102
  id: _public_i_p_address_dns_settings_1a32e803e434326ab1623197342bfef102
  parent: com.microsoft.azure.management.network.implementation.api._public_i_p_address_dns_settings
  href: com.microsoft.azure.management.network.implementation.api._public_i_p_address_dns_settings.yml
  langs:
  - java
  name: withFqdn(String fqdn)
  fullName: PublicIPAddressDnsSettings com.microsoft.azure.management.network.implementation.api.PublicIPAddressDnsSettings.withFqdn(String fqdn)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/api/PublicIPAddressDnsSettings.java
    startLine: 72
  package: com.microsoft.azure.management.network.implementation.api
  summary: >-
    <p>Set the fqdn value.</p>

    <p></p>
  syntax:
    content: public PublicIPAddressDnsSettings withFqdn(String fqdn)
    parameters:
    - id: fqdn
      type: "26831127"
      description: <p>the fqdn value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation.api._public_i_p_address_dns_settings
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation.api._public_i_p_address_dns_settings" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network.implementation.api._public_i_p_address_dns_settings_1a3d3c850e00cf145a033e8d14b087cb8f
  id: _public_i_p_address_dns_settings_1a3d3c850e00cf145a033e8d14b087cb8f
  parent: com.microsoft.azure.management.network.implementation.api._public_i_p_address_dns_settings
  href: com.microsoft.azure.management.network.implementation.api._public_i_p_address_dns_settings.yml
  langs:
  - java
  name: withReverseFqdn(String reverseFqdn)
  fullName: PublicIPAddressDnsSettings com.microsoft.azure.management.network.implementation.api.PublicIPAddressDnsSettings.withReverseFqdn(String reverseFqdn)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/api/PublicIPAddressDnsSettings.java
    startLine: 92
  package: com.microsoft.azure.management.network.implementation.api
  summary: >-
    <p>Set the reverseFqdn value.</p>

    <p></p>
  syntax:
    content: public PublicIPAddressDnsSettings withReverseFqdn(String reverseFqdn)
    parameters:
    - id: reverseFqdn
      type: "26831127"
      description: <p>the reverseFqdn value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation.api._public_i_p_address_dns_settings
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation.api._public_i_p_address_dns_settings" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure._azure
  parent: com.microsoft.azure
  href: com.microsoft.azure._azure.yml
  name: Azure
  fullName: com.microsoft.azure.Azure
  type: Class
  summary: <p>The entry point for accessing resource management APIs in <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class Azure
- uid: com.microsoft.azure.management.network.implementation.api._public_i_p_address_dns_settings
  parent: com.microsoft.azure.management.network.implementation.api
  href: com.microsoft.azure.management.network.implementation.api._public_i_p_address_dns_settings.yml
  name: PublicIPAddressDnsSettings
  fullName: com.microsoft.azure.management.network.implementation.api.PublicIPAddressDnsSettings
  type: Class
  summary: <p>Contains FQDN of the DNS record associated with the public IP address. </p>
  syntax: *o1
