items:
- uid: com.microsoft.azure.management.compute._virtual_machine_scale_set_network_configuration
  id: _virtual_machine_scale_set_network_configuration
  parent: com.microsoft.azure.management.compute
  children:
  - com.microsoft.azure.management.compute._virtual_machine_scale_set_network_configuration_1aca9f0954207443730ea0f70245de469f
  - com.microsoft.azure.management.compute._virtual_machine_scale_set_network_configuration_1a8f646df43505f97f54f5521b194867af
  - com.microsoft.azure.management.compute._virtual_machine_scale_set_network_configuration_1a8081b072e622cb3f20ff55eb0b86951f
  - com.microsoft.azure.management.compute._virtual_machine_scale_set_network_configuration_1a5d845d7f85186e07789aa975b35d7718
  - com.microsoft.azure.management.compute._virtual_machine_scale_set_network_configuration_1a176dca4b56a8545cdb2a0c1ccaac0003
  - com.microsoft.azure.management.compute._virtual_machine_scale_set_network_configuration_1aabba2be6a806dbe2caedb2d18f8b23ad
  href: com.microsoft.azure.management.compute._virtual_machine_scale_set_network_configuration.yml
  langs:
  - java
  name: VirtualMachineScaleSetNetworkConfiguration
  fullName: com.microsoft.azure.management.compute.VirtualMachineScaleSetNetworkConfiguration
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineScaleSetNetworkConfiguration.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineScaleSetNetworkConfiguration.java
    startLine: 20
  package: com.microsoft.azure.management.compute
  summary: <p>Describes a virtual machine scale set network profile's network configurations. </p>
  syntax: &o1
    content: public class VirtualMachineScaleSetNetworkConfiguration extends SubResource
  inheritance:
  - java.lang.Object
  - com.microsoft.azure._sub_resource
  inheritedMembers:
  - com.microsoft.azure._sub_resource_1a92e02020e7fca6a3d2284bc1db599e52
  - com.microsoft.azure._sub_resource_1a522b0146c9247308f3752dd123100d8a
- uid: com.microsoft.azure.management.compute._virtual_machine_scale_set_network_configuration_1aca9f0954207443730ea0f70245de469f
  id: _virtual_machine_scale_set_network_configuration_1aca9f0954207443730ea0f70245de469f
  parent: com.microsoft.azure.management.compute._virtual_machine_scale_set_network_configuration
  href: com.microsoft.azure.management.compute._virtual_machine_scale_set_network_configuration.yml
  langs:
  - java
  name: ipConfigurations()
  fullName: List<VirtualMachineScaleSetIPConfiguration> com.microsoft.azure.management.compute.VirtualMachineScaleSetNetworkConfiguration.ipConfigurations()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineScaleSetNetworkConfiguration.java
    startLine: 84
  package: com.microsoft.azure.management.compute
  summary: >-
    <p>Get the ipConfigurations value.</p>

    <p></p>
  syntax:
    content: public List< VirtualMachineScaleSetIPConfiguration > ipConfigurations()
    return:
      type: f6a6204dcom.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration9ec3e006
      description: <p>the ipConfigurations value </p>
- uid: com.microsoft.azure.management.compute._virtual_machine_scale_set_network_configuration_1a8f646df43505f97f54f5521b194867af
  id: _virtual_machine_scale_set_network_configuration_1a8f646df43505f97f54f5521b194867af
  parent: com.microsoft.azure.management.compute._virtual_machine_scale_set_network_configuration
  href: com.microsoft.azure.management.compute._virtual_machine_scale_set_network_configuration.yml
  langs:
  - java
  name: name()
  fullName: String com.microsoft.azure.management.compute.VirtualMachineScaleSetNetworkConfiguration.name()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineScaleSetNetworkConfiguration.java
    startLine: 44
  package: com.microsoft.azure.management.compute
  summary: >-
    <p>Get the name value.</p>

    <p></p>
  syntax:
    content: public String name()
    return:
      type: "26831127"
      description: <p>the name value </p>
- uid: com.microsoft.azure.management.compute._virtual_machine_scale_set_network_configuration_1a8081b072e622cb3f20ff55eb0b86951f
  id: _virtual_machine_scale_set_network_configuration_1a8081b072e622cb3f20ff55eb0b86951f
  parent: com.microsoft.azure.management.compute._virtual_machine_scale_set_network_configuration
  href: com.microsoft.azure.management.compute._virtual_machine_scale_set_network_configuration.yml
  langs:
  - java
  name: primary()
  fullName: Boolean com.microsoft.azure.management.compute.VirtualMachineScaleSetNetworkConfiguration.primary()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineScaleSetNetworkConfiguration.java
    startLine: 64
  package: com.microsoft.azure.management.compute
  summary: >-
    <p>Get the primary value.</p>

    <p></p>
  syntax:
    content: public Boolean primary()
    return:
      type: 866c2227
      description: <p>the primary value </p>
- uid: com.microsoft.azure.management.compute._virtual_machine_scale_set_network_configuration_1a5d845d7f85186e07789aa975b35d7718
  id: _virtual_machine_scale_set_network_configuration_1a5d845d7f85186e07789aa975b35d7718
  parent: com.microsoft.azure.management.compute._virtual_machine_scale_set_network_configuration
  href: com.microsoft.azure.management.compute._virtual_machine_scale_set_network_configuration.yml
  langs:
  - java
  name: withIpConfigurations(List< VirtualMachineScaleSetIPConfiguration > ipConfigurations)
  fullName: VirtualMachineScaleSetNetworkConfiguration com.microsoft.azure.management.compute.VirtualMachineScaleSetNetworkConfiguration.withIpConfigurations(List< VirtualMachineScaleSetIPConfiguration > ipConfigurations)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineScaleSetNetworkConfiguration.java
    startLine: 94
  package: com.microsoft.azure.management.compute
  summary: >-
    <p>Set the ipConfigurations value.</p>

    <p></p>
  syntax:
    content: public VirtualMachineScaleSetNetworkConfiguration withIpConfigurations(List< VirtualMachineScaleSetIPConfiguration > ipConfigurations)
    parameters:
    - id: ipConfigurations
      type: f6a6204dcom.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration9ec3e006
      description: <p>the ipConfigurations value to set </p>
    return:
      type: com.microsoft.azure.management.compute._virtual_machine_scale_set_network_configuration
      description: <p>the <xref href="com.microsoft.azure.management.compute._virtual_machine_scale_set_network_configuration" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.compute._virtual_machine_scale_set_network_configuration_1a176dca4b56a8545cdb2a0c1ccaac0003
  id: _virtual_machine_scale_set_network_configuration_1a176dca4b56a8545cdb2a0c1ccaac0003
  parent: com.microsoft.azure.management.compute._virtual_machine_scale_set_network_configuration
  href: com.microsoft.azure.management.compute._virtual_machine_scale_set_network_configuration.yml
  langs:
  - java
  name: withName(String name)
  fullName: VirtualMachineScaleSetNetworkConfiguration com.microsoft.azure.management.compute.VirtualMachineScaleSetNetworkConfiguration.withName(String name)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineScaleSetNetworkConfiguration.java
    startLine: 54
  package: com.microsoft.azure.management.compute
  summary: >-
    <p>Set the name value.</p>

    <p></p>
  syntax:
    content: public VirtualMachineScaleSetNetworkConfiguration withName(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>the name value to set </p>
    return:
      type: com.microsoft.azure.management.compute._virtual_machine_scale_set_network_configuration
      description: <p>the <xref href="com.microsoft.azure.management.compute._virtual_machine_scale_set_network_configuration" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.compute._virtual_machine_scale_set_network_configuration_1aabba2be6a806dbe2caedb2d18f8b23ad
  id: _virtual_machine_scale_set_network_configuration_1aabba2be6a806dbe2caedb2d18f8b23ad
  parent: com.microsoft.azure.management.compute._virtual_machine_scale_set_network_configuration
  href: com.microsoft.azure.management.compute._virtual_machine_scale_set_network_configuration.yml
  langs:
  - java
  name: withPrimary(Boolean primary)
  fullName: VirtualMachineScaleSetNetworkConfiguration com.microsoft.azure.management.compute.VirtualMachineScaleSetNetworkConfiguration.withPrimary(Boolean primary)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineScaleSetNetworkConfiguration.java
    startLine: 74
  package: com.microsoft.azure.management.compute
  summary: >-
    <p>Set the primary value.</p>

    <p></p>
  syntax:
    content: public VirtualMachineScaleSetNetworkConfiguration withPrimary(Boolean primary)
    parameters:
    - id: primary
      type: 866c2227
      description: <p>the primary value to set </p>
    return:
      type: com.microsoft.azure.management.compute._virtual_machine_scale_set_network_configuration
      description: <p>the <xref href="com.microsoft.azure.management.compute._virtual_machine_scale_set_network_configuration" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 866c2227
  spec.java:
  - name: Boolean
    fullName: Boolean
- uid: f6a6204dcom.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration9ec3e006
  spec.java:
  - name: 'List< '
    fullName: 'List< '
  - uid: com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration
    name: VirtualMachineScaleSetIPConfiguration
    fullName: com.microsoft.azure.management.compute.VirtualMachineScaleSetIPConfiguration
    href: com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration.yml
  - name: ' >'
    fullName: ' >'
- uid: com.microsoft.azure._sub_resource_1a92e02020e7fca6a3d2284bc1db599e52
  parent: com.microsoft.azure._sub_resource
  href: com.microsoft.azure._sub_resource.yml
  name: id()
  fullName: String com.microsoft.azure.SubResource.id()
  type: Method
  summary: >-
    <p>Get the id value.</p>

    <p></p>
  syntax:
    content: public String id()
    return:
      type: "26831127"
      description: <p>the id value </p>
- uid: com.microsoft.azure._sub_resource_1a522b0146c9247308f3752dd123100d8a
  parent: com.microsoft.azure._sub_resource
  href: com.microsoft.azure._sub_resource.yml
  name: withId(String id)
  fullName: SubResource com.microsoft.azure.SubResource.withId(String id)
  type: Method
  summary: >-
    <p>Set the id value.</p>

    <p></p>
  syntax:
    content: public SubResource withId(String id)
    parameters:
    - id: id
      type: "26831127"
      description: <p>the id value to set </p>
    return:
      type: com.microsoft.azure._sub_resource
      description: <p>the sub resource itself </p>
- uid: com.microsoft.azure._sub_resource
  parent: com.microsoft.azure
  href: com.microsoft.azure._sub_resource.yml
  name: SubResource
  fullName: com.microsoft.azure.SubResource
  type: Class
  summary: <p>The <xref href="com.microsoft.azure._sub_resource" data-throw-if-not-resolved="false"></xref> model. </p>
  syntax:
    content: public class SubResource
- uid: com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration
  parent: com.microsoft.azure.management.compute
  href: com.microsoft.azure.management.compute._virtual_machine_scale_set_i_p_configuration.yml
  name: VirtualMachineScaleSetIPConfiguration
  fullName: com.microsoft.azure.management.compute.VirtualMachineScaleSetIPConfiguration
  type: Class
  summary: <p>Describes a virtual machine scale set network profile's IP configuration. </p>
  syntax:
    content: public class VirtualMachineScaleSetIPConfiguration extends SubResource
- uid: com.microsoft.azure.management.compute._virtual_machine_scale_set_network_configuration
  parent: com.microsoft.azure.management.compute
  href: com.microsoft.azure.management.compute._virtual_machine_scale_set_network_configuration.yml
  name: VirtualMachineScaleSetNetworkConfiguration
  fullName: com.microsoft.azure.management.compute.VirtualMachineScaleSetNetworkConfiguration
  type: Class
  summary: <p>Describes a virtual machine scale set network profile's network configurations. </p>
  syntax: *o1
