items:
- uid: com.microsoft.azure.management.website._hosting_environment_status
  id: _hosting_environment_status
  parent: com.microsoft.azure.management.website
  children:
  - com.microsoft.azure.management.website._hosting_environment_status_1a1512f042797919781aef6aadb32b7671
  - com.microsoft.azure.management.website._hosting_environment_status_1a8e9738ef13ca9ea16690f72a32290dbe
  - com.microsoft.azure.management.website._hosting_environment_status_1ac9256187b2cc443da15aa32f2b9b4483
  - com.microsoft.azure.management.website._hosting_environment_status_1a82cc554c1533ce5b35ccd08824751486
  - com.microsoft.azure.management.website._hosting_environment_status_1a46c5a49bdfbf99b9414a576320ffaacb
  - com.microsoft.azure.management.website._hosting_environment_status_1a0849137afcfaff9fab9fca25de118234
  - com.microsoft.azure.management.website._hosting_environment_status_1ab7cc3a5b5cd75c9db9d144c41411578e
  href: com.microsoft.azure.management.website._hosting_environment_status.yml
  langs:
  - java
  name: HostingEnvironmentStatus
  fullName: com.microsoft.azure.management.website.HostingEnvironmentStatus
  type: Enum
  source:
    remote: &o0
      path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/HostingEnvironmentStatus.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/HostingEnvironmentStatus.java
    startLine: 16
  package: com.microsoft.azure.management.website
  summary: <p>Defines values for <xref href="com.microsoft.azure.management.website._hosting_environment_status" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: &o1
    content: public enum HostingEnvironmentStatus
  inheritance:
  - java.lang.Object
  - java.lang.Enum<HostingEnvironmentStatus>
- uid: com.microsoft.azure.management.website._hosting_environment_status_1a1512f042797919781aef6aadb32b7671
  id: _hosting_environment_status_1a1512f042797919781aef6aadb32b7671
  parent: com.microsoft.azure.management.website._hosting_environment_status
  href: com.microsoft.azure.management.website._hosting_environment_status.yml
  langs:
  - java
  name: DELETING
  fullName: com.microsoft.azure.management.website.HostingEnvironmentStatus.DELETING
  type: Constructor
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/HostingEnvironmentStatus.java
    startLine: 27
  package: com.microsoft.azure.management.website
  summary: <p>Enum value Deleting. </p>
  syntax:
    content: public DELETING=("Deleting")
- uid: com.microsoft.azure.management.website._hosting_environment_status_1a8e9738ef13ca9ea16690f72a32290dbe
  id: _hosting_environment_status_1a8e9738ef13ca9ea16690f72a32290dbe
  parent: com.microsoft.azure.management.website._hosting_environment_status
  href: com.microsoft.azure.management.website._hosting_environment_status.yml
  langs:
  - java
  name: fromString(String value)
  fullName: static HostingEnvironmentStatus com.microsoft.azure.management.website.HostingEnvironmentStatus.fromString(String value)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/HostingEnvironmentStatus.java
    startLine: 43
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Parses a serialized value to a <xref href="com.microsoft.azure.management.website._hosting_environment_status" data-throw-if-not-resolved="false"></xref> instance.</p>

    <p></p>
  syntax:
    content: public static HostingEnvironmentStatus fromString(String value)
    parameters:
    - id: value
      type: "26831127"
      description: <p>the serialized value to parse. </p>
    return:
      type: com.microsoft.azure.management.website._hosting_environment_status
      description: <p>the parsed <xref href="com.microsoft.azure.management.website._hosting_environment_status" data-throw-if-not-resolved="false"></xref> object, or null if unable to parse. </p>
- uid: com.microsoft.azure.management.website._hosting_environment_status_1ac9256187b2cc443da15aa32f2b9b4483
  id: _hosting_environment_status_1ac9256187b2cc443da15aa32f2b9b4483
  parent: com.microsoft.azure.management.website._hosting_environment_status
  href: com.microsoft.azure.management.website._hosting_environment_status.yml
  langs:
  - java
  name: HostingEnvironmentStatus(String value)
  fullName: com.microsoft.azure.management.website.HostingEnvironmentStatus.HostingEnvironmentStatus(String value)
  type: Constructor
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/HostingEnvironmentStatus.java
    startLine: 32
  package: com.microsoft.azure.management.website
  syntax:
    content: public HostingEnvironmentStatus(String value)
    parameters:
    - id: value
      type: "26831127"
- uid: com.microsoft.azure.management.website._hosting_environment_status_1a82cc554c1533ce5b35ccd08824751486
  id: _hosting_environment_status_1a82cc554c1533ce5b35ccd08824751486
  parent: com.microsoft.azure.management.website._hosting_environment_status
  href: com.microsoft.azure.management.website._hosting_environment_status.yml
  langs:
  - java
  name: PREPARING
  fullName: com.microsoft.azure.management.website.HostingEnvironmentStatus.PREPARING
  type: Constructor
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/HostingEnvironmentStatus.java
    startLine: 18
  package: com.microsoft.azure.management.website
  summary: <p>Enum value Preparing. </p>
  syntax:
    content: public PREPARING=("Preparing")
- uid: com.microsoft.azure.management.website._hosting_environment_status_1a46c5a49bdfbf99b9414a576320ffaacb
  id: _hosting_environment_status_1a46c5a49bdfbf99b9414a576320ffaacb
  parent: com.microsoft.azure.management.website._hosting_environment_status
  href: com.microsoft.azure.management.website._hosting_environment_status.yml
  langs:
  - java
  name: READY
  fullName: com.microsoft.azure.management.website.HostingEnvironmentStatus.READY
  type: Constructor
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/HostingEnvironmentStatus.java
    startLine: 21
  package: com.microsoft.azure.management.website
  summary: <p>Enum value Ready. </p>
  syntax:
    content: public READY=("Ready")
- uid: com.microsoft.azure.management.website._hosting_environment_status_1a0849137afcfaff9fab9fca25de118234
  id: _hosting_environment_status_1a0849137afcfaff9fab9fca25de118234
  parent: com.microsoft.azure.management.website._hosting_environment_status
  href: com.microsoft.azure.management.website._hosting_environment_status.yml
  langs:
  - java
  name: SCALING
  fullName: com.microsoft.azure.management.website.HostingEnvironmentStatus.SCALING
  type: Constructor
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/HostingEnvironmentStatus.java
    startLine: 24
  package: com.microsoft.azure.management.website
  summary: <p>Enum value Scaling. </p>
  syntax:
    content: public SCALING=("Scaling")
- uid: com.microsoft.azure.management.website._hosting_environment_status_1ab7cc3a5b5cd75c9db9d144c41411578e
  id: _hosting_environment_status_1ab7cc3a5b5cd75c9db9d144c41411578e
  parent: com.microsoft.azure.management.website._hosting_environment_status
  href: com.microsoft.azure.management.website._hosting_environment_status.yml
  langs:
  - java
  name: toString()
  fullName: String com.microsoft.azure.management.website.HostingEnvironmentStatus.toString()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/HostingEnvironmentStatus.java
    startLine: 55
  package: com.microsoft.azure.management.website
  syntax:
    content: public String toString()
    return:
      type: "26831127"
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.management.website._hosting_environment_status
  parent: com.microsoft.azure.management.website
  href: com.microsoft.azure.management.website._hosting_environment_status.yml
  name: HostingEnvironmentStatus
  fullName: com.microsoft.azure.management.website.HostingEnvironmentStatus
  type: Enum
  summary: <p>Defines values for <xref href="com.microsoft.azure.management.website._hosting_environment_status" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: *o1
