items:
- uid: com.microsoft.azure.management.network._network_interface_dns_settings
  id: _network_interface_dns_settings
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._network_interface_dns_settings_1a8bc8dbda1252b39ab8a8391e1cde2151
  - com.microsoft.azure.management.network._network_interface_dns_settings_1a45625f996306edacb749d7e6400e4ae8
  - com.microsoft.azure.management.network._network_interface_dns_settings_1a86f8988db05c77fd3b35fe773ad50fcc
  - com.microsoft.azure.management.network._network_interface_dns_settings_1ac29a024507effaafcf06eabcf2de254a
  - com.microsoft.azure.management.network._network_interface_dns_settings_1aca4de2d3e7a64e45a26c20e5149e18fd
  - com.microsoft.azure.management.network._network_interface_dns_settings_1ab91f17826233441ccfe365b6b68fc1ca
  - com.microsoft.azure.management.network._network_interface_dns_settings_1a24aa55ee76891c584c48d8863a615a42
  - com.microsoft.azure.management.network._network_interface_dns_settings_1abfc29b492ffa25e3eed4094bb49488c7
  - com.microsoft.azure.management.network._network_interface_dns_settings_1a809ca84ad92096fd68ace485859797f0
  - com.microsoft.azure.management.network._network_interface_dns_settings_1ab2c7340250a6723516843585aeb953a7
  href: com.microsoft.azure.management.network._network_interface_dns_settings.yml
  langs:
  - java
  name: NetworkInterfaceDnsSettings
  fullName: com.microsoft.azure.management.network.NetworkInterfaceDnsSettings
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NetworkInterfaceDnsSettings.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NetworkInterfaceDnsSettings.java
    startLine: 15
  package: com.microsoft.azure.management.network
  summary: <p>Dns settings of a network interface. </p>
  syntax: &o1
    content: public class NetworkInterfaceDnsSettings
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.network._network_interface_dns_settings_1a8bc8dbda1252b39ab8a8391e1cde2151
  id: _network_interface_dns_settings_1a8bc8dbda1252b39ab8a8391e1cde2151
  parent: com.microsoft.azure.management.network._network_interface_dns_settings
  href: com.microsoft.azure.management.network._network_interface_dns_settings.yml
  langs:
  - java
  name: appliedDnsServers()
  fullName: List<String> com.microsoft.azure.management.network.NetworkInterfaceDnsSettings.appliedDnsServers()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NetworkInterfaceDnsSettings.java
    startLine: 66
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the appliedDnsServers value.</p>

    <p></p>
  syntax:
    content: public List< String > appliedDnsServers()
    return:
      type: f35af49b
      description: <p>the appliedDnsServers value </p>
- uid: com.microsoft.azure.management.network._network_interface_dns_settings_1a45625f996306edacb749d7e6400e4ae8
  id: _network_interface_dns_settings_1a45625f996306edacb749d7e6400e4ae8
  parent: com.microsoft.azure.management.network._network_interface_dns_settings
  href: com.microsoft.azure.management.network._network_interface_dns_settings.yml
  langs:
  - java
  name: dnsServers()
  fullName: List<String> com.microsoft.azure.management.network.NetworkInterfaceDnsSettings.dnsServers()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NetworkInterfaceDnsSettings.java
    startLine: 46
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the dnsServers value.</p>

    <p></p>
  syntax:
    content: public List< String > dnsServers()
    return:
      type: f35af49b
      description: <p>the dnsServers value </p>
- uid: com.microsoft.azure.management.network._network_interface_dns_settings_1a86f8988db05c77fd3b35fe773ad50fcc
  id: _network_interface_dns_settings_1a86f8988db05c77fd3b35fe773ad50fcc
  parent: com.microsoft.azure.management.network._network_interface_dns_settings
  href: com.microsoft.azure.management.network._network_interface_dns_settings.yml
  langs:
  - java
  name: internalDnsNameLabel()
  fullName: String com.microsoft.azure.management.network.NetworkInterfaceDnsSettings.internalDnsNameLabel()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NetworkInterfaceDnsSettings.java
    startLine: 86
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the internalDnsNameLabel value.</p>

    <p></p>
  syntax:
    content: public String internalDnsNameLabel()
    return:
      type: "26831127"
      description: <p>the internalDnsNameLabel value </p>
- uid: com.microsoft.azure.management.network._network_interface_dns_settings_1ac29a024507effaafcf06eabcf2de254a
  id: _network_interface_dns_settings_1ac29a024507effaafcf06eabcf2de254a
  parent: com.microsoft.azure.management.network._network_interface_dns_settings
  href: com.microsoft.azure.management.network._network_interface_dns_settings.yml
  langs:
  - java
  name: internalDomainNameSuffix()
  fullName: String com.microsoft.azure.management.network.NetworkInterfaceDnsSettings.internalDomainNameSuffix()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NetworkInterfaceDnsSettings.java
    startLine: 126
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the internalDomainNameSuffix value.</p>

    <p></p>
  syntax:
    content: public String internalDomainNameSuffix()
    return:
      type: "26831127"
      description: <p>the internalDomainNameSuffix value </p>
- uid: com.microsoft.azure.management.network._network_interface_dns_settings_1aca4de2d3e7a64e45a26c20e5149e18fd
  id: _network_interface_dns_settings_1aca4de2d3e7a64e45a26c20e5149e18fd
  parent: com.microsoft.azure.management.network._network_interface_dns_settings
  href: com.microsoft.azure.management.network._network_interface_dns_settings.yml
  langs:
  - java
  name: internalFqdn()
  fullName: String com.microsoft.azure.management.network.NetworkInterfaceDnsSettings.internalFqdn()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NetworkInterfaceDnsSettings.java
    startLine: 106
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the internalFqdn value.</p>

    <p></p>
  syntax:
    content: public String internalFqdn()
    return:
      type: "26831127"
      description: <p>the internalFqdn value </p>
- uid: com.microsoft.azure.management.network._network_interface_dns_settings_1ab91f17826233441ccfe365b6b68fc1ca
  id: _network_interface_dns_settings_1ab91f17826233441ccfe365b6b68fc1ca
  parent: com.microsoft.azure.management.network._network_interface_dns_settings
  href: com.microsoft.azure.management.network._network_interface_dns_settings.yml
  langs:
  - java
  name: withAppliedDnsServers(List< String > appliedDnsServers)
  fullName: NetworkInterfaceDnsSettings com.microsoft.azure.management.network.NetworkInterfaceDnsSettings.withAppliedDnsServers(List< String > appliedDnsServers)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NetworkInterfaceDnsSettings.java
    startLine: 76
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the appliedDnsServers value.</p>

    <p></p>
  syntax:
    content: public NetworkInterfaceDnsSettings withAppliedDnsServers(List< String > appliedDnsServers)
    parameters:
    - id: appliedDnsServers
      type: f35af49b
      description: <p>the appliedDnsServers value to set </p>
    return:
      type: com.microsoft.azure.management.network._network_interface_dns_settings
      description: <p>the <xref href="com.microsoft.azure.management.network._network_interface_dns_settings" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network._network_interface_dns_settings_1a24aa55ee76891c584c48d8863a615a42
  id: _network_interface_dns_settings_1a24aa55ee76891c584c48d8863a615a42
  parent: com.microsoft.azure.management.network._network_interface_dns_settings
  href: com.microsoft.azure.management.network._network_interface_dns_settings.yml
  langs:
  - java
  name: withDnsServers(List< String > dnsServers)
  fullName: NetworkInterfaceDnsSettings com.microsoft.azure.management.network.NetworkInterfaceDnsSettings.withDnsServers(List< String > dnsServers)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NetworkInterfaceDnsSettings.java
    startLine: 56
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the dnsServers value.</p>

    <p></p>
  syntax:
    content: public NetworkInterfaceDnsSettings withDnsServers(List< String > dnsServers)
    parameters:
    - id: dnsServers
      type: f35af49b
      description: <p>the dnsServers value to set </p>
    return:
      type: com.microsoft.azure.management.network._network_interface_dns_settings
      description: <p>the <xref href="com.microsoft.azure.management.network._network_interface_dns_settings" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network._network_interface_dns_settings_1abfc29b492ffa25e3eed4094bb49488c7
  id: _network_interface_dns_settings_1abfc29b492ffa25e3eed4094bb49488c7
  parent: com.microsoft.azure.management.network._network_interface_dns_settings
  href: com.microsoft.azure.management.network._network_interface_dns_settings.yml
  langs:
  - java
  name: withInternalDnsNameLabel(String internalDnsNameLabel)
  fullName: NetworkInterfaceDnsSettings com.microsoft.azure.management.network.NetworkInterfaceDnsSettings.withInternalDnsNameLabel(String internalDnsNameLabel)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NetworkInterfaceDnsSettings.java
    startLine: 96
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the internalDnsNameLabel value.</p>

    <p></p>
  syntax:
    content: public NetworkInterfaceDnsSettings withInternalDnsNameLabel(String internalDnsNameLabel)
    parameters:
    - id: internalDnsNameLabel
      type: "26831127"
      description: <p>the internalDnsNameLabel value to set </p>
    return:
      type: com.microsoft.azure.management.network._network_interface_dns_settings
      description: <p>the <xref href="com.microsoft.azure.management.network._network_interface_dns_settings" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network._network_interface_dns_settings_1a809ca84ad92096fd68ace485859797f0
  id: _network_interface_dns_settings_1a809ca84ad92096fd68ace485859797f0
  parent: com.microsoft.azure.management.network._network_interface_dns_settings
  href: com.microsoft.azure.management.network._network_interface_dns_settings.yml
  langs:
  - java
  name: withInternalDomainNameSuffix(String internalDomainNameSuffix)
  fullName: NetworkInterfaceDnsSettings com.microsoft.azure.management.network.NetworkInterfaceDnsSettings.withInternalDomainNameSuffix(String internalDomainNameSuffix)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NetworkInterfaceDnsSettings.java
    startLine: 136
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the internalDomainNameSuffix value.</p>

    <p></p>
  syntax:
    content: public NetworkInterfaceDnsSettings withInternalDomainNameSuffix(String internalDomainNameSuffix)
    parameters:
    - id: internalDomainNameSuffix
      type: "26831127"
      description: <p>the internalDomainNameSuffix value to set </p>
    return:
      type: com.microsoft.azure.management.network._network_interface_dns_settings
      description: <p>the <xref href="com.microsoft.azure.management.network._network_interface_dns_settings" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network._network_interface_dns_settings_1ab2c7340250a6723516843585aeb953a7
  id: _network_interface_dns_settings_1ab2c7340250a6723516843585aeb953a7
  parent: com.microsoft.azure.management.network._network_interface_dns_settings
  href: com.microsoft.azure.management.network._network_interface_dns_settings.yml
  langs:
  - java
  name: withInternalFqdn(String internalFqdn)
  fullName: NetworkInterfaceDnsSettings com.microsoft.azure.management.network.NetworkInterfaceDnsSettings.withInternalFqdn(String internalFqdn)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NetworkInterfaceDnsSettings.java
    startLine: 116
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the internalFqdn value.</p>

    <p></p>
  syntax:
    content: public NetworkInterfaceDnsSettings withInternalFqdn(String internalFqdn)
    parameters:
    - id: internalFqdn
      type: "26831127"
      description: <p>the internalFqdn value to set </p>
    return:
      type: com.microsoft.azure.management.network._network_interface_dns_settings
      description: <p>the <xref href="com.microsoft.azure.management.network._network_interface_dns_settings" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: f35af49b
  spec.java:
  - name: List< String >
    fullName: List< String >
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.management.network._network_interface_dns_settings
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._network_interface_dns_settings.yml
  name: NetworkInterfaceDnsSettings
  fullName: com.microsoft.azure.management.network.NetworkInterfaceDnsSettings
  type: Class
  summary: <p>Dns settings of a network interface. </p>
  syntax: *o1
