items:
- uid: com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._with_private_ip
  id: _with_private_ip
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._with_private_ip_1abcd818c7d38c16ad0ca295f31ec2cb22
  - com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._with_private_ip_1acdeda1d77ff9936ce36d0b7f2677dbde
  href: com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._with_private_ip.yml
  langs:
  - java
  name: NicIpConfiguration.DefinitionStages.WithPrivateIp<ParentT>
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.DefinitionStages.WithPrivateIp<ParentT>
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
    startLine: 149
  package: com.microsoft.azure.management.network
  summary: >-
    <p>The stage of the network interface IP configuration definition allowing to specify private IP address within a virtual network subnet.</p>

    <p></p>
  syntax:
    content: public interface WithPrivateIp<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable_1a92836b66fb83b831c1470a093c42d42d" data-throw-if-not-resolved="false"></xref></p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._with_private_ip_1abcd818c7d38c16ad0ca295f31ec2cb22
  id: _with_private_ip_1abcd818c7d38c16ad0ca295f31ec2cb22
  parent: com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._with_private_ip
  href: com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._with_private_ip.yml
  langs:
  - java
  name: withPrivateIpAddressDynamic()
  fullName: WithAttach<ParentT> com.microsoft.azure.management.network.NicIpConfiguration.DefinitionStages.WithPrivateIp< ParentT >.withPrivateIpAddressDynamic()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
    startLine: 156
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Enables dynamic private IP address allocation within the specified existing virtual network subnet for the network interface IP configuration.</p>

    <p></p>
  syntax:
    content: public WithAttach< ParentT > withPrivateIpAddressDynamic()
    return:
      type: com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._with_attacha6da57ba
      description: <p>the next stage of network interface IP configuration definition </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._with_private_ip_1acdeda1d77ff9936ce36d0b7f2677dbde
  id: _with_private_ip_1acdeda1d77ff9936ce36d0b7f2677dbde
  parent: com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._with_private_ip
  href: com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._with_private_ip.yml
  langs:
  - java
  name: withPrivateIpAddressStatic(String staticPrivateIpAddress)
  fullName: WithAttach<ParentT> com.microsoft.azure.management.network.NicIpConfiguration.DefinitionStages.WithPrivateIp< ParentT >.withPrivateIpAddressStatic(String staticPrivateIpAddress)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
    startLine: 166
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Assigns the specified static private IP address within the specified existing virtual network subnet to the network interface IP configuration.</p>

    <p></p>
  syntax:
    content: public WithAttach< ParentT > withPrivateIpAddressStatic(String staticPrivateIpAddress)
    parameters:
    - id: staticPrivateIpAddress
      type: "26831127"
      description: <p>the static IP address within the specified subnet to assign to the network interface </p>
    return:
      type: com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._with_attacha6da57ba
      description: <p>the next stage of network interface IP configuration definition </p>
references:
- uid: 18a275b1
  spec.java:
  - name: ParentT
    fullName: ParentT
- uid: com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._with_attacha6da57ba
  spec.java:
  - uid: com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._with_attach
    name: NicIpConfiguration.DefinitionStages.WithAttach<ParentT>
    fullName: com.microsoft.azure.management.network.NicIpConfiguration.DefinitionStages.WithAttach<ParentT>
    href: com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._with_attach.yml
  - name: < ParentT >
    fullName: < ParentT >
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.management.network._nic_ip_configuration._definition
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._nic_ip_configuration._definition.yml
  name: NicIpConfiguration.Definition<ParentT>
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.Definition<ParentT>
  type: Interface
  summary: <p>The entirety of the network interface IP configuration definition. </p>
  syntax:
    content: public interface Definition<ParentT> extends NicIpConfiguration.DefinitionStages.Blank< ParentT >,NicIpConfiguration.DefinitionStages.WithAttach< ParentT >,NicIpConfiguration.DefinitionStages.WithNetwork< ParentT >,NicIpConfiguration.DefinitionStages.WithSubnet< ParentT >,NicIpConfiguration.DefinitionStages.WithPrivateIp< ParentT >
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable_1a92836b66fb83b831c1470a093c42d42d" data-throw-if-not-resolved="false"></xref></p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._with_attach
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._with_attach.yml
  name: NicIpConfiguration.DefinitionStages.WithAttach<ParentT>
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.DefinitionStages.WithAttach<ParentT>
  type: Interface
  summary: >-
    <p>The final stage of network interface IP configuration. </p>

    <p>At this stage, any remaining optional settings can be specified, or the network interface IP configuration definition can be attached to the parent network interface definition using <ref refid="" kindref="compound">WithAttach#attach()</ref>.</p>

    <p></p>
  syntax:
    content: public interface WithAttach<ParentT> extends Attachable< ParentT >.InDefinition,NicIpConfiguration.DefinitionStages.WithPublicIpAddress< ParentT >
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable_1a92836b66fb83b831c1470a093c42d42d" data-throw-if-not-resolved="false"></xref></p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._attachable_1a92836b66fb83b831c1470a093c42d42d
  parent: com.microsoft.azure.management.resources.fluentcore.model._attachable
  href: com.microsoft.azure.management.resources.fluentcore.model._attachable.yml
  name: attach()
  fullName: ParentT com.microsoft.azure.management.resources.fluentcore.model.Attachable< ParentT >.attach()
  type: Method
  summary: <p>Attaches this child object's definition to its parent's definition. </p>
  syntax:
    content: public ParentT attach()
    return:
      type: 18a275b1
      description: <p>the next stage of the parent object's definition </p>
