items:
- uid: com.microsoft.azure.management.network.implementation.api._application_gateway_operational_state
  id: _application_gateway_operational_state
  parent: com.microsoft.azure.management.network.implementation.api
  children:
  - com.microsoft.azure.management.network.implementation.api._application_gateway_operational_state_1a34b8fea0868c3790e3d4b91b090669f5
  - com.microsoft.azure.management.network.implementation.api._application_gateway_operational_state_1ae5f200122e5b8e56cecf613e8bacb7ec
  - com.microsoft.azure.management.network.implementation.api._application_gateway_operational_state_1a12d6701e10f3c05d3e115dffd28a9941
  - com.microsoft.azure.management.network.implementation.api._application_gateway_operational_state_1a86fc5cbf483b62eda15159dda9d2e2a1
  href: com.microsoft.azure.management.network.implementation.api._application_gateway_operational_state.yml
  langs:
  - java
  name: ApplicationGatewayOperationalState
  fullName: com.microsoft.azure.management.network.implementation.api.ApplicationGatewayOperationalState
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/api/ApplicationGatewayOperationalState.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/api/ApplicationGatewayOperationalState.java
    startLine: 11
  assemblies:
  - com.microsoft.azure.management.network.implementation.api
  package: com.microsoft.azure.management.network.implementation.api
  summary: <p>Defines values for <xref href="com.microsoft.azure.management.network.implementation.api._application_gateway_operational_state" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: &o1
    content: public class ApplicationGatewayOperationalState
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.network.implementation.api._application_gateway_operational_state_1a34b8fea0868c3790e3d4b91b090669f5
  id: _application_gateway_operational_state_1a34b8fea0868c3790e3d4b91b090669f5
  parent: com.microsoft.azure.management.network.implementation.api._application_gateway_operational_state
  href: com.microsoft.azure.management.network.implementation.api._application_gateway_operational_state.yml
  langs:
  - java
  name: RUNNING
  fullName: final String com.microsoft.azure.management.network.implementation.api.ApplicationGatewayOperationalState.RUNNING
  type: Field
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/api/ApplicationGatewayOperationalState.java
    startLine: 19
  assemblies:
  - com.microsoft.azure.management.network.implementation.api
  package: com.microsoft.azure.management.network.implementation.api
  summary: <p>Static value Running for <xref href="com.microsoft.azure.management.network.implementation.api._application_gateway_operational_state" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public static final String RUNNING= "Running"
    return:
      type: 3d93591e
- uid: com.microsoft.azure.management.network.implementation.api._application_gateway_operational_state_1ae5f200122e5b8e56cecf613e8bacb7ec
  id: _application_gateway_operational_state_1ae5f200122e5b8e56cecf613e8bacb7ec
  parent: com.microsoft.azure.management.network.implementation.api._application_gateway_operational_state
  href: com.microsoft.azure.management.network.implementation.api._application_gateway_operational_state.yml
  langs:
  - java
  name: STARTING
  fullName: final String com.microsoft.azure.management.network.implementation.api.ApplicationGatewayOperationalState.STARTING
  type: Field
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/api/ApplicationGatewayOperationalState.java
    startLine: 16
  assemblies:
  - com.microsoft.azure.management.network.implementation.api
  package: com.microsoft.azure.management.network.implementation.api
  summary: <p>Static value Starting for <xref href="com.microsoft.azure.management.network.implementation.api._application_gateway_operational_state" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public static final String STARTING= "Starting"
    return:
      type: 3d93591e
- uid: com.microsoft.azure.management.network.implementation.api._application_gateway_operational_state_1a12d6701e10f3c05d3e115dffd28a9941
  id: _application_gateway_operational_state_1a12d6701e10f3c05d3e115dffd28a9941
  parent: com.microsoft.azure.management.network.implementation.api._application_gateway_operational_state
  href: com.microsoft.azure.management.network.implementation.api._application_gateway_operational_state.yml
  langs:
  - java
  name: STOPPED
  fullName: final String com.microsoft.azure.management.network.implementation.api.ApplicationGatewayOperationalState.STOPPED
  type: Field
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/api/ApplicationGatewayOperationalState.java
    startLine: 13
  assemblies:
  - com.microsoft.azure.management.network.implementation.api
  package: com.microsoft.azure.management.network.implementation.api
  summary: <p>Static value Stopped for <xref href="com.microsoft.azure.management.network.implementation.api._application_gateway_operational_state" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public static final String STOPPED= "Stopped"
    return:
      type: 3d93591e
- uid: com.microsoft.azure.management.network.implementation.api._application_gateway_operational_state_1a86fc5cbf483b62eda15159dda9d2e2a1
  id: _application_gateway_operational_state_1a86fc5cbf483b62eda15159dda9d2e2a1
  parent: com.microsoft.azure.management.network.implementation.api._application_gateway_operational_state
  href: com.microsoft.azure.management.network.implementation.api._application_gateway_operational_state.yml
  langs:
  - java
  name: STOPPING
  fullName: final String com.microsoft.azure.management.network.implementation.api.ApplicationGatewayOperationalState.STOPPING
  type: Field
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/api/ApplicationGatewayOperationalState.java
    startLine: 22
  assemblies:
  - com.microsoft.azure.management.network.implementation.api
  package: com.microsoft.azure.management.network.implementation.api
  summary: <p>Static value Stopping for <xref href="com.microsoft.azure.management.network.implementation.api._application_gateway_operational_state" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public static final String STOPPING= "Stopping"
    return:
      type: 3d93591e
references:
- uid: 3d93591e
  spec.java:
  - name: final String
    fullName: final String
- uid: com.microsoft.azure.management.network.implementation.api._application_gateway_operational_state
  parent: com.microsoft.azure.management.network.implementation.api
  href: com.microsoft.azure.management.network.implementation.api._application_gateway_operational_state.yml
  name: ApplicationGatewayOperationalState
  fullName: com.microsoft.azure.management.network.implementation.api.ApplicationGatewayOperationalState
  type: Class
  summary: <p>Defines values for <xref href="com.microsoft.azure.management.network.implementation.api._application_gateway_operational_state" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: *o1
