items:
- uid: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_result
  id: _compute_node_get_remote_login_settings_result
  parent: com.microsoft.azure.batch.protocol.models
  children:
  - com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_result.remoteLoginIPAddress()
  - com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_result.remoteLoginPort()
  - com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_result.withRemoteLoginIPAddress(String)
  - com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_result.withRemoteLoginPort(int)
  href: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_result.yml
  langs:
  - java
  name: ComputeNodeGetRemoteLoginSettingsResult
  fullName: com.microsoft.azure.batch.protocol.models.ComputeNodeGetRemoteLoginSettingsResult
  type: Class
  source:
    remote: &o0
      path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ComputeNodeGetRemoteLoginSettingsResult.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ComputeNodeGetRemoteLoginSettingsResult.java
    startLine: 15
  package: com.microsoft.azure.batch.protocol.models
  summary: <p>Response to a ComputeNodeOperation.GetRemoteLoginSettings request. </p>
  syntax: &o1
    content: public class ComputeNodeGetRemoteLoginSettingsResult
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_result.remoteLoginIPAddress()
  id: remoteLoginIPAddress()
  parent: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_result
  href: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_result.yml
  langs:
  - java
  name: remoteLoginIPAddress()
  fullName: String com.microsoft.azure.batch.protocol.models.ComputeNodeGetRemoteLoginSettingsResult.remoteLoginIPAddress()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ComputeNodeGetRemoteLoginSettingsResult.java
    startLine: 33
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the remoteLoginIPAddress value.</p>

    <p></p>
  syntax:
    content: public String remoteLoginIPAddress()
    return:
      type: "26831127"
      description: <p>the remoteLoginIPAddress value </p>
- uid: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_result.remoteLoginPort()
  id: remoteLoginPort()
  parent: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_result
  href: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_result.yml
  langs:
  - java
  name: remoteLoginPort()
  fullName: int com.microsoft.azure.batch.protocol.models.ComputeNodeGetRemoteLoginSettingsResult.remoteLoginPort()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ComputeNodeGetRemoteLoginSettingsResult.java
    startLine: 53
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the remoteLoginPort value.</p>

    <p></p>
  syntax:
    content: public int remoteLoginPort()
    return:
      type: f75371fa
      description: <p>the remoteLoginPort value </p>
- uid: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_result.withRemoteLoginIPAddress(String)
  id: withRemoteLoginIPAddress(String)
  parent: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_result
  href: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_result.yml
  langs:
  - java
  name: withRemoteLoginIPAddress(String remoteLoginIPAddress)
  fullName: ComputeNodeGetRemoteLoginSettingsResult com.microsoft.azure.batch.protocol.models.ComputeNodeGetRemoteLoginSettingsResult.withRemoteLoginIPAddress(String remoteLoginIPAddress)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ComputeNodeGetRemoteLoginSettingsResult.java
    startLine: 43
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the remoteLoginIPAddress value.</p>

    <p></p>
  syntax:
    content: public ComputeNodeGetRemoteLoginSettingsResult withRemoteLoginIPAddress(String remoteLoginIPAddress)
    parameters:
    - id: remoteLoginIPAddress
      type: "26831127"
      description: <p>the remoteLoginIPAddress value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_result
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_result" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_result.withRemoteLoginPort(int)
  id: withRemoteLoginPort(int)
  parent: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_result
  href: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_result.yml
  langs:
  - java
  name: withRemoteLoginPort(int remoteLoginPort)
  fullName: ComputeNodeGetRemoteLoginSettingsResult com.microsoft.azure.batch.protocol.models.ComputeNodeGetRemoteLoginSettingsResult.withRemoteLoginPort(int remoteLoginPort)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/ComputeNodeGetRemoteLoginSettingsResult.java
    startLine: 63
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the remoteLoginPort value.</p>

    <p></p>
  syntax:
    content: public ComputeNodeGetRemoteLoginSettingsResult withRemoteLoginPort(int remoteLoginPort)
    parameters:
    - id: remoteLoginPort
      type: f75371fa
      description: <p>the remoteLoginPort value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_result
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_result" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
- uid: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_result
  parent: com.microsoft.azure.batch.protocol.models
  href: com.microsoft.azure.batch.protocol.models._compute_node_get_remote_login_settings_result.yml
  name: ComputeNodeGetRemoteLoginSettingsResult
  fullName: com.microsoft.azure.batch.protocol.models.ComputeNodeGetRemoteLoginSettingsResult
  type: Class
  summary: <p>Response to a ComputeNodeOperation.GetRemoteLoginSettings request. </p>
  syntax: *o1
