items:
- uid: com.microsoft.azure.management.resources._deployment._update
  id: _update
  parent: com.microsoft.azure.management.resources
  href: com.microsoft.azure.management.resources._deployment._update.yml
  langs:
  - java
  name: Deployment.Update
  fullName: com.microsoft.azure.management.resources.Deployment.Update
  type: Interface
  source:
    remote:
      path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/Deployment.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/Deployment.java
    startLine: 304
  package: com.microsoft.azure.management.resources
  summary: >-
    <p>The template for a deployment update operation, containing all the settings that can be modified. </p>

    <p>Call <xref href="com.microsoft.azure.management.resources.fluentcore.model._appliable_1a644f6f9ad9fb815ebc68becb7a5e3406" data-throw-if-not-resolved="false"></xref> to apply the changes to the deployment in <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public interface Update
  inheritance:
  - com.microsoft.azure.management.resources.fluentcore.model._indexable
  - com.microsoft.azure.management.resources.fluentcore.model._appliable
  inheritedMembers:
  - com.microsoft.azure.management.resources.fluentcore.model._appliable_1a644f6f9ad9fb815ebc68becb7a5e3406
  - com.microsoft.azure.management.resources.fluentcore.model._appliable_1a614b76a85ab8e27c82a680c826e7c293
  - com.microsoft.azure.management.resources.fluentcore.model._indexable_1ab0ae133d20d97eaee0480795ee886bde
  - com.microsoft.azure.management.resources._deployment._update_with_deployment_mode_1a56ad4627c4e0edfccecc1343a77ca693
  - com.microsoft.azure.management.resources._deployment._update_with_parameters_1a87f612519aac2c0a47661f65fca84a4c
  - com.microsoft.azure.management.resources._deployment._update_with_parameters_1a9ba178b4c0ca8bfc0a21c15217160eac
  - com.microsoft.azure.management.resources._deployment._update_with_parameters_1abf6c5a5a8b5f654c3755719e508aa5db
  - com.microsoft.azure.management.resources._deployment._update_with_template_1a8cd6131f5db065b088be9baadcc88865
  - com.microsoft.azure.management.resources._deployment._update_with_template_1ae08dc79cd1d04e7c78e7d576a653a536
  - com.microsoft.azure.management.resources._deployment._update_with_template_1abbccad4dfdf15d9fda7d32e65d0965ad
references:
- uid: com.microsoft.azure.management.resources.fluentcore.model._appliable_1a644f6f9ad9fb815ebc68becb7a5e3406
  parent: com.microsoft.azure.management.resources.fluentcore.model._appliable
  href: com.microsoft.azure.management.resources.fluentcore.model._appliable.yml
  name: apply()
  fullName: T com.microsoft.azure.management.resources.fluentcore.model.Appliable< T >.apply()
  type: Method
  summary: >-
    <p>Execute the update request.</p>

    <p></p>
  syntax:
    content: public T apply()
    return:
      type: 8ce1ecb9
      description: <p>the updated resource </p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._appliable_1a614b76a85ab8e27c82a680c826e7c293
  parent: com.microsoft.azure.management.resources.fluentcore.model._appliable
  href: com.microsoft.azure.management.resources.fluentcore.model._appliable.yml
  name: applyAsync(ServiceCallback< T > callback)
  fullName: ServiceCall com.microsoft.azure.management.resources.fluentcore.model.Appliable< T >.applyAsync(ServiceCallback< T > callback)
  type: Method
  summary: >-
    <p>Execute the update request asynchronously.</p>

    <p></p>
  syntax:
    content: public ServiceCall applyAsync(ServiceCallback< T > callback)
    parameters:
    - id: callback
      type: com.microsoft.rest._service_callback34132889
      description: <p>the callback for success and failure </p>
    return:
      type: com.microsoft.rest._service_call
      description: <p>the handle to the REST call </p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._indexable_1ab0ae133d20d97eaee0480795ee886bde
  parent: com.microsoft.azure.management.resources.fluentcore.model._indexable
  href: com.microsoft.azure.management.resources.fluentcore.model._indexable.yml
  name: key()
  fullName: String com.microsoft.azure.management.resources.fluentcore.model.Indexable.key()
  type: Method
  syntax:
    content: public String key()
    return:
      type: "26831127"
      description: <p>the index key. </p>
- uid: com.microsoft.azure.management.resources._deployment._update_with_deployment_mode_1a56ad4627c4e0edfccecc1343a77ca693
  parent: com.microsoft.azure.management.resources._deployment._update_with_deployment_mode
  href: com.microsoft.azure.management.resources._deployment._update_with_deployment_mode.yml
  name: withMode(DeploymentMode mode)
  fullName: Update com.microsoft.azure.management.resources.Deployment.UpdateWithDeploymentMode.withMode(DeploymentMode mode)
  type: Method
  summary: >-
    <p>Specifies the deployment mode.</p>

    <p></p>
  syntax:
    content: public Update withMode(DeploymentMode mode)
    parameters:
    - id: mode
      type: com.microsoft.azure.management.resources.implementation.api._deployment_mode
      description: <p>the mode of the deployment </p>
    return:
      type: com.microsoft.azure.management.resources._deployment._update
      description: <p>the next stage of the deployment update </p>
- uid: com.microsoft.azure.management.resources._deployment._update_with_parameters_1a87f612519aac2c0a47661f65fca84a4c
  parent: com.microsoft.azure.management.resources._deployment._update_with_parameters
  href: com.microsoft.azure.management.resources._deployment._update_with_parameters.yml
  name: withParameters(Object parameters)
  fullName: Update com.microsoft.azure.management.resources.Deployment.UpdateWithParameters.withParameters(Object parameters)
  type: Method
  summary: >-
    <p>Specifies the parameters as a Java object.</p>

    <p></p>
  syntax:
    content: public Update withParameters(Object parameters)
    parameters:
    - id: parameters
      type: "79317049"
      description: <p>the Java object </p>
    return:
      type: com.microsoft.azure.management.resources._deployment._update
      description: <p>the next stage of the deployment update </p>
- uid: com.microsoft.azure.management.resources._deployment._update_with_parameters_1a9ba178b4c0ca8bfc0a21c15217160eac
  parent: com.microsoft.azure.management.resources._deployment._update_with_parameters
  href: com.microsoft.azure.management.resources._deployment._update_with_parameters.yml
  name: withParameters(String parametersJson)
  fullName: Update com.microsoft.azure.management.resources.Deployment.UpdateWithParameters.withParameters(String parametersJson)
  type: Method
  summary: >-
    <p>Specifies the parameters as a JSON string.</p>

    <p></p>
  syntax:
    content: public Update withParameters(String parametersJson)
    parameters:
    - id: parametersJson
      type: "26831127"
      description: <p>the JSON string </p>
    return:
      type: com.microsoft.azure.management.resources._deployment._update
      description: <p>the next stage of the deployment update </p>
- uid: com.microsoft.azure.management.resources._deployment._update_with_parameters_1abf6c5a5a8b5f654c3755719e508aa5db
  parent: com.microsoft.azure.management.resources._deployment._update_with_parameters
  href: com.microsoft.azure.management.resources._deployment._update_with_parameters.yml
  name: withParametersLink(String uri, String contentVersion)
  fullName: Update com.microsoft.azure.management.resources.Deployment.UpdateWithParameters.withParametersLink(String uri, String contentVersion)
  type: Method
  summary: >-
    <p>Specifies the parameters as a URL.</p>

    <p></p>
  syntax:
    content: public Update withParametersLink(String uri, String contentVersion)
    parameters:
    - id: uri
      type: "26831127"
      description: <p>the location of the remote parameters file </p>
    - id: contentVersion
      type: "26831127"
      description: <p>the version of the parameters file </p>
    return:
      type: com.microsoft.azure.management.resources._deployment._update
      description: <p>the next stage of the deployment update </p>
- uid: com.microsoft.azure.management.resources._deployment._update_with_template_1a8cd6131f5db065b088be9baadcc88865
  parent: com.microsoft.azure.management.resources._deployment._update_with_template
  href: com.microsoft.azure.management.resources._deployment._update_with_template.yml
  name: withTemplate(Object template)
  fullName: Update com.microsoft.azure.management.resources.Deployment.UpdateWithTemplate.withTemplate(Object template)
  type: Method
  summary: >-
    <p>Specifies the template as a Java object.</p>

    <p></p>
  syntax:
    content: public Update withTemplate(Object template)
    parameters:
    - id: template
      type: "79317049"
      description: <p>the Java object </p>
    return:
      type: com.microsoft.azure.management.resources._deployment._update
      description: <p>the next stage of the deployment update </p>
- uid: com.microsoft.azure.management.resources._deployment._update_with_template_1ae08dc79cd1d04e7c78e7d576a653a536
  parent: com.microsoft.azure.management.resources._deployment._update_with_template
  href: com.microsoft.azure.management.resources._deployment._update_with_template.yml
  name: withTemplate(String templateJson)
  fullName: Update com.microsoft.azure.management.resources.Deployment.UpdateWithTemplate.withTemplate(String templateJson)
  type: Method
  summary: >-
    <p>Specifies the template as a JSON string.</p>

    <p></p>
  syntax:
    content: public Update withTemplate(String templateJson)
    parameters:
    - id: templateJson
      type: "26831127"
      description: <p>the JSON string </p>
    return:
      type: com.microsoft.azure.management.resources._deployment._update
      description: <p>the next stage of the deployment update </p>
- uid: com.microsoft.azure.management.resources._deployment._update_with_template_1abbccad4dfdf15d9fda7d32e65d0965ad
  parent: com.microsoft.azure.management.resources._deployment._update_with_template
  href: com.microsoft.azure.management.resources._deployment._update_with_template.yml
  name: withTemplateLink(String uri, String contentVersion)
  fullName: Update com.microsoft.azure.management.resources.Deployment.UpdateWithTemplate.withTemplateLink(String uri, String contentVersion)
  type: Method
  summary: >-
    <p>Specifies the template as a URL.</p>

    <p></p>
  syntax:
    content: public Update withTemplateLink(String uri, String contentVersion)
    parameters:
    - id: uri
      type: "26831127"
      description: <p>the location of the remote template file </p>
    - id: contentVersion
      type: "26831127"
      description: <p>the version of the template file </p>
    return:
      type: com.microsoft.azure.management.resources._deployment._update
      description: <p>the next stage of the deployment update </p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._appliable
  parent: com.microsoft.azure.management.resources.fluentcore.model
  href: com.microsoft.azure.management.resources.fluentcore.model._appliable.yml
  name: Appliable
  fullName: com.microsoft.azure.management.resources.fluentcore.model.Appliable
  type: Interface
  summary: >-
    <p>The base interface for all template interfaces that support update operations.</p>

    <p></p>
  syntax:
    content: public interface Appliable
- uid: com.microsoft.azure.management.resources._deployment._update_with_template
  parent: com.microsoft.azure.management.resources
  href: com.microsoft.azure.management.resources._deployment._update_with_template.yml
  name: Deployment.UpdateWithTemplate
  fullName: com.microsoft.azure.management.resources.Deployment.UpdateWithTemplate
  type: Interface
  summary: <p>A deployment update allowing to change the template. </p>
  syntax:
    content: public interface UpdateWithTemplate
- uid: com.microsoft.azure.management.resources._deployment._update_with_parameters
  parent: com.microsoft.azure.management.resources
  href: com.microsoft.azure.management.resources._deployment._update_with_parameters.yml
  name: Deployment.UpdateWithParameters
  fullName: com.microsoft.azure.management.resources.Deployment.UpdateWithParameters
  type: Interface
  summary: <p>A deployment update allowing to change the parameters. </p>
  syntax:
    content: public interface UpdateWithParameters
- uid: com.microsoft.azure.management.resources._deployment._update_with_deployment_mode
  parent: com.microsoft.azure.management.resources
  href: com.microsoft.azure.management.resources._deployment._update_with_deployment_mode.yml
  name: Deployment.UpdateWithDeploymentMode
  fullName: com.microsoft.azure.management.resources.Deployment.UpdateWithDeploymentMode
  type: Interface
  summary: <p>A deployment update allowing to change the deployment mode. </p>
  syntax:
    content: public interface UpdateWithDeploymentMode
- uid: com.microsoft.azure.management.resources.implementation._deployment_impl
- uid: com.microsoft.azure._azure
  parent: com.microsoft.azure
  href: com.microsoft.azure._azure.yml
  name: Azure
  fullName: com.microsoft.azure.Azure
  type: Class
  summary: <p>The entry point for accessing resource management APIs in <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class Azure
