items:
- uid: com.microsoft.azure.management.network._public_i_p_address_dns_settings
  id: _public_i_p_address_dns_settings
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._public_i_p_address_dns_settings_1a44be7f61ab623eb6f49cd5de96ad1e72
  - com.microsoft.azure.management.network._public_i_p_address_dns_settings_1a3813ab3fea3237805834bbf2f8932694
  - com.microsoft.azure.management.network._public_i_p_address_dns_settings_1aa07d65bb905c621e54ed8dd52ada1e69
  - com.microsoft.azure.management.network._public_i_p_address_dns_settings_1a40a0220eff2d8e9a456da592b9e4f604
  - com.microsoft.azure.management.network._public_i_p_address_dns_settings_1ac138414f088095bef821c93faa5c7d6c
  - com.microsoft.azure.management.network._public_i_p_address_dns_settings_1a8b5441b373d6595751ce2021af359273
  href: com.microsoft.azure.management.network._public_i_p_address_dns_settings.yml
  langs:
  - java
  name: PublicIPAddressDnsSettings
  fullName: com.microsoft.azure.management.network.PublicIPAddressDnsSettings
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/PublicIPAddressDnsSettings.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/PublicIPAddressDnsSettings.java
    startLine: 14
  package: com.microsoft.azure.management.network
  summary: <p>Contains FQDN of the DNS record associated with the public IP address. </p>
  syntax: &o1
    content: public class PublicIPAddressDnsSettings
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.network._public_i_p_address_dns_settings_1a44be7f61ab623eb6f49cd5de96ad1e72
  id: _public_i_p_address_dns_settings_1a44be7f61ab623eb6f49cd5de96ad1e72
  parent: com.microsoft.azure.management.network._public_i_p_address_dns_settings
  href: com.microsoft.azure.management.network._public_i_p_address_dns_settings.yml
  langs:
  - java
  name: domainNameLabel()
  fullName: String com.microsoft.azure.management.network.PublicIPAddressDnsSettings.domainNameLabel()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/PublicIPAddressDnsSettings.java
    startLine: 44
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the domainNameLabel value.</p>

    <p></p>
  syntax:
    content: public String domainNameLabel()
    return:
      type: "26831127"
      description: <p>the domainNameLabel value </p>
- uid: com.microsoft.azure.management.network._public_i_p_address_dns_settings_1a3813ab3fea3237805834bbf2f8932694
  id: _public_i_p_address_dns_settings_1a3813ab3fea3237805834bbf2f8932694
  parent: com.microsoft.azure.management.network._public_i_p_address_dns_settings
  href: com.microsoft.azure.management.network._public_i_p_address_dns_settings.yml
  langs:
  - java
  name: fqdn()
  fullName: String com.microsoft.azure.management.network.PublicIPAddressDnsSettings.fqdn()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/PublicIPAddressDnsSettings.java
    startLine: 64
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the fqdn value.</p>

    <p></p>
  syntax:
    content: public String fqdn()
    return:
      type: "26831127"
      description: <p>the fqdn value </p>
- uid: com.microsoft.azure.management.network._public_i_p_address_dns_settings_1aa07d65bb905c621e54ed8dd52ada1e69
  id: _public_i_p_address_dns_settings_1aa07d65bb905c621e54ed8dd52ada1e69
  parent: com.microsoft.azure.management.network._public_i_p_address_dns_settings
  href: com.microsoft.azure.management.network._public_i_p_address_dns_settings.yml
  langs:
  - java
  name: reverseFqdn()
  fullName: String com.microsoft.azure.management.network.PublicIPAddressDnsSettings.reverseFqdn()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/PublicIPAddressDnsSettings.java
    startLine: 84
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the reverseFqdn value.</p>

    <p></p>
  syntax:
    content: public String reverseFqdn()
    return:
      type: "26831127"
      description: <p>the reverseFqdn value </p>
- uid: com.microsoft.azure.management.network._public_i_p_address_dns_settings_1a40a0220eff2d8e9a456da592b9e4f604
  id: _public_i_p_address_dns_settings_1a40a0220eff2d8e9a456da592b9e4f604
  parent: com.microsoft.azure.management.network._public_i_p_address_dns_settings
  href: com.microsoft.azure.management.network._public_i_p_address_dns_settings.yml
  langs:
  - java
  name: withDomainNameLabel(String domainNameLabel)
  fullName: PublicIPAddressDnsSettings com.microsoft.azure.management.network.PublicIPAddressDnsSettings.withDomainNameLabel(String domainNameLabel)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/PublicIPAddressDnsSettings.java
    startLine: 54
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the domainNameLabel value.</p>

    <p></p>
  syntax:
    content: public PublicIPAddressDnsSettings withDomainNameLabel(String domainNameLabel)
    parameters:
    - id: domainNameLabel
      type: "26831127"
      description: <p>the domainNameLabel value to set </p>
    return:
      type: com.microsoft.azure.management.network._public_i_p_address_dns_settings
      description: <p>the <xref href="com.microsoft.azure.management.network._public_i_p_address_dns_settings" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network._public_i_p_address_dns_settings_1ac138414f088095bef821c93faa5c7d6c
  id: _public_i_p_address_dns_settings_1ac138414f088095bef821c93faa5c7d6c
  parent: com.microsoft.azure.management.network._public_i_p_address_dns_settings
  href: com.microsoft.azure.management.network._public_i_p_address_dns_settings.yml
  langs:
  - java
  name: withFqdn(String fqdn)
  fullName: PublicIPAddressDnsSettings com.microsoft.azure.management.network.PublicIPAddressDnsSettings.withFqdn(String fqdn)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/PublicIPAddressDnsSettings.java
    startLine: 74
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the fqdn value.</p>

    <p></p>
  syntax:
    content: public PublicIPAddressDnsSettings withFqdn(String fqdn)
    parameters:
    - id: fqdn
      type: "26831127"
      description: <p>the fqdn value to set </p>
    return:
      type: com.microsoft.azure.management.network._public_i_p_address_dns_settings
      description: <p>the <xref href="com.microsoft.azure.management.network._public_i_p_address_dns_settings" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network._public_i_p_address_dns_settings_1a8b5441b373d6595751ce2021af359273
  id: _public_i_p_address_dns_settings_1a8b5441b373d6595751ce2021af359273
  parent: com.microsoft.azure.management.network._public_i_p_address_dns_settings
  href: com.microsoft.azure.management.network._public_i_p_address_dns_settings.yml
  langs:
  - java
  name: withReverseFqdn(String reverseFqdn)
  fullName: PublicIPAddressDnsSettings com.microsoft.azure.management.network.PublicIPAddressDnsSettings.withReverseFqdn(String reverseFqdn)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/PublicIPAddressDnsSettings.java
    startLine: 94
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the reverseFqdn value.</p>

    <p></p>
  syntax:
    content: public PublicIPAddressDnsSettings withReverseFqdn(String reverseFqdn)
    parameters:
    - id: reverseFqdn
      type: "26831127"
      description: <p>the reverseFqdn value to set </p>
    return:
      type: com.microsoft.azure.management.network._public_i_p_address_dns_settings
      description: <p>the <xref href="com.microsoft.azure.management.network._public_i_p_address_dns_settings" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure._azure
  parent: com.microsoft.azure
  href: com.microsoft.azure._azure.yml
  name: Azure
  fullName: com.microsoft.azure.Azure
  type: Class
  summary: <p>The entry point for accessing resource management APIs in <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class Azure
- uid: com.microsoft.azure.management.network._public_i_p_address_dns_settings
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._public_i_p_address_dns_settings.yml
  name: PublicIPAddressDnsSettings
  fullName: com.microsoft.azure.management.network.PublicIPAddressDnsSettings
  type: Class
  summary: <p>Contains FQDN of the DNS record associated with the public IP address. </p>
  syntax: *o1
