items:
- uid: com.microsoft.azure.management.network._application_gateway_tier
  id: _application_gateway_tier
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._application_gateway_tier_1a64d623ef612d53aa01206a5f764a785d
  - com.microsoft.azure.management.network._application_gateway_tier_1af27b9e3d9cbe1a43712ae0fe81886e01
  - com.microsoft.azure.management.network._application_gateway_tier_1a56fde39c528f1de709590b5c72e851c0
  - com.microsoft.azure.management.network._application_gateway_tier_1ac1eeea88dbc40b38c94872399e129fba
  - com.microsoft.azure.management.network._application_gateway_tier_1ac6c86ec9f7d042e1d094d5f8efea4528
  href: com.microsoft.azure.management.network._application_gateway_tier.yml
  langs:
  - java
  name: ApplicationGatewayTier
  fullName: com.microsoft.azure.management.network.ApplicationGatewayTier
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayTier.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayTier.java
    startLine: 15
  package: com.microsoft.azure.management.network
  summary: <p>Defines values for <xref href="com.microsoft.azure.management.network._application_gateway_tier" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: &o1
    content: public class ApplicationGatewayTier
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.network._application_gateway_tier_1a64d623ef612d53aa01206a5f764a785d
  id: _application_gateway_tier_1a64d623ef612d53aa01206a5f764a785d
  parent: com.microsoft.azure.management.network._application_gateway_tier
  href: com.microsoft.azure.management.network._application_gateway_tier.yml
  langs:
  - java
  name: ApplicationGatewayTier(String value)
  fullName: com.microsoft.azure.management.network.ApplicationGatewayTier.ApplicationGatewayTier(String value)
  type: Constructor
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayTier.java
    startLine: 25
  package: com.microsoft.azure.management.network
  summary: <p>Creates a custom value for <xref href="com.microsoft.azure.management.network._application_gateway_tier" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public ApplicationGatewayTier(String value)
    parameters:
    - id: value
      type: "26831127"
      description: <p>the custom value </p>
- uid: com.microsoft.azure.management.network._application_gateway_tier_1af27b9e3d9cbe1a43712ae0fe81886e01
  id: _application_gateway_tier_1af27b9e3d9cbe1a43712ae0fe81886e01
  parent: com.microsoft.azure.management.network._application_gateway_tier
  href: com.microsoft.azure.management.network._application_gateway_tier.yml
  langs:
  - java
  name: equals(Object obj)
  fullName: boolean com.microsoft.azure.management.network.ApplicationGatewayTier.equals(Object obj)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayTier.java
    startLine: 41
  package: com.microsoft.azure.management.network
  syntax:
    content: public boolean equals(Object obj)
    parameters:
    - id: obj
      type: "79317049"
    return:
      type: 4fc6e284
- uid: com.microsoft.azure.management.network._application_gateway_tier_1a56fde39c528f1de709590b5c72e851c0
  id: _application_gateway_tier_1a56fde39c528f1de709590b5c72e851c0
  parent: com.microsoft.azure.management.network._application_gateway_tier
  href: com.microsoft.azure.management.network._application_gateway_tier.yml
  langs:
  - java
  name: hashCode()
  fullName: int com.microsoft.azure.management.network.ApplicationGatewayTier.hashCode()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayTier.java
    startLine: 36
  package: com.microsoft.azure.management.network
  syntax:
    content: public int hashCode()
    return:
      type: f75371fa
- uid: com.microsoft.azure.management.network._application_gateway_tier_1ac1eeea88dbc40b38c94872399e129fba
  id: _application_gateway_tier_1ac1eeea88dbc40b38c94872399e129fba
  parent: com.microsoft.azure.management.network._application_gateway_tier
  href: com.microsoft.azure.management.network._application_gateway_tier.yml
  langs:
  - java
  name: STANDARD
  fullName: final ApplicationGatewayTier com.microsoft.azure.management.network.ApplicationGatewayTier.STANDARD
  type: Field
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayTier.java
    startLine: 17
  package: com.microsoft.azure.management.network
  summary: <p>Static value Standard for <xref href="com.microsoft.azure.management.network._application_gateway_tier" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public static final ApplicationGatewayTier STANDARD= new ApplicationGatewayTier("Standard")
    return:
      type: 93de0ef9com.microsoft.azure.management.network._application_gateway_tier
- uid: com.microsoft.azure.management.network._application_gateway_tier_1ac6c86ec9f7d042e1d094d5f8efea4528
  id: _application_gateway_tier_1ac6c86ec9f7d042e1d094d5f8efea4528
  parent: com.microsoft.azure.management.network._application_gateway_tier
  href: com.microsoft.azure.management.network._application_gateway_tier.yml
  langs:
  - java
  name: toString()
  fullName: String com.microsoft.azure.management.network.ApplicationGatewayTier.toString()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayTier.java
    startLine: 31
  package: com.microsoft.azure.management.network
  syntax:
    content: public String toString()
    return:
      type: "26831127"
references:
- uid: 93de0ef9com.microsoft.azure.management.network._application_gateway_tier
  spec.java:
  - name: 'final '
    fullName: 'final '
  - uid: com.microsoft.azure.management.network._application_gateway_tier
    name: ApplicationGatewayTier
    fullName: com.microsoft.azure.management.network.ApplicationGatewayTier
    href: com.microsoft.azure.management.network._application_gateway_tier.yml
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
- uid: "79317049"
  spec.java:
  - name: Object
    fullName: Object
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: com.microsoft.azure.management.network._application_gateway_tier
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_tier.yml
  name: ApplicationGatewayTier
  fullName: com.microsoft.azure.management.network.ApplicationGatewayTier
  type: Class
  summary: <p>Defines values for <xref href="com.microsoft.azure.management.network._application_gateway_tier" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: *o1
