items:
- uid: com.microsoft.azure.management.network._application_gateway_ssl_protocol
  id: _application_gateway_ssl_protocol
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._application_gateway_ssl_protocol_1ad8fd529d29bb3ae009b5df9b4bfd309d
  - com.microsoft.azure.management.network._application_gateway_ssl_protocol_1a87ac0388d77110b3d3f1b1da28fe6c4d
  - com.microsoft.azure.management.network._application_gateway_ssl_protocol_1ae73146570b3bd7c61dd141e1bb71e074
  - com.microsoft.azure.management.network._application_gateway_ssl_protocol_1a14a37f76f00f50868adfc1a69ee4184b
  - com.microsoft.azure.management.network._application_gateway_ssl_protocol_1af35997d6e9f8615c85e1e1ac171d0654
  - com.microsoft.azure.management.network._application_gateway_ssl_protocol_1ad1cee7277d471b2e3435fa2e6177464b
  - com.microsoft.azure.management.network._application_gateway_ssl_protocol_1a42c26b65a6a76b13fbdb1c29f1292cc4
  href: com.microsoft.azure.management.network._application_gateway_ssl_protocol.yml
  langs:
  - java
  name: ApplicationGatewaySslProtocol
  fullName: com.microsoft.azure.management.network.ApplicationGatewaySslProtocol
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySslProtocol.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySslProtocol.java
    startLine: 15
  package: com.microsoft.azure.management.network
  summary: <p>Defines values for <xref href="com.microsoft.azure.management.network._application_gateway_ssl_protocol" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: &o1
    content: public class ApplicationGatewaySslProtocol
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.network._application_gateway_ssl_protocol_1ad8fd529d29bb3ae009b5df9b4bfd309d
  id: _application_gateway_ssl_protocol_1ad8fd529d29bb3ae009b5df9b4bfd309d
  parent: com.microsoft.azure.management.network._application_gateway_ssl_protocol
  href: com.microsoft.azure.management.network._application_gateway_ssl_protocol.yml
  langs:
  - java
  name: ApplicationGatewaySslProtocol(String value)
  fullName: com.microsoft.azure.management.network.ApplicationGatewaySslProtocol.ApplicationGatewaySslProtocol(String value)
  type: Constructor
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySslProtocol.java
    startLine: 31
  package: com.microsoft.azure.management.network
  summary: <p>Creates a custom value for <xref href="com.microsoft.azure.management.network._application_gateway_ssl_protocol" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public ApplicationGatewaySslProtocol(String value)
    parameters:
    - id: value
      type: "26831127"
      description: <p>the custom value </p>
- uid: com.microsoft.azure.management.network._application_gateway_ssl_protocol_1a87ac0388d77110b3d3f1b1da28fe6c4d
  id: _application_gateway_ssl_protocol_1a87ac0388d77110b3d3f1b1da28fe6c4d
  parent: com.microsoft.azure.management.network._application_gateway_ssl_protocol
  href: com.microsoft.azure.management.network._application_gateway_ssl_protocol.yml
  langs:
  - java
  name: equals(Object obj)
  fullName: boolean com.microsoft.azure.management.network.ApplicationGatewaySslProtocol.equals(Object obj)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySslProtocol.java
    startLine: 47
  package: com.microsoft.azure.management.network
  syntax:
    content: public boolean equals(Object obj)
    parameters:
    - id: obj
      type: "79317049"
    return:
      type: 4fc6e284
- uid: com.microsoft.azure.management.network._application_gateway_ssl_protocol_1ae73146570b3bd7c61dd141e1bb71e074
  id: _application_gateway_ssl_protocol_1ae73146570b3bd7c61dd141e1bb71e074
  parent: com.microsoft.azure.management.network._application_gateway_ssl_protocol
  href: com.microsoft.azure.management.network._application_gateway_ssl_protocol.yml
  langs:
  - java
  name: hashCode()
  fullName: int com.microsoft.azure.management.network.ApplicationGatewaySslProtocol.hashCode()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySslProtocol.java
    startLine: 42
  package: com.microsoft.azure.management.network
  syntax:
    content: public int hashCode()
    return:
      type: f75371fa
- uid: com.microsoft.azure.management.network._application_gateway_ssl_protocol_1a14a37f76f00f50868adfc1a69ee4184b
  id: _application_gateway_ssl_protocol_1a14a37f76f00f50868adfc1a69ee4184b
  parent: com.microsoft.azure.management.network._application_gateway_ssl_protocol
  href: com.microsoft.azure.management.network._application_gateway_ssl_protocol.yml
  langs:
  - java
  name: TLSV1_0
  fullName: final ApplicationGatewaySslProtocol com.microsoft.azure.management.network.ApplicationGatewaySslProtocol.TLSV1_0
  type: Field
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySslProtocol.java
    startLine: 17
  package: com.microsoft.azure.management.network
  summary: <p>Static value TLSv1_0 for <xref href="com.microsoft.azure.management.network._application_gateway_ssl_protocol" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public static final ApplicationGatewaySslProtocol TLSV1_0= new ApplicationGatewaySslProtocol("TLSv1_0")
    return:
      type: 93de0ef9com.microsoft.azure.management.network._application_gateway_ssl_protocol
- uid: com.microsoft.azure.management.network._application_gateway_ssl_protocol_1af35997d6e9f8615c85e1e1ac171d0654
  id: _application_gateway_ssl_protocol_1af35997d6e9f8615c85e1e1ac171d0654
  parent: com.microsoft.azure.management.network._application_gateway_ssl_protocol
  href: com.microsoft.azure.management.network._application_gateway_ssl_protocol.yml
  langs:
  - java
  name: TLSV1_1
  fullName: final ApplicationGatewaySslProtocol com.microsoft.azure.management.network.ApplicationGatewaySslProtocol.TLSV1_1
  type: Field
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySslProtocol.java
    startLine: 20
  package: com.microsoft.azure.management.network
  summary: <p>Static value TLSv1_1 for <xref href="com.microsoft.azure.management.network._application_gateway_ssl_protocol" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public static final ApplicationGatewaySslProtocol TLSV1_1= new ApplicationGatewaySslProtocol("TLSv1_1")
    return:
      type: 93de0ef9com.microsoft.azure.management.network._application_gateway_ssl_protocol
- uid: com.microsoft.azure.management.network._application_gateway_ssl_protocol_1ad1cee7277d471b2e3435fa2e6177464b
  id: _application_gateway_ssl_protocol_1ad1cee7277d471b2e3435fa2e6177464b
  parent: com.microsoft.azure.management.network._application_gateway_ssl_protocol
  href: com.microsoft.azure.management.network._application_gateway_ssl_protocol.yml
  langs:
  - java
  name: TLSV1_2
  fullName: final ApplicationGatewaySslProtocol com.microsoft.azure.management.network.ApplicationGatewaySslProtocol.TLSV1_2
  type: Field
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySslProtocol.java
    startLine: 23
  package: com.microsoft.azure.management.network
  summary: <p>Static value TLSv1_2 for <xref href="com.microsoft.azure.management.network._application_gateway_ssl_protocol" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public static final ApplicationGatewaySslProtocol TLSV1_2= new ApplicationGatewaySslProtocol("TLSv1_2")
    return:
      type: 93de0ef9com.microsoft.azure.management.network._application_gateway_ssl_protocol
- uid: com.microsoft.azure.management.network._application_gateway_ssl_protocol_1a42c26b65a6a76b13fbdb1c29f1292cc4
  id: _application_gateway_ssl_protocol_1a42c26b65a6a76b13fbdb1c29f1292cc4
  parent: com.microsoft.azure.management.network._application_gateway_ssl_protocol
  href: com.microsoft.azure.management.network._application_gateway_ssl_protocol.yml
  langs:
  - java
  name: toString()
  fullName: String com.microsoft.azure.management.network.ApplicationGatewaySslProtocol.toString()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySslProtocol.java
    startLine: 37
  package: com.microsoft.azure.management.network
  syntax:
    content: public String toString()
    return:
      type: "26831127"
references:
- uid: 93de0ef9com.microsoft.azure.management.network._application_gateway_ssl_protocol
  spec.java:
  - name: 'final '
    fullName: 'final '
  - uid: com.microsoft.azure.management.network._application_gateway_ssl_protocol
    name: ApplicationGatewaySslProtocol
    fullName: com.microsoft.azure.management.network.ApplicationGatewaySslProtocol
    href: com.microsoft.azure.management.network._application_gateway_ssl_protocol.yml
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
- uid: "79317049"
  spec.java:
  - name: Object
    fullName: Object
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: com.microsoft.azure.management.network._application_gateway_ssl_protocol
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_ssl_protocol.yml
  name: ApplicationGatewaySslProtocol
  fullName: com.microsoft.azure.management.network.ApplicationGatewaySslProtocol
  type: Class
  summary: <p>Defines values for <xref href="com.microsoft.azure.management.network._application_gateway_ssl_protocol" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: *o1
