items:
- uid: com.microsoft.azure.management.network._application_gateway_path_rule
  id: _application_gateway_path_rule
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._application_gateway_path_rule_1a68485f180ccbb4ede2ff886938cb6787
  - com.microsoft.azure.management.network._application_gateway_path_rule_1ab1259f5c912d559b92814981abeb3e22
  - com.microsoft.azure.management.network._application_gateway_path_rule_1a4ca09baa7c48dcd3a6355e149ca1afaa
  - com.microsoft.azure.management.network._application_gateway_path_rule_1a50838ef84a58d2ec9841374c414f4d0d
  - com.microsoft.azure.management.network._application_gateway_path_rule_1aa84973b419e1fad2bc4f8bf93dcc141b
  - com.microsoft.azure.management.network._application_gateway_path_rule_1adc2ac49ab106b2365d8bf02c44b4025e
  - com.microsoft.azure.management.network._application_gateway_path_rule_1a29f7fb685765b26cd525131a25fbe913
  - com.microsoft.azure.management.network._application_gateway_path_rule_1a34069b9bbd4275f7a8e62cb921c72ced
  - com.microsoft.azure.management.network._application_gateway_path_rule_1af8545f4bc9f67027de3e4993ffca95ee
  - com.microsoft.azure.management.network._application_gateway_path_rule_1a1fa24f1918aa715429bde1f1db0abd36
  - com.microsoft.azure.management.network._application_gateway_path_rule_1ab5cea0b650ca40740dfbcbd0c643f202
  - com.microsoft.azure.management.network._application_gateway_path_rule_1a860a8e31230488c7c65c1fb688afb979
  href: com.microsoft.azure.management.network._application_gateway_path_rule.yml
  langs:
  - java
  name: ApplicationGatewayPathRule
  fullName: com.microsoft.azure.management.network.ApplicationGatewayPathRule
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayPathRule.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayPathRule.java
    startLine: 19
  package: com.microsoft.azure.management.network
  summary: <p>Path rule of URL path map of application gateway. </p>
  syntax: &o1
    content: public class ApplicationGatewayPathRule extends SubResource
  inheritance:
  - java.lang.Object
  - com.microsoft.azure._sub_resource
  inheritedMembers:
  - com.microsoft.azure._sub_resource_1a92e02020e7fca6a3d2284bc1db599e52
  - com.microsoft.azure._sub_resource_1a522b0146c9247308f3752dd123100d8a
- uid: com.microsoft.azure.management.network._application_gateway_path_rule_1a68485f180ccbb4ede2ff886938cb6787
  id: _application_gateway_path_rule_1a68485f180ccbb4ede2ff886938cb6787
  parent: com.microsoft.azure.management.network._application_gateway_path_rule
  href: com.microsoft.azure.management.network._application_gateway_path_rule.yml
  langs:
  - java
  name: backendAddressPool()
  fullName: SubResource com.microsoft.azure.management.network.ApplicationGatewayPathRule.backendAddressPool()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayPathRule.java
    startLine: 81
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the backendAddressPool value.</p>

    <p></p>
  syntax:
    content: public SubResource backendAddressPool()
    return:
      type: com.microsoft.azure._sub_resource
      description: <p>the backendAddressPool value </p>
- uid: com.microsoft.azure.management.network._application_gateway_path_rule_1ab1259f5c912d559b92814981abeb3e22
  id: _application_gateway_path_rule_1ab1259f5c912d559b92814981abeb3e22
  parent: com.microsoft.azure.management.network._application_gateway_path_rule
  href: com.microsoft.azure.management.network._application_gateway_path_rule.yml
  langs:
  - java
  name: backendHttpSettings()
  fullName: SubResource com.microsoft.azure.management.network.ApplicationGatewayPathRule.backendHttpSettings()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayPathRule.java
    startLine: 101
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the backendHttpSettings value.</p>

    <p></p>
  syntax:
    content: public SubResource backendHttpSettings()
    return:
      type: com.microsoft.azure._sub_resource
      description: <p>the backendHttpSettings value </p>
- uid: com.microsoft.azure.management.network._application_gateway_path_rule_1a4ca09baa7c48dcd3a6355e149ca1afaa
  id: _application_gateway_path_rule_1a4ca09baa7c48dcd3a6355e149ca1afaa
  parent: com.microsoft.azure.management.network._application_gateway_path_rule
  href: com.microsoft.azure.management.network._application_gateway_path_rule.yml
  langs:
  - java
  name: etag()
  fullName: String com.microsoft.azure.management.network.ApplicationGatewayPathRule.etag()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayPathRule.java
    startLine: 161
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the etag value.</p>

    <p></p>
  syntax:
    content: public String etag()
    return:
      type: "26831127"
      description: <p>the etag value </p>
- uid: com.microsoft.azure.management.network._application_gateway_path_rule_1a50838ef84a58d2ec9841374c414f4d0d
  id: _application_gateway_path_rule_1a50838ef84a58d2ec9841374c414f4d0d
  parent: com.microsoft.azure.management.network._application_gateway_path_rule
  href: com.microsoft.azure.management.network._application_gateway_path_rule.yml
  langs:
  - java
  name: name()
  fullName: String com.microsoft.azure.management.network.ApplicationGatewayPathRule.name()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayPathRule.java
    startLine: 141
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the name value.</p>

    <p></p>
  syntax:
    content: public String name()
    return:
      type: "26831127"
      description: <p>the name value </p>
- uid: com.microsoft.azure.management.network._application_gateway_path_rule_1aa84973b419e1fad2bc4f8bf93dcc141b
  id: _application_gateway_path_rule_1aa84973b419e1fad2bc4f8bf93dcc141b
  parent: com.microsoft.azure.management.network._application_gateway_path_rule
  href: com.microsoft.azure.management.network._application_gateway_path_rule.yml
  langs:
  - java
  name: paths()
  fullName: List<String> com.microsoft.azure.management.network.ApplicationGatewayPathRule.paths()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayPathRule.java
    startLine: 61
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the paths value.</p>

    <p></p>
  syntax:
    content: public List< String > paths()
    return:
      type: f35af49b
      description: <p>the paths value </p>
- uid: com.microsoft.azure.management.network._application_gateway_path_rule_1adc2ac49ab106b2365d8bf02c44b4025e
  id: _application_gateway_path_rule_1adc2ac49ab106b2365d8bf02c44b4025e
  parent: com.microsoft.azure.management.network._application_gateway_path_rule
  href: com.microsoft.azure.management.network._application_gateway_path_rule.yml
  langs:
  - java
  name: provisioningState()
  fullName: String com.microsoft.azure.management.network.ApplicationGatewayPathRule.provisioningState()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayPathRule.java
    startLine: 121
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the provisioningState value.</p>

    <p></p>
  syntax:
    content: public String provisioningState()
    return:
      type: "26831127"
      description: <p>the provisioningState value </p>
- uid: com.microsoft.azure.management.network._application_gateway_path_rule_1a29f7fb685765b26cd525131a25fbe913
  id: _application_gateway_path_rule_1a29f7fb685765b26cd525131a25fbe913
  parent: com.microsoft.azure.management.network._application_gateway_path_rule
  href: com.microsoft.azure.management.network._application_gateway_path_rule.yml
  langs:
  - java
  name: withBackendAddressPool(SubResource backendAddressPool)
  fullName: ApplicationGatewayPathRule com.microsoft.azure.management.network.ApplicationGatewayPathRule.withBackendAddressPool(SubResource backendAddressPool)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayPathRule.java
    startLine: 91
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the backendAddressPool value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewayPathRule withBackendAddressPool(SubResource backendAddressPool)
    parameters:
    - id: backendAddressPool
      type: com.microsoft.azure._sub_resource
      description: <p>the backendAddressPool value to set </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_path_rule
      description: <p>the <xref href="com.microsoft.azure.management.network._application_gateway_path_rule" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network._application_gateway_path_rule_1a34069b9bbd4275f7a8e62cb921c72ced
  id: _application_gateway_path_rule_1a34069b9bbd4275f7a8e62cb921c72ced
  parent: com.microsoft.azure.management.network._application_gateway_path_rule
  href: com.microsoft.azure.management.network._application_gateway_path_rule.yml
  langs:
  - java
  name: withBackendHttpSettings(SubResource backendHttpSettings)
  fullName: ApplicationGatewayPathRule com.microsoft.azure.management.network.ApplicationGatewayPathRule.withBackendHttpSettings(SubResource backendHttpSettings)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayPathRule.java
    startLine: 111
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the backendHttpSettings value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewayPathRule withBackendHttpSettings(SubResource backendHttpSettings)
    parameters:
    - id: backendHttpSettings
      type: com.microsoft.azure._sub_resource
      description: <p>the backendHttpSettings value to set </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_path_rule
      description: <p>the <xref href="com.microsoft.azure.management.network._application_gateway_path_rule" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network._application_gateway_path_rule_1af8545f4bc9f67027de3e4993ffca95ee
  id: _application_gateway_path_rule_1af8545f4bc9f67027de3e4993ffca95ee
  parent: com.microsoft.azure.management.network._application_gateway_path_rule
  href: com.microsoft.azure.management.network._application_gateway_path_rule.yml
  langs:
  - java
  name: withEtag(String etag)
  fullName: ApplicationGatewayPathRule com.microsoft.azure.management.network.ApplicationGatewayPathRule.withEtag(String etag)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayPathRule.java
    startLine: 171
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the etag value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewayPathRule withEtag(String etag)
    parameters:
    - id: etag
      type: "26831127"
      description: <p>the etag value to set </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_path_rule
      description: <p>the <xref href="com.microsoft.azure.management.network._application_gateway_path_rule" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network._application_gateway_path_rule_1a1fa24f1918aa715429bde1f1db0abd36
  id: _application_gateway_path_rule_1a1fa24f1918aa715429bde1f1db0abd36
  parent: com.microsoft.azure.management.network._application_gateway_path_rule
  href: com.microsoft.azure.management.network._application_gateway_path_rule.yml
  langs:
  - java
  name: withName(String name)
  fullName: ApplicationGatewayPathRule com.microsoft.azure.management.network.ApplicationGatewayPathRule.withName(String name)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayPathRule.java
    startLine: 151
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the name value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewayPathRule withName(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>the name value to set </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_path_rule
      description: <p>the <xref href="com.microsoft.azure.management.network._application_gateway_path_rule" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network._application_gateway_path_rule_1ab5cea0b650ca40740dfbcbd0c643f202
  id: _application_gateway_path_rule_1ab5cea0b650ca40740dfbcbd0c643f202
  parent: com.microsoft.azure.management.network._application_gateway_path_rule
  href: com.microsoft.azure.management.network._application_gateway_path_rule.yml
  langs:
  - java
  name: withPaths(List< String > paths)
  fullName: ApplicationGatewayPathRule com.microsoft.azure.management.network.ApplicationGatewayPathRule.withPaths(List< String > paths)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayPathRule.java
    startLine: 71
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the paths value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewayPathRule withPaths(List< String > paths)
    parameters:
    - id: paths
      type: f35af49b
      description: <p>the paths value to set </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_path_rule
      description: <p>the <xref href="com.microsoft.azure.management.network._application_gateway_path_rule" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network._application_gateway_path_rule_1a860a8e31230488c7c65c1fb688afb979
  id: _application_gateway_path_rule_1a860a8e31230488c7c65c1fb688afb979
  parent: com.microsoft.azure.management.network._application_gateway_path_rule
  href: com.microsoft.azure.management.network._application_gateway_path_rule.yml
  langs:
  - java
  name: withProvisioningState(String provisioningState)
  fullName: ApplicationGatewayPathRule com.microsoft.azure.management.network.ApplicationGatewayPathRule.withProvisioningState(String provisioningState)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayPathRule.java
    startLine: 131
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the provisioningState value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewayPathRule withProvisioningState(String provisioningState)
    parameters:
    - id: provisioningState
      type: "26831127"
      description: <p>the provisioningState value to set </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_path_rule
      description: <p>the <xref href="com.microsoft.azure.management.network._application_gateway_path_rule" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: f35af49b
  spec.java:
  - name: List< String >
    fullName: List< String >
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure._sub_resource_1a92e02020e7fca6a3d2284bc1db599e52
  parent: com.microsoft.azure._sub_resource
  href: com.microsoft.azure._sub_resource.yml
  name: id()
  fullName: String com.microsoft.azure.SubResource.id()
  type: Method
  summary: >-
    <p>Get the id value.</p>

    <p></p>
  syntax:
    content: public String id()
    return:
      type: "26831127"
      description: <p>the id value </p>
- uid: com.microsoft.azure._sub_resource_1a522b0146c9247308f3752dd123100d8a
  parent: com.microsoft.azure._sub_resource
  href: com.microsoft.azure._sub_resource.yml
  name: withId(String id)
  fullName: SubResource com.microsoft.azure.SubResource.withId(String id)
  type: Method
  summary: >-
    <p>Set the id value.</p>

    <p></p>
  syntax:
    content: public SubResource withId(String id)
    parameters:
    - id: id
      type: "26831127"
      description: <p>the id value to set </p>
    return:
      type: com.microsoft.azure._sub_resource
      description: <p>the sub resource itself </p>
- uid: com.microsoft.azure._sub_resource
  parent: com.microsoft.azure
  href: com.microsoft.azure._sub_resource.yml
  name: SubResource
  fullName: com.microsoft.azure.SubResource
  type: Class
  summary: <p>The <xref href="com.microsoft.azure._sub_resource" data-throw-if-not-resolved="false"></xref> model. </p>
  syntax:
    content: public class SubResource
- uid: com.microsoft.azure.management.network._application_gateway_path_rule
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_path_rule.yml
  name: ApplicationGatewayPathRule
  fullName: com.microsoft.azure.management.network.ApplicationGatewayPathRule
  type: Class
  summary: <p>Path rule of URL path map of application gateway. </p>
  syntax: *o1
