items:
- uid: com.microsoft.azure.management.network._application_gateway_request_routing_rule_type
  id: _application_gateway_request_routing_rule_type
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._application_gateway_request_routing_rule_type_1a8ead11ced6ebce9778a0473325ceab8f
  - com.microsoft.azure.management.network._application_gateway_request_routing_rule_type_1a3b757dcda8eb9f32bfbaa857fb7060a6
  - com.microsoft.azure.management.network._application_gateway_request_routing_rule_type_1af04884de62be77538f8a0c5e64566ad5
  - com.microsoft.azure.management.network._application_gateway_request_routing_rule_type_1acf54a0fa99baf93233561afa6a54f6c3
  - com.microsoft.azure.management.network._application_gateway_request_routing_rule_type_1aafd04ac491864d32dcdfd81aade4e466
  - com.microsoft.azure.management.network._application_gateway_request_routing_rule_type_1a05e1e1574eb96f7fb64b252d7f7b69cc
  href: com.microsoft.azure.management.network._application_gateway_request_routing_rule_type.yml
  langs:
  - java
  name: ApplicationGatewayRequestRoutingRuleType
  fullName: com.microsoft.azure.management.network.ApplicationGatewayRequestRoutingRuleType
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayRequestRoutingRuleType.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayRequestRoutingRuleType.java
    startLine: 15
  package: com.microsoft.azure.management.network
  summary: <p>Defines values for <xref href="com.microsoft.azure.management.network._application_gateway_request_routing_rule_type" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: &o1
    content: public class ApplicationGatewayRequestRoutingRuleType
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.network._application_gateway_request_routing_rule_type_1a8ead11ced6ebce9778a0473325ceab8f
  id: _application_gateway_request_routing_rule_type_1a8ead11ced6ebce9778a0473325ceab8f
  parent: com.microsoft.azure.management.network._application_gateway_request_routing_rule_type
  href: com.microsoft.azure.management.network._application_gateway_request_routing_rule_type.yml
  langs:
  - java
  name: ApplicationGatewayRequestRoutingRuleType(String value)
  fullName: com.microsoft.azure.management.network.ApplicationGatewayRequestRoutingRuleType.ApplicationGatewayRequestRoutingRuleType(String value)
  type: Constructor
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayRequestRoutingRuleType.java
    startLine: 28
  package: com.microsoft.azure.management.network
  summary: <p>Creates a custom value for <xref href="com.microsoft.azure.management.network._application_gateway_request_routing_rule_type" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public ApplicationGatewayRequestRoutingRuleType(String value)
    parameters:
    - id: value
      type: "26831127"
      description: <p>the custom value </p>
- uid: com.microsoft.azure.management.network._application_gateway_request_routing_rule_type_1a3b757dcda8eb9f32bfbaa857fb7060a6
  id: _application_gateway_request_routing_rule_type_1a3b757dcda8eb9f32bfbaa857fb7060a6
  parent: com.microsoft.azure.management.network._application_gateway_request_routing_rule_type
  href: com.microsoft.azure.management.network._application_gateway_request_routing_rule_type.yml
  langs:
  - java
  name: BASIC
  fullName: final ApplicationGatewayRequestRoutingRuleType com.microsoft.azure.management.network.ApplicationGatewayRequestRoutingRuleType.BASIC
  type: Field
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayRequestRoutingRuleType.java
    startLine: 17
  package: com.microsoft.azure.management.network
  summary: <p>Static value Basic for <xref href="com.microsoft.azure.management.network._application_gateway_request_routing_rule_type" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public static final ApplicationGatewayRequestRoutingRuleType BASIC= new ApplicationGatewayRequestRoutingRuleType("Basic")
    return:
      type: 93de0ef9com.microsoft.azure.management.network._application_gateway_request_routing_rule_type
- uid: com.microsoft.azure.management.network._application_gateway_request_routing_rule_type_1af04884de62be77538f8a0c5e64566ad5
  id: _application_gateway_request_routing_rule_type_1af04884de62be77538f8a0c5e64566ad5
  parent: com.microsoft.azure.management.network._application_gateway_request_routing_rule_type
  href: com.microsoft.azure.management.network._application_gateway_request_routing_rule_type.yml
  langs:
  - java
  name: equals(Object obj)
  fullName: boolean com.microsoft.azure.management.network.ApplicationGatewayRequestRoutingRuleType.equals(Object obj)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayRequestRoutingRuleType.java
    startLine: 44
  package: com.microsoft.azure.management.network
  syntax:
    content: public boolean equals(Object obj)
    parameters:
    - id: obj
      type: "79317049"
    return:
      type: 4fc6e284
- uid: com.microsoft.azure.management.network._application_gateway_request_routing_rule_type_1acf54a0fa99baf93233561afa6a54f6c3
  id: _application_gateway_request_routing_rule_type_1acf54a0fa99baf93233561afa6a54f6c3
  parent: com.microsoft.azure.management.network._application_gateway_request_routing_rule_type
  href: com.microsoft.azure.management.network._application_gateway_request_routing_rule_type.yml
  langs:
  - java
  name: hashCode()
  fullName: int com.microsoft.azure.management.network.ApplicationGatewayRequestRoutingRuleType.hashCode()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayRequestRoutingRuleType.java
    startLine: 39
  package: com.microsoft.azure.management.network
  syntax:
    content: public int hashCode()
    return:
      type: f75371fa
- uid: com.microsoft.azure.management.network._application_gateway_request_routing_rule_type_1aafd04ac491864d32dcdfd81aade4e466
  id: _application_gateway_request_routing_rule_type_1aafd04ac491864d32dcdfd81aade4e466
  parent: com.microsoft.azure.management.network._application_gateway_request_routing_rule_type
  href: com.microsoft.azure.management.network._application_gateway_request_routing_rule_type.yml
  langs:
  - java
  name: PATH_BASED_ROUTING
  fullName: final ApplicationGatewayRequestRoutingRuleType com.microsoft.azure.management.network.ApplicationGatewayRequestRoutingRuleType.PATH_BASED_ROUTING
  type: Field
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayRequestRoutingRuleType.java
    startLine: 20
  package: com.microsoft.azure.management.network
  summary: <p>Static value PathBasedRouting for <xref href="com.microsoft.azure.management.network._application_gateway_request_routing_rule_type" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public static final ApplicationGatewayRequestRoutingRuleType PATH_BASED_ROUTING= new ApplicationGatewayRequestRoutingRuleType("PathBasedRouting")
    return:
      type: 93de0ef9com.microsoft.azure.management.network._application_gateway_request_routing_rule_type
- uid: com.microsoft.azure.management.network._application_gateway_request_routing_rule_type_1a05e1e1574eb96f7fb64b252d7f7b69cc
  id: _application_gateway_request_routing_rule_type_1a05e1e1574eb96f7fb64b252d7f7b69cc
  parent: com.microsoft.azure.management.network._application_gateway_request_routing_rule_type
  href: com.microsoft.azure.management.network._application_gateway_request_routing_rule_type.yml
  langs:
  - java
  name: toString()
  fullName: String com.microsoft.azure.management.network.ApplicationGatewayRequestRoutingRuleType.toString()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayRequestRoutingRuleType.java
    startLine: 34
  package: com.microsoft.azure.management.network
  syntax:
    content: public String toString()
    return:
      type: "26831127"
references:
- uid: 93de0ef9com.microsoft.azure.management.network._application_gateway_request_routing_rule_type
  spec.java:
  - name: 'final '
    fullName: 'final '
  - uid: com.microsoft.azure.management.network._application_gateway_request_routing_rule_type
    name: ApplicationGatewayRequestRoutingRuleType
    fullName: com.microsoft.azure.management.network.ApplicationGatewayRequestRoutingRuleType
    href: com.microsoft.azure.management.network._application_gateway_request_routing_rule_type.yml
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
- uid: "79317049"
  spec.java:
  - name: Object
    fullName: Object
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: com.microsoft.azure.management.network._application_gateway_request_routing_rule_type
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_request_routing_rule_type.yml
  name: ApplicationGatewayRequestRoutingRuleType
  fullName: com.microsoft.azure.management.network.ApplicationGatewayRequestRoutingRuleType
  type: Class
  summary: <p>Defines values for <xref href="com.microsoft.azure.management.network._application_gateway_request_routing_rule_type" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: *o1
