items:
- uid: com.microsoft.azure.management.website.implementation.api._azure_blob_storage_http_logs_config
  id: _azure_blob_storage_http_logs_config
  parent: com.microsoft.azure.management.website.implementation.api
  children:
  - com.microsoft.azure.management.website.implementation.api._azure_blob_storage_http_logs_config_1a15ad7254cf4160fbf116455f4837388b
  - com.microsoft.azure.management.website.implementation.api._azure_blob_storage_http_logs_config_1a4a3d32378b07dd4d3b7874f7cd1d6ddd
  - com.microsoft.azure.management.website.implementation.api._azure_blob_storage_http_logs_config_1a13e4959f7e806f1bf321d71ce814264f
  - com.microsoft.azure.management.website.implementation.api._azure_blob_storage_http_logs_config_1ab036e5bf0f48c3fd10954e7d9e654b82
  - com.microsoft.azure.management.website.implementation.api._azure_blob_storage_http_logs_config_1a845056be292ee30ce588f6f959dcbc1a
  - com.microsoft.azure.management.website.implementation.api._azure_blob_storage_http_logs_config_1a647bc90d8536039ae5d681975a46a4dc
  href: com.microsoft.azure.management.website.implementation.api._azure_blob_storage_http_logs_config.yml
  langs:
  - java
  name: AzureBlobStorageHttpLogsConfig
  fullName: com.microsoft.azure.management.website.implementation.api.AzureBlobStorageHttpLogsConfig
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/AzureBlobStorageHttpLogsConfig.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/AzureBlobStorageHttpLogsConfig.java
    startLine: 12
  package: com.microsoft.azure.management.website.implementation.api
  summary: <p>Http logs to azure blob storage configuration. </p>
  syntax: &o1
    content: public class AzureBlobStorageHttpLogsConfig
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.website.implementation.api._azure_blob_storage_http_logs_config_1a15ad7254cf4160fbf116455f4837388b
  id: _azure_blob_storage_http_logs_config_1a15ad7254cf4160fbf116455f4837388b
  parent: com.microsoft.azure.management.website.implementation.api._azure_blob_storage_http_logs_config
  href: com.microsoft.azure.management.website.implementation.api._azure_blob_storage_http_logs_config.yml
  langs:
  - java
  name: enabled()
  fullName: Boolean com.microsoft.azure.management.website.implementation.api.AzureBlobStorageHttpLogsConfig.enabled()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/AzureBlobStorageHttpLogsConfig.java
    startLine: 76
  package: com.microsoft.azure.management.website.implementation.api
  summary: >-
    <p>Get the enabled value.</p>

    <p></p>
  syntax:
    content: public Boolean enabled()
    return:
      type: 866c2227
      description: <p>the enabled value </p>
- uid: com.microsoft.azure.management.website.implementation.api._azure_blob_storage_http_logs_config_1a4a3d32378b07dd4d3b7874f7cd1d6ddd
  id: _azure_blob_storage_http_logs_config_1a4a3d32378b07dd4d3b7874f7cd1d6ddd
  parent: com.microsoft.azure.management.website.implementation.api._azure_blob_storage_http_logs_config
  href: com.microsoft.azure.management.website.implementation.api._azure_blob_storage_http_logs_config.yml
  langs:
  - java
  name: retentionInDays()
  fullName: Integer com.microsoft.azure.management.website.implementation.api.AzureBlobStorageHttpLogsConfig.retentionInDays()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/AzureBlobStorageHttpLogsConfig.java
    startLine: 56
  package: com.microsoft.azure.management.website.implementation.api
  summary: >-
    <p>Get the retentionInDays value.</p>

    <p></p>
  syntax:
    content: public Integer retentionInDays()
    return:
      type: 08effaa0
      description: <p>the retentionInDays value </p>
- uid: com.microsoft.azure.management.website.implementation.api._azure_blob_storage_http_logs_config_1a13e4959f7e806f1bf321d71ce814264f
  id: _azure_blob_storage_http_logs_config_1a13e4959f7e806f1bf321d71ce814264f
  parent: com.microsoft.azure.management.website.implementation.api._azure_blob_storage_http_logs_config
  href: com.microsoft.azure.management.website.implementation.api._azure_blob_storage_http_logs_config.yml
  langs:
  - java
  name: sasUrl()
  fullName: String com.microsoft.azure.management.website.implementation.api.AzureBlobStorageHttpLogsConfig.sasUrl()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/AzureBlobStorageHttpLogsConfig.java
    startLine: 36
  package: com.microsoft.azure.management.website.implementation.api
  summary: >-
    <p>Get the sasUrl value.</p>

    <p></p>
  syntax:
    content: public String sasUrl()
    return:
      type: "26831127"
      description: <p>the sasUrl value </p>
- uid: com.microsoft.azure.management.website.implementation.api._azure_blob_storage_http_logs_config_1ab036e5bf0f48c3fd10954e7d9e654b82
  id: _azure_blob_storage_http_logs_config_1ab036e5bf0f48c3fd10954e7d9e654b82
  parent: com.microsoft.azure.management.website.implementation.api._azure_blob_storage_http_logs_config
  href: com.microsoft.azure.management.website.implementation.api._azure_blob_storage_http_logs_config.yml
  langs:
  - java
  name: withEnabled(Boolean enabled)
  fullName: AzureBlobStorageHttpLogsConfig com.microsoft.azure.management.website.implementation.api.AzureBlobStorageHttpLogsConfig.withEnabled(Boolean enabled)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/AzureBlobStorageHttpLogsConfig.java
    startLine: 86
  package: com.microsoft.azure.management.website.implementation.api
  summary: >-
    <p>Set the enabled value.</p>

    <p></p>
  syntax:
    content: public AzureBlobStorageHttpLogsConfig withEnabled(Boolean enabled)
    parameters:
    - id: enabled
      type: 866c2227
      description: <p>the enabled value to set </p>
    return:
      type: com.microsoft.azure.management.website.implementation.api._azure_blob_storage_http_logs_config
      description: <p>the <xref href="com.microsoft.azure.management.website.implementation.api._azure_blob_storage_http_logs_config" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.website.implementation.api._azure_blob_storage_http_logs_config_1a845056be292ee30ce588f6f959dcbc1a
  id: _azure_blob_storage_http_logs_config_1a845056be292ee30ce588f6f959dcbc1a
  parent: com.microsoft.azure.management.website.implementation.api._azure_blob_storage_http_logs_config
  href: com.microsoft.azure.management.website.implementation.api._azure_blob_storage_http_logs_config.yml
  langs:
  - java
  name: withRetentionInDays(Integer retentionInDays)
  fullName: AzureBlobStorageHttpLogsConfig com.microsoft.azure.management.website.implementation.api.AzureBlobStorageHttpLogsConfig.withRetentionInDays(Integer retentionInDays)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/AzureBlobStorageHttpLogsConfig.java
    startLine: 66
  package: com.microsoft.azure.management.website.implementation.api
  summary: >-
    <p>Set the retentionInDays value.</p>

    <p></p>
  syntax:
    content: public AzureBlobStorageHttpLogsConfig withRetentionInDays(Integer retentionInDays)
    parameters:
    - id: retentionInDays
      type: 08effaa0
      description: <p>the retentionInDays value to set </p>
    return:
      type: com.microsoft.azure.management.website.implementation.api._azure_blob_storage_http_logs_config
      description: <p>the <xref href="com.microsoft.azure.management.website.implementation.api._azure_blob_storage_http_logs_config" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.website.implementation.api._azure_blob_storage_http_logs_config_1a647bc90d8536039ae5d681975a46a4dc
  id: _azure_blob_storage_http_logs_config_1a647bc90d8536039ae5d681975a46a4dc
  parent: com.microsoft.azure.management.website.implementation.api._azure_blob_storage_http_logs_config
  href: com.microsoft.azure.management.website.implementation.api._azure_blob_storage_http_logs_config.yml
  langs:
  - java
  name: withSasUrl(String sasUrl)
  fullName: AzureBlobStorageHttpLogsConfig com.microsoft.azure.management.website.implementation.api.AzureBlobStorageHttpLogsConfig.withSasUrl(String sasUrl)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/AzureBlobStorageHttpLogsConfig.java
    startLine: 46
  package: com.microsoft.azure.management.website.implementation.api
  summary: >-
    <p>Set the sasUrl value.</p>

    <p></p>
  syntax:
    content: public AzureBlobStorageHttpLogsConfig withSasUrl(String sasUrl)
    parameters:
    - id: sasUrl
      type: "26831127"
      description: <p>the sasUrl value to set </p>
    return:
      type: com.microsoft.azure.management.website.implementation.api._azure_blob_storage_http_logs_config
      description: <p>the <xref href="com.microsoft.azure.management.website.implementation.api._azure_blob_storage_http_logs_config" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 08effaa0
  spec.java:
  - name: Integer
    fullName: Integer
- uid: 866c2227
  spec.java:
  - name: Boolean
    fullName: Boolean
- uid: com.microsoft.azure.management.website.implementation.api._azure_blob_storage_http_logs_config
  parent: com.microsoft.azure.management.website.implementation.api
  href: com.microsoft.azure.management.website.implementation.api._azure_blob_storage_http_logs_config.yml
  name: AzureBlobStorageHttpLogsConfig
  fullName: com.microsoft.azure.management.website.implementation.api.AzureBlobStorageHttpLogsConfig
  type: Class
  summary: <p>Http logs to azure blob storage configuration. </p>
  syntax: *o1
