items:
- uid: com.microsoft.azure.management.network.implementation._application_gateway_frontend_port_inner
  id: _application_gateway_frontend_port_inner
  parent: com.microsoft.azure.management.network.implementation
  children:
  - com.microsoft.azure.management.network.implementation._application_gateway_frontend_port_inner.etag()
  - com.microsoft.azure.management.network.implementation._application_gateway_frontend_port_inner.name()
  - com.microsoft.azure.management.network.implementation._application_gateway_frontend_port_inner.port()
  - com.microsoft.azure.management.network.implementation._application_gateway_frontend_port_inner.provisioningState()
  - com.microsoft.azure.management.network.implementation._application_gateway_frontend_port_inner.withEtag(String)
  - com.microsoft.azure.management.network.implementation._application_gateway_frontend_port_inner.withName(String)
  - com.microsoft.azure.management.network.implementation._application_gateway_frontend_port_inner.withPort(Integer)
  - com.microsoft.azure.management.network.implementation._application_gateway_frontend_port_inner.withProvisioningState(String)
  href: com.microsoft.azure.management.network.implementation._application_gateway_frontend_port_inner.yml
  langs:
  - java
  name: ApplicationGatewayFrontendPortInner
  fullName: com.microsoft.azure.management.network.implementation.ApplicationGatewayFrontendPortInner
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayFrontendPortInner.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayFrontendPortInner.java
    startLine: 18
  package: com.microsoft.azure.management.network.implementation
  summary: <p>Frontend Port of application gateway. </p>
  syntax: &o1
    content: public class ApplicationGatewayFrontendPortInner extends SubResource
  inheritance:
  - java.lang.Object
  - com.microsoft.azure._sub_resource
  inheritedMembers:
  - com.microsoft.azure._sub_resource.id()
  - com.microsoft.azure._sub_resource.withId(String)
- uid: com.microsoft.azure.management.network.implementation._application_gateway_frontend_port_inner.etag()
  id: etag()
  parent: com.microsoft.azure.management.network.implementation._application_gateway_frontend_port_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_frontend_port_inner.yml
  langs:
  - java
  name: etag()
  fullName: String com.microsoft.azure.management.network.implementation.ApplicationGatewayFrontendPortInner.etag()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayFrontendPortInner.java
    startLine: 108
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Get the etag value.</p>

    <p></p>
  syntax:
    content: public String etag()
    return:
      type: "26831127"
      description: <p>the etag value </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_frontend_port_inner.name()
  id: name()
  parent: com.microsoft.azure.management.network.implementation._application_gateway_frontend_port_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_frontend_port_inner.yml
  langs:
  - java
  name: name()
  fullName: String com.microsoft.azure.management.network.implementation.ApplicationGatewayFrontendPortInner.name()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayFrontendPortInner.java
    startLine: 88
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Get the name value.</p>

    <p></p>
  syntax:
    content: public String name()
    return:
      type: "26831127"
      description: <p>the name value </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_frontend_port_inner.port()
  id: port()
  parent: com.microsoft.azure.management.network.implementation._application_gateway_frontend_port_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_frontend_port_inner.yml
  langs:
  - java
  name: port()
  fullName: Integer com.microsoft.azure.management.network.implementation.ApplicationGatewayFrontendPortInner.port()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayFrontendPortInner.java
    startLine: 48
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Get the port value.</p>

    <p></p>
  syntax:
    content: public Integer port()
    return:
      type: 08effaa0
      description: <p>the port value </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_frontend_port_inner.provisioningState()
  id: provisioningState()
  parent: com.microsoft.azure.management.network.implementation._application_gateway_frontend_port_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_frontend_port_inner.yml
  langs:
  - java
  name: provisioningState()
  fullName: String com.microsoft.azure.management.network.implementation.ApplicationGatewayFrontendPortInner.provisioningState()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayFrontendPortInner.java
    startLine: 68
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Get the provisioningState value.</p>

    <p></p>
  syntax:
    content: public String provisioningState()
    return:
      type: "26831127"
      description: <p>the provisioningState value </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_frontend_port_inner.withEtag(String)
  id: withEtag(String)
  parent: com.microsoft.azure.management.network.implementation._application_gateway_frontend_port_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_frontend_port_inner.yml
  langs:
  - java
  name: withEtag(String etag)
  fullName: ApplicationGatewayFrontendPortInner com.microsoft.azure.management.network.implementation.ApplicationGatewayFrontendPortInner.withEtag(String etag)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayFrontendPortInner.java
    startLine: 118
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Set the etag value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewayFrontendPortInner withEtag(String etag)
    parameters:
    - id: etag
      type: "26831127"
      description: <p>the etag value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation._application_gateway_frontend_port_inner
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation._application_gateway_frontend_port_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_frontend_port_inner.withName(String)
  id: withName(String)
  parent: com.microsoft.azure.management.network.implementation._application_gateway_frontend_port_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_frontend_port_inner.yml
  langs:
  - java
  name: withName(String name)
  fullName: ApplicationGatewayFrontendPortInner com.microsoft.azure.management.network.implementation.ApplicationGatewayFrontendPortInner.withName(String name)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayFrontendPortInner.java
    startLine: 98
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Set the name value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewayFrontendPortInner withName(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>the name value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation._application_gateway_frontend_port_inner
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation._application_gateway_frontend_port_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_frontend_port_inner.withPort(Integer)
  id: withPort(Integer)
  parent: com.microsoft.azure.management.network.implementation._application_gateway_frontend_port_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_frontend_port_inner.yml
  langs:
  - java
  name: withPort(Integer port)
  fullName: ApplicationGatewayFrontendPortInner com.microsoft.azure.management.network.implementation.ApplicationGatewayFrontendPortInner.withPort(Integer port)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayFrontendPortInner.java
    startLine: 58
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Set the port value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewayFrontendPortInner withPort(Integer port)
    parameters:
    - id: port
      type: 08effaa0
      description: <p>the port value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation._application_gateway_frontend_port_inner
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation._application_gateway_frontend_port_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_frontend_port_inner.withProvisioningState(String)
  id: withProvisioningState(String)
  parent: com.microsoft.azure.management.network.implementation._application_gateway_frontend_port_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_frontend_port_inner.yml
  langs:
  - java
  name: withProvisioningState(String provisioningState)
  fullName: ApplicationGatewayFrontendPortInner com.microsoft.azure.management.network.implementation.ApplicationGatewayFrontendPortInner.withProvisioningState(String provisioningState)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayFrontendPortInner.java
    startLine: 78
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Set the provisioningState value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewayFrontendPortInner withProvisioningState(String provisioningState)
    parameters:
    - id: provisioningState
      type: "26831127"
      description: <p>the provisioningState value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation._application_gateway_frontend_port_inner
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation._application_gateway_frontend_port_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: 08effaa0
  spec.java:
  - name: Integer
    fullName: Integer
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure._sub_resource.id()
  parent: com.microsoft.azure._sub_resource
  href: com.microsoft.azure._sub_resource.yml
  name: id()
  fullName: String com.microsoft.azure.SubResource.id()
  type: Method
  summary: >-
    <p>Get the id value.</p>

    <p></p>
  syntax:
    content: public String id()
    return:
      type: "26831127"
      description: <p>the id value </p>
- uid: com.microsoft.azure._sub_resource.withId(String)
  parent: com.microsoft.azure._sub_resource
  href: com.microsoft.azure._sub_resource.yml
  name: withId(String id)
  fullName: SubResource com.microsoft.azure.SubResource.withId(String id)
  type: Method
  summary: >-
    <p>Set the id value.</p>

    <p></p>
  syntax:
    content: public SubResource withId(String id)
    parameters:
    - id: id
      type: "26831127"
      description: <p>the id value to set </p>
    return:
      type: com.microsoft.azure._sub_resource
      description: <p>the sub resource itself </p>
- uid: com.microsoft.azure._sub_resource
  parent: com.microsoft.azure
  href: com.microsoft.azure._sub_resource.yml
  name: SubResource
  fullName: com.microsoft.azure.SubResource
  type: Class
  summary: <p>The <xref href="com.microsoft.azure._sub_resource" data-throw-if-not-resolved="false"></xref> model. </p>
  syntax:
    content: public class SubResource
- uid: com.microsoft.azure.management.network.implementation._application_gateway_frontend_port_inner
  parent: com.microsoft.azure.management.network.implementation
  href: com.microsoft.azure.management.network.implementation._application_gateway_frontend_port_inner.yml
  name: ApplicationGatewayFrontendPortInner
  fullName: com.microsoft.azure.management.network.implementation.ApplicationGatewayFrontendPortInner
  type: Class
  summary: <p>Frontend Port of application gateway. </p>
  syntax: *o1
