items:
- uid: com.microsoft.azure.batch._application_operations
  id: _application_operations
  parent: com.microsoft.azure.batch
  children:
  - com.microsoft.azure.batch._application_operations.customBehaviors()
  - com.microsoft.azure.batch._application_operations.getApplication(String)
  - com.microsoft.azure.batch._application_operations.getApplication(String,Iterable< BatchClientBehavior >)
  - com.microsoft.azure.batch._application_operations.listApplications()
  - com.microsoft.azure.batch._application_operations.listApplications(Iterable< BatchClientBehavior >)
  - com.microsoft.azure.batch._application_operations.withCustomBehaviors(Collection< BatchClientBehavior >)
  href: com.microsoft.azure.batch._application_operations.yml
  langs:
  - java
  name: ApplicationOperations
  fullName: com.microsoft.azure.batch.ApplicationOperations
  type: Class
  source:
    remote: &o0
      path: azure-batch/src/main/java/com/microsoft/azure/batch/ApplicationOperations.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-batch/src/main/java/com/microsoft/azure/batch/ApplicationOperations.java
    startLine: 21
  package: com.microsoft.azure.batch
  syntax:
    content: public class ApplicationOperations implements IInheritedBehaviors
  inheritance:
  - java.lang.Object
  - com.microsoft.azure.batch._i_inherited_behaviors
  inheritedMembers:
  - com.microsoft.azure.batch._application_operations.ApplicationOperations(BatchClient,Collection< BatchClientBehavior >)
- uid: com.microsoft.azure.batch._application_operations.customBehaviors()
  id: customBehaviors()
  parent: com.microsoft.azure.batch._application_operations
  href: com.microsoft.azure.batch._application_operations.yml
  langs:
  - java
  name: customBehaviors()
  fullName: Collection<BatchClientBehavior> com.microsoft.azure.batch.ApplicationOperations.customBehaviors()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/ApplicationOperations.java
    startLine: 35
  package: com.microsoft.azure.batch
  syntax:
    content: public Collection< BatchClientBehavior > customBehaviors()
    return:
      type: 642418facom.microsoft.azure.batch._batch_client_behavior9ec3e006
  overridden: com.microsoft.azure.batch._i_inherited_behaviors.customBehaviors()
- uid: com.microsoft.azure.batch._application_operations.getApplication(String)
  id: getApplication(String)
  parent: com.microsoft.azure.batch._application_operations
  href: com.microsoft.azure.batch._application_operations.yml
  langs:
  - java
  name: getApplication(String applicationId)
  fullName: ApplicationSummary com.microsoft.azure.batch.ApplicationOperations.getApplication(String applicationId)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/ApplicationOperations.java
    startLine: 59
  package: com.microsoft.azure.batch
  syntax:
    content: public ApplicationSummary getApplication(String applicationId)
    parameters:
    - id: applicationId
      type: "26831127"
    return:
      type: com.microsoft.azure.batch.protocol.models._application_summary
- uid: com.microsoft.azure.batch._application_operations.getApplication(String,Iterable< BatchClientBehavior >)
  id: getApplication(String,Iterable< BatchClientBehavior >)
  parent: com.microsoft.azure.batch._application_operations
  href: com.microsoft.azure.batch._application_operations.yml
  langs:
  - java
  name: getApplication(String applicationId, Iterable< BatchClientBehavior > additionalBehaviors)
  fullName: ApplicationSummary com.microsoft.azure.batch.ApplicationOperations.getApplication(String applicationId, Iterable< BatchClientBehavior > additionalBehaviors)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/ApplicationOperations.java
    startLine: 63
  package: com.microsoft.azure.batch
  syntax:
    content: public ApplicationSummary getApplication(String applicationId, Iterable< BatchClientBehavior > additionalBehaviors)
    parameters:
    - id: applicationId
      type: "26831127"
    - id: additionalBehaviors
      type: ca2e68b6com.microsoft.azure.batch._batch_client_behavior9ec3e006
    return:
      type: com.microsoft.azure.batch.protocol.models._application_summary
- uid: com.microsoft.azure.batch._application_operations.listApplications()
  id: listApplications()
  parent: com.microsoft.azure.batch._application_operations
  href: com.microsoft.azure.batch._application_operations.yml
  langs:
  - java
  name: listApplications()
  fullName: List<ApplicationSummary> com.microsoft.azure.batch.ApplicationOperations.listApplications()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/ApplicationOperations.java
    startLine: 45
  package: com.microsoft.azure.batch
  syntax:
    content: public List< ApplicationSummary > listApplications()
    return:
      type: f6a6204dcom.microsoft.azure.batch.protocol.models._application_summary9ec3e006
- uid: com.microsoft.azure.batch._application_operations.listApplications(Iterable< BatchClientBehavior >)
  id: listApplications(Iterable< BatchClientBehavior >)
  parent: com.microsoft.azure.batch._application_operations
  href: com.microsoft.azure.batch._application_operations.yml
  langs:
  - java
  name: listApplications(Iterable< BatchClientBehavior > additionalBehaviors)
  fullName: List<ApplicationSummary> com.microsoft.azure.batch.ApplicationOperations.listApplications(Iterable< BatchClientBehavior > additionalBehaviors)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/ApplicationOperations.java
    startLine: 49
  package: com.microsoft.azure.batch
  syntax:
    content: public List< ApplicationSummary > listApplications(Iterable< BatchClientBehavior > additionalBehaviors)
    parameters:
    - id: additionalBehaviors
      type: ca2e68b6com.microsoft.azure.batch._batch_client_behavior9ec3e006
    return:
      type: f6a6204dcom.microsoft.azure.batch.protocol.models._application_summary9ec3e006
- uid: com.microsoft.azure.batch._application_operations.withCustomBehaviors(Collection< BatchClientBehavior >)
  id: withCustomBehaviors(Collection< BatchClientBehavior >)
  parent: com.microsoft.azure.batch._application_operations
  href: com.microsoft.azure.batch._application_operations.yml
  langs:
  - java
  name: withCustomBehaviors(Collection< BatchClientBehavior > behaviors)
  fullName: IInheritedBehaviors com.microsoft.azure.batch.ApplicationOperations.withCustomBehaviors(Collection< BatchClientBehavior > behaviors)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/ApplicationOperations.java
    startLine: 40
  package: com.microsoft.azure.batch
  syntax:
    content: public IInheritedBehaviors withCustomBehaviors(Collection< BatchClientBehavior > behaviors)
    parameters:
    - id: behaviors
      type: 642418facom.microsoft.azure.batch._batch_client_behavior9ec3e006
    return:
      type: com.microsoft.azure.batch._i_inherited_behaviors
  overridden: com.microsoft.azure.batch._i_inherited_behaviors.withCustomBehaviors(Collection< BatchClientBehavior >)
references:
- uid: 642418facom.microsoft.azure.batch._batch_client_behavior9ec3e006
  spec.java:
  - name: 'Collection< '
    fullName: 'Collection< '
  - uid: com.microsoft.azure.batch._batch_client_behavior
    name: BatchClientBehavior
    fullName: com.microsoft.azure.batch.BatchClientBehavior
    href: com.microsoft.azure.batch._batch_client_behavior.yml
  - name: " >"
    fullName: " >"
- uid: f6a6204dcom.microsoft.azure.batch.protocol.models._application_summary9ec3e006
  spec.java:
  - name: 'List< '
    fullName: 'List< '
  - uid: com.microsoft.azure.batch.protocol.models._application_summary
    name: ApplicationSummary
    fullName: com.microsoft.azure.batch.protocol.models.ApplicationSummary
    href: com.microsoft.azure.batch.protocol.models._application_summary.yml
  - name: " >"
    fullName: " >"
- uid: ca2e68b6com.microsoft.azure.batch._batch_client_behavior9ec3e006
  spec.java:
  - name: 'Iterable< '
    fullName: 'Iterable< '
  - uid: com.microsoft.azure.batch._batch_client_behavior
    name: BatchClientBehavior
    fullName: com.microsoft.azure.batch.BatchClientBehavior
    href: com.microsoft.azure.batch._batch_client_behavior.yml
  - name: " >"
    fullName: " >"
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.batch._application_operations.ApplicationOperations(BatchClient,Collection< BatchClientBehavior >)
- uid: com.microsoft.azure.batch._i_inherited_behaviors
  parent: com.microsoft.azure.batch
  href: com.microsoft.azure.batch._i_inherited_behaviors.yml
  name: IInheritedBehaviors
  fullName: com.microsoft.azure.batch.IInheritedBehaviors
  type: Interface
  syntax:
    content: public interface IInheritedBehaviors
- uid: com.microsoft.azure.batch._batch_client_behavior
  parent: com.microsoft.azure.batch
  href: com.microsoft.azure.batch._batch_client_behavior.yml
  name: BatchClientBehavior
  fullName: com.microsoft.azure.batch.BatchClientBehavior
  type: Class
  syntax:
    content: public class BatchClientBehavior
- uid: com.microsoft.azure.batch._batch_client
  parent: com.microsoft.azure.batch
  href: com.microsoft.azure.batch._batch_client.yml
  name: BatchClient
  fullName: com.microsoft.azure.batch.BatchClient
  type: Class
  syntax:
    content: public class BatchClient
- uid: com.microsoft.azure.batch._i_inherited_behaviors.customBehaviors()
  parent: com.microsoft.azure.batch._i_inherited_behaviors
  href: com.microsoft.azure.batch._i_inherited_behaviors.yml
  name: customBehaviors()
  fullName: Collection<BatchClientBehavior> com.microsoft.azure.batch.IInheritedBehaviors.customBehaviors()
  type: Method
  syntax:
    content: public Collection< BatchClientBehavior > customBehaviors()
    return:
      type: 642418facom.microsoft.azure.batch._batch_client_behavior9ec3e006
- uid: com.microsoft.azure.batch._i_inherited_behaviors.withCustomBehaviors(Collection< BatchClientBehavior >)
  parent: com.microsoft.azure.batch._i_inherited_behaviors
  href: com.microsoft.azure.batch._i_inherited_behaviors.yml
  name: withCustomBehaviors(Collection< BatchClientBehavior > behaviors)
  fullName: IInheritedBehaviors com.microsoft.azure.batch.IInheritedBehaviors.withCustomBehaviors(Collection< BatchClientBehavior > behaviors)
  type: Method
  syntax:
    content: public IInheritedBehaviors withCustomBehaviors(Collection< BatchClientBehavior > behaviors)
    parameters:
    - id: behaviors
      type: 642418facom.microsoft.azure.batch._batch_client_behavior9ec3e006
    return:
      type: com.microsoft.azure.batch._i_inherited_behaviors
- uid: com.microsoft.azure.batch.protocol.models._application_summary
  parent: com.microsoft.azure.batch.protocol.models
  href: com.microsoft.azure.batch.protocol.models._application_summary.yml
  name: ApplicationSummary
  fullName: com.microsoft.azure.batch.protocol.models.ApplicationSummary
  type: Class
  summary: <p>Contains information about an application in an <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> Batch account. </p>
  syntax:
    content: public class ApplicationSummary
- uid: com.microsoft.azure.batch.protocol.models._batch_error_exception
  parent: com.microsoft.azure.batch.protocol.models
  href: com.microsoft.azure.batch.protocol.models._batch_error_exception.yml
  name: BatchErrorException
  fullName: com.microsoft.azure.batch.protocol.models.BatchErrorException
  type: Class
  summary: <p>Exception thrown for an invalid response with <xref href="com.microsoft.azure.batch.protocol.models._batch_error" data-throw-if-not-resolved="false"></xref> information. </p>
  syntax:
    content: public class BatchErrorException
