items:
- uid: com.microsoft.azure.management.website.implementation.api._hosting_environment_collection_inner
  id: _hosting_environment_collection_inner
  parent: com.microsoft.azure.management.website.implementation.api
  children:
  - com.microsoft.azure.management.website.implementation.api._hosting_environment_collection_inner_1a65ad4d654f2a3985ad0c0695878814ab
  - com.microsoft.azure.management.website.implementation.api._hosting_environment_collection_inner_1a2bb87191bd3c68d5db1b81c9a7387322
  - com.microsoft.azure.management.website.implementation.api._hosting_environment_collection_inner_1a2de747d54f7852992c4349c76057ba22
  - com.microsoft.azure.management.website.implementation.api._hosting_environment_collection_inner_1a7868f2286d3805e0eec7728e1cca8027
  href: com.microsoft.azure.management.website.implementation.api._hosting_environment_collection_inner.yml
  langs:
  - java
  name: HostingEnvironmentCollectionInner
  fullName: com.microsoft.azure.management.website.implementation.api.HostingEnvironmentCollectionInner
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/HostingEnvironmentCollectionInner.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/HostingEnvironmentCollectionInner.java
    startLine: 13
  assemblies:
  - com.microsoft.azure.management.website.implementation.api
  package: com.microsoft.azure.management.website.implementation.api
  summary: <p>Collection of hosting environments (App Service Environments). </p>
  syntax: &o1
    content: public class HostingEnvironmentCollectionInner
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.website.implementation.api._hosting_environment_collection_inner_1a65ad4d654f2a3985ad0c0695878814ab
  id: _hosting_environment_collection_inner_1a65ad4d654f2a3985ad0c0695878814ab
  parent: com.microsoft.azure.management.website.implementation.api._hosting_environment_collection_inner
  href: com.microsoft.azure.management.website.implementation.api._hosting_environment_collection_inner.yml
  langs:
  - java
  name: nextLink()
  fullName: String com.microsoft.azure.management.website.implementation.api.HostingEnvironmentCollectionInner.nextLink()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/HostingEnvironmentCollectionInner.java
    startLine: 49
  assemblies:
  - com.microsoft.azure.management.website.implementation.api
  package: com.microsoft.azure.management.website.implementation.api
  summary: >-
    <p>Get the nextLink value.</p>

    <p></p>
  syntax:
    content: public String nextLink()
    return:
      type: "26831127"
      description: <p>the nextLink value </p>
- uid: com.microsoft.azure.management.website.implementation.api._hosting_environment_collection_inner_1a2bb87191bd3c68d5db1b81c9a7387322
  id: _hosting_environment_collection_inner_1a2bb87191bd3c68d5db1b81c9a7387322
  parent: com.microsoft.azure.management.website.implementation.api._hosting_environment_collection_inner
  href: com.microsoft.azure.management.website.implementation.api._hosting_environment_collection_inner.yml
  langs:
  - java
  name: value()
  fullName: List<HostingEnvironmentInner> com.microsoft.azure.management.website.implementation.api.HostingEnvironmentCollectionInner.value()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/HostingEnvironmentCollectionInner.java
    startLine: 29
  assemblies:
  - com.microsoft.azure.management.website.implementation.api
  package: com.microsoft.azure.management.website.implementation.api
  summary: >-
    <p>Get the value value.</p>

    <p></p>
  syntax:
    content: public List< HostingEnvironmentInner > value()
    return:
      type: f6a6204dcom.microsoft.azure.management.website.implementation.api._hosting_environment_inner9ec3e006
      description: <p>the value value </p>
- uid: com.microsoft.azure.management.website.implementation.api._hosting_environment_collection_inner_1a2de747d54f7852992c4349c76057ba22
  id: _hosting_environment_collection_inner_1a2de747d54f7852992c4349c76057ba22
  parent: com.microsoft.azure.management.website.implementation.api._hosting_environment_collection_inner
  href: com.microsoft.azure.management.website.implementation.api._hosting_environment_collection_inner.yml
  langs:
  - java
  name: withNextLink(String nextLink)
  fullName: HostingEnvironmentCollectionInner com.microsoft.azure.management.website.implementation.api.HostingEnvironmentCollectionInner.withNextLink(String nextLink)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/HostingEnvironmentCollectionInner.java
    startLine: 59
  assemblies:
  - com.microsoft.azure.management.website.implementation.api
  package: com.microsoft.azure.management.website.implementation.api
  summary: >-
    <p>Set the nextLink value.</p>

    <p></p>
  syntax:
    content: public HostingEnvironmentCollectionInner withNextLink(String nextLink)
    parameters:
    - id: nextLink
      type: "26831127"
      description: <p>the nextLink value to set </p>
    return:
      type: com.microsoft.azure.management.website.implementation.api._hosting_environment_collection_inner
      description: <p>the <xref href="com.microsoft.azure.management.website.implementation.api._hosting_environment_collection_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.website.implementation.api._hosting_environment_collection_inner_1a7868f2286d3805e0eec7728e1cca8027
  id: _hosting_environment_collection_inner_1a7868f2286d3805e0eec7728e1cca8027
  parent: com.microsoft.azure.management.website.implementation.api._hosting_environment_collection_inner
  href: com.microsoft.azure.management.website.implementation.api._hosting_environment_collection_inner.yml
  langs:
  - java
  name: withValue(List< HostingEnvironmentInner > value)
  fullName: HostingEnvironmentCollectionInner com.microsoft.azure.management.website.implementation.api.HostingEnvironmentCollectionInner.withValue(List< HostingEnvironmentInner > value)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/HostingEnvironmentCollectionInner.java
    startLine: 39
  assemblies:
  - com.microsoft.azure.management.website.implementation.api
  package: com.microsoft.azure.management.website.implementation.api
  summary: >-
    <p>Set the value value.</p>

    <p></p>
  syntax:
    content: public HostingEnvironmentCollectionInner withValue(List< HostingEnvironmentInner > value)
    parameters:
    - id: value
      type: f6a6204dcom.microsoft.azure.management.website.implementation.api._hosting_environment_inner9ec3e006
      description: <p>the value value to set </p>
    return:
      type: com.microsoft.azure.management.website.implementation.api._hosting_environment_collection_inner
      description: <p>the <xref href="com.microsoft.azure.management.website.implementation.api._hosting_environment_collection_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: f6a6204dcom.microsoft.azure.management.website.implementation.api._hosting_environment_inner9ec3e006
  spec.java:
  - name: 'List< '
    fullName: 'List< '
  - uid: com.microsoft.azure.management.website.implementation.api._hosting_environment_inner
    name: HostingEnvironmentInner
    fullName: com.microsoft.azure.management.website.implementation.api.HostingEnvironmentInner
    href: com.microsoft.azure.management.website.implementation.api._hosting_environment_inner.yml
  - name: ' >'
    fullName: ' >'
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.management.website.implementation.api._hosting_environment_inner
  parent: com.microsoft.azure.management.website.implementation.api
  href: com.microsoft.azure.management.website.implementation.api._hosting_environment_inner.yml
  name: HostingEnvironmentInner
  fullName: com.microsoft.azure.management.website.implementation.api.HostingEnvironmentInner
  type: Class
  summary: <p>Description of an hostingEnvironment (App Service Environment). </p>
  syntax:
    content: public class HostingEnvironmentInner
- uid: com.microsoft.azure.management.website.implementation.api._hosting_environment_collection_inner
  parent: com.microsoft.azure.management.website.implementation.api
  href: com.microsoft.azure.management.website.implementation.api._hosting_environment_collection_inner.yml
  name: HostingEnvironmentCollectionInner
  fullName: com.microsoft.azure.management.website.implementation.api.HostingEnvironmentCollectionInner
  type: Class
  summary: <p>Collection of hosting environments (App Service Environments). </p>
  syntax: *o1
