items:
- uid: com.microsoft.azure.management.website._slot_config_names
  id: _slot_config_names
  parent: com.microsoft.azure.management.website
  children:
  - com.microsoft.azure.management.website._slot_config_names.appSettingNames()
  - com.microsoft.azure.management.website._slot_config_names.connectionStringNames()
  - classcom.microsoft.azure.management.website._slot_config_names.withAppSettingNames(List< String >)
  - classcom.microsoft.azure.management.website._slot_config_names.withConnectionStringNames(List< String >)
  href: com.microsoft.azure.management.website._slot_config_names.yml
  langs:
  - java
  name: SlotConfigNames
  fullName: com.microsoft.azure.management.website.SlotConfigNames
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/SlotConfigNames.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/SlotConfigNames.java
    startLine: 18
  package: com.microsoft.azure.management.website
  summary: <p>Class containing names for connection strings and application settings to be marked as sticky to the slot and not moved during swap operation This is valid for all deployment slots under the site. </p>
  syntax: &o1
    content: public class SlotConfigNames
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.website._slot_config_names.appSettingNames()
  id: appSettingNames()
  parent: com.microsoft.azure.management.website._slot_config_names
  href: com.microsoft.azure.management.website._slot_config_names.yml
  langs:
  - java
  name: appSettingNames()
  fullName: List<String> com.microsoft.azure.management.website.SlotConfigNames.appSettingNames()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/SlotConfigNames.java
    startLine: 54
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Get the appSettingNames value.</p>

    <p></p>
  syntax:
    content: public List< String > appSettingNames()
    return:
      type: f35af49b
      description: <p>the appSettingNames value </p>
- uid: com.microsoft.azure.management.website._slot_config_names.connectionStringNames()
  id: connectionStringNames()
  parent: com.microsoft.azure.management.website._slot_config_names
  href: com.microsoft.azure.management.website._slot_config_names.yml
  langs:
  - java
  name: connectionStringNames()
  fullName: List<String> com.microsoft.azure.management.website.SlotConfigNames.connectionStringNames()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/SlotConfigNames.java
    startLine: 34
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Get the connectionStringNames value.</p>

    <p></p>
  syntax:
    content: public List< String > connectionStringNames()
    return:
      type: f35af49b
      description: <p>the connectionStringNames value </p>
- uid: classcom.microsoft.azure.management.website._slot_config_names.withAppSettingNames(List< String >)
  id: withAppSettingNames(List< String >)
  parent: com.microsoft.azure.management.website._slot_config_names
  href: com.microsoft.azure.management.website._slot_config_names.yml
  langs:
  - java
  name: withAppSettingNames(List< String > appSettingNames)
  fullName: SlotConfigNames com.microsoft.azure.management.website.SlotConfigNames.withAppSettingNames(List< String > appSettingNames)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/SlotConfigNames.java
    startLine: 64
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Set the appSettingNames value.</p>

    <p></p>
  syntax:
    content: public SlotConfigNames withAppSettingNames(List< String > appSettingNames)
    parameters:
    - id: appSettingNames
      type: f35af49b
      description: <p>the appSettingNames value to set </p>
    return:
      type: com.microsoft.azure.management.website._slot_config_names
      description: <p>the <xref href="com.microsoft.azure.management.website._slot_config_names" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: classcom.microsoft.azure.management.website._slot_config_names.withConnectionStringNames(List< String >)
  id: withConnectionStringNames(List< String >)
  parent: com.microsoft.azure.management.website._slot_config_names
  href: com.microsoft.azure.management.website._slot_config_names.yml
  langs:
  - java
  name: withConnectionStringNames(List< String > connectionStringNames)
  fullName: SlotConfigNames com.microsoft.azure.management.website.SlotConfigNames.withConnectionStringNames(List< String > connectionStringNames)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/SlotConfigNames.java
    startLine: 44
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Set the connectionStringNames value.</p>

    <p></p>
  syntax:
    content: public SlotConfigNames withConnectionStringNames(List< String > connectionStringNames)
    parameters:
    - id: connectionStringNames
      type: f35af49b
      description: <p>the connectionStringNames value to set </p>
    return:
      type: com.microsoft.azure.management.website._slot_config_names
      description: <p>the <xref href="com.microsoft.azure.management.website._slot_config_names" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: f35af49b
  spec.java:
  - name: List< String >
    fullName: List< String >
- uid: com.microsoft.azure.management.website._slot_config_names
  parent: com.microsoft.azure.management.website
  href: com.microsoft.azure.management.website._slot_config_names.yml
  name: SlotConfigNames
  fullName: com.microsoft.azure.management.website.SlotConfigNames
  type: Class
  summary: <p>Class containing names for connection strings and application settings to be marked as sticky to the slot and not moved during swap operation This is valid for all deployment slots under the site. </p>
  syntax: *o1
