items:
- uid: com.microsoft.azure.management.website.implementation.api._virtual_application
  id: _virtual_application
  parent: com.microsoft.azure.management.website.implementation.api
  children:
  - com.microsoft.azure.management.website.implementation.api._virtual_application_1a092e2c742ea30882f032bc6f9f3adbaf
  - com.microsoft.azure.management.website.implementation.api._virtual_application_1a62e2a56f3b98c9c964e2119700d05176
  - com.microsoft.azure.management.website.implementation.api._virtual_application_1a5dda29cfc3211add73992de2d515ea82
  - com.microsoft.azure.management.website.implementation.api._virtual_application_1acc5cb073a34c7e6b616ece4502f3aa97
  - com.microsoft.azure.management.website.implementation.api._virtual_application_1ace5beed3860875f8d2f0dd2a4321aecd
  - com.microsoft.azure.management.website.implementation.api._virtual_application_1a444bc16d47a2884675fe3c54ecd5e1e5
  - com.microsoft.azure.management.website.implementation.api._virtual_application_1a3654742f5f8a7d610f4232e7fa694cf7
  - com.microsoft.azure.management.website.implementation.api._virtual_application_1a000eacccfae1d4a5bed66f17a7949cf5
  href: com.microsoft.azure.management.website.implementation.api._virtual_application.yml
  langs:
  - java
  name: VirtualApplication
  fullName: com.microsoft.azure.management.website.implementation.api.VirtualApplication
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/VirtualApplication.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/VirtualApplication.java
    startLine: 13
  package: com.microsoft.azure.management.website.implementation.api
  summary: <p>The <xref href="com.microsoft.azure.management.website.implementation.api._virtual_application" data-throw-if-not-resolved="false"></xref> model. </p>
  syntax: &o1
    content: public class VirtualApplication
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.website.implementation.api._virtual_application_1a092e2c742ea30882f032bc6f9f3adbaf
  id: _virtual_application_1a092e2c742ea30882f032bc6f9f3adbaf
  parent: com.microsoft.azure.management.website.implementation.api._virtual_application
  href: com.microsoft.azure.management.website.implementation.api._virtual_application.yml
  langs:
  - java
  name: physicalPath()
  fullName: String com.microsoft.azure.management.website.implementation.api.VirtualApplication.physicalPath()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/VirtualApplication.java
    startLine: 59
  package: com.microsoft.azure.management.website.implementation.api
  summary: >-
    <p>Get the physicalPath value.</p>

    <p></p>
  syntax:
    content: public String physicalPath()
    return:
      type: "26831127"
      description: <p>the physicalPath value </p>
- uid: com.microsoft.azure.management.website.implementation.api._virtual_application_1a62e2a56f3b98c9c964e2119700d05176
  id: _virtual_application_1a62e2a56f3b98c9c964e2119700d05176
  parent: com.microsoft.azure.management.website.implementation.api._virtual_application
  href: com.microsoft.azure.management.website.implementation.api._virtual_application.yml
  langs:
  - java
  name: preloadEnabled()
  fullName: Boolean com.microsoft.azure.management.website.implementation.api.VirtualApplication.preloadEnabled()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/VirtualApplication.java
    startLine: 79
  package: com.microsoft.azure.management.website.implementation.api
  summary: >-
    <p>Get the preloadEnabled value.</p>

    <p></p>
  syntax:
    content: public Boolean preloadEnabled()
    return:
      type: 866c2227
      description: <p>the preloadEnabled value </p>
- uid: com.microsoft.azure.management.website.implementation.api._virtual_application_1a5dda29cfc3211add73992de2d515ea82
  id: _virtual_application_1a5dda29cfc3211add73992de2d515ea82
  parent: com.microsoft.azure.management.website.implementation.api._virtual_application
  href: com.microsoft.azure.management.website.implementation.api._virtual_application.yml
  langs:
  - java
  name: virtualDirectories()
  fullName: List<VirtualDirectory> com.microsoft.azure.management.website.implementation.api.VirtualApplication.virtualDirectories()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/VirtualApplication.java
    startLine: 99
  package: com.microsoft.azure.management.website.implementation.api
  summary: >-
    <p>Get the virtualDirectories value.</p>

    <p></p>
  syntax:
    content: public List< VirtualDirectory > virtualDirectories()
    return:
      type: f6a6204dcom.microsoft.azure.management.website.implementation.api._virtual_directory9ec3e006
      description: <p>the virtualDirectories value </p>
- uid: com.microsoft.azure.management.website.implementation.api._virtual_application_1acc5cb073a34c7e6b616ece4502f3aa97
  id: _virtual_application_1acc5cb073a34c7e6b616ece4502f3aa97
  parent: com.microsoft.azure.management.website.implementation.api._virtual_application
  href: com.microsoft.azure.management.website.implementation.api._virtual_application.yml
  langs:
  - java
  name: virtualPath()
  fullName: String com.microsoft.azure.management.website.implementation.api.VirtualApplication.virtualPath()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/VirtualApplication.java
    startLine: 39
  package: com.microsoft.azure.management.website.implementation.api
  summary: >-
    <p>Get the virtualPath value.</p>

    <p></p>
  syntax:
    content: public String virtualPath()
    return:
      type: "26831127"
      description: <p>the virtualPath value </p>
- uid: com.microsoft.azure.management.website.implementation.api._virtual_application_1ace5beed3860875f8d2f0dd2a4321aecd
  id: _virtual_application_1ace5beed3860875f8d2f0dd2a4321aecd
  parent: com.microsoft.azure.management.website.implementation.api._virtual_application
  href: com.microsoft.azure.management.website.implementation.api._virtual_application.yml
  langs:
  - java
  name: withPhysicalPath(String physicalPath)
  fullName: VirtualApplication com.microsoft.azure.management.website.implementation.api.VirtualApplication.withPhysicalPath(String physicalPath)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/VirtualApplication.java
    startLine: 69
  package: com.microsoft.azure.management.website.implementation.api
  summary: >-
    <p>Set the physicalPath value.</p>

    <p></p>
  syntax:
    content: public VirtualApplication withPhysicalPath(String physicalPath)
    parameters:
    - id: physicalPath
      type: "26831127"
      description: <p>the physicalPath value to set </p>
    return:
      type: com.microsoft.azure.management.website.implementation.api._virtual_application
      description: <p>the <xref href="com.microsoft.azure.management.website.implementation.api._virtual_application" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.website.implementation.api._virtual_application_1a444bc16d47a2884675fe3c54ecd5e1e5
  id: _virtual_application_1a444bc16d47a2884675fe3c54ecd5e1e5
  parent: com.microsoft.azure.management.website.implementation.api._virtual_application
  href: com.microsoft.azure.management.website.implementation.api._virtual_application.yml
  langs:
  - java
  name: withPreloadEnabled(Boolean preloadEnabled)
  fullName: VirtualApplication com.microsoft.azure.management.website.implementation.api.VirtualApplication.withPreloadEnabled(Boolean preloadEnabled)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/VirtualApplication.java
    startLine: 89
  package: com.microsoft.azure.management.website.implementation.api
  summary: >-
    <p>Set the preloadEnabled value.</p>

    <p></p>
  syntax:
    content: public VirtualApplication withPreloadEnabled(Boolean preloadEnabled)
    parameters:
    - id: preloadEnabled
      type: 866c2227
      description: <p>the preloadEnabled value to set </p>
    return:
      type: com.microsoft.azure.management.website.implementation.api._virtual_application
      description: <p>the <xref href="com.microsoft.azure.management.website.implementation.api._virtual_application" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.website.implementation.api._virtual_application_1a3654742f5f8a7d610f4232e7fa694cf7
  id: _virtual_application_1a3654742f5f8a7d610f4232e7fa694cf7
  parent: com.microsoft.azure.management.website.implementation.api._virtual_application
  href: com.microsoft.azure.management.website.implementation.api._virtual_application.yml
  langs:
  - java
  name: withVirtualDirectories(List< VirtualDirectory > virtualDirectories)
  fullName: VirtualApplication com.microsoft.azure.management.website.implementation.api.VirtualApplication.withVirtualDirectories(List< VirtualDirectory > virtualDirectories)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/VirtualApplication.java
    startLine: 109
  package: com.microsoft.azure.management.website.implementation.api
  summary: >-
    <p>Set the virtualDirectories value.</p>

    <p></p>
  syntax:
    content: public VirtualApplication withVirtualDirectories(List< VirtualDirectory > virtualDirectories)
    parameters:
    - id: virtualDirectories
      type: f6a6204dcom.microsoft.azure.management.website.implementation.api._virtual_directory9ec3e006
      description: <p>the virtualDirectories value to set </p>
    return:
      type: com.microsoft.azure.management.website.implementation.api._virtual_application
      description: <p>the <xref href="com.microsoft.azure.management.website.implementation.api._virtual_application" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.website.implementation.api._virtual_application_1a000eacccfae1d4a5bed66f17a7949cf5
  id: _virtual_application_1a000eacccfae1d4a5bed66f17a7949cf5
  parent: com.microsoft.azure.management.website.implementation.api._virtual_application
  href: com.microsoft.azure.management.website.implementation.api._virtual_application.yml
  langs:
  - java
  name: withVirtualPath(String virtualPath)
  fullName: VirtualApplication com.microsoft.azure.management.website.implementation.api.VirtualApplication.withVirtualPath(String virtualPath)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/VirtualApplication.java
    startLine: 49
  package: com.microsoft.azure.management.website.implementation.api
  summary: >-
    <p>Set the virtualPath value.</p>

    <p></p>
  syntax:
    content: public VirtualApplication withVirtualPath(String virtualPath)
    parameters:
    - id: virtualPath
      type: "26831127"
      description: <p>the virtualPath value to set </p>
    return:
      type: com.microsoft.azure.management.website.implementation.api._virtual_application
      description: <p>the <xref href="com.microsoft.azure.management.website.implementation.api._virtual_application" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 866c2227
  spec.java:
  - name: Boolean
    fullName: Boolean
- uid: f6a6204dcom.microsoft.azure.management.website.implementation.api._virtual_directory9ec3e006
  spec.java:
  - name: 'List< '
    fullName: 'List< '
  - uid: com.microsoft.azure.management.website.implementation.api._virtual_directory
    name: VirtualDirectory
    fullName: com.microsoft.azure.management.website.implementation.api.VirtualDirectory
    href: com.microsoft.azure.management.website.implementation.api._virtual_directory.yml
  - name: ' >'
    fullName: ' >'
- uid: com.microsoft.azure.management.website.implementation.api._virtual_directory
  parent: com.microsoft.azure.management.website.implementation.api
  href: com.microsoft.azure.management.website.implementation.api._virtual_directory.yml
  name: VirtualDirectory
  fullName: com.microsoft.azure.management.website.implementation.api.VirtualDirectory
  type: Class
  summary: <p>The <xref href="com.microsoft.azure.management.website.implementation.api._virtual_directory" data-throw-if-not-resolved="false"></xref> model. </p>
  syntax:
    content: public class VirtualDirectory
- uid: com.microsoft.azure.management.website.implementation.api._virtual_application
  parent: com.microsoft.azure.management.website.implementation.api
  href: com.microsoft.azure.management.website.implementation.api._virtual_application.yml
  name: VirtualApplication
  fullName: com.microsoft.azure.management.website.implementation.api.VirtualApplication
  type: Class
  summary: <p>The <xref href="com.microsoft.azure.management.website.implementation.api._virtual_application" data-throw-if-not-resolved="false"></xref> model. </p>
  syntax: *o1
