items:
- uid: com.microsoft.azure.credentials._application_token_credentials
  id: _application_token_credentials
  parent: com.microsoft.azure.credentials
  children:
  - com.microsoft.azure.credentials._application_token_credentials.ApplicationTokenCredentials(String,String,String,AzureEnvironment)
  - com.microsoft.azure.credentials._application_token_credentials.defaultSubscriptionId()
  - com.microsoft.azure.credentials._application_token_credentials.fromFile(File)
  - com.microsoft.azure.credentials._application_token_credentials.getClientId()
  - com.microsoft.azure.credentials._application_token_credentials.getDomain()
  - com.microsoft.azure.credentials._application_token_credentials.getEnvironment()
  - com.microsoft.azure.credentials._application_token_credentials.getSecret()
  - com.microsoft.azure.credentials._application_token_credentials.getToken()
  - com.microsoft.azure.credentials._application_token_credentials.refreshToken()
  - com.microsoft.azure.credentials._application_token_credentials.withDefaultSubscriptionId(String)
  href: com.microsoft.azure.credentials._application_token_credentials.yml
  langs:
  - java
  name: ApplicationTokenCredentials
  fullName: com.microsoft.azure.credentials.ApplicationTokenCredentials
  type: Class
  source:
    remote: &o0
      path: runtimes/azure-client-authentication/src/main/java/com/microsoft/azure/credentials/ApplicationTokenCredentials.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: runtimes/azure-client-authentication/src/main/java/com/microsoft/azure/credentials/ApplicationTokenCredentials.java
    startLine: 25
  package: com.microsoft.azure.credentials
  summary: <p>Token based credentials for use with a REST Service Client. </p>
  syntax: &o1
    content: public class ApplicationTokenCredentials extends TokenCredentials
  inheritance:
  - java.lang.Object
  - com.microsoft.rest.credentials._service_client_credentials
  - com.microsoft.rest.credentials._token_credentials
  inheritedMembers:
  - com.microsoft.rest.credentials._token_credentials.applyCredentialsFilter(OkHttpClient.Builder)
  - com.microsoft.rest.credentials._token_credentials.getScheme()
  - com.microsoft.rest.credentials._token_credentials.scheme()
  - com.microsoft.rest.credentials._token_credentials.setToken(String)
  - com.microsoft.rest.credentials._token_credentials.token()
  - com.microsoft.rest.credentials._token_credentials.TokenCredentials(String,String)
- uid: com.microsoft.azure.credentials._application_token_credentials.ApplicationTokenCredentials(String,String,String,AzureEnvironment)
  id: ApplicationTokenCredentials(String,String,String,AzureEnvironment)
  parent: com.microsoft.azure.credentials._application_token_credentials
  href: com.microsoft.azure.credentials._application_token_credentials.yml
  langs:
  - java
  name: ApplicationTokenCredentials(String clientId, String domain, String secret, AzureEnvironment environment)
  fullName: com.microsoft.azure.credentials.ApplicationTokenCredentials.ApplicationTokenCredentials(String clientId, String domain, String secret, AzureEnvironment environment)
  type: Constructor
  source:
    remote: *o0
    path: runtimes/azure-client-authentication/src/main/java/com/microsoft/azure/credentials/ApplicationTokenCredentials.java
    startLine: 48
  package: com.microsoft.azure.credentials
  summary: >-
    <p>Initializes a new instance of the <xref href="com.microsoft.azure.credentials._user_token_credentials" data-throw-if-not-resolved="false"></xref>.</p>

    <p></p>
  syntax:
    content: public ApplicationTokenCredentials(String clientId, String domain, String secret, AzureEnvironment environment)
    parameters:
    - id: clientId
      type: "26831127"
      description: <p>the active directory application client id. </p>
    - id: domain
      type: "26831127"
      description: <p>the domain or tenant id containing this application. </p>
    - id: secret
      type: "26831127"
      description: <p>the authentication secret for the application. </p>
    - id: environment
      type: com.microsoft.azure.credentials._azure_environment
      description: <p>the <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> environment to authenticate with. If null is provided, <xref href="com.microsoft.azure.credentials._azure_environment.AZURE()" data-throw-if-not-resolved="false"></xref> will be used. </p>
- uid: com.microsoft.azure.credentials._application_token_credentials.defaultSubscriptionId()
  id: defaultSubscriptionId()
  parent: com.microsoft.azure.credentials._application_token_credentials
  href: com.microsoft.azure.credentials._application_token_credentials.yml
  langs:
  - java
  name: defaultSubscriptionId()
  fullName: String com.microsoft.azure.credentials.ApplicationTokenCredentials.defaultSubscriptionId()
  type: Method
  source:
    remote: *o0
    path: runtimes/azure-client-authentication/src/main/java/com/microsoft/azure/credentials/ApplicationTokenCredentials.java
    startLine: 95
  package: com.microsoft.azure.credentials
  syntax:
    content: public String defaultSubscriptionId()
    return:
      type: "26831127"
      description: <p>The default subscription ID, if any </p>
- uid: com.microsoft.azure.credentials._application_token_credentials.fromFile(File)
  id: fromFile(File)
  parent: com.microsoft.azure.credentials._application_token_credentials
  href: com.microsoft.azure.credentials._application_token_credentials.yml
  langs:
  - java
  name: fromFile(File credentialsFile)
  fullName: static ApplicationTokenCredentials com.microsoft.azure.credentials.ApplicationTokenCredentials.fromFile(File credentialsFile)
  type: Method
  source:
    remote: *o0
    path: runtimes/azure-client-authentication/src/main/java/com/microsoft/azure/credentials/ApplicationTokenCredentials.java
    startLine: 126
  package: com.microsoft.azure.credentials
  summary: >-
    <p>Initializes the credentials based on the provided credentials file.</p>

    <p></p>
  syntax:
    content: public static ApplicationTokenCredentials fromFile(File credentialsFile)
    parameters:
    - id: credentialsFile
      type: 8291270b
      description: '<p>A file with credentials, using the standard Java properties format. and the following keys: subscription=&lt;subscription-id&gt; tenant=&lt;tenant-id&gt; client=&lt;client-id&gt; key=&lt;client-key&gt; managementURI=&lt;management-URI&gt; baseURL=&lt;base-URL&gt; authURL=&lt;authentication-URL&gt;</p>'
    return:
      type: com.microsoft.azure.credentials._application_token_credentials
      description: <p>The credentials based on the file. </p>
  exceptions:
  - type: cbf33bbe
    description: <p>exception thrown from file access errors. </p>
- uid: com.microsoft.azure.credentials._application_token_credentials.getClientId()
  id: getClientId()
  parent: com.microsoft.azure.credentials._application_token_credentials
  href: com.microsoft.azure.credentials._application_token_credentials.yml
  langs:
  - java
  name: getClientId()
  fullName: String com.microsoft.azure.credentials.ApplicationTokenCredentials.getClientId()
  type: Method
  source:
    remote: *o0
    path: runtimes/azure-client-authentication/src/main/java/com/microsoft/azure/credentials/ApplicationTokenCredentials.java
    startLine: 163
  package: com.microsoft.azure.credentials
  summary: >-
    <p>Gets the active directory application client id.</p>

    <p></p>
  syntax:
    content: public String getClientId()
    return:
      type: "26831127"
      description: <p>the active directory application client id. </p>
- uid: com.microsoft.azure.credentials._application_token_credentials.getDomain()
  id: getDomain()
  parent: com.microsoft.azure.credentials._application_token_credentials
  href: com.microsoft.azure.credentials._application_token_credentials.yml
  langs:
  - java
  name: getDomain()
  fullName: String com.microsoft.azure.credentials.ApplicationTokenCredentials.getDomain()
  type: Method
  source:
    remote: *o0
    path: runtimes/azure-client-authentication/src/main/java/com/microsoft/azure/credentials/ApplicationTokenCredentials.java
    startLine: 172
  package: com.microsoft.azure.credentials
  summary: >-
    <p>Gets the tenant or domain the containing the application.</p>

    <p></p>
  syntax:
    content: public String getDomain()
    return:
      type: "26831127"
      description: <p>the tenant or domain the containing the application. </p>
- uid: com.microsoft.azure.credentials._application_token_credentials.getEnvironment()
  id: getEnvironment()
  parent: com.microsoft.azure.credentials._application_token_credentials
  href: com.microsoft.azure.credentials._application_token_credentials.yml
  langs:
  - java
  name: getEnvironment()
  fullName: AzureEnvironment com.microsoft.azure.credentials.ApplicationTokenCredentials.getEnvironment()
  type: Method
  source:
    remote: *o0
    path: runtimes/azure-client-authentication/src/main/java/com/microsoft/azure/credentials/ApplicationTokenCredentials.java
    startLine: 190
  package: com.microsoft.azure.credentials
  summary: >-
    <p>Gets the <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> environment to authenticate with.</p>

    <p></p>
  syntax:
    content: public AzureEnvironment getEnvironment()
    return:
      type: com.microsoft.azure.credentials._azure_environment
      description: <p>the <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> environment to authenticate with. </p>
- uid: com.microsoft.azure.credentials._application_token_credentials.getSecret()
  id: getSecret()
  parent: com.microsoft.azure.credentials._application_token_credentials
  href: com.microsoft.azure.credentials._application_token_credentials.yml
  langs:
  - java
  name: getSecret()
  fullName: String com.microsoft.azure.credentials.ApplicationTokenCredentials.getSecret()
  type: Method
  source:
    remote: *o0
    path: runtimes/azure-client-authentication/src/main/java/com/microsoft/azure/credentials/ApplicationTokenCredentials.java
    startLine: 181
  package: com.microsoft.azure.credentials
  summary: >-
    <p>Gets the authentication secret for the application.</p>

    <p></p>
  syntax:
    content: public String getSecret()
    return:
      type: "26831127"
      description: <p>the authentication secret for the application. </p>
- uid: com.microsoft.azure.credentials._application_token_credentials.getToken()
  id: getToken()
  parent: com.microsoft.azure.credentials._application_token_credentials
  href: com.microsoft.azure.credentials._application_token_credentials.yml
  langs:
  - java
  name: getToken()
  fullName: String com.microsoft.azure.credentials.ApplicationTokenCredentials.getToken()
  type: Method
  source:
    remote: *o0
    path: runtimes/azure-client-authentication/src/main/java/com/microsoft/azure/credentials/ApplicationTokenCredentials.java
    startLine: 195
  package: com.microsoft.azure.credentials
  syntax:
    content: public String getToken()
    return:
      type: "26831127"
- uid: com.microsoft.azure.credentials._application_token_credentials.refreshToken()
  id: refreshToken()
  parent: com.microsoft.azure.credentials._application_token_credentials
  href: com.microsoft.azure.credentials._application_token_credentials.yml
  langs:
  - java
  name: refreshToken()
  fullName: void com.microsoft.azure.credentials.ApplicationTokenCredentials.refreshToken()
  type: Method
  source:
    remote: *o0
    path: runtimes/azure-client-authentication/src/main/java/com/microsoft/azure/credentials/ApplicationTokenCredentials.java
    startLine: 204
  package: com.microsoft.azure.credentials
  syntax:
    content: public void refreshToken()
- uid: com.microsoft.azure.credentials._application_token_credentials.withDefaultSubscriptionId(String)
  id: withDefaultSubscriptionId(String)
  parent: com.microsoft.azure.credentials._application_token_credentials
  href: com.microsoft.azure.credentials._application_token_credentials.yml
  langs:
  - java
  name: withDefaultSubscriptionId(String subscriptionId)
  fullName: ApplicationTokenCredentials com.microsoft.azure.credentials.ApplicationTokenCredentials.withDefaultSubscriptionId(String subscriptionId)
  type: Method
  source:
    remote: *o0
    path: runtimes/azure-client-authentication/src/main/java/com/microsoft/azure/credentials/ApplicationTokenCredentials.java
    startLine: 105
  package: com.microsoft.azure.credentials
  summary: >-
    <p>Set default subscription ID.</p>

    <p></p>
  syntax:
    content: public ApplicationTokenCredentials withDefaultSubscriptionId(String subscriptionId)
    parameters:
    - id: subscriptionId
      type: "26831127"
      description: <p>the default subscription ID. </p>
    return:
      type: com.microsoft.azure.credentials._application_token_credentials
      description: <p>the credentials object itself. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: cbf33bbe
  spec.java:
  - name: IOException
    fullName: IOException
- uid: 8291270b
  spec.java:
  - name: File
    fullName: File
- uid: com.microsoft.rest.credentials._token_credentials.applyCredentialsFilter(OkHttpClient.Builder)
  parent: com.microsoft.rest.credentials._token_credentials
  href: com.microsoft.rest.credentials._token_credentials.yml
  name: applyCredentialsFilter(OkHttpClient.Builder clientBuilder)
  fullName: void com.microsoft.rest.credentials.TokenCredentials.applyCredentialsFilter(OkHttpClient.Builder clientBuilder)
  type: Method
  summary: >-
    <p>Apply the credentials to the HTTP client builder.</p>

    <p></p>
  syntax:
    content: public void applyCredentialsFilter(OkHttpClient.Builder clientBuilder)
    parameters:
    - id: clientBuilder
      type: 2c0be77c
      description: <p>the builder for building up an <ref refid="" kindref="compound">OkHttpClient</ref></p>
- uid: com.microsoft.rest.credentials._token_credentials.getScheme()
  parent: com.microsoft.rest.credentials._token_credentials
  href: com.microsoft.rest.credentials._token_credentials.yml
  name: getScheme()
  fullName: String com.microsoft.rest.credentials.TokenCredentials.getScheme()
  type: Method
  summary: >-
    <p>Get the authentication scheme.</p>

    <p></p>
  syntax:
    content: public String getScheme()
    return:
      type: "26831127"
      description: <p>the authentication scheme </p>
- uid: com.microsoft.rest.credentials._token_credentials.scheme()
  parent: com.microsoft.rest.credentials._token_credentials
  href: com.microsoft.rest.credentials._token_credentials.yml
  name: scheme
  fullName: String com.microsoft.rest.credentials.TokenCredentials.scheme
  type: Field
  summary: <p>The authentication scheme. </p>
  syntax:
    content: protected String scheme
    return:
      type: "26831127"
- uid: com.microsoft.rest.credentials._token_credentials.setToken(String)
  parent: com.microsoft.rest.credentials._token_credentials
  href: com.microsoft.rest.credentials._token_credentials.yml
  name: setToken(String token)
  fullName: void com.microsoft.rest.credentials.TokenCredentials.setToken(String token)
  type: Method
  summary: >-
    <p>Set the secure token.</p>

    <p></p>
  syntax:
    content: public void setToken(String token)
    parameters:
    - id: token
      type: "26831127"
      description: <p>the token string </p>
- uid: com.microsoft.rest.credentials._token_credentials.token()
  parent: com.microsoft.rest.credentials._token_credentials
  href: com.microsoft.rest.credentials._token_credentials.yml
  name: token
  fullName: String com.microsoft.rest.credentials.TokenCredentials.token
  type: Field
  summary: <p>The secure token. </p>
  syntax:
    content: protected String token
    return:
      type: "26831127"
- uid: com.microsoft.rest.credentials._token_credentials.TokenCredentials(String,String)
  parent: com.microsoft.rest.credentials._token_credentials
  href: com.microsoft.rest.credentials._token_credentials.yml
  name: TokenCredentials(String scheme, String token)
  fullName: com.microsoft.rest.credentials.TokenCredentials.TokenCredentials(String scheme, String token)
  type: Constructor
  summary: >-
    <p>Initializes a new instance of the <xref href="com.microsoft.rest.credentials._token_credentials" data-throw-if-not-resolved="false"></xref>.</p>

    <p></p>
  syntax:
    content: public TokenCredentials(String scheme, String token)
    parameters:
    - id: scheme
      type: "26831127"
      description: <p>scheme to use. If null, defaults to Bearer </p>
    - id: token
      type: "26831127"
      description: <p>valid token </p>
- uid: com.microsoft.rest.credentials._token_credentials
  parent: com.microsoft.rest.credentials
  href: com.microsoft.rest.credentials._token_credentials.yml
  name: TokenCredentials
  fullName: com.microsoft.rest.credentials.TokenCredentials
  type: Class
  summary: <p>Token based credentials for use with a REST Service Client. </p>
  syntax:
    content: public class TokenCredentials
- uid: com.microsoft.azure.credentials._azure_environment
  parent: com.microsoft.azure.credentials
  href: com.microsoft.azure.credentials._azure_environment.yml
  name: AzureEnvironment
  fullName: com.microsoft.azure.credentials.AzureEnvironment
  type: Class
  summary: <p>An instance of this class describes an environment in <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class AzureEnvironment
- uid: com.microsoft.azure._azure
  parent: com.microsoft.azure
  href: com.microsoft.azure._azure.yml
  name: Azure
  fullName: com.microsoft.azure.Azure
  type: Class
  summary: <p>The entry point for accessing resource management APIs in <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class Azure
- uid: com.microsoft.azure.credentials._user_token_credentials
  parent: com.microsoft.azure.credentials
  href: com.microsoft.azure.credentials._user_token_credentials.yml
  name: UserTokenCredentials
  fullName: com.microsoft.azure.credentials.UserTokenCredentials
  type: Class
  summary: <p>Token based credentials for use with a REST Service Client. </p>
  syntax:
    content: public class UserTokenCredentials
- uid: com.microsoft.azure.credentials._azure_environment.AZURE()
  parent: com.microsoft.azure.credentials._azure_environment
  href: com.microsoft.azure.credentials._azure_environment.yml
  name: AZURE
  fullName: final AzureEnvironment com.microsoft.azure.credentials.AzureEnvironment.AZURE
  type: Field
  summary: <p>Provides the settings for authentication with <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: >-
      public static final AzureEnvironment AZURE= new AzureEnvironment(
                  "https://login.windows.net/",
                  "https://management.core.windows.net/",
                  true)
    return:
      type: 93de0ef9com.microsoft.azure.credentials._azure_environment
- uid: com.microsoft.azure.credentials._application_token_credentials
  parent: com.microsoft.azure.credentials
  href: com.microsoft.azure.credentials._application_token_credentials.yml
  name: ApplicationTokenCredentials
  fullName: com.microsoft.azure.credentials.ApplicationTokenCredentials
  type: Class
  summary: <p>Token based credentials for use with a REST Service Client. </p>
  syntax: *o1
