items:
- uid: com.microsoft.azure.management.network._application_gateway_sku
  id: _application_gateway_sku
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._application_gateway_sku_1a8033b9c0b445ab8b7f3081fe990c6bef
  - com.microsoft.azure.management.network._application_gateway_sku_1a01313c7ba9c42601dbea40b40cea0cf7
  - com.microsoft.azure.management.network._application_gateway_sku_1a8b600a79f647609f535c9787ebb7ccef
  - com.microsoft.azure.management.network._application_gateway_sku_1acc7fe5049881c5030acf4ca23cb81c10
  - com.microsoft.azure.management.network._application_gateway_sku_1a60bfc9afd6dd8edc7032922d55c8f768
  - com.microsoft.azure.management.network._application_gateway_sku_1a27b19d9b4fad291fb55aecf6cc18bad4
  href: com.microsoft.azure.management.network._application_gateway_sku.yml
  langs:
  - java
  name: ApplicationGatewaySku
  fullName: com.microsoft.azure.management.network.ApplicationGatewaySku
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySku.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySku.java
    startLine: 14
  package: com.microsoft.azure.management.network
  summary: <p>SKU of application gateway. </p>
  syntax: &o1
    content: public class ApplicationGatewaySku
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.network._application_gateway_sku_1a8033b9c0b445ab8b7f3081fe990c6bef
  id: _application_gateway_sku_1a8033b9c0b445ab8b7f3081fe990c6bef
  parent: com.microsoft.azure.management.network._application_gateway_sku
  href: com.microsoft.azure.management.network._application_gateway_sku.yml
  langs:
  - java
  name: capacity()
  fullName: Integer com.microsoft.azure.management.network.ApplicationGatewaySku.capacity()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySku.java
    startLine: 77
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the capacity value.</p>

    <p></p>
  syntax:
    content: public Integer capacity()
    return:
      type: 08effaa0
      description: <p>the capacity value </p>
- uid: com.microsoft.azure.management.network._application_gateway_sku_1a01313c7ba9c42601dbea40b40cea0cf7
  id: _application_gateway_sku_1a01313c7ba9c42601dbea40b40cea0cf7
  parent: com.microsoft.azure.management.network._application_gateway_sku
  href: com.microsoft.azure.management.network._application_gateway_sku.yml
  langs:
  - java
  name: name()
  fullName: ApplicationGatewaySkuName com.microsoft.azure.management.network.ApplicationGatewaySku.name()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySku.java
    startLine: 37
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the name value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewaySkuName name()
    return:
      type: com.microsoft.azure.management.network._application_gateway_sku_name
      description: <p>the name value </p>
- uid: com.microsoft.azure.management.network._application_gateway_sku_1a8b600a79f647609f535c9787ebb7ccef
  id: _application_gateway_sku_1a8b600a79f647609f535c9787ebb7ccef
  parent: com.microsoft.azure.management.network._application_gateway_sku
  href: com.microsoft.azure.management.network._application_gateway_sku.yml
  langs:
  - java
  name: tier()
  fullName: ApplicationGatewayTier com.microsoft.azure.management.network.ApplicationGatewaySku.tier()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySku.java
    startLine: 57
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the tier value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewayTier tier()
    return:
      type: com.microsoft.azure.management.network._application_gateway_tier
      description: <p>the tier value </p>
- uid: com.microsoft.azure.management.network._application_gateway_sku_1acc7fe5049881c5030acf4ca23cb81c10
  id: _application_gateway_sku_1acc7fe5049881c5030acf4ca23cb81c10
  parent: com.microsoft.azure.management.network._application_gateway_sku
  href: com.microsoft.azure.management.network._application_gateway_sku.yml
  langs:
  - java
  name: withCapacity(Integer capacity)
  fullName: ApplicationGatewaySku com.microsoft.azure.management.network.ApplicationGatewaySku.withCapacity(Integer capacity)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySku.java
    startLine: 87
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the capacity value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewaySku withCapacity(Integer capacity)
    parameters:
    - id: capacity
      type: 08effaa0
      description: <p>the capacity value to set </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_sku
      description: <p>the <xref href="com.microsoft.azure.management.network._application_gateway_sku" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network._application_gateway_sku_1a60bfc9afd6dd8edc7032922d55c8f768
  id: _application_gateway_sku_1a60bfc9afd6dd8edc7032922d55c8f768
  parent: com.microsoft.azure.management.network._application_gateway_sku
  href: com.microsoft.azure.management.network._application_gateway_sku.yml
  langs:
  - java
  name: withName(ApplicationGatewaySkuName name)
  fullName: ApplicationGatewaySku com.microsoft.azure.management.network.ApplicationGatewaySku.withName(ApplicationGatewaySkuName name)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySku.java
    startLine: 47
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the name value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewaySku withName(ApplicationGatewaySkuName name)
    parameters:
    - id: name
      type: com.microsoft.azure.management.network._application_gateway_sku_name
      description: <p>the name value to set </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_sku
      description: <p>the <xref href="com.microsoft.azure.management.network._application_gateway_sku" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network._application_gateway_sku_1a27b19d9b4fad291fb55aecf6cc18bad4
  id: _application_gateway_sku_1a27b19d9b4fad291fb55aecf6cc18bad4
  parent: com.microsoft.azure.management.network._application_gateway_sku
  href: com.microsoft.azure.management.network._application_gateway_sku.yml
  langs:
  - java
  name: withTier(ApplicationGatewayTier tier)
  fullName: ApplicationGatewaySku com.microsoft.azure.management.network.ApplicationGatewaySku.withTier(ApplicationGatewayTier tier)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySku.java
    startLine: 67
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the tier value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewaySku withTier(ApplicationGatewayTier tier)
    parameters:
    - id: tier
      type: com.microsoft.azure.management.network._application_gateway_tier
      description: <p>the tier value to set </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_sku
      description: <p>the <xref href="com.microsoft.azure.management.network._application_gateway_sku" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: 08effaa0
  spec.java:
  - name: Integer
    fullName: Integer
- uid: com.microsoft.azure.management.network._application_gateway_sku_name
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_sku_name.yml
  name: ApplicationGatewaySkuName
  fullName: com.microsoft.azure.management.network.ApplicationGatewaySkuName
  type: Class
  summary: <p>Defines values for <xref href="com.microsoft.azure.management.network._application_gateway_sku_name" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class ApplicationGatewaySkuName
- uid: com.microsoft.azure.management.network._application_gateway_tier
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_tier.yml
  name: ApplicationGatewayTier
  fullName: com.microsoft.azure.management.network.ApplicationGatewayTier
  type: Class
  summary: <p>Defines values for <xref href="com.microsoft.azure.management.network._application_gateway_tier" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class ApplicationGatewayTier
- uid: com.microsoft.azure.management.network._application_gateway_sku
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_sku.yml
  name: ApplicationGatewaySku
  fullName: com.microsoft.azure.management.network.ApplicationGatewaySku
  type: Class
  summary: <p>SKU of application gateway. </p>
  syntax: *o1
