items:
- uid: com.microsoft.azure.management.website.implementation.api._file_system_application_logs_config
  id: _file_system_application_logs_config
  parent: com.microsoft.azure.management.website.implementation.api
  children:
  - com.microsoft.azure.management.website.implementation.api._file_system_application_logs_config_1a80b5003a705b0bfb04859c31deba42e4
  - com.microsoft.azure.management.website.implementation.api._file_system_application_logs_config_1ab22b4a7453ded0a357c8245578031902
  href: com.microsoft.azure.management.website.implementation.api._file_system_application_logs_config.yml
  langs:
  - java
  name: FileSystemApplicationLogsConfig
  fullName: com.microsoft.azure.management.website.implementation.api.FileSystemApplicationLogsConfig
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/FileSystemApplicationLogsConfig.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/FileSystemApplicationLogsConfig.java
    startLine: 12
  package: com.microsoft.azure.management.website.implementation.api
  summary: <p>Application logs to file system configuration. </p>
  syntax: &o1
    content: public class FileSystemApplicationLogsConfig
- uid: com.microsoft.azure.management.website.implementation.api._file_system_application_logs_config_1a80b5003a705b0bfb04859c31deba42e4
  id: _file_system_application_logs_config_1a80b5003a705b0bfb04859c31deba42e4
  parent: com.microsoft.azure.management.website.implementation.api._file_system_application_logs_config
  href: com.microsoft.azure.management.website.implementation.api._file_system_application_logs_config.yml
  langs:
  - java
  name: level()
  fullName: LogLevel com.microsoft.azure.management.website.implementation.api.FileSystemApplicationLogsConfig.level()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/FileSystemApplicationLogsConfig.java
    startLine: 24
  package: com.microsoft.azure.management.website.implementation.api
  summary: >-
    <p>Get the level value.</p>

    <p></p>
  syntax:
    content: public LogLevel level()
    return:
      type: com.microsoft.azure.management.website.implementation.api._log_level
      description: <p>the level value </p>
- uid: com.microsoft.azure.management.website.implementation.api._file_system_application_logs_config_1ab22b4a7453ded0a357c8245578031902
  id: _file_system_application_logs_config_1ab22b4a7453ded0a357c8245578031902
  parent: com.microsoft.azure.management.website.implementation.api._file_system_application_logs_config
  href: com.microsoft.azure.management.website.implementation.api._file_system_application_logs_config.yml
  langs:
  - java
  name: withLevel(LogLevel level)
  fullName: FileSystemApplicationLogsConfig com.microsoft.azure.management.website.implementation.api.FileSystemApplicationLogsConfig.withLevel(LogLevel level)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/FileSystemApplicationLogsConfig.java
    startLine: 34
  package: com.microsoft.azure.management.website.implementation.api
  summary: >-
    <p>Set the level value.</p>

    <p></p>
  syntax:
    content: public FileSystemApplicationLogsConfig withLevel(LogLevel level)
    parameters:
    - id: level
      type: com.microsoft.azure.management.website.implementation.api._log_level
      description: <p>the level value to set </p>
    return:
      type: com.microsoft.azure.management.website.implementation.api._file_system_application_logs_config
      description: <p>the <xref href="com.microsoft.azure.management.website.implementation.api._file_system_application_logs_config" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: com.microsoft.azure.management.website.implementation.api._log_level
  parent: com.microsoft.azure.management.website.implementation.api
  href: com.microsoft.azure.management.website.implementation.api._log_level.yml
  name: LogLevel
  fullName: com.microsoft.azure.management.website.implementation.api.LogLevel
  type: Enum
  summary: <p>Defines values for <xref href="com.microsoft.azure.management.website.implementation.api._log_level" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public enum LogLevel
- uid: com.microsoft.azure.management.website.implementation.api._file_system_application_logs_config
  parent: com.microsoft.azure.management.website.implementation.api
  href: com.microsoft.azure.management.website.implementation.api._file_system_application_logs_config.yml
  name: FileSystemApplicationLogsConfig
  fullName: com.microsoft.azure.management.website.implementation.api.FileSystemApplicationLogsConfig
  type: Class
  summary: <p>Application logs to file system configuration. </p>
  syntax: *o1
