items:
- uid: com.microsoft.azure.management.network._application_gateway_ssl_policy
  id: _application_gateway_ssl_policy
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._application_gateway_ssl_policy.disabledSslProtocols()
  - com.microsoft.azure.management.network._application_gateway_ssl_policy.withDisabledSslProtocols(List< ApplicationGatewaySslProtocol >)
  href: com.microsoft.azure.management.network._application_gateway_ssl_policy.yml
  langs:
  - java
  name: ApplicationGatewaySslPolicy
  fullName: com.microsoft.azure.management.network.ApplicationGatewaySslPolicy
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySslPolicy.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySslPolicy.java
    startLine: 15
  package: com.microsoft.azure.management.network
  summary: <p>Application gateway SSL policy. </p>
  syntax: &o1
    content: public class ApplicationGatewaySslPolicy
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.network._application_gateway_ssl_policy.disabledSslProtocols()
  id: disabledSslProtocols()
  parent: com.microsoft.azure.management.network._application_gateway_ssl_policy
  href: com.microsoft.azure.management.network._application_gateway_ssl_policy.yml
  langs:
  - java
  name: disabledSslProtocols()
  fullName: List<ApplicationGatewaySslProtocol> com.microsoft.azure.management.network.ApplicationGatewaySslPolicy.disabledSslProtocols()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySslPolicy.java
    startLine: 26
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Get the disabledSslProtocols value.</p>

    <p></p>
  syntax:
    content: public List< ApplicationGatewaySslProtocol > disabledSslProtocols()
    return:
      type: f6a6204dcom.microsoft.azure.management.network._application_gateway_ssl_protocol9ec3e006
      description: <p>the disabledSslProtocols value </p>
- uid: com.microsoft.azure.management.network._application_gateway_ssl_policy.withDisabledSslProtocols(List< ApplicationGatewaySslProtocol >)
  id: withDisabledSslProtocols(List< ApplicationGatewaySslProtocol >)
  parent: com.microsoft.azure.management.network._application_gateway_ssl_policy
  href: com.microsoft.azure.management.network._application_gateway_ssl_policy.yml
  langs:
  - java
  name: withDisabledSslProtocols(List< ApplicationGatewaySslProtocol > disabledSslProtocols)
  fullName: ApplicationGatewaySslPolicy com.microsoft.azure.management.network.ApplicationGatewaySslPolicy.withDisabledSslProtocols(List< ApplicationGatewaySslProtocol > disabledSslProtocols)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySslPolicy.java
    startLine: 36
  package: com.microsoft.azure.management.network
  summary: >-
    <p>Set the disabledSslProtocols value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewaySslPolicy withDisabledSslProtocols(List< ApplicationGatewaySslProtocol > disabledSslProtocols)
    parameters:
    - id: disabledSslProtocols
      type: f6a6204dcom.microsoft.azure.management.network._application_gateway_ssl_protocol9ec3e006
      description: <p>the disabledSslProtocols value to set </p>
    return:
      type: com.microsoft.azure.management.network._application_gateway_ssl_policy
      description: <p>the <xref href="com.microsoft.azure.management.network._application_gateway_ssl_policy" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: f6a6204dcom.microsoft.azure.management.network._application_gateway_ssl_protocol9ec3e006
  spec.java:
  - name: 'List< '
    fullName: 'List< '
  - uid: com.microsoft.azure.management.network._application_gateway_ssl_protocol
    name: ApplicationGatewaySslProtocol
    fullName: com.microsoft.azure.management.network.ApplicationGatewaySslProtocol
    href: com.microsoft.azure.management.network._application_gateway_ssl_protocol.yml
  - name: " >"
    fullName: " >"
- uid: com.microsoft.azure.management.network._application_gateway_ssl_protocol
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_ssl_protocol.yml
  name: ApplicationGatewaySslProtocol
  fullName: com.microsoft.azure.management.network.ApplicationGatewaySslProtocol
  type: Class
  summary: <p>Defines values for <xref href="com.microsoft.azure.management.network._application_gateway_ssl_protocol" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class ApplicationGatewaySslProtocol
- uid: com.microsoft.azure.management.network._application_gateway_ssl_policy
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_ssl_policy.yml
  name: ApplicationGatewaySslPolicy
  fullName: com.microsoft.azure.management.network.ApplicationGatewaySslPolicy
  type: Class
  summary: <p>Application gateway SSL policy. </p>
  syntax: *o1
