items:
- uid: com.microsoft.azure.management.website.implementation.api._file_system_http_logs_config
  id: _file_system_http_logs_config
  parent: com.microsoft.azure.management.website.implementation.api
  children:
  - com.microsoft.azure.management.website.implementation.api._file_system_http_logs_config_1aa863cbd6851d43353eaf9fef41aaab99
  - com.microsoft.azure.management.website.implementation.api._file_system_http_logs_config_1aa37a147681be7580a42f601b73a9c6b3
  - com.microsoft.azure.management.website.implementation.api._file_system_http_logs_config_1a1c35bdfb1f353fb6787dedec3f1abd18
  - com.microsoft.azure.management.website.implementation.api._file_system_http_logs_config_1a9d527721850028c8667b99c82caf17fb
  - com.microsoft.azure.management.website.implementation.api._file_system_http_logs_config_1a10966adb0601b9e49da79ace882ae164
  - com.microsoft.azure.management.website.implementation.api._file_system_http_logs_config_1a3011c022ad4852bb3d03728583b1594e
  href: com.microsoft.azure.management.website.implementation.api._file_system_http_logs_config.yml
  langs:
  - java
  name: FileSystemHttpLogsConfig
  fullName: com.microsoft.azure.management.website.implementation.api.FileSystemHttpLogsConfig
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/FileSystemHttpLogsConfig.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/FileSystemHttpLogsConfig.java
    startLine: 12
  assemblies:
  - com.microsoft.azure.management.website.implementation.api
  package: com.microsoft.azure.management.website.implementation.api
  summary: <p>Http logs to file system configuration. </p>
  syntax: &o1
    content: public class FileSystemHttpLogsConfig
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.website.implementation.api._file_system_http_logs_config_1aa863cbd6851d43353eaf9fef41aaab99
  id: _file_system_http_logs_config_1aa863cbd6851d43353eaf9fef41aaab99
  parent: com.microsoft.azure.management.website.implementation.api._file_system_http_logs_config
  href: com.microsoft.azure.management.website.implementation.api._file_system_http_logs_config.yml
  langs:
  - java
  name: enabled()
  fullName: Boolean com.microsoft.azure.management.website.implementation.api.FileSystemHttpLogsConfig.enabled()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/FileSystemHttpLogsConfig.java
    startLine: 78
  assemblies:
  - com.microsoft.azure.management.website.implementation.api
  package: com.microsoft.azure.management.website.implementation.api
  summary: >-
    <p>Get the enabled value.</p>

    <p></p>
  syntax:
    content: public Boolean enabled()
    return:
      type: 866c2227
      description: <p>the enabled value </p>
- uid: com.microsoft.azure.management.website.implementation.api._file_system_http_logs_config_1aa37a147681be7580a42f601b73a9c6b3
  id: _file_system_http_logs_config_1aa37a147681be7580a42f601b73a9c6b3
  parent: com.microsoft.azure.management.website.implementation.api._file_system_http_logs_config
  href: com.microsoft.azure.management.website.implementation.api._file_system_http_logs_config.yml
  langs:
  - java
  name: retentionInDays()
  fullName: Integer com.microsoft.azure.management.website.implementation.api.FileSystemHttpLogsConfig.retentionInDays()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/FileSystemHttpLogsConfig.java
    startLine: 58
  assemblies:
  - com.microsoft.azure.management.website.implementation.api
  package: com.microsoft.azure.management.website.implementation.api
  summary: >-
    <p>Get the retentionInDays value.</p>

    <p></p>
  syntax:
    content: public Integer retentionInDays()
    return:
      type: 08effaa0
      description: <p>the retentionInDays value </p>
- uid: com.microsoft.azure.management.website.implementation.api._file_system_http_logs_config_1a1c35bdfb1f353fb6787dedec3f1abd18
  id: _file_system_http_logs_config_1a1c35bdfb1f353fb6787dedec3f1abd18
  parent: com.microsoft.azure.management.website.implementation.api._file_system_http_logs_config
  href: com.microsoft.azure.management.website.implementation.api._file_system_http_logs_config.yml
  langs:
  - java
  name: retentionInMb()
  fullName: Integer com.microsoft.azure.management.website.implementation.api.FileSystemHttpLogsConfig.retentionInMb()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/FileSystemHttpLogsConfig.java
    startLine: 38
  assemblies:
  - com.microsoft.azure.management.website.implementation.api
  package: com.microsoft.azure.management.website.implementation.api
  summary: >-
    <p>Get the retentionInMb value.</p>

    <p></p>
  syntax:
    content: public Integer retentionInMb()
    return:
      type: 08effaa0
      description: <p>the retentionInMb value </p>
- uid: com.microsoft.azure.management.website.implementation.api._file_system_http_logs_config_1a9d527721850028c8667b99c82caf17fb
  id: _file_system_http_logs_config_1a9d527721850028c8667b99c82caf17fb
  parent: com.microsoft.azure.management.website.implementation.api._file_system_http_logs_config
  href: com.microsoft.azure.management.website.implementation.api._file_system_http_logs_config.yml
  langs:
  - java
  name: withEnabled(Boolean enabled)
  fullName: FileSystemHttpLogsConfig com.microsoft.azure.management.website.implementation.api.FileSystemHttpLogsConfig.withEnabled(Boolean enabled)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/FileSystemHttpLogsConfig.java
    startLine: 88
  assemblies:
  - com.microsoft.azure.management.website.implementation.api
  package: com.microsoft.azure.management.website.implementation.api
  summary: >-
    <p>Set the enabled value.</p>

    <p></p>
  syntax:
    content: public FileSystemHttpLogsConfig withEnabled(Boolean enabled)
    parameters:
    - id: enabled
      type: 866c2227
      description: <p>the enabled value to set </p>
    return:
      type: com.microsoft.azure.management.website.implementation.api._file_system_http_logs_config
      description: <p>the <xref href="com.microsoft.azure.management.website.implementation.api._file_system_http_logs_config" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.website.implementation.api._file_system_http_logs_config_1a10966adb0601b9e49da79ace882ae164
  id: _file_system_http_logs_config_1a10966adb0601b9e49da79ace882ae164
  parent: com.microsoft.azure.management.website.implementation.api._file_system_http_logs_config
  href: com.microsoft.azure.management.website.implementation.api._file_system_http_logs_config.yml
  langs:
  - java
  name: withRetentionInDays(Integer retentionInDays)
  fullName: FileSystemHttpLogsConfig com.microsoft.azure.management.website.implementation.api.FileSystemHttpLogsConfig.withRetentionInDays(Integer retentionInDays)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/FileSystemHttpLogsConfig.java
    startLine: 68
  assemblies:
  - com.microsoft.azure.management.website.implementation.api
  package: com.microsoft.azure.management.website.implementation.api
  summary: >-
    <p>Set the retentionInDays value.</p>

    <p></p>
  syntax:
    content: public FileSystemHttpLogsConfig withRetentionInDays(Integer retentionInDays)
    parameters:
    - id: retentionInDays
      type: 08effaa0
      description: <p>the retentionInDays value to set </p>
    return:
      type: com.microsoft.azure.management.website.implementation.api._file_system_http_logs_config
      description: <p>the <xref href="com.microsoft.azure.management.website.implementation.api._file_system_http_logs_config" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.website.implementation.api._file_system_http_logs_config_1a3011c022ad4852bb3d03728583b1594e
  id: _file_system_http_logs_config_1a3011c022ad4852bb3d03728583b1594e
  parent: com.microsoft.azure.management.website.implementation.api._file_system_http_logs_config
  href: com.microsoft.azure.management.website.implementation.api._file_system_http_logs_config.yml
  langs:
  - java
  name: withRetentionInMb(Integer retentionInMb)
  fullName: FileSystemHttpLogsConfig com.microsoft.azure.management.website.implementation.api.FileSystemHttpLogsConfig.withRetentionInMb(Integer retentionInMb)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/FileSystemHttpLogsConfig.java
    startLine: 48
  assemblies:
  - com.microsoft.azure.management.website.implementation.api
  package: com.microsoft.azure.management.website.implementation.api
  summary: >-
    <p>Set the retentionInMb value.</p>

    <p></p>
  syntax:
    content: public FileSystemHttpLogsConfig withRetentionInMb(Integer retentionInMb)
    parameters:
    - id: retentionInMb
      type: 08effaa0
      description: <p>the retentionInMb value to set </p>
    return:
      type: com.microsoft.azure.management.website.implementation.api._file_system_http_logs_config
      description: <p>the <xref href="com.microsoft.azure.management.website.implementation.api._file_system_http_logs_config" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: 08effaa0
  spec.java:
  - name: Integer
    fullName: Integer
- uid: 866c2227
  spec.java:
  - name: Boolean
    fullName: Boolean
- uid: com.microsoft.azure.management.website.implementation.api._file_system_http_logs_config
  parent: com.microsoft.azure.management.website.implementation.api
  href: com.microsoft.azure.management.website.implementation.api._file_system_http_logs_config.yml
  name: FileSystemHttpLogsConfig
  fullName: com.microsoft.azure.management.website.implementation.api.FileSystemHttpLogsConfig
  type: Class
  summary: <p>Http logs to file system configuration. </p>
  syntax: *o1
