items:
- uid: com.microsoft.azure.batch.protocol.models._virtual_machine_configuration
  id: _virtual_machine_configuration
  parent: com.microsoft.azure.batch.protocol.models
  children:
  - com.microsoft.azure.batch.protocol.models._virtual_machine_configuration_1a587a8192ce80ec5a10ded7d6eccd043f
  - com.microsoft.azure.batch.protocol.models._virtual_machine_configuration_1a875eebdaa950b080357fd86c16730e44
  - com.microsoft.azure.batch.protocol.models._virtual_machine_configuration_1a3f21bc3aa90f330c32b7ecd91048ef09
  - com.microsoft.azure.batch.protocol.models._virtual_machine_configuration_1aa46219dc5fa3337d02ca93d80adf9bed
  - com.microsoft.azure.batch.protocol.models._virtual_machine_configuration_1afb721212797f216713446f1273087fc1
  - com.microsoft.azure.batch.protocol.models._virtual_machine_configuration_1a8d9faf84f4de046b37beeb6f55339c3f
  href: com.microsoft.azure.batch.protocol.models._virtual_machine_configuration.yml
  langs:
  - java
  name: VirtualMachineConfiguration
  fullName: com.microsoft.azure.batch.protocol.models.VirtualMachineConfiguration
  type: Class
  source:
    remote: &o0
      path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/VirtualMachineConfiguration.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/VirtualMachineConfiguration.java
    startLine: 16
  package: com.microsoft.azure.batch.protocol.models
  summary: <p>The configuration for compute nodes in a pool based on the <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> Virtual Machines infrastructure. </p>
  syntax: &o1
    content: public class VirtualMachineConfiguration
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.batch.protocol.models._virtual_machine_configuration_1a587a8192ce80ec5a10ded7d6eccd043f
  id: _virtual_machine_configuration_1a587a8192ce80ec5a10ded7d6eccd043f
  parent: com.microsoft.azure.batch.protocol.models._virtual_machine_configuration
  href: com.microsoft.azure.batch.protocol.models._virtual_machine_configuration.yml
  langs:
  - java
  name: imageReference()
  fullName: ImageReference com.microsoft.azure.batch.protocol.models.VirtualMachineConfiguration.imageReference()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/VirtualMachineConfiguration.java
    startLine: 45
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the imageReference value.</p>

    <p></p>
  syntax:
    content: public ImageReference imageReference()
    return:
      type: com.microsoft.azure.batch.protocol.models._image_reference
      description: <p>the imageReference value </p>
- uid: com.microsoft.azure.batch.protocol.models._virtual_machine_configuration_1a875eebdaa950b080357fd86c16730e44
  id: _virtual_machine_configuration_1a875eebdaa950b080357fd86c16730e44
  parent: com.microsoft.azure.batch.protocol.models._virtual_machine_configuration
  href: com.microsoft.azure.batch.protocol.models._virtual_machine_configuration.yml
  langs:
  - java
  name: nodeAgentSKUId()
  fullName: String com.microsoft.azure.batch.protocol.models.VirtualMachineConfiguration.nodeAgentSKUId()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/VirtualMachineConfiguration.java
    startLine: 65
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the nodeAgentSKUId value.</p>

    <p></p>
  syntax:
    content: public String nodeAgentSKUId()
    return:
      type: "26831127"
      description: <p>the nodeAgentSKUId value </p>
- uid: com.microsoft.azure.batch.protocol.models._virtual_machine_configuration_1a3f21bc3aa90f330c32b7ecd91048ef09
  id: _virtual_machine_configuration_1a3f21bc3aa90f330c32b7ecd91048ef09
  parent: com.microsoft.azure.batch.protocol.models._virtual_machine_configuration
  href: com.microsoft.azure.batch.protocol.models._virtual_machine_configuration.yml
  langs:
  - java
  name: windowsConfiguration()
  fullName: WindowsConfiguration com.microsoft.azure.batch.protocol.models.VirtualMachineConfiguration.windowsConfiguration()
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/VirtualMachineConfiguration.java
    startLine: 85
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Get the windowsConfiguration value.</p>

    <p></p>
  syntax:
    content: public WindowsConfiguration windowsConfiguration()
    return:
      type: com.microsoft.azure.batch.protocol.models._windows_configuration
      description: <p>the windowsConfiguration value </p>
- uid: com.microsoft.azure.batch.protocol.models._virtual_machine_configuration_1aa46219dc5fa3337d02ca93d80adf9bed
  id: _virtual_machine_configuration_1aa46219dc5fa3337d02ca93d80adf9bed
  parent: com.microsoft.azure.batch.protocol.models._virtual_machine_configuration
  href: com.microsoft.azure.batch.protocol.models._virtual_machine_configuration.yml
  langs:
  - java
  name: withImageReference(ImageReference imageReference)
  fullName: VirtualMachineConfiguration com.microsoft.azure.batch.protocol.models.VirtualMachineConfiguration.withImageReference(ImageReference imageReference)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/VirtualMachineConfiguration.java
    startLine: 55
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the imageReference value.</p>

    <p></p>
  syntax:
    content: public VirtualMachineConfiguration withImageReference(ImageReference imageReference)
    parameters:
    - id: imageReference
      type: com.microsoft.azure.batch.protocol.models._image_reference
      description: <p>the imageReference value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._virtual_machine_configuration
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._virtual_machine_configuration" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.batch.protocol.models._virtual_machine_configuration_1afb721212797f216713446f1273087fc1
  id: _virtual_machine_configuration_1afb721212797f216713446f1273087fc1
  parent: com.microsoft.azure.batch.protocol.models._virtual_machine_configuration
  href: com.microsoft.azure.batch.protocol.models._virtual_machine_configuration.yml
  langs:
  - java
  name: withNodeAgentSKUId(String nodeAgentSKUId)
  fullName: VirtualMachineConfiguration com.microsoft.azure.batch.protocol.models.VirtualMachineConfiguration.withNodeAgentSKUId(String nodeAgentSKUId)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/VirtualMachineConfiguration.java
    startLine: 75
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the nodeAgentSKUId value.</p>

    <p></p>
  syntax:
    content: public VirtualMachineConfiguration withNodeAgentSKUId(String nodeAgentSKUId)
    parameters:
    - id: nodeAgentSKUId
      type: "26831127"
      description: <p>the nodeAgentSKUId value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._virtual_machine_configuration
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._virtual_machine_configuration" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.batch.protocol.models._virtual_machine_configuration_1a8d9faf84f4de046b37beeb6f55339c3f
  id: _virtual_machine_configuration_1a8d9faf84f4de046b37beeb6f55339c3f
  parent: com.microsoft.azure.batch.protocol.models._virtual_machine_configuration
  href: com.microsoft.azure.batch.protocol.models._virtual_machine_configuration.yml
  langs:
  - java
  name: withWindowsConfiguration(WindowsConfiguration windowsConfiguration)
  fullName: VirtualMachineConfiguration com.microsoft.azure.batch.protocol.models.VirtualMachineConfiguration.withWindowsConfiguration(WindowsConfiguration windowsConfiguration)
  type: Method
  source:
    remote: *o0
    path: azure-batch/src/main/java/com/microsoft/azure/batch/protocol/models/VirtualMachineConfiguration.java
    startLine: 95
  package: com.microsoft.azure.batch.protocol.models
  summary: >-
    <p>Set the windowsConfiguration value.</p>

    <p></p>
  syntax:
    content: public VirtualMachineConfiguration withWindowsConfiguration(WindowsConfiguration windowsConfiguration)
    parameters:
    - id: windowsConfiguration
      type: com.microsoft.azure.batch.protocol.models._windows_configuration
      description: <p>the windowsConfiguration value to set </p>
    return:
      type: com.microsoft.azure.batch.protocol.models._virtual_machine_configuration
      description: <p>the <xref href="com.microsoft.azure.batch.protocol.models._virtual_machine_configuration" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.batch.protocol.models._image_reference
  parent: com.microsoft.azure.batch.protocol.models
  href: com.microsoft.azure.batch.protocol.models._image_reference.yml
  name: ImageReference
  fullName: com.microsoft.azure.batch.protocol.models.ImageReference
  type: Class
  summary: <p>A reference to an <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> Virtual Machines Marketplace image. </p>
  syntax:
    content: public class ImageReference
- uid: com.microsoft.azure._azure
  parent: com.microsoft.azure
  href: com.microsoft.azure._azure.yml
  name: Azure
  fullName: com.microsoft.azure.Azure
  type: Class
  summary: <p>The entry point for accessing resource management APIs in <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class Azure
- uid: com.microsoft.azure._node
  parent: com.microsoft.azure
  href: com.microsoft.azure._node.yml
  name: Node<T>
  fullName: com.microsoft.azure.Node<T>
  type: Class
  summary: >-
    <p>Type represents a node in a <xref href="com.microsoft.azure._graph" data-throw-if-not-resolved="false"></xref>.</p>

    <p></p>
  syntax:
    content: public class Node<T>
    typeParameters:
    - type: 8ce1ecb9
      description: <p>the type of the data stored in the node </p>
- uid: com.microsoft.azure.batch.protocol.models._windows_configuration
  parent: com.microsoft.azure.batch.protocol.models
  href: com.microsoft.azure.batch.protocol.models._windows_configuration.yml
  name: WindowsConfiguration
  fullName: com.microsoft.azure.batch.protocol.models.WindowsConfiguration
  type: Class
  summary: <p>Windows operating system settings to apply to the virtual machine. </p>
  syntax:
    content: public class WindowsConfiguration
- uid: com.microsoft.azure.batch.protocol.models._virtual_machine_configuration
  parent: com.microsoft.azure.batch.protocol.models
  href: com.microsoft.azure.batch.protocol.models._virtual_machine_configuration.yml
  name: VirtualMachineConfiguration
  fullName: com.microsoft.azure.batch.protocol.models.VirtualMachineConfiguration
  type: Class
  summary: <p>The configuration for compute nodes in a pool based on the <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> Virtual Machines infrastructure. </p>
  syntax: *o1
