items:
- uid: com.microsoft.azure.management.website._hosting_environment_status
  id: _hosting_environment_status
  parent: com.microsoft.azure.management.website
  children:
  - com.microsoft.azure.management.website._hosting_environment_status.DELETING()
  - com.microsoft.azure.management.website._hosting_environment_status.fromString(String)
  - com.microsoft.azure.management.website._hosting_environment_status.HostingEnvironmentStatus(String)
  - com.microsoft.azure.management.website._hosting_environment_status.PREPARING()
  - com.microsoft.azure.management.website._hosting_environment_status.READY()
  - com.microsoft.azure.management.website._hosting_environment_status.SCALING()
  - com.microsoft.azure.management.website._hosting_environment_status.toString()
  href: com.microsoft.azure.management.website._hosting_environment_status.yml
  langs:
  - java
  name: HostingEnvironmentStatus
  fullName: com.microsoft.azure.management.website.HostingEnvironmentStatus
  type: Enum
  source:
    remote: &o0
      path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/HostingEnvironmentStatus.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/HostingEnvironmentStatus.java
    startLine: 16
  package: com.microsoft.azure.management.website
  summary: <p>Defines values for <xref href="com.microsoft.azure.management.website._hosting_environment_status" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: &o1
    content: public enum HostingEnvironmentStatus
  inheritance:
  - java.lang.Object
  - java.lang.Enum<HostingEnvironmentStatus>
- uid: com.microsoft.azure.management.website._hosting_environment_status.DELETING()
  id: DELETING()
  parent: com.microsoft.azure.management.website._hosting_environment_status
  href: com.microsoft.azure.management.website._hosting_environment_status.yml
  langs:
  - java
  name: DELETING
  fullName: com.microsoft.azure.management.website.HostingEnvironmentStatus.DELETING
  type: Constructor
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/HostingEnvironmentStatus.java
    startLine: 27
  package: com.microsoft.azure.management.website
  summary: <p>Enum value Deleting. </p>
  syntax:
    content: public DELETING=("Deleting")
- uid: com.microsoft.azure.management.website._hosting_environment_status.fromString(String)
  id: fromString(String)
  parent: com.microsoft.azure.management.website._hosting_environment_status
  href: com.microsoft.azure.management.website._hosting_environment_status.yml
  langs:
  - java
  name: fromString(String value)
  fullName: static HostingEnvironmentStatus com.microsoft.azure.management.website.HostingEnvironmentStatus.fromString(String value)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/HostingEnvironmentStatus.java
    startLine: 43
  package: com.microsoft.azure.management.website
  summary: >-
    <p>Parses a serialized value to a <xref href="com.microsoft.azure.management.website._hosting_environment_status" data-throw-if-not-resolved="false"></xref> instance.</p>

    <p></p>
  syntax:
    content: public static HostingEnvironmentStatus fromString(String value)
    parameters:
    - id: value
      type: "26831127"
      description: <p>the serialized value to parse. </p>
    return:
      type: com.microsoft.azure.management.website._hosting_environment_status
      description: <p>the parsed <xref href="com.microsoft.azure.management.website._hosting_environment_status" data-throw-if-not-resolved="false"></xref> object, or null if unable to parse. </p>
- uid: com.microsoft.azure.management.website._hosting_environment_status.HostingEnvironmentStatus(String)
  id: HostingEnvironmentStatus(String)
  parent: com.microsoft.azure.management.website._hosting_environment_status
  href: com.microsoft.azure.management.website._hosting_environment_status.yml
  langs:
  - java
  name: HostingEnvironmentStatus(String value)
  fullName: com.microsoft.azure.management.website.HostingEnvironmentStatus.HostingEnvironmentStatus(String value)
  type: Constructor
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/HostingEnvironmentStatus.java
    startLine: 32
  package: com.microsoft.azure.management.website
  syntax:
    content: public HostingEnvironmentStatus(String value)
    parameters:
    - id: value
      type: "26831127"
- uid: com.microsoft.azure.management.website._hosting_environment_status.PREPARING()
  id: PREPARING()
  parent: com.microsoft.azure.management.website._hosting_environment_status
  href: com.microsoft.azure.management.website._hosting_environment_status.yml
  langs:
  - java
  name: PREPARING
  fullName: com.microsoft.azure.management.website.HostingEnvironmentStatus.PREPARING
  type: Constructor
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/HostingEnvironmentStatus.java
    startLine: 18
  package: com.microsoft.azure.management.website
  summary: <p>Enum value Preparing. </p>
  syntax:
    content: public PREPARING=("Preparing")
- uid: com.microsoft.azure.management.website._hosting_environment_status.READY()
  id: READY()
  parent: com.microsoft.azure.management.website._hosting_environment_status
  href: com.microsoft.azure.management.website._hosting_environment_status.yml
  langs:
  - java
  name: READY
  fullName: com.microsoft.azure.management.website.HostingEnvironmentStatus.READY
  type: Constructor
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/HostingEnvironmentStatus.java
    startLine: 21
  package: com.microsoft.azure.management.website
  summary: <p>Enum value Ready. </p>
  syntax:
    content: public READY=("Ready")
- uid: com.microsoft.azure.management.website._hosting_environment_status.SCALING()
  id: SCALING()
  parent: com.microsoft.azure.management.website._hosting_environment_status
  href: com.microsoft.azure.management.website._hosting_environment_status.yml
  langs:
  - java
  name: SCALING
  fullName: com.microsoft.azure.management.website.HostingEnvironmentStatus.SCALING
  type: Constructor
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/HostingEnvironmentStatus.java
    startLine: 24
  package: com.microsoft.azure.management.website
  summary: <p>Enum value Scaling. </p>
  syntax:
    content: public SCALING=("Scaling")
- uid: com.microsoft.azure.management.website._hosting_environment_status.toString()
  id: toString()
  parent: com.microsoft.azure.management.website._hosting_environment_status
  href: com.microsoft.azure.management.website._hosting_environment_status.yml
  langs:
  - java
  name: toString()
  fullName: String com.microsoft.azure.management.website.HostingEnvironmentStatus.toString()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/HostingEnvironmentStatus.java
    startLine: 55
  package: com.microsoft.azure.management.website
  syntax:
    content: public String toString()
    return:
      type: "26831127"
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.management.website._hosting_environment_status
  parent: com.microsoft.azure.management.website
  href: com.microsoft.azure.management.website._hosting_environment_status.yml
  name: HostingEnvironmentStatus
  fullName: com.microsoft.azure.management.website.HostingEnvironmentStatus
  type: Enum
  summary: <p>Defines values for <xref href="com.microsoft.azure.management.website._hosting_environment_status" data-throw-if-not-resolved="false"></xref>. </p>
  syntax: *o1
