items:
- uid: com.microsoft.azure.management.resources._deployment._update_stages._with_parameters
  id: _with_parameters
  parent: com.microsoft.azure.management.resources
  children:
  - com.microsoft.azure.management.resources._deployment._update_stages._with_parameters_1a15a895e3ecc67407ec2dc96fbe4e72e5
  - com.microsoft.azure.management.resources._deployment._update_stages._with_parameters_1a49b820e6b5e5114e90206faf79d595e7
  - com.microsoft.azure.management.resources._deployment._update_stages._with_parameters_1acc6a928e52301f70ce6700624273ed6b
  href: com.microsoft.azure.management.resources._deployment._update_stages._with_parameters.yml
  langs:
  - java
  name: Deployment.UpdateStages.WithParameters
  fullName: com.microsoft.azure.management.resources.Deployment.UpdateStages.WithParameters
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/Deployment.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/Deployment.java
    startLine: 294
  package: com.microsoft.azure.management.resources
  summary: <p>A deployment update allowing to change the parameters. </p>
  syntax:
    content: public interface WithParameters
- uid: com.microsoft.azure.management.resources._deployment._update_stages._with_parameters_1a15a895e3ecc67407ec2dc96fbe4e72e5
  id: _with_parameters_1a15a895e3ecc67407ec2dc96fbe4e72e5
  parent: com.microsoft.azure.management.resources._deployment._update_stages._with_parameters
  href: com.microsoft.azure.management.resources._deployment._update_stages._with_parameters.yml
  langs:
  - java
  name: withParameters(Object parameters)
  fullName: Update com.microsoft.azure.management.resources.Deployment.UpdateStages.WithParameters.withParameters(Object parameters)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/Deployment.java
    startLine: 301
  package: com.microsoft.azure.management.resources
  summary: >-
    <p>Specifies the parameters as a Java object.</p>

    <p></p>
  syntax:
    content: public Update withParameters(Object parameters)
    parameters:
    - id: parameters
      type: "79317049"
      description: <p>the Java object </p>
    return:
      type: com.microsoft.azure.management.resources._deployment._update
      description: <p>the next stage of the deployment update </p>
- uid: com.microsoft.azure.management.resources._deployment._update_stages._with_parameters_1a49b820e6b5e5114e90206faf79d595e7
  id: _with_parameters_1a49b820e6b5e5114e90206faf79d595e7
  parent: com.microsoft.azure.management.resources._deployment._update_stages._with_parameters
  href: com.microsoft.azure.management.resources._deployment._update_stages._with_parameters.yml
  langs:
  - java
  name: withParameters(String parametersJson)
  fullName: Update com.microsoft.azure.management.resources.Deployment.UpdateStages.WithParameters.withParameters(String parametersJson)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/Deployment.java
    startLine: 310
  package: com.microsoft.azure.management.resources
  summary: >-
    <p>Specifies the parameters as a JSON string.</p>

    <p></p>
  syntax:
    content: public Update withParameters(String parametersJson)
    parameters:
    - id: parametersJson
      type: "26831127"
      description: <p>the JSON string </p>
    return:
      type: com.microsoft.azure.management.resources._deployment._update
      description: <p>the next stage of the deployment update </p>
  exceptions:
  - type: cbf33bbe
    description: <p>exception thrown from serialization/deserialization </p>
- uid: com.microsoft.azure.management.resources._deployment._update_stages._with_parameters_1acc6a928e52301f70ce6700624273ed6b
  id: _with_parameters_1acc6a928e52301f70ce6700624273ed6b
  parent: com.microsoft.azure.management.resources._deployment._update_stages._with_parameters
  href: com.microsoft.azure.management.resources._deployment._update_stages._with_parameters.yml
  langs:
  - java
  name: withParametersLink(String uri, String contentVersion)
  fullName: Update com.microsoft.azure.management.resources.Deployment.UpdateStages.WithParameters.withParametersLink(String uri, String contentVersion)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/Deployment.java
    startLine: 319
  package: com.microsoft.azure.management.resources
  summary: >-
    <p>Specifies the parameters as a URL.</p>

    <p></p>
  syntax:
    content: public Update withParametersLink(String uri, String contentVersion)
    parameters:
    - id: uri
      type: "26831127"
      description: <p>the location of the remote parameters file </p>
    - id: contentVersion
      type: "26831127"
      description: <p>the version of the parameters file </p>
    return:
      type: com.microsoft.azure.management.resources._deployment._update
      description: <p>the next stage of the deployment update </p>
references:
- uid: "79317049"
  spec.java:
  - name: Object
    fullName: Object
- uid: cbf33bbe
  spec.java:
  - name: IOException
    fullName: IOException
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.management.resources._deployment._update
  parent: com.microsoft.azure.management.resources
  href: com.microsoft.azure.management.resources._deployment._update.yml
  name: Deployment.Update
  fullName: com.microsoft.azure.management.resources.Deployment.Update
  type: Interface
  summary: >-
    <p>The template for a deployment update operation, containing all the settings that can be modified. </p>

    <p>Call <xref href="com.microsoft.azure.management.resources.fluentcore.model._appliable_1a644f6f9ad9fb815ebc68becb7a5e3406" data-throw-if-not-resolved="false"></xref> to apply the changes to the deployment in <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public interface Update extends Appliable< Deployment >,Deployment.UpdateStages.WithTemplate,Deployment.UpdateStages.WithParameters,Deployment.UpdateStages.WithMode
