items:
- uid: com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner
  id: _slot_config_names_resource_inner
  parent: com.microsoft.azure.management.website.implementation
  children:
  - com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner.appSettingNames()
  - com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner.connectionStringNames()
  - com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner.withAppSettingNames(List< String >)
  - com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner.withConnectionStringNames(List< String >)
  href: com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner.yml
  langs:
  - java
  name: SlotConfigNamesResourceInner
  fullName: com.microsoft.azure.management.website.implementation.SlotConfigNamesResourceInner
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/SlotConfigNamesResourceInner.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/SlotConfigNamesResourceInner.java
    startLine: 19
  package: com.microsoft.azure.management.website.implementation
  summary: <p>Slot Config names azure resource. </p>
  syntax: &o1
    content: public class SlotConfigNamesResourceInner extends Resource
  inheritance:
  - java.lang.Object
  - com.microsoft.azure._resource
  inheritedMembers:
  - com.microsoft.azure._resource.getTags()
  - com.microsoft.azure._resource.id()
  - com.microsoft.azure._resource.location()
  - com.microsoft.azure._resource.name()
  - com.microsoft.azure._resource.type()
  - com.microsoft.azure._resource.withLocation(String)
  - com.microsoft.azure._resource.withTags(Map< String, String >)
- uid: com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner.appSettingNames()
  id: appSettingNames()
  parent: com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner
  href: com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner.yml
  langs:
  - java
  name: appSettingNames()
  fullName: List<String> com.microsoft.azure.management.website.implementation.SlotConfigNamesResourceInner.appSettingNames()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/SlotConfigNamesResourceInner.java
    startLine: 57
  package: com.microsoft.azure.management.website.implementation
  summary: >-
    <p>Get the appSettingNames value.</p>

    <p></p>
  syntax:
    content: public List< String > appSettingNames()
    return:
      type: f35af49b
      description: <p>the appSettingNames value </p>
- uid: com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner.connectionStringNames()
  id: connectionStringNames()
  parent: com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner
  href: com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner.yml
  langs:
  - java
  name: connectionStringNames()
  fullName: List<String> com.microsoft.azure.management.website.implementation.SlotConfigNamesResourceInner.connectionStringNames()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/SlotConfigNamesResourceInner.java
    startLine: 37
  package: com.microsoft.azure.management.website.implementation
  summary: >-
    <p>Get the connectionStringNames value.</p>

    <p></p>
  syntax:
    content: public List< String > connectionStringNames()
    return:
      type: f35af49b
      description: <p>the connectionStringNames value </p>
- uid: com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner.withAppSettingNames(List< String >)
  id: withAppSettingNames(List< String >)
  parent: com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner
  href: com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner.yml
  langs:
  - java
  name: withAppSettingNames(List< String > appSettingNames)
  fullName: SlotConfigNamesResourceInner com.microsoft.azure.management.website.implementation.SlotConfigNamesResourceInner.withAppSettingNames(List< String > appSettingNames)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/SlotConfigNamesResourceInner.java
    startLine: 67
  package: com.microsoft.azure.management.website.implementation
  summary: >-
    <p>Set the appSettingNames value.</p>

    <p></p>
  syntax:
    content: public SlotConfigNamesResourceInner withAppSettingNames(List< String > appSettingNames)
    parameters:
    - id: appSettingNames
      type: f35af49b
      description: <p>the appSettingNames value to set </p>
    return:
      type: com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner
      description: <p>the <xref href="com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner.withConnectionStringNames(List< String >)
  id: withConnectionStringNames(List< String >)
  parent: com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner
  href: com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner.yml
  langs:
  - java
  name: withConnectionStringNames(List< String > connectionStringNames)
  fullName: SlotConfigNamesResourceInner com.microsoft.azure.management.website.implementation.SlotConfigNamesResourceInner.withConnectionStringNames(List< String > connectionStringNames)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/SlotConfigNamesResourceInner.java
    startLine: 47
  package: com.microsoft.azure.management.website.implementation
  summary: >-
    <p>Set the connectionStringNames value.</p>

    <p></p>
  syntax:
    content: public SlotConfigNamesResourceInner withConnectionStringNames(List< String > connectionStringNames)
    parameters:
    - id: connectionStringNames
      type: f35af49b
      description: <p>the connectionStringNames value to set </p>
    return:
      type: com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner
      description: <p>the <xref href="com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: f35af49b
  spec.java:
  - name: List< String >
    fullName: List< String >
- uid: com.microsoft.azure._resource.getTags()
  parent: com.microsoft.azure._resource
  href: com.microsoft.azure._resource.yml
  name: getTags()
  fullName: Map<String, String> com.microsoft.azure.Resource.getTags()
  type: Method
  summary: >-
    <p>Get the tags value.</p>

    <p></p>
  syntax:
    content: public Map< String, String > getTags()
    return:
      type: 805937fc
      description: <p>the tags value </p>
- uid: com.microsoft.azure._resource.id()
  parent: com.microsoft.azure._resource
  href: com.microsoft.azure._resource.yml
  name: id()
  fullName: String com.microsoft.azure.Resource.id()
  type: Method
  summary: >-
    <p>Get the id value.</p>

    <p></p>
  syntax:
    content: public String id()
    return:
      type: "26831127"
      description: <p>the id value </p>
- uid: com.microsoft.azure._resource.location()
  parent: com.microsoft.azure._resource
  href: com.microsoft.azure._resource.yml
  name: location()
  fullName: String com.microsoft.azure.Resource.location()
  type: Method
  summary: >-
    <p>Get the location value.</p>

    <p></p>
  syntax:
    content: public String location()
    return:
      type: "26831127"
      description: <p>the location value </p>
- uid: com.microsoft.azure._resource.name()
  parent: com.microsoft.azure._resource
  href: com.microsoft.azure._resource.yml
  name: name()
  fullName: String com.microsoft.azure.Resource.name()
  type: Method
  summary: >-
    <p>Get the name value.</p>

    <p></p>
  syntax:
    content: public String name()
    return:
      type: "26831127"
      description: <p>the name value </p>
- uid: com.microsoft.azure._resource.type()
  parent: com.microsoft.azure._resource
  href: com.microsoft.azure._resource.yml
  name: type()
  fullName: String com.microsoft.azure.Resource.type()
  type: Method
  summary: >-
    <p>Get the type value.</p>

    <p></p>
  syntax:
    content: public String type()
    return:
      type: "26831127"
      description: <p>the type value </p>
- uid: com.microsoft.azure._resource.withLocation(String)
  parent: com.microsoft.azure._resource
  href: com.microsoft.azure._resource.yml
  name: withLocation(String location)
  fullName: Resource com.microsoft.azure.Resource.withLocation(String location)
  type: Method
  summary: >-
    <p>Set the location value.</p>

    <p></p>
  syntax:
    content: public Resource withLocation(String location)
    parameters:
    - id: location
      type: "26831127"
      description: <p>the location value to set </p>
    return:
      type: com.microsoft.azure._resource
      description: <p>the resource itself </p>
- uid: com.microsoft.azure._resource.withTags(Map< String, String >)
  parent: com.microsoft.azure._resource
  href: com.microsoft.azure._resource.yml
  name: withTags(Map< String, String > tags)
  fullName: Resource com.microsoft.azure.Resource.withTags(Map< String, String > tags)
  type: Method
  summary: >-
    <p>Set the tags value.</p>

    <p></p>
  syntax:
    content: public Resource withTags(Map< String, String > tags)
    parameters:
    - id: tags
      type: 805937fc
      description: <p>the tags value to set </p>
    return:
      type: com.microsoft.azure._resource
      description: <p>the resource itself </p>
- uid: com.microsoft.azure._resource
  parent: com.microsoft.azure
  href: com.microsoft.azure._resource.yml
  name: Resource
  fullName: com.microsoft.azure.Resource
  type: Class
  summary: <p>The <xref href="com.microsoft.azure._resource" data-throw-if-not-resolved="false"></xref> model. </p>
  syntax:
    content: public class Resource
- uid: com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner
  parent: com.microsoft.azure.management.website.implementation
  href: com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner.yml
  name: SlotConfigNamesResourceInner
  fullName: com.microsoft.azure.management.website.implementation.SlotConfigNamesResourceInner
  type: Class
  summary: <p>Slot Config names azure resource. </p>
  syntax: *o1
