items:
- uid: com.microsoft.azure.management.network.implementation.api._express_route_circuit_peering_config
  id: _express_route_circuit_peering_config
  parent: com.microsoft.azure.management.network.implementation.api
  children:
  - com.microsoft.azure.management.network.implementation.api._express_route_circuit_peering_config_1a4039466494efcfa08d8622b7094c57c0
  - com.microsoft.azure.management.network.implementation.api._express_route_circuit_peering_config_1a57b28658bd3b1cfc164f5a58d03b09bb
  - com.microsoft.azure.management.network.implementation.api._express_route_circuit_peering_config_1abf34572bdc63e7c7d1609a8a4fe95da3
  - com.microsoft.azure.management.network.implementation.api._express_route_circuit_peering_config_1acb9b5dc62ebb16b7065ce338f9198423
  - com.microsoft.azure.management.network.implementation.api._express_route_circuit_peering_config_1a6776e4af6442fc1743bc86a5269a03bd
  - com.microsoft.azure.management.network.implementation.api._express_route_circuit_peering_config_1aeaf922b436bedf7d12f9c0b71056d393
  - com.microsoft.azure.management.network.implementation.api._express_route_circuit_peering_config_1a5754d99117ba9d2ccb5e2ad9babdb017
  - com.microsoft.azure.management.network.implementation.api._express_route_circuit_peering_config_1af51b98caebd8e00a9472f687cc3ca307
  href: com.microsoft.azure.management.network.implementation.api._express_route_circuit_peering_config.yml
  langs:
  - java
  name: ExpressRouteCircuitPeeringConfig
  fullName: com.microsoft.azure.management.network.implementation.api.ExpressRouteCircuitPeeringConfig
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/api/ExpressRouteCircuitPeeringConfig.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/api/ExpressRouteCircuitPeeringConfig.java
    startLine: 13
  package: com.microsoft.azure.management.network.implementation.api
  summary: <p>Specfies the peering config. </p>
  syntax: &o1
    content: public class ExpressRouteCircuitPeeringConfig
- uid: com.microsoft.azure.management.network.implementation.api._express_route_circuit_peering_config_1a4039466494efcfa08d8622b7094c57c0
  id: _express_route_circuit_peering_config_1a4039466494efcfa08d8622b7094c57c0
  parent: com.microsoft.azure.management.network.implementation.api._express_route_circuit_peering_config
  href: com.microsoft.azure.management.network.implementation.api._express_route_circuit_peering_config.yml
  langs:
  - java
  name: advertisedPublicPrefixes()
  fullName: List<String> com.microsoft.azure.management.network.implementation.api.ExpressRouteCircuitPeeringConfig.advertisedPublicPrefixes()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/api/ExpressRouteCircuitPeeringConfig.java
    startLine: 41
  package: com.microsoft.azure.management.network.implementation.api
  summary: >-
    <p>Get the advertisedPublicPrefixes value.</p>

    <p></p>
  syntax:
    content: public List< String > advertisedPublicPrefixes()
    return:
      type: f35af49b
      description: <p>the advertisedPublicPrefixes value </p>
- uid: com.microsoft.azure.management.network.implementation.api._express_route_circuit_peering_config_1a57b28658bd3b1cfc164f5a58d03b09bb
  id: _express_route_circuit_peering_config_1a57b28658bd3b1cfc164f5a58d03b09bb
  parent: com.microsoft.azure.management.network.implementation.api._express_route_circuit_peering_config
  href: com.microsoft.azure.management.network.implementation.api._express_route_circuit_peering_config.yml
  langs:
  - java
  name: advertisedPublicPrefixesState()
  fullName: String com.microsoft.azure.management.network.implementation.api.ExpressRouteCircuitPeeringConfig.advertisedPublicPrefixesState()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/api/ExpressRouteCircuitPeeringConfig.java
    startLine: 61
  package: com.microsoft.azure.management.network.implementation.api
  summary: >-
    <p>Get the advertisedPublicPrefixesState value.</p>

    <p></p>
  syntax:
    content: public String advertisedPublicPrefixesState()
    return:
      type: "26831127"
      description: <p>the advertisedPublicPrefixesState value </p>
- uid: com.microsoft.azure.management.network.implementation.api._express_route_circuit_peering_config_1abf34572bdc63e7c7d1609a8a4fe95da3
  id: _express_route_circuit_peering_config_1abf34572bdc63e7c7d1609a8a4fe95da3
  parent: com.microsoft.azure.management.network.implementation.api._express_route_circuit_peering_config
  href: com.microsoft.azure.management.network.implementation.api._express_route_circuit_peering_config.yml
  langs:
  - java
  name: customerASN()
  fullName: Integer com.microsoft.azure.management.network.implementation.api.ExpressRouteCircuitPeeringConfig.customerASN()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/api/ExpressRouteCircuitPeeringConfig.java
    startLine: 81
  package: com.microsoft.azure.management.network.implementation.api
  summary: >-
    <p>Get the customerASN value.</p>

    <p></p>
  syntax:
    content: public Integer customerASN()
    return:
      type: 08effaa0
      description: <p>the customerASN value </p>
- uid: com.microsoft.azure.management.network.implementation.api._express_route_circuit_peering_config_1acb9b5dc62ebb16b7065ce338f9198423
  id: _express_route_circuit_peering_config_1acb9b5dc62ebb16b7065ce338f9198423
  parent: com.microsoft.azure.management.network.implementation.api._express_route_circuit_peering_config
  href: com.microsoft.azure.management.network.implementation.api._express_route_circuit_peering_config.yml
  langs:
  - java
  name: routingRegistryName()
  fullName: String com.microsoft.azure.management.network.implementation.api.ExpressRouteCircuitPeeringConfig.routingRegistryName()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/api/ExpressRouteCircuitPeeringConfig.java
    startLine: 101
  package: com.microsoft.azure.management.network.implementation.api
  summary: >-
    <p>Get the routingRegistryName value.</p>

    <p></p>
  syntax:
    content: public String routingRegistryName()
    return:
      type: "26831127"
      description: <p>the routingRegistryName value </p>
- uid: com.microsoft.azure.management.network.implementation.api._express_route_circuit_peering_config_1a6776e4af6442fc1743bc86a5269a03bd
  id: _express_route_circuit_peering_config_1a6776e4af6442fc1743bc86a5269a03bd
  parent: com.microsoft.azure.management.network.implementation.api._express_route_circuit_peering_config
  href: com.microsoft.azure.management.network.implementation.api._express_route_circuit_peering_config.yml
  langs:
  - java
  name: withAdvertisedPublicPrefixes(List< String > advertisedPublicPrefixes)
  fullName: ExpressRouteCircuitPeeringConfig com.microsoft.azure.management.network.implementation.api.ExpressRouteCircuitPeeringConfig.withAdvertisedPublicPrefixes(List< String > advertisedPublicPrefixes)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/api/ExpressRouteCircuitPeeringConfig.java
    startLine: 51
  package: com.microsoft.azure.management.network.implementation.api
  summary: >-
    <p>Set the advertisedPublicPrefixes value.</p>

    <p></p>
  syntax:
    content: public ExpressRouteCircuitPeeringConfig withAdvertisedPublicPrefixes(List< String > advertisedPublicPrefixes)
    parameters:
    - id: advertisedPublicPrefixes
      type: f35af49b
      description: <p>the advertisedPublicPrefixes value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation.api._express_route_circuit_peering_config
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation.api._express_route_circuit_peering_config" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network.implementation.api._express_route_circuit_peering_config_1aeaf922b436bedf7d12f9c0b71056d393
  id: _express_route_circuit_peering_config_1aeaf922b436bedf7d12f9c0b71056d393
  parent: com.microsoft.azure.management.network.implementation.api._express_route_circuit_peering_config
  href: com.microsoft.azure.management.network.implementation.api._express_route_circuit_peering_config.yml
  langs:
  - java
  name: withAdvertisedPublicPrefixesState(String advertisedPublicPrefixesState)
  fullName: ExpressRouteCircuitPeeringConfig com.microsoft.azure.management.network.implementation.api.ExpressRouteCircuitPeeringConfig.withAdvertisedPublicPrefixesState(String advertisedPublicPrefixesState)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/api/ExpressRouteCircuitPeeringConfig.java
    startLine: 71
  package: com.microsoft.azure.management.network.implementation.api
  summary: >-
    <p>Set the advertisedPublicPrefixesState value.</p>

    <p></p>
  syntax:
    content: public ExpressRouteCircuitPeeringConfig withAdvertisedPublicPrefixesState(String advertisedPublicPrefixesState)
    parameters:
    - id: advertisedPublicPrefixesState
      type: "26831127"
      description: <p>the advertisedPublicPrefixesState value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation.api._express_route_circuit_peering_config
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation.api._express_route_circuit_peering_config" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network.implementation.api._express_route_circuit_peering_config_1a5754d99117ba9d2ccb5e2ad9babdb017
  id: _express_route_circuit_peering_config_1a5754d99117ba9d2ccb5e2ad9babdb017
  parent: com.microsoft.azure.management.network.implementation.api._express_route_circuit_peering_config
  href: com.microsoft.azure.management.network.implementation.api._express_route_circuit_peering_config.yml
  langs:
  - java
  name: withCustomerASN(Integer customerASN)
  fullName: ExpressRouteCircuitPeeringConfig com.microsoft.azure.management.network.implementation.api.ExpressRouteCircuitPeeringConfig.withCustomerASN(Integer customerASN)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/api/ExpressRouteCircuitPeeringConfig.java
    startLine: 91
  package: com.microsoft.azure.management.network.implementation.api
  summary: >-
    <p>Set the customerASN value.</p>

    <p></p>
  syntax:
    content: public ExpressRouteCircuitPeeringConfig withCustomerASN(Integer customerASN)
    parameters:
    - id: customerASN
      type: 08effaa0
      description: <p>the customerASN value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation.api._express_route_circuit_peering_config
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation.api._express_route_circuit_peering_config" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network.implementation.api._express_route_circuit_peering_config_1af51b98caebd8e00a9472f687cc3ca307
  id: _express_route_circuit_peering_config_1af51b98caebd8e00a9472f687cc3ca307
  parent: com.microsoft.azure.management.network.implementation.api._express_route_circuit_peering_config
  href: com.microsoft.azure.management.network.implementation.api._express_route_circuit_peering_config.yml
  langs:
  - java
  name: withRoutingRegistryName(String routingRegistryName)
  fullName: ExpressRouteCircuitPeeringConfig com.microsoft.azure.management.network.implementation.api.ExpressRouteCircuitPeeringConfig.withRoutingRegistryName(String routingRegistryName)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/api/ExpressRouteCircuitPeeringConfig.java
    startLine: 111
  package: com.microsoft.azure.management.network.implementation.api
  summary: >-
    <p>Set the routingRegistryName value.</p>

    <p></p>
  syntax:
    content: public ExpressRouteCircuitPeeringConfig withRoutingRegistryName(String routingRegistryName)
    parameters:
    - id: routingRegistryName
      type: "26831127"
      description: <p>the routingRegistryName value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation.api._express_route_circuit_peering_config
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation.api._express_route_circuit_peering_config" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: f35af49b
  spec.java:
  - name: List< String >
    fullName: List< String >
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 08effaa0
  spec.java:
  - name: Integer
    fullName: Integer
- uid: com.microsoft.azure.management.network.implementation.api._express_route_circuit_peering_config
  parent: com.microsoft.azure.management.network.implementation.api
  href: com.microsoft.azure.management.network.implementation.api._express_route_circuit_peering_config.yml
  name: ExpressRouteCircuitPeeringConfig
  fullName: com.microsoft.azure.management.network.implementation.api.ExpressRouteCircuitPeeringConfig
  type: Class
  summary: <p>Specfies the peering config. </p>
  syntax: *o1
