items:
- uid: com.microsoft.azure.management.website.implementation.api._site_logs_config_inner
  id: _site_logs_config_inner
  parent: com.microsoft.azure.management.website.implementation.api
  children:
  - com.microsoft.azure.management.website.implementation.api._site_logs_config_inner_1adf75e8c4f40559e4d4193d99cc792f17
  - com.microsoft.azure.management.website.implementation.api._site_logs_config_inner_1aaf2e8b1b912bd427de53e5682985d209
  - com.microsoft.azure.management.website.implementation.api._site_logs_config_inner_1a0bb0692b361c2bb05388a7d849ef9803
  - com.microsoft.azure.management.website.implementation.api._site_logs_config_inner_1a9dddd8a9f8f62c771a5e93df2e8d8e28
  - com.microsoft.azure.management.website.implementation.api._site_logs_config_inner_1a459b365a2861953b1d6d461053bdd98e
  - com.microsoft.azure.management.website.implementation.api._site_logs_config_inner_1a44cc9642b5d88106f5f31ee22e31f760
  - com.microsoft.azure.management.website.implementation.api._site_logs_config_inner_1a4d417bdc9ee0742a3dcc02036982da99
  - com.microsoft.azure.management.website.implementation.api._site_logs_config_inner_1aba1a99ddcd8f663c4c6268fba12df0bb
  href: com.microsoft.azure.management.website.implementation.api._site_logs_config_inner.yml
  langs:
  - java
  name: SiteLogsConfigInner
  fullName: com.microsoft.azure.management.website.implementation.api.SiteLogsConfigInner
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/SiteLogsConfigInner.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java.git
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/SiteLogsConfigInner.java
    startLine: 16
  package: com.microsoft.azure.management.website.implementation.api
  summary: <p>Configuration of <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> web site. </p>
  syntax: &o1
    content: public class SiteLogsConfigInner extends Resource
  inheritance:
  - java.lang.Object
  - com.microsoft.azure._resource
  inheritedMembers:
  - com.microsoft.azure._resource_1a2e102c3a5a80cabb644ef19ec31a9b9a
  - com.microsoft.azure._resource_1a00cc4f65c2d841294380d99ba4fd8782
  - com.microsoft.azure._resource_1ae54c7770e81b739bf0ecf42aa3881887
  - com.microsoft.azure._resource_1a0acbe5481adee4c388e642dfdfeb18e6
  - com.microsoft.azure._resource_1aff3f1f9fe4db6f84d424cd354369e1cd
  - com.microsoft.azure._resource_1a6a1f31436a35ab46583c7e741601a2e8
  - com.microsoft.azure._resource_1a832de9258cf4a03d822c4fe33db8768b
- uid: com.microsoft.azure.management.website.implementation.api._site_logs_config_inner_1adf75e8c4f40559e4d4193d99cc792f17
  id: _site_logs_config_inner_1adf75e8c4f40559e4d4193d99cc792f17
  parent: com.microsoft.azure.management.website.implementation.api._site_logs_config_inner
  href: com.microsoft.azure.management.website.implementation.api._site_logs_config_inner.yml
  langs:
  - java
  name: applicationLogs()
  fullName: ApplicationLogsConfig com.microsoft.azure.management.website.implementation.api.SiteLogsConfigInner.applicationLogs()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/SiteLogsConfigInner.java
    startLine: 46
  package: com.microsoft.azure.management.website.implementation.api
  summary: >-
    <p>Get the applicationLogs value.</p>

    <p></p>
  syntax:
    content: public ApplicationLogsConfig applicationLogs()
    return:
      type: com.microsoft.azure.management.website.implementation.api._application_logs_config
      description: <p>the applicationLogs value </p>
- uid: com.microsoft.azure.management.website.implementation.api._site_logs_config_inner_1aaf2e8b1b912bd427de53e5682985d209
  id: _site_logs_config_inner_1aaf2e8b1b912bd427de53e5682985d209
  parent: com.microsoft.azure.management.website.implementation.api._site_logs_config_inner
  href: com.microsoft.azure.management.website.implementation.api._site_logs_config_inner.yml
  langs:
  - java
  name: detailedErrorMessages()
  fullName: EnabledConfig com.microsoft.azure.management.website.implementation.api.SiteLogsConfigInner.detailedErrorMessages()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/SiteLogsConfigInner.java
    startLine: 106
  package: com.microsoft.azure.management.website.implementation.api
  summary: >-
    <p>Get the detailedErrorMessages value.</p>

    <p></p>
  syntax:
    content: public EnabledConfig detailedErrorMessages()
    return:
      type: com.microsoft.azure.management.website.implementation.api._enabled_config
      description: <p>the detailedErrorMessages value </p>
- uid: com.microsoft.azure.management.website.implementation.api._site_logs_config_inner_1a0bb0692b361c2bb05388a7d849ef9803
  id: _site_logs_config_inner_1a0bb0692b361c2bb05388a7d849ef9803
  parent: com.microsoft.azure.management.website.implementation.api._site_logs_config_inner
  href: com.microsoft.azure.management.website.implementation.api._site_logs_config_inner.yml
  langs:
  - java
  name: failedRequestsTracing()
  fullName: EnabledConfig com.microsoft.azure.management.website.implementation.api.SiteLogsConfigInner.failedRequestsTracing()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/SiteLogsConfigInner.java
    startLine: 86
  package: com.microsoft.azure.management.website.implementation.api
  summary: >-
    <p>Get the failedRequestsTracing value.</p>

    <p></p>
  syntax:
    content: public EnabledConfig failedRequestsTracing()
    return:
      type: com.microsoft.azure.management.website.implementation.api._enabled_config
      description: <p>the failedRequestsTracing value </p>
- uid: com.microsoft.azure.management.website.implementation.api._site_logs_config_inner_1a9dddd8a9f8f62c771a5e93df2e8d8e28
  id: _site_logs_config_inner_1a9dddd8a9f8f62c771a5e93df2e8d8e28
  parent: com.microsoft.azure.management.website.implementation.api._site_logs_config_inner
  href: com.microsoft.azure.management.website.implementation.api._site_logs_config_inner.yml
  langs:
  - java
  name: httpLogs()
  fullName: HttpLogsConfig com.microsoft.azure.management.website.implementation.api.SiteLogsConfigInner.httpLogs()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/SiteLogsConfigInner.java
    startLine: 66
  package: com.microsoft.azure.management.website.implementation.api
  summary: >-
    <p>Get the httpLogs value.</p>

    <p></p>
  syntax:
    content: public HttpLogsConfig httpLogs()
    return:
      type: com.microsoft.azure.management.website.implementation.api._http_logs_config
      description: <p>the httpLogs value </p>
- uid: com.microsoft.azure.management.website.implementation.api._site_logs_config_inner_1a459b365a2861953b1d6d461053bdd98e
  id: _site_logs_config_inner_1a459b365a2861953b1d6d461053bdd98e
  parent: com.microsoft.azure.management.website.implementation.api._site_logs_config_inner
  href: com.microsoft.azure.management.website.implementation.api._site_logs_config_inner.yml
  langs:
  - java
  name: withApplicationLogs(ApplicationLogsConfig applicationLogs)
  fullName: SiteLogsConfigInner com.microsoft.azure.management.website.implementation.api.SiteLogsConfigInner.withApplicationLogs(ApplicationLogsConfig applicationLogs)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/SiteLogsConfigInner.java
    startLine: 56
  package: com.microsoft.azure.management.website.implementation.api
  summary: >-
    <p>Set the applicationLogs value.</p>

    <p></p>
  syntax:
    content: public SiteLogsConfigInner withApplicationLogs(ApplicationLogsConfig applicationLogs)
    parameters:
    - id: applicationLogs
      type: com.microsoft.azure.management.website.implementation.api._application_logs_config
      description: <p>the applicationLogs value to set </p>
    return:
      type: com.microsoft.azure.management.website.implementation.api._site_logs_config_inner
      description: <p>the <xref href="com.microsoft.azure.management.website.implementation.api._site_logs_config_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.website.implementation.api._site_logs_config_inner_1a44cc9642b5d88106f5f31ee22e31f760
  id: _site_logs_config_inner_1a44cc9642b5d88106f5f31ee22e31f760
  parent: com.microsoft.azure.management.website.implementation.api._site_logs_config_inner
  href: com.microsoft.azure.management.website.implementation.api._site_logs_config_inner.yml
  langs:
  - java
  name: withDetailedErrorMessages(EnabledConfig detailedErrorMessages)
  fullName: SiteLogsConfigInner com.microsoft.azure.management.website.implementation.api.SiteLogsConfigInner.withDetailedErrorMessages(EnabledConfig detailedErrorMessages)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/SiteLogsConfigInner.java
    startLine: 116
  package: com.microsoft.azure.management.website.implementation.api
  summary: >-
    <p>Set the detailedErrorMessages value.</p>

    <p></p>
  syntax:
    content: public SiteLogsConfigInner withDetailedErrorMessages(EnabledConfig detailedErrorMessages)
    parameters:
    - id: detailedErrorMessages
      type: com.microsoft.azure.management.website.implementation.api._enabled_config
      description: <p>the detailedErrorMessages value to set </p>
    return:
      type: com.microsoft.azure.management.website.implementation.api._site_logs_config_inner
      description: <p>the <xref href="com.microsoft.azure.management.website.implementation.api._site_logs_config_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.website.implementation.api._site_logs_config_inner_1a4d417bdc9ee0742a3dcc02036982da99
  id: _site_logs_config_inner_1a4d417bdc9ee0742a3dcc02036982da99
  parent: com.microsoft.azure.management.website.implementation.api._site_logs_config_inner
  href: com.microsoft.azure.management.website.implementation.api._site_logs_config_inner.yml
  langs:
  - java
  name: withFailedRequestsTracing(EnabledConfig failedRequestsTracing)
  fullName: SiteLogsConfigInner com.microsoft.azure.management.website.implementation.api.SiteLogsConfigInner.withFailedRequestsTracing(EnabledConfig failedRequestsTracing)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/SiteLogsConfigInner.java
    startLine: 96
  package: com.microsoft.azure.management.website.implementation.api
  summary: >-
    <p>Set the failedRequestsTracing value.</p>

    <p></p>
  syntax:
    content: public SiteLogsConfigInner withFailedRequestsTracing(EnabledConfig failedRequestsTracing)
    parameters:
    - id: failedRequestsTracing
      type: com.microsoft.azure.management.website.implementation.api._enabled_config
      description: <p>the failedRequestsTracing value to set </p>
    return:
      type: com.microsoft.azure.management.website.implementation.api._site_logs_config_inner
      description: <p>the <xref href="com.microsoft.azure.management.website.implementation.api._site_logs_config_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.website.implementation.api._site_logs_config_inner_1aba1a99ddcd8f663c4c6268fba12df0bb
  id: _site_logs_config_inner_1aba1a99ddcd8f663c4c6268fba12df0bb
  parent: com.microsoft.azure.management.website.implementation.api._site_logs_config_inner
  href: com.microsoft.azure.management.website.implementation.api._site_logs_config_inner.yml
  langs:
  - java
  name: withHttpLogs(HttpLogsConfig httpLogs)
  fullName: SiteLogsConfigInner com.microsoft.azure.management.website.implementation.api.SiteLogsConfigInner.withHttpLogs(HttpLogsConfig httpLogs)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/api/SiteLogsConfigInner.java
    startLine: 76
  package: com.microsoft.azure.management.website.implementation.api
  summary: >-
    <p>Set the httpLogs value.</p>

    <p></p>
  syntax:
    content: public SiteLogsConfigInner withHttpLogs(HttpLogsConfig httpLogs)
    parameters:
    - id: httpLogs
      type: com.microsoft.azure.management.website.implementation.api._http_logs_config
      description: <p>the httpLogs value to set </p>
    return:
      type: com.microsoft.azure.management.website.implementation.api._site_logs_config_inner
      description: <p>the <xref href="com.microsoft.azure.management.website.implementation.api._site_logs_config_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: com.microsoft.azure._resource_1a2e102c3a5a80cabb644ef19ec31a9b9a
  parent: com.microsoft.azure._resource
  href: com.microsoft.azure._resource.yml
  name: getTags()
  fullName: Map<String, String> com.microsoft.azure.Resource.getTags()
  type: Method
  summary: >-
    <p>Get the tags value.</p>

    <p></p>
  syntax:
    content: public Map< String, String > getTags()
    return:
      type: 805937fc
      description: <p>the tags value </p>
- uid: com.microsoft.azure._resource_1a00cc4f65c2d841294380d99ba4fd8782
  parent: com.microsoft.azure._resource
  href: com.microsoft.azure._resource.yml
  name: id()
  fullName: String com.microsoft.azure.Resource.id()
  type: Method
  summary: >-
    <p>Get the id value.</p>

    <p></p>
  syntax:
    content: public String id()
    return:
      type: "26831127"
      description: <p>the id value </p>
- uid: com.microsoft.azure._resource_1ae54c7770e81b739bf0ecf42aa3881887
  parent: com.microsoft.azure._resource
  href: com.microsoft.azure._resource.yml
  name: location()
  fullName: String com.microsoft.azure.Resource.location()
  type: Method
  summary: >-
    <p>Get the location value.</p>

    <p></p>
  syntax:
    content: public String location()
    return:
      type: "26831127"
      description: <p>the location value </p>
- uid: com.microsoft.azure._resource_1a0acbe5481adee4c388e642dfdfeb18e6
  parent: com.microsoft.azure._resource
  href: com.microsoft.azure._resource.yml
  name: name()
  fullName: String com.microsoft.azure.Resource.name()
  type: Method
  summary: >-
    <p>Get the name value.</p>

    <p></p>
  syntax:
    content: public String name()
    return:
      type: "26831127"
      description: <p>the name value </p>
- uid: com.microsoft.azure._resource_1aff3f1f9fe4db6f84d424cd354369e1cd
  parent: com.microsoft.azure._resource
  href: com.microsoft.azure._resource.yml
  name: type()
  fullName: String com.microsoft.azure.Resource.type()
  type: Method
  summary: >-
    <p>Get the type value.</p>

    <p></p>
  syntax:
    content: public String type()
    return:
      type: "26831127"
      description: <p>the type value </p>
- uid: com.microsoft.azure._resource_1a6a1f31436a35ab46583c7e741601a2e8
  parent: com.microsoft.azure._resource
  href: com.microsoft.azure._resource.yml
  name: withLocation(String location)
  fullName: Resource com.microsoft.azure.Resource.withLocation(String location)
  type: Method
  summary: >-
    <p>Set the location value.</p>

    <p></p>
  syntax:
    content: public Resource withLocation(String location)
    parameters:
    - id: location
      type: "26831127"
      description: <p>the location value to set </p>
    return:
      type: com.microsoft.azure._resource
      description: <p>the resource itself </p>
- uid: com.microsoft.azure._resource_1a832de9258cf4a03d822c4fe33db8768b
  parent: com.microsoft.azure._resource
  href: com.microsoft.azure._resource.yml
  name: withTags(Map< String, String > tags)
  fullName: Resource com.microsoft.azure.Resource.withTags(Map< String, String > tags)
  type: Method
  summary: >-
    <p>Set the tags value.</p>

    <p></p>
  syntax:
    content: public Resource withTags(Map< String, String > tags)
    parameters:
    - id: tags
      type: 805937fc
      description: <p>the tags value to set </p>
    return:
      type: com.microsoft.azure._resource
      description: <p>the resource itself </p>
- uid: com.microsoft.azure._resource
  parent: com.microsoft.azure
  href: com.microsoft.azure._resource.yml
  name: Resource
  fullName: com.microsoft.azure.Resource
  type: Class
  summary: <p>The <xref href="com.microsoft.azure._resource" data-throw-if-not-resolved="false"></xref> model. </p>
  syntax:
    content: public class Resource
- uid: com.microsoft.azure.management.website.implementation.api._application_logs_config
  parent: com.microsoft.azure.management.website.implementation.api
  href: com.microsoft.azure.management.website.implementation.api._application_logs_config.yml
  name: ApplicationLogsConfig
  fullName: com.microsoft.azure.management.website.implementation.api.ApplicationLogsConfig
  type: Class
  summary: <p>Application logs configuration. </p>
  syntax:
    content: public class ApplicationLogsConfig
- uid: com.microsoft.azure.management.website.implementation.api._http_logs_config
  parent: com.microsoft.azure.management.website.implementation.api
  href: com.microsoft.azure.management.website.implementation.api._http_logs_config.yml
  name: HttpLogsConfig
  fullName: com.microsoft.azure.management.website.implementation.api.HttpLogsConfig
  type: Class
  summary: <p>Http logs configuration. </p>
  syntax:
    content: public class HttpLogsConfig
- uid: com.microsoft.azure.management.website.implementation.api._enabled_config
  parent: com.microsoft.azure.management.website.implementation.api
  href: com.microsoft.azure.management.website.implementation.api._enabled_config.yml
  name: EnabledConfig
  fullName: com.microsoft.azure.management.website.implementation.api.EnabledConfig
  type: Class
  summary: <p>Enabled configuration. </p>
  syntax:
    content: public class EnabledConfig
- uid: com.microsoft.azure.management.website.implementation.api._site_logs_config_inner
  parent: com.microsoft.azure.management.website.implementation.api
  href: com.microsoft.azure.management.website.implementation.api._site_logs_config_inner.yml
  name: SiteLogsConfigInner
  fullName: com.microsoft.azure.management.website.implementation.api.SiteLogsConfigInner
  type: Class
  summary: <p>Configuration of <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref> web site. </p>
  syntax: *o1
- uid: com.microsoft.azure._azure
  parent: com.microsoft.azure
  href: com.microsoft.azure._azure.yml
  name: Azure
  fullName: com.microsoft.azure.Azure
  type: Class
  summary: <p>The entry point for accessing resource management APIs in <xref href="com.microsoft.azure._azure" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class Azure
